### ISSUE TITLE
Overview.md needs content for features and architecture (and functionality)

### ISSUE THREAD

**Issue by dmolesUC** [CDLUC3/mrt-doc#1]
[Overview.md](https://github.com/CDLUC3/mrt-doc/wiki/Overview) looks like it's supposed to link to Features and Architecture pages, or else include Features and Architecture sections, but these don't exist.

**Comment by dmolesUC3** [comment]
I [commented out](https://github.com/CDLUC3/mrt-doc/wiki/Overview/86eb31bffb37ecbb68829e6c3c7f76189df39021) the orphaned links/titles and added a TODO, pro tem.

**Comment by dmolesUC3** [comment]
I added a link to the new [Architecture](https://github.com/CDLUC3/mrt-doc/wiki/Architecture) page.
