### ISSUE TITLE
Verbose server.out file on LDAP hosts

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1001]
LDAP hosts reveal a server.out file over 7GB on both hosts.  This file appears to get rolled over when the service is restarted.  I base this guess on the date of the pid file compared to the first lines of the server.out file:

Ashley will go add this file to puppet configs for logrotation.  However, this is a very verbose log.  Is there a config option for OpenDJ service to adjust verbosity for this log?

**Comment by mreyescdl** [comment]
The `server.out` log file contains OpenJDK thread information only.
We have seen this on Ingest and Storage as well, and it is my understanding that this is done for long running Java threads (for debugging)

I'm hopeful that we can turn off this behavior which seems to be the default and introduced recently with a JDK update.

**Comment by mreyescdl** [comment]
To script up a new Java store, please refer to https://confluence.ucop.edu/display/UC3/LDAP+operations

After creation, we need to copy to /ldap/opendj/config/truststore and restart LDAP
