### ISSUE TITLE
Modify the Storage Node Report to alarm at specific thresholds -- Add to Consistency Report

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1006]
- [ ] Add per node overhead factor (if available)
- [ ] Store storage caps in the code (i.e. SDSC 300T)
- [ ] WARN at 80%
- [ ] FAIL at 90%
- [ ] Add to consistency reports

**Comment by terrywbrady** [comment]
@elopatin-uc3 ,

I am going to set up the node report to run as a consistency report.  Please let me know your thoughts about allocations and warning limits (%) in the Storage Nodes report.

Let me know if we should show an allocation for Wasabi.

**Comment by elopatin-uc3** [comment]
@terrywbrady The Warn and Fail limits of 80% and 90% respectively make sense to me, knowing that SDSC can easily increase our allocation when needed. 

At this time I don't think it makes sense to note a Wasabi allocation, as will fail the limit check consistently and it's unclear when we will increase our allocation to 400 or 500TB.
