### ISSUE TITLE
Replic refactor with dependabot upgrade and mrt-cloud changes supporting retry

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#1009]
### Problem
The nexus maven repository has the problem that upgrading to a newer jar version can require manual mvn uploads for all jar pieces. This process can take enormous amounts of time.

Replic has a number of dependabot alerts on local jars. 

Replic has consistently been failing on wasabi replication.
See: Replic - processing of large content #990

### Solution
- Upgrade replic jars to dependabot recommendations
- Convert replic from running on master to main
- Use Terry refactor build with Ashley's deploy
- Use mrt-cloud retry to (hopefully) fix wasabi replication failures for large content

### Upgrade replic jars to dependabot recommendations
- dependabot recommendations do NOT identify that code changes may be required for a specific upgrade
- upgrades on jar dependencies need to be made for both src and war pom.xml
- not all dependabot identified problems have a substitute jar.

### Convert replic from running on master to main
- Steps
See:
https://www.r-bloggers.com/2020/07/5-steps-to-change-github-default-branch-from-master-to-main/
and
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch

### Terry's refactor
- run Jenkins to create war from branch
  http://builds.cdlib.org/job/mrt-replic-refactor-dev/

- run Jenkins to build deploy war from previously created tag:
  http://builds.cdlib.org/job/mrt-replic-refactor/

#### Refactor Note:
- The refactor process requires that the pipeline Jenkinsfile be included on the branch being processed at the top level of the mvn repository
- Be VERY careful in the creation of the tag used in mrt-replic-refactor. The tag must be created with all content used for the deploy. If a previous github merge was performed, be sure download the merged main from github.
- Agreed, that a tag must be created on an uploaded branch.  For myself, main.

### Ashley deploy 
- On the server for the deploy,  set MERRITT_REPLIC_RELEASE to deploy tag
Example: 
~~~
export MERRITT_REPLIC_RELEASE=0.0.17
~~~
- Shutdown to-deploy server
~~~
init.d/replic38001 stop
~~~
- install deploy war
~~~
cd /apps/dpr2/tools/deploy
./deploy_semver.sh
~~~
- restart server
~~~
init.d/eplic38001 start
~~~

#### Ashley comments on audit
These features will be needed to be supported on replic
~~~
[Ashley Gould](https://app.slack.com/team/U011A1ERK54)  [4:07 PM](https://cdlib.slack.com/archives/C86U0VBLH/p1645747628437099)
[@mreyes](https://cdlib.slack.com/team/U032L1M27) I've made an initial edit mrt-tomcat/config/deploy/uc3-mrt-audit-stg.rb. Does this look reasonable to you?
set :rails_env, "uc3-mrt-audit-stg"
set :semantic_version, ENV['MERRITT_AUDIT_RELEASE'] || 'undefined'
puts "----- uc3-mrt-autid-stg branch of https://github.com/CDLUC3/tomcat8_catalina_base -----"
set :repo_url, "https://github.com/CDLUC3/tomcat8_catalina_base"
set :branch, "uc3-mrt-audit-stg"

set :application, "merritt-audit"
set :build_url, "http://builds.cdlib.org/userContent/mrt-audit/mrt-audit.#{fetch(:semantic_version)}.war"
[cut]
The enviroment var where we supply the git tag is MERRITT_AUDIT_RELEASE

Looks great [@Ashley Gould](https://cdlib.slack.com/team/U011A1ERK54)
 
[terrywbrady](https://app.slack.com/team/UPK51CNLD)  [4:14 PM](https://cdlib.slack.com/archives/C86U0VBLH/p1645748096137189)
Great.  The name is currently mrt-audit-semver.war
~~~

### Use mrt-cloud retry to fix wasabi replication failures for large content
The mrt-cloud refactor includes changes to support replication retry:
- change to replic to support inline retry
- changes to S3 handling to use RetryStrategy=FullJitterBackoffStrategy
- upgrade of aws-java-sdk jar to 1.12.190 release

These changes should hopefully resolve the number of replication failures to wasabi. Local testing of the mrt-cloud has successfully processed 3 of the failed updates without using local code retry.

**Comment by dloy** [comment]
Current dependency on completion:
Inventory mrt-zoo refactor #1016

**Comment by terrywbrady** [comment]
See email with subject "RE:[CASE 9885348711] Questions about retries in S3 SDK"

**Comment by dloy** [comment]
Question:  do this for the refactor? 
- Scan (replic) - updates required before rerun #987

**Comment by terrywbrady** [comment]
@dloy , how much time would it add to include 987?
