### ISSUE TITLE
Ingest service in Docker Dev returning empty batch state

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1011]
This issue has impacted my testing in docker.  It would be good to trace why this response is not empty.

Could this be due to a jar update in core?

After performing an upload via the UI, this response is returned from ingest.

```
<?xml version="1.0" encoding="UTF-8"?>
<bat:batchState xmlns:bat='http://uc3.cdlib.org/ontology/mrt/ingest/batch'>
</bat:batchState>
```

**Comment by mreyescdl** [comment]
@terrywbrady Are you still seeing this behavior?

If so, I'll try and replicate on docker 03

**Comment by terrywbrady** [comment]
@mreyescdl , I suspect that it still is.  I have the following in place on docker01 to make the issue silent in the UI.

https://github.com/CDLUC3/mrt-dashboard/pull/120/files

**Comment by terrywbrady** [comment]
@elopatin-uc3 , I believe this is resolved

**Comment by elopatin-uc3** [comment]
Label added; closing.
