### ISSUE TITLE
Merritt Integration Tests and Unit Tests

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1019]
## Project Status
- [x] #1045 
- [ ] Merge https://github.com/CDLUC3/mrt-jenkins/pull/3/files 
- [x] #1046 
- [x] #1041
- [ ] #1042 
- [x] #1043 
- [x] #1044

### Define new integration tests containers as needed

https://github.com/CDLUC3/merritt-docker/tree/main/mrt-inttest-services

### src/test/docker/docker-compose.yml 

Use this file to manually launch integration test containers

_Ingest used as an example_
```
version: '3.9'
services:
  zoo:
    container_name: it-zoo
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/mrt-zookeeper:dev
    ports:
    - published: 2181
      target: 2181
    stdin_open: true
    tty: true
  ezid:
    container_name: it-server
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/mrt-ezid-store-mock:dev
    ports:
    - published: 4567
      target: 4567
```

#### Define docker registry
```
    <itDockerRegistry>itDockerRegistry</itDockerRegistry>
```
#### Define profile to set docker registry based on AWS account
```
<profiles>
       <profile>
           <id>aws</id>
           <activation>
               <property>
                   <name>env.AWS_ACCOUNT_ID</name>
               </property>
           </activation>
           <properties>
               <!-- Override only if necessary -->
               <itDockerRegistry>${env.AWS_ACCOUNT_ID}.dkr.ecr.${env.AWS_REGION}.amazonaws.com</itDockerRegistry>
           </properties>
       </profile>
   </profiles>
```

#### Configure io.fabric8 plugin to run integration test containers.  Port numbers will be dynamic when run through maven.

_Ingest used as an example_
```
      <plugin>
        <groupId>io.fabric8</groupId>
        <artifactId>docker-maven-plugin</artifactId>
        <version>0.20.1</version>
        <executions>
            <execution>
                <id>prepare-it-server</id>
                <phase>pre-integration-test</phase>
                <goals>
                    <goal>start</goal>
                </goals>
                <configuration>
                    <images>
                        <image>
                            <!-- https://github.com/CDLUC3/merritt-docker/tree/main/mrt-services/ezid_mock -->
                            <name>${itDockerRegistry}/mrt-ezid-store-mock:dev</name>
                            <alias>it-server</alias>
                            <run>
                                <ports>
                                    <port>it-server.port:4567</port>
                                </ports>
                                <wait>
                                    <time>2000</time>
                                </wait>
                            </run>
                        </image>
                        <image>
                            <alias>it-zoo</alias>
                            <name>zookeeper:3.4</name>
                            <run>
                                <ports>
                                    <port>it-zoo.port:2181</port>
                                </ports>
                                <wait>
                                    <time>2000</time>
                                </wait>
                            </run>
                        </image>
                    </images>
                </configuration>
            </execution>
            <execution>
                <id>remove-it-server</id>
                <phase>post-integration-test</phase>
                <goals>
                    <goal>stop</goal>
                </goals>
            </execution>
        </executions>
      </plugin>
```
#### Configure the maven-failsafe-plugin to run integration tests -- use env vars to pass in dynamic port numbers

_Ingest used as an example_

Notes
- In the configuration below, integration tests are configured to be in classes named `**/*IT`
- `-DskipITs` is the default mechanism to disable integration tests

```
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-failsafe-plugin</artifactId>
        <version>2.22.2</version>
        <executions>
          <execution>
            <goals>
              <goal>integration-test</goal>
              <goal>verify</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <includes>
            <include>**/*IT</include>
          </includes>
          <environmentVariables>
            <it-server.port>${it-server.port}</it-server.port>
            <it-zoo.port>${it-zoo.port}</it-zoo.port>
          </environmentVariables>
        </configuration>
      </plugin>
```
#### Allow -Dskip.surefire.tests if unit tests can be slow to run

Notes
- By default, unit tests are configured to be in classes named `**/Test*` or `**/*Test`
- In the configuration below, `-Dskip.surefire.tests` is the default mechanism to disable unit tests

```
     <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.22.2</version>
        <configuration>
          <!-- Includes Test* and *Test by default -->
          <!-- skips surefire tests without skipping failsafe tests.
                     Property value seems to magically default to false -->
          <skipTests>${skip.surefire.tests}</skipTests>
        </configuration>
      </plugin>
```

#### Enable Coverage Report
```
<plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>0.8.5</version>
        <executions>
                <execution>
                    <id>default-prepare-agent</id>
                    <goals>
                        <goal>prepare-agent</goal>
                    </goals>
                </execution>
                <execution>
                    <id>default-report</id>
                    <phase>verify</phase>
                    <goals>
                        <goal>report</goal>
                    </goals>
                </execution>
        </executions>
      </plugin>
```

## Params to control maven tests

<a name="Commands">Commands</a>
- `mvn test` - run unit tests
- `mvn verify` - run unit tests and integration tests, create coverage report
- `mvn install -DskipTests -Ddocker.skip` - skip all tests
- `mvn verify -Dskip.surefire.tests` - skip unit tests, but run IT tests
- `mvn install -DskipITs -Ddocker.skip` - skip integration tests

---

## Testing with Embedded Tomcat

https://github.com/CDLUC3/merritt-tinker/tree/main/sample-war

---

## Demo
- [x] Demo unit tests and integration tests from maven
- [x] Demo unit tests from VSCode
- [x] Demo integration tests from VSCode
  - [x] Must manually start IT containers

## Questions for the team
- [x] Where to store IT container dockerfiles?
  - [x] in each microservice repo
  - [x] in a centralized Merritt repo
- [x] Where to store IT container images?
  - ~build on demand~
  - [x] store in ECR 
    - how would Jenkins access this?
    - re-use some merritt-docker images
    - can we reference ECR images in our public repos without revealing our AWS account id?
  - ~build locally on DEV machines and on Jenkins server~

## Questions for IAS
- [x] Can our Jenkins server be given read ("pull") access to ECR
  - yes, if needed

## Images needed
- UI: database
- Ingest: ezid, zk, mock storage, mock inv
- Inventory: database, zk
- Store: minio, zk
- Audit: database, minio
- Replic: database, minio

**Comment by dloy** [comment]
## Use an environment variable equivalent to "mvn install -DskipTests -Ddocker.skip"
### requirements
The intent of this environment variable:
~~~
export SKIP_DOCKER_TEST=true
~~~
is to:
- allow backward compatibility of the pom.xml containing the tests without changing command line mvn.
- provide identical behavior if the env variable is not used or is set to "false". No unit test changes are required to support it.

Backward compatibility is required because the docker test environment is not available on all systems. Updating all mvn requests to include "mvn -DskipTests -Ddocker.skip" will work, but with some tools (e.g. older netbeans) this can be difficult.

### pom.xml change
The following change sets the initial default values of the pom.xml at time of execution.

Note:
- if SKIP_DOCKER_TEST is not defined or is set =false the behavior of the pom.xml remains the same.
~~~
    <properties>
        ....
	<docker.skip>${env.SKIP_DOCKER_TEST}</docker.skip>
	<skipTests>${env.SKIP_DOCKER_TEST}</skipTests>
    </properties>
~~~
- it is critical that the pom.xml behavior remain identical without the environment variable. If there are any operational changes that impact the unit test performance, the pom.xml should be modified to meet these requirements.

**Comment by terrywbrady** [comment]
@dloy , this change makes sense to me.  I am glad you are able to get this working in the pom.

**Comment by terrywbrady** [comment]
@elopatin-uc3 , this can be closed

**Comment by elopatin-uc3** [comment]
Closing
