### ISSUE TITLE
New UCSF feed: Glantz, Center for Tobacco Control Research and Education Video Library

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1025]
Source ticket: https://help.oac.cdlib.org/support/tickets/105950

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/8534

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_8534.atom

Root folder in Nuxeo:
/asset-library/UCSF/Glantz/Center for Tobacco Control Research and Education Video Library

Merritt collection:
UCSF Library Stanton A. Glantz collection
https://merritt.cdlib.org/m/ucsf_lib_stantonglantz
ark:/13030/m55t61wj

**Comment by mreyescdl** [comment]
Script created and puppetized to run at 03:50 on Thursdays.
Set to "absent" until Feed available and run manually as a test

**Comment by elopatin-uc3** [comment]
@mreyescdl Adrian had to make small correction to the path for the root folder in Nuxeo. This feed should be available next Tuesday.

**Comment by mreyescdl** [comment]
Feed available, but no access to S3 bucket which is part of the payload contained in feed.

**Comment by mreyescdl** [comment]
Submitted at a rate of 2/hour, this proved to cause nagios alert with Storage.
Will fluctuate between holding and releasing collection to trickle processing and not burden resources.
