### ISSUE TITLE
Admintool file list query maxes out lambda memory for objects with 40K files

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1029]
Relates to #1027

**Comment by terrywbrady** [comment]
This prevents the error from appearing.  We may want to add pagination later.  

https://github.com/CDLUC3/mrt-admin-lambda/commit/39d92f86ab4a9398fd5fb23f0aeaf3efacc6c85f

**Comment by elopatin-uc3** [comment]
Thanks @terrywbrady for addressing this.
