### ISSUE TITLE
LBNL Owner object replication issue - 	ark:/13030/j21n79mc

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1034]

**Comment by dloy** [comment]
There were 2 problems with replicating this object:
- it was copied to only glacier
- a bug (soon to be fixed) in replic prevented any updates if just the replicated field was set to null and all secondaries were up to date. 

Fix:
- add wasabi copy
- set replicated and version_number to null

3 copies now exist
