### ISSUE TITLE
Evgenia LEADING fellow intern - access issues

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1037]
## CDLSYS Request
```
Issue:	Create DEV box for Leading Fellows Intern (by July 1)
Issue Number:	14647

```
The Merritt Team will have a fellow/intern working with us for 6 months starting July 1. She will work with the Palestinian Museum content. The end goal will be to ingest this data into Merritt with good metadata. Once that data has been ingested, this environment will be discarded.

The fellow is a library school grad who will do some development. We would like her work to take place in an isolated environment. The team met today to refine our requirements.

* Create a modest sized server (your choice of initial instance type)
* Create a 250G EBS volume for her work. We might want to temporarily mount this elsewhere to facilitate data transfers at the later end of the project.
* The working volume should be read/writeable by the merritt team and the fellow
* Create a login for the fellow (Evgenia)
* All of her work will take place on this box. She should not need to ssh to other hosts (except something like the bastion if needed)
* DEV box should have READ access to UC3 stage s3 bucket. No other buckets should be available.
* The box should not need Merritt SSM variables. It would be ok if the DEV variables are accessible.
* Software needed on the box
* Java 8 JDK - to run some tools that Terry has written
* Ruby 2.7
* Python (current version)
* AWS cli (for listing s3 files)
* We would like for the box to have docker installed. The work will require access to a database clone from the Palestinian Museum and MODS files from UCLA. Docker should allow us to configure other tools that will work with this data.

Background information where the team as compiled these requirements:

* https://github.com/CDLUC3/mrt-doc/issues/1037
* Please CC Eric on any requests for more information
* Marisa is working through details about the desktop that Evgenia will use.

---

## Assumptions
- Evgenia will use her Mac, no ucop desktop will be provided
- Work will take place on a new DEV box configured with necessary tools
- IAS will advise on how Evgenia can access the DEV box w/o VPN or an AD account

## Access options:
- ssh to DEV box (via bastion?)
  - Optional suggestion: VSCode + ssh
- Cloud9 via aws sso

## Dev box needs
- Ideally, no ability to direct connect to Merritt servers via http.  Not essential.
- READ access to S3 bucket containing PM images.  No other S3 buckets should be accessible.
- R/W access to the PM folders on the EFS drive.  No other EFS access.
  - Consider having a separate EFS drive instead.
  - Or, possibly an EBS volume to work with. This could be moved as needed during/after the project.
- Ability to access a snapshot of PM database from their installation of [CollectiveAccess](https://manual.collectiveaccess.org/setup/backups.html?highlight=mysql).  
  - CollectiveAccess uses MySQL.
  - Should database be RDS or should database just be accessible through a docker container on the DEV box. 
- Dev box can run Java, Python, Ruby
- Ideally dev box can run docker in order to run database snapshots and a possible web server for serving up assets/reports prepared by Evgenia within the EFS folder

## Potential files to be used/generated on EFS or EBS:
- 120K metadata files (MODS)
- CSV files
- Working files and subsets of images for testing
- Merritt manifest files

## Question for Mark
- if we prepare content to be ingested on our EFS, how can we make it accessible for ingest via a manifest?
- this EFS is accessible to multiple boxes, so this new DEV box will not need to serve the content
 
## Other Access
- Slack
- GitHub limited access
  - read/write to a dedicated new repo for any assets created for the effort 
- Merritt Stage 
  - read access for example collections
  - read/write for PM collection
- Merritt Prod
  - read/write for PM collection 

Follow the model of how these folks access
https://confluence.ucop.edu/display/UC3/External+contributor+Access
- Dave N  
- Ryan  

How does Ashley use VPN?

**Evgenia Workflow Requirements**
- [ ] access to content in S3 to pull that down, PAL museum portion of EFS (access limited to only this portion of EFS), database snapshot, run in Docker image or RDS server?  mods files are created from CSV that are dumps of database
- [ ] collection of mods files, deposit into EFS, requires access to EFS
- [ ] FileAnalyzer requres Java install
- [ ] use Python or Ruby for any development efforts
- [ ] @marisastrong to reach out to IAS for IP Range/Public Facing IP address question and/or option to go through a cloud9 account attached to a dev server 

Misc notes
- prevent accidental deletion of S3 content
- scoped EFS access
- ideally no SSM/ECR
- READ S3

**Comment by marisastrong** [comment]
Evgenia uses an older Macbook; would an AWS-based desktop be helpful?  
How much storage on device is needed?

**Comment by terrywbrady** [comment]
Define criteria.  Too late to request Mac.  PC maybe.

AD/VPN access is unlikely for short term.
