### ISSUE TITLE
Store delete - tombstone manifest

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#1051]
Scan tests have shown a number of manifests that remain after a storage object delete takes place.

An example:
~~~
<?xml version="1.1"?>
<objectInfo xmlns="http://uc3.cdlib.org/ontology/mrt/manifest">
   <object id="ark:/13030/testout5001">
     <current>0</current>
     <fileCount>0</fileCount>
     <totalSize>0</totalSize>
     <actualCount>0</actualCount>
     <actualSize>0</actualSize>
     <versionCount>0</versionCount>
     <lastAddVersion>2022-05-13T21:10:15+00:00</lastAddVersion>
     <lastDeleteVersion>2022-05-13T21:10:52+00:00</lastDeleteVersion>
   </object>
 </objectInfo>
~~~
This remaining manifest is basically a tombstone, it no longer references any remaining content in the object because it all has been removed.

Also, this S3 object (file) is no longer referenced by the inv database. 

To facilitate the scan delete process, it would be useful to delete these empty standalone manifest.xml once all versions of the object have been removed.

To do this a single line needs to be added in store2 to DeleteObject to remove this file on completion.

**Comment by elopatin-uc3** [comment]
No longer needed.
