### ISSUE TITLE
cdl maven repo issue

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1060]
I was trying to rebuild the docker stack to test something out with David.  The cdl maven repo was not responding as normal.
```
mvn dependency:get -Dmaven.legacyLocalRepo=true -DgroupId=net.sf -DartifactId=jargs -Dversion=1.0 -Dpackaging=jar -DrepoUrl=https://mvn.cdlib.org/content/repositories/public/
```
We have mostly eliminated these dependencies, but there is still a lingering bit that depends on the old mvn repo.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.1:get (default-cli) on project standalone-pom: Couldn't download artifact: Could not transfer artifact net.sf:jargs:jar:1.0 from/to temp (https://mvn.cdlib.org/content/repositories/public/): Failed to transfer file: https://mvn.cdlib.org/content/repositories/public/net/sf/jargs/1.0/jargs-1.0.jar. Return code is: 500 , ReasonPhrase:Proxy Error.
```

Do you have any idea what the problem might be?

**Comment by mreyescdl** [comment]
Java store had expired, but is now updated.

We'll need to automate the creation of the JKS after IAS supplies us with a new LetsEncrypt cert
