### ISSUE TITLE
[RELEASE] access - store refactor - 2022-06-22 (Storage) and 2022-06-28 (Access)

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#1068]
# Overview of Release
This release installs the store refactor described in Issue:
[mrt-store refactor - ingest store and access services #1040](https://github.com/CDLUC3/mrt-doc/issues/1040)

# Service(s)
This install affects access and storage microservices

# Github Issue Link(s)
https://github.com/CDLUC3/mrt-doc/issues/1040

# Servers affected
## Stage (week 5/31/2022)
uc3-mrtaccess01x2-stg
uc3-mrtaccess02x2-stg
uc3-mrtstore01x2-stg
uc3-mrtstore02x2-stg

## Prod (week 6/6/2022)
uc3-mrtaccess01x2-prd
uc3-mrtaccess02x2-prd
uc3-mrtstore05x2-prd
uc3-mrtstore06x2-prd

# Source Code:
Link(s) to tagged release(s)
https://github.com/CDLUC3/mrt-store/commit/a3b6281160eefa8a0d1afa8decba6977f4931c93
https://github.com/CDLUC3/mrt-store/commit/b22da403c89d18a69a538ca4584cf3c3df87cf6c
https://github.com/CDLUC3/mrt-store/commit/c812de61895a58f1c4eb638b0cb106b7f7fa25c8
https://github.com/CDLUC3/mrt-store/commit/f8835e38ec504029704a30dce8f0d2b03e289659
https://github.com/CDLUC3/mrt-store/commit/dfb039e40dd11c74edfaa95d0aece4057224df69

# Source Code Tag
0.0.16

# Jenkins/Build Info: (if applicable)
https://builds.cdlib.org/view/Development/job/mrt-store-refactor/38/

# Deployment Steps (if applicable)
### For each server
- [ ] Install Capistrano script for deploy of storage/access given source code based on tag
- [ ] Removal server from load balancer
- [ ] deploy of new code to removed server
- [ ] validate
- [ ] add server back into load balancer

# Infrastructure Changes to support deployment (ALB, EFS, etc)
## Capistrano changes to support storage refactor
- Base refactor deploy script /apps/dpr2store/tools/deploy/deploy_semver.sh
- Capistrano script access: /apps/dpr2store/tools/deploy/mrt-tomcat/uc3-mrt-access-stg
- Capistrano script storage: /apps/dpr2store/tools/deploy/mrt-tomcat/uc3-mrt-storage-stg

# Rollback Instructions

**Comment by dloy** [comment]
A reinstall of access and store was required because of the deletion of the deprecated mrt-store-src - this changed the release from -0.0.15 to 0.0.16.

Additional changes were required in mrt-tomcat to include the refactor handling and to use "main" from "master"

**Comment by dloy** [comment]
Major problem on stage:
- access server .war files are disappearing
- storage server .war file are reverting to an earlier version 
Guessing the problem is related to puppet/capistrano

**Comment by dloy** [comment]
## Setup production release scripts
The production release requires for each server:

### Access
- /apps/dpr2store/tools/deploy/deploy_semver.sh
- /apps/dpr2store/tools/deploy/mrt-tomcat/config/deploy/uc3-mrt-access-prd.rb

#### deploy_semver.sh
~~~
#!/usr/bin/env bash

# Support new semantic Jenkins pipeline
# Usage:
#   export MERRITT_STORAGE_RELEASE=<semver>
#   ./deploy_semver.sh


if [ -n "$MERRITT_STORAGE_RELEASE" ]; then
    cd /apps/dpr2store/tools/deploy/mrt-tomcat
    MERRITT_STORAGE_RELEASE=${MERRITT_STORAGE_RELEASE} cap uc3-mrt-access-prd deploy
else
  echo "Must define Environment variable MERRITT_STORAGE_RELEASE"
fi

exit
~~~
#### uc3-mrt-access-prd.rb
~~~
# Simple Role Syntax
# ==================
# Supports bulk-adding hosts to roles, the primary
# server in each group is considered to be the first
# unless any hosts have the primary property set.
# Don't declare `role :all`, it's a meta role
#role :app, %w{mark.reyes@ucop.edu}
#role :web, %w{mark.reyes@ucop.edu}

# Extended Server Syntax
# ======================
# This can be used to drop a more detailed server
# definition into the server list. The second argument
# something that quacks like a hash can be used to set
# extended properties on the server.
# ---- Needed for non-rails deployment???
set :rails_env, "uc3-mrt-access-prd"

puts "----- uc3-mrt-access-prd branch of https://github.com/CDLUC3/tomcat8_catalina_base -----"
set :repo_url, "https://github.com/CDLUC3/tomcat8_catalina_base"
set :branch, "uc3-mrt-access-prd"

set :application, "merritt-store"
set :semantic_version, ENV['MERRITT_ACCESS_RELEASE'] || 'undefined'
set :build_url, "http://builds.cdlib.org/userContent/mrt-store/mrt-store-#{fetch(:semantic_version)}.war"

set :target, "storage.war"
set :deploy_to, "/dpr2store/apps/storage35121"

set :tomcat_pid, "#{fetch(:deploy_to)}/storage.pid"
set :tomcat_log, "#{fetch(:deploy_to)}/shared/log/tomcat.log"

# additional directories needed by storage
set :linked_dirs, fetch(:linked_dirs).push("webapps/container")

server "localhost", user: "dpr2store", roles: %w{web app}

# custom
namespace :custom do

  desc 'Custom deploy action'
  task :deploy_bits do
    on roles(:app) do
        puts "Add source code version to Tomcat directory"
        execute "/usr/bin/curl --silent -X GET https://api.github.com/repos/cdluc3/mrt-store/commits | /bin/fgrep 'sha' | /usr/bin/head -1 >> /dpr2store/apps/storage35121/version"
    end
  end

  desc 'Custom pre-stop action'
  task :prestop do
    on roles(:app) do
        puts "No custom prestop action"
    end
  end

  desc 'Custom post-start action'
  task :poststart do
    on roles(:app) do
        puts "No custom poststart action"
    end
  end
end
~~~

### Store
- /apps/dpr2store/tools/deploy/deploy_semver.sh
- /apps/dpr2store/tools/deploy/mrt-tomcat/config/deploy/uc3-mrt-store-prd.rb

#### deploy_semver.sh
~~~
#!/usr/bin/env bash

# Support new semantic Jenkins pipeline
# Usage:
#   export MERRITT_STORAGE_RELEASE=<semver>
#   ./deploy_semver.sh


if [ -n "$MERRITT_STORAGE_RELEASE" ]; then
    cd /apps/dpr2store/tools/deploy/mrt-tomcat
    MERRITT_STORAGE_RELEASE=${MERRITT_STORAGE_RELEASE} cap uc3-mrt-store-prd deploy
else
  echo "Must define Environment variable MERRITT_STORAGE_RELEASE"
fi

exit
~~~

#### uc3-mrt-store-prd.rb
~~~
# Simple Role Syntax
# ==================
# Supports bulk-adding hosts to roles, the primary
# server in each group is considered to be the first
# unless any hosts have the primary property set.
# Don't declare `role :all`, it's a meta role
#role :app, %w{mark.reyes@ucop.edu}
#role :web, %w{mark.reyes@ucop.edu}

# Extended Server Syntax
# ======================
# This can be used to drop a more detailed server
# definition into the server list. The second argument
# something that quacks like a hash can be used to set
# extended properties on the server.
# ---- Needed for non-rails deployment???
set :rails_env, "uc3-mrt-store-prd"

puts "----- uc3-mrt-store-prd branch of https://github.com/CDLUC3/tomcat8_catalina_base -----"
set :repo_url, "https://github.com/CDLUC3/tomcat8_catalina_base"
set :branch, "uc3-mrt-store-prd"

set :application, "merritt-store"
set :semantic_version, ENV['MERRITT_STORE_RELEASE'] || 'undefined'
set :build_url, "http://builds.cdlib.org/userContent/mrt-store/mrt-store-#{fetch(:semantic_version)}.war"

set :target, "storage.war"
set :deploy_to, "/dpr2store/apps/storage35121"

set :tomcat_pid, "#{fetch(:deploy_to)}/storage.pid"
set :tomcat_log, "#{fetch(:deploy_to)}/shared/log/tomcat.log"

# additional directories needed by storage
set :linked_dirs, fetch(:linked_dirs).push("webapps/container")

server "localhost", user: "dpr2store", roles: %w{web app}

# custom
namespace :custom do

  desc 'Custom deploy action'
  task :deploy_bits do
    on roles(:app) do
        puts "Add source code version to Tomcat directory"
        execute "/usr/bin/curl --silent -X GET https://api.github.com/repos/cdluc3/mrt-store/commits | /bin/fgrep 'sha' | /usr/bin/head -1 >> /dpr2store/apps/storage35121/version"
    end
  end

  desc 'Custom pre-stop action'
  task :prestop do
    on roles(:app) do
        puts "No custom prestop action"
    end
  end

  desc 'Custom post-start action'
  task :poststart do
    on roles(:app) do
        puts "No custom poststart action"
    end
  end
end
~~~

**Comment by elopatin-uc3** [comment]
David is planning to wait until Mark is back from break to deploy.

**Comment by dloy** [comment]
Production storage servers comple 6/22/2022.

**Comment by dloy** [comment]
## Access servers deploy on 6/28 - 4pm. 

Access server deploy will require that:
access02 be paused for processing large zip content
access01 and access03 will be:
- removed from ALB
- deployed
- restored to ALB

No down time is expected for this service. Additional access times on return of zip content will increase by at least 15 minutes during  this update.
