### ISSUE TITLE
UCI Nuxeo feed: Spectre

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1074]
Source ticket: https://help.oac.cdlib.org/a/tickets/107081

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/26696/

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_26696.atom

Root folder in Nuxeo:
https://nuxeo.cdlib.org/nuxeo/nxpath/default/asset-library/UCI/SCA_UniversityArchives/Publications/Spectre

Merritt collection:
UC Irvine Library SCA University Publications
ark:/13030/m5549nb2

**Comment by mreyescdl** [comment]
Ran manually - 1 object total

Enabled cron

Ticket complete

**Comment by elopatin-uc3** [comment]
Thanks, Mark; requestor notified
