### ISSUE TITLE
UCI Nuxeo feed: Spectrum

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1075]
Source ticket: https://help.oac.cdlib.org/a/tickets/107084

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/26697/

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_26697.atom

Root folder in Nuxeo:
https://nuxeo.cdlib.org/nuxeo/nxpath/default/asset-library/UCI/SCA_UniversityArchives/Publications/Spectrum

Merritt collection:
UC Irvine Library SCA University Publications
ark:/13030/m5549nb2

**Comment by mreyescdl** [comment]
Created script: production-26697-UC-Irvine-Library-SCA-UPub-Spectrum-uci_lib_sca_upub.csh

Nuxeo feed not available yet

Create Puppet Cron entry, but set to disable.  Set to run at 03:40

To do: When feed available:

  - run manually
  - Enable cron entry

**Comment by mreyescdl** [comment]
Feed still unavailable

**Comment by mreyescdl** [comment]
Ran manually - 11 objects

Enabling weekly cron - 0340 on Thursday

Ticket complete

**Comment by elopatin-uc3** [comment]
Thanks, @mreyescdl!
