### ISSUE TITLE
UCI Nuxeo feed: Newporter

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1076]
Source ticket: https://help.oac.cdlib.org/a/tickets/107085

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/26700/

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_26700.atom

Root folder in Nuxeo:
https://nuxeo.cdlib.org/nuxeo/nxpath/default/asset-library/UCI/SCA_UniversityArchives/Publications/Newporter

Merritt collection:
UC Irvine Library SCA University Publications
ark:/13030/m5549nb2

**Comment by mreyescdl** [comment]
Created script: production-26700-UC-Irvine-Library-SCA-UPub-Newporter-uci_lib_sca_upub.csh

Nuxeo feed not available yet

Create Puppet Cron entry, but set to disable. Set to run at 03:35

To do: When feed available:

run manually
Enable cron entry

**Comment by mreyescdl** [comment]
Manually run - 1 object

Enabled Cron

Ticket complete

**Comment by elopatin-uc3** [comment]
Thanks, Mark; requestor notified.
