### ISSUE TITLE
UCI Nuxeo feed: UCI General Catalogue

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1078]
Source ticket: https://help.oac.cdlib.org/a/tickets/107088

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/26699

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_26699.atom

Root folder in Nuxeo:
https://nuxeo.cdlib.org/nuxeo/nxpath/default/asset-library/UCI/SCA_UniversityArchives/Publications/Course Catalogs

Merritt collection:
UC Irvine Library SCA University Publications
ark:/13030/m5549nb2

**Comment by mreyescdl** [comment]
Created script: production-26699-UC-Irvine-Library-SCA-UPub-General-Catalogue-uci_lib_sca_upub.csh

Nuxeo feed not available yet

Create Puppet Cron entry, but set to disable. Set to run at 03:25

To do: When feed available:
  - run manually
  - Enable cron entry

**Comment by elopatin-uc3** [comment]
Thanks again Mark; I've let the requestor know this deposit is complete.
