### ISSUE TITLE
mrt-tomcat - master to main and Puppet

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#1079]
## Problem
 mrt-tomcat repository is used to:
- support construction of mrtHome on microservices. This need is deprecated and now is only used on store (gone with refactor), sword, and oai
- provide the Capistrano ruby scripts used for deploying content to tomcat based on Jenkins.

Github has requested a migration of the HEAD from master to the main branch.  This change was recently made in the Github mrt-tomcat but each Merritt tomcat host has its own local version that continues to contain the master branch that is no long present remotely.

Puppet cycles the local mrt-tomcat repositories every few minutes. After this cycle the local mrt-tomcat will no longer point to main but to master - if a master branch exists.

With storage refactoring the Puppet cycle branch change had the impact of restoring the master version of the deploy ruby script and of resetting the war. In some cases the war was replaced (storage) with an earlier war version and with access the war was removed.  How the war handling takes place in regards to Puppet, I am not clear. 

This problem exists on all of our tomcat servers. This problem needs to be fixed before any future redeploys take place. **This is a prerequisite for both the storage production redeploys and also all Dryad glacier bucket redeploys.**

## A manual solution
One manual process to fixed these problems:
- move the local /apps/dpr2store/tools/deploy/mrt-tomcat to say /apps/dpr2store/tools/deploy/mrt-tomcat.220602
- git clone https://github.com/CDLUC3/mrt-tomcat

With the new mrt-tomcat the deploy scripts were not replaced or destroyed by the Puppet cycle, and the local war file was not replaced or destroyed. 

My attempts to pull the needed changes in did not initially work because of local merges that were manually required. Totally replacing the repository did work.

## Puppet solution
If there is an automated way to totally replace the existing mrt-tomcat to eliminate the master branch - this would be preferred. 

I do not understand the details of how Puppet:
- forces the HEAD->master 
- how it destroys or replaces the local war

From what I have observed replacing mrt-tomcat with the current version (e.g. move and new clone) works.

I'm hoping someone familiar with this process can provide a better solution than manually replacing all mrt-tomcat.

**Comment by dloy** [comment]
### Some notes on Puppet issues
Puppet was specifically set up on store and access servers to automatically deploy using Capistrano, if the latest version was different than latest on the machine. 

The server was forced to use "master" for resolving a version change. The master branch contained an older version for the deploy and used an old version of the deploy script.

The deploy for refactor involves an environment variable that may or may not be preserved on the server. Any attempt to use the new refactor deploy scripts automatically will fail without the semantic tag (e.g. 0.0.16)

Ashley has turned off the automatic deploy handling for the only 2 services having it - storage and access.

**Comment by elopatin-uc3** [comment]
Puppet is no longer managing sword-info.txt. Closing
