### ISSUE TITLE
[Ingest] Change Worker pool size and Download thread count (EFS performance related)

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#1080]
EFS performance issue with UCSF Glantz and large UCB submission.  Analysis for root cause is still ongoing, but it seems to be related to:

- EFS throughput
- Network I/O for EC2 hosts

Short term fix is to reduce the processing capacity for each Ingest worker:

- Worker thread count is SSM var
- Download thread count is hard coded (part of this tix is to make this an SSM var)

**Comment by mreyescdl** [comment]
STAGE
Created new SSM parm
     /uc3/mrt/stg/ingest/config/numDownloadThreads   3

Altered parm
      /uc3/mrt/stg/ingest/config/numThreads   3

Deployed to stage tag: 0.0.26.dev01  (threadPool branch)

**Comment by elopatin-uc3** [comment]
The current plan is to make this change in production when Mark is back (after 6/16).

**Comment by mreyescdl** [comment]
PRODUCTION
Created new SSM parm
/uc3/mrt/prd/ingest/config/numDownloadThreads 3

Altered parm
/uc3/mrt/prd/ingest/config/numThreads 3


Will deploy using tag 0.0.26

**Comment by mreyescdl** [comment]
Release complete: 
     https://github.com/CDLUC3/mrt-doc/issues/1101
