### ISSUE TITLE
Merritt Admin Tool Usability Testing

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1081]
Terry and Rachael met on 6/3 to discuss an approach for this testing.

## Environments to be used
- Admin Tool: Prod and Stage can be accessed
- Collection Admin Tool: Rachael and Jane can be given STAGE access
  - We can grant access once you have logged into the main admin tool

## Pages
These pages use mustache templates for rendering.
- Admin Tool Pages: https://github.com/CDLUC3/mrt-admin-lambda/tree/main/src-admintool/web
  - Sub applications
    - Reports
    - Consistency Reports  
- Collection Admin Tool Pages: https://github.com/CDLUC3/mrt-admin-lambda/tree/main/src-colladmin/web
  - Sub applications
    - Reports
    - Ingest Queue
    - Collection Creation 
      - Eric has recorded a video illustrating the use of this tool.  When we tackle this one, it might be worth reviewing. 
    - Storage Admin
    - Storage Scan
 
## Functions
The majority of both tools function as a single page app that displays different reports.  Those reports are defined in a yaml file.
- Admin Tool Reports: https://github.com/CDLUC3/mrt-admin-lambda/blob/main/src-admintool/config/reports.yml
- Collection Admin Tool Reports: https://github.com/CDLUC3/mrt-admin-lambda/blob/main/src-colladmin/config/actions.yml
  - Some of these actions are reports.  Some of these actions occur when a button is pressed. 

## Data Types
- Data Type Icons
  - https://github.com/CDLUC3/mrt-admin-lambda/tree/main/src-common
- Every report column has a header
- Many report columns have a data type
- Some data types have special CSS rules (look for td.class and th.class)
  - https://github.com/CDLUC3/mrt-admin-lambda/blob/main/src-common/template/api-table.css
- Some data types have special rules to convert a text value into a hyperlink (to both admin tools or to merritt)
  - https://github.com/CDLUC3/mrt-admin-lambda/blob/main/src-common/template/api-table.js#L497-L708
- At a minimum, it would be valuable to catalog and assign a meaning to each data type
  - I imagine that it could be useful to assign icons to the data types to help a user know where they are going when a link is clicked

## Use Cases
- Check system consistency reports
  - Daily; Eric, Terry, Mark
- Resolve consistency report issues - restart ingest job, audit for object, replication for object
  - Daily: Eric, Terry, Mark
- Run ad-hoc report to answer a question about the system data
  - Weekly: Eric, Terry, Marisa
- Run report to verify system configuration details (server names, server types, ssm params)
  - Weekly: Terry, Eric
- Prepare reports for campus contacts or for publishing a blog post
  - Obtain submission metrics active collections, organized by campus
  - Also FY start vs. to-date, high-level storage use data
  - Monthly: Eric
- Configure new Merritt collections
  - Monthly: Eric 
- Scan storage nodes to look for stray content
  - Quarterly: Terry      
- Answer questions about a specific Merritt object
  - Weekly: Terry, Eric
- Answer questions about specific Merritt submissions
  - Typically viewed via collection and batch-specific metrics
  - Weekly: Eric, Mark
- Monitor progress for a specific Merritt submission
  - Typically viewed via collection and batch-specific metrics
  - Weekly: Eric, Mark
- Review report results posted into a slack discussion or a zoom meeting
  - Weekly: Eric, Terry, Mark, David, Marisa, Ashley, Scott, Martin
- Pause/unpause Merritt submissions for server patching and software releases
  - Monthly: Eric, Terry, Mark, Ashley 
- Prepare collection or owner-specific storage forecast for campuses
  - Monthly: Eric
- Prepare Merritt charge-back reports for campuses
  - Filtering by campus or campus unit
  - Annually: Eric

## Troubleshooting Guide (links back to the Collection Admin Tool pages)
- https://github.com/CDLUC3/mrt-doc-private/blob/main/docs/system-recovery/README.md#data-issues

## Hierarchy Page
- https://github.com/CDLUC3/mrt-admin-lambda/blob/main/src-hier/hier.md

**Comment by terrywbrady** [comment]
Already discussed:
- New landing page

Potentials focus areas we discussed on 1/6:
- improve icon based navigation
- define breadcrumb usability
- improve table crontrols

**Comment by elopatin-uc3** [comment]
Remaining areas we're waiting to hear back from UX about:
- improve icon based navigation
- improve table controls

**Comment by elopatin-uc3** [comment]
New input and deliverables from UX, reviewed on 6/27/23.

**Comment by terrywbrady** [comment]
@elopatin-uc3 , I recommend we close this now that we have the follow up tickets in place

**Comment by elopatin-uc3** [comment]
New tickets that were created: 1514-1517
