### ISSUE TITLE
UCB Object cleanup on EFS

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1093]
1. Check the **List Ingest Queue Profile Counts** report in Collection admin for **ucb_lib_prechmat_content** entries:
https://merritt-colladmin.cdlib.org/web/collIndex.html?path=ingest-queue-by-profile

2. **After** all **UC Berkeley Pre 1912 Chinese Materials submissions have completed**, we need to clean up leftover files on the EFS from the following batches:

bid-6ebfc64a-e527-477a-ab47-83ce01440089
bid-4feb8ca4-fb3a-4538-8ba9-4de833f6cea0
bid-6ebfc64a-e527-477a-ab47-83ce01440089

**Comment by mreyescdl** [comment]
Updated metadata with a second version for objects:

```
https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm52c6309
https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm5zm2mn0
```

**Comment by mreyescdl** [comment]
Cleaned up batch folders listed above (3 total)
However, there is still 4.8TB on disk.   Will investigate

**Comment by mreyescdl** [comment]
Disk is pretty clean.  Just a discrepancy between "df" and "du" results.  

```
$ df -h .
Filesystem                                 Size  Used Avail Use% Mounted on
fs-3b22fd91.efs.us-west-2.amazonaws.com:/  8.0E  4.7T  8.0E   1% /apps/ingest-prd-shared

$ du -sh .
2.5G    .
```
