### ISSUE TITLE
Sword - yaml and refactor conversion

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#1096]
## Earlier Issue
This Issue details the specific update needs of Sword 

An earlier Issue for the yaml conversion of both Sword and OAI is:
https://github.com/CDLUC3/mrt-doc/issues/609

## Sword upgrade
The Sword service that is specifically used by Dryad for content interactions with Merritt has not been updated to meet either the yaml or refactor needs of other Merritt microservices.

### Yaml conversion
The general requirement of the yaml conversion is to make the microservice more portable without being being tied to a specific file architecture. This architecture is more amenable to docker handling.

Currently all properties used by sword for processing are extracted from the mrtHome/sword/sword-info.txt and a Properties file specific to the environment (stage and prod).  These properties need to be upgraded for extraction from a yaml file saved as a jar with specific  dynamic and update content being set from an SSM repository specific to stage and prod values.  A major feature of this upgrade is the removal of proprietary content (passwords) from local configurations.

Part of this conversion is setting the microservice log path dynamically as an environment variable.

### Refactor conversion
Refactor program changes includes the following:
- upgrade local jars to meet github depandabot needs
- use of Jenkinsfile for build
- github migration of HEAD from master to main

External refactor changes include
- Merritt development Jenkins refactor method
- upgrade of  Capistrano deploy scripts
- upgrade of local environment variables to support deploy

**Comment by elopatin-uc3** [comment]
Thanks for noting the earlier issue @dloy .
