### ISSUE TITLE
Merritt RDS Size

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1097]
Ashley noted that we are gradually approaching the size allocation for the Merritt Inventory Database.  

When the database size is increased, there is an opportunity to grow to a size that would provide a dramatic increase in IO burst credits.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volume-types.html#EBSVolumeTypes_gp2

Just putting this on our radar to track.

**Comment by ashleygould** [comment]
Current size is 200GB with 28.4GB free space remaining - roughly 85% full.
Disk usage increasing by about 2GB per month.  Current cost for disk is $46.00/month
($0.23 per GB per month)

At 200GB our baseline IOPs is 600. Sustaining a load of 3000 IOPS will deplete burst credits in less than 40 minutes. IOPS must remain lower than baseline for 2 hours for burst credits to recover.

Increasing allocated disk space to 300GB will increase our baseline IOPs to 900.  The cost for disk would be about $70.00/month .
