### ISSUE TITLE
Resolve issues with the ingest load balancer used by sword

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1098]
See also, https://github.com/CDLUC3/mrt-doc/issues/1065

**Sever Patching on 6/7** 

Resulted in an after-hours emergency.

Sword was no longer able to talk to ingest.  

_sword-info.txt was using an address that no longer exists. (I think)._

To resolve, sword requests were routed to ingest02-aws.cdlib.org

**6/15 - Ashley, David, Eric, Scott, Terry met**

Scott paused submissions.

Modified sword-info.txt to use ingest.cdlib.org.  _This is now under puppet control_

The sword service immediately saw failures.

Scott saw failures.

The value was reset to ingest01-aws.cdlib.org.

**David recommended that Mark investigate**

The assumption is that there is something about the synchronous request that caused this failure.

**Comment by dloy** [comment]
## Maybe related to this problem for using merritt.cdlib.org:33121
### using nslookup
~~~
> nslookup
> set q=cname
> merritt.cdlib.org
	Server:         172.31.0.2
	Address:        172.31.0.2#53

> merritt-aws.cdlib.org
Server:         172.31.0.2
Address:        172.31.0.2#53

Non-authoritative answer:
merritt-aws.cdlib.org   canonical name = uc3-mrtweb01x2-prd.cdlib.org.

~~~

### looking at apache uc3-mrtweb01x2-prd:/apps/apache/conf/conf.d/mrt.conf
~~~
<VirtualHost *:18880>
    ServerName merritt-aws.cdlib.org
    ServerAlias merritt.cdlib.org
...
 RewriteRule ^/ingest-balancer-manager$ http://uc3-mrtweb-prd.cdlib.org:33121/balancer-manager [P,QSA,L]
...


mrt.conf:        BalancerMember http://ingest01-aws.cdlib.org:33121 max=1 acquire=1
mrt.conf:        BalancerMember http://ingest02-aws.cdlib.org:33121 max=1 acquire=1
mrt.conf:        BalancerMember http://ingest03-aws.cdlib.org:33121 max=1 acquire=1
~~~

Note that uc3-mrtweb01x2-prd does have a running port=33121

~~~-bash-4.2$ telnet uc3-mrtweb01x2-prd 33121
Trying 172.30.20.236..
Connected to uc3-mrtweb01x2-prd.
Escape character is '^]'.
^]
~~~

### Comments
- appears merritt.cdlib.org was originally CNAMEd to uc3-mrtweb01x2-prd for the apache ingest load balancer
- CNAME now points to a ui load balancer
- suspect Rewrite rules for apache did allow for synchronous connections

### From Martin
~~~

[martin_haye](https://app.slack.com/team/U02FC7LUF)
  [9:25 AM](https://cdlib.slack.com/archives/D016DF52DFV/p1655483158085229)
The change was made June 9 last year (2021) at 5:12 pm

commit bc0f880f95b17e3aa04d095f456cd6923d22bd1b
Author: cdlinfra <cdlinfra@cdlib.org>
Date:   Wed Jun 9 17:12:56 2021 -0700

    Updated cdlib.org hosted zones. Changed merritt.cdlib.org to now use uc3-mrtui-prd-alb. + Joe

diff --git a/route53/output/cdlib.org.hz b/route53/output/cdlib.org.hz
index 39b9545f..bbb4df90 100644
--- a/route53/output/cdlib.org.hz
+++ b/route53/output/cdlib.org.hz
@@ -3135,7 +3135,7 @@
         {
             "ResourceRecords": [
                 {
-                    "Value": "uc3-mrtweb01x2-prd.cdlib.org"
+                    "Value": "uc3-mrtui-prd-alb-742655803.us-west-2.elb.amazonaws.com"
                 }
             ], 
             "Type": "CNAME",
~~~

***The remaining mystery is why it took so long for this to break**

**Comment by terrywbrady** [comment]
Mark, David, Scott, Ashley and Terry met and successfully deployed this change.

David confirmed the fix in the Sword logs.

Scott successfully sent an ADD and an UPDATE through the system.
