### ISSUE TITLE
UCM Nuxeo feed: UCANR, UC Cooperative Extension Records

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1115]
Source ticket: https://help.oac.cdlib.org/a/tickets/107288

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/27754/

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27754.atom

Root folder in Nuxeo:
https://nuxeo.cdlib.org/nuxeo/nxdoc/default/86f135dd-9542-43f6-9a2b-ad8740417b26/view_documents

Merritt collection:
UC Merced Library UCCE ANR
ark:/13030/m5pk7bc5

**Comment by mreyescdl** [comment]
@elopatin-uc3 Feed not yet available.  I'll try on Wednesday

**Comment by mreyescdl** [comment]
@elopatin-uc3 
Feed is now available - 191 entries
Is this okay to run?

**Comment by elopatin-uc3** [comment]
@mreyescdl , yes, all good to run this one. Thanks for checking in.

**Comment by mreyescdl** [comment]
Script already exists and current production contains 10 objects.
production-27754-UCM-UCANR-UC-Cooperative-Extension-Records-ucm_lib_ucce_anr.csh

Current feed has 191 entries, so lets run and sync Merritt collection with feed

**Comment by mreyescdl** [comment]
Manual run is complete - now at 191 objects, as expected.

Already scheduled to run at 03:20 on Thursday.

Ticket complete
