### ISSUE TITLE
[Build] Modify all Jenkins jobs to use Jenkinsfile

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#112]
Possible prereqs:
- install Pipeline plugin, anything else we need
- create new jobs in parallel so we don't break old ones

For each of the repositories below, add a [Declarative Pipeline](https://jenkins.io/doc/book/pipeline/#declarative-versus-scripted-pipeline-syntax) [Jenkinsfile](https://jenkins.io/doc/book/pipeline/jenkinsfile/) to support the jobs built from that repository (listed below), and modify the jobs to use that Jenkinsfile.

(For a rough example, see [the Jenkinsfile in this fork of mrt-core2](https://github.com/dmolesUC3/mrt-core2/blob/master/Jenkinsfile). Note though that the "JDK" parameter values and "maven" tool name set in that Jenkinsfile don't match the ones on builds.cdlib.org.)

- [cdl-zk-queue](https://github.com/CDLUC3/cdl-zk-queue) (builds [cdl-zk-queue](http://builds.cdlib.org/job/cdl-zk-queue))
- [mrt-audit](https://github.com/CDLUC3/mrt-audit) (builds [mrt-build-audit](http://builds.cdlib.org/job/mrt-build-audit))
- [mrt-cloudhost-pub](https://github.com/CDLUC3/mrt-cloudhost-pub) (builds [mrt-cloudhost-pub](http://builds.cdlib.org/job/mrt-cloudhost-pub), [mrt-jetty-cloudhost](http://builds.cdlib.org/job/mrt-jetty-cloudhost))
- [mrt-conf-prv](https://github.com/cdlib/mrt-conf-prv) (builds [git-mrt-xoai](http://builds.cdlib.org/job/git-mrt-xoai), [mrt-build-mysql](http://builds.cdlib.org/job/mrt-build-mysql), [mrt-build-s3](http://builds.cdlib.org/job/mrt-build-s3), [mrt-build-store](http://builds.cdlib.org/job/mrt-build-store))
- [mrt-core2](https://github.com/CDLUC3/mrt-core2) (builds [git-core2](http://builds.cdlib.org/job/git-core2))
- [mrt-dataONE](https://github.com/CDLUC3/mrt-dataONE) (builds [git-dataONE](http://builds.cdlib.org/job/git-dataONE))
- [mrt-ingest](https://github.com/CDLUC3/mrt-ingest) (builds [mrt-ingest-dev](http://builds.cdlib.org/job/mrt-ingest-dev), [mrt-ingest-stage](http://builds.cdlib.org/job/mrt-ingest-stage))
- [mrt-inventory](https://github.com/CDLUC3/mrt-inventory) (builds [mrt-build-inv](http://builds.cdlib.org/job/mrt-build-inv))
- [mrt-oai](https://github.com/CDLUC3/mrt-oai) (builds [mrt-build-oai](http://builds.cdlib.org/job/mrt-build-oai))
- [mrt-replic](https://github.com/CDLUC3/mrt-replic) (builds [mrt-build-replic](http://builds.cdlib.org/job/mrt-build-replic))
- [mrt-s3-pub](https://github.com/CDLUC3/mrt-s3-pub) (builds [mrt-s3-pub](http://builds.cdlib.org/job/mrt-s3-pub))
- [mrt-store](https://github.com/CDLUC3/mrt-store) (builds [mrt-store-pub](http://builds.cdlib.org/job/mrt-store-pub))
- [mrt-sword](https://github.com/CDLUC3/mrt-sword) (builds [mrt-build-sword](http://builds.cdlib.org/job/mrt-build-sword))
- [mrt-zoo](https://github.com/CDLUC3/mrt-zoo) (builds [git-mrt-zoo](http://builds.cdlib.org/job/git-mrt-zoo))

 - [ ] cdl-zk-queue
 - [ ] mrt-audit
 - [ ] mrt-cloudhost-pub
 - [ ] mrt-conf-prv
 - [ ] mrt-core2
 - [ ] mrt-dataONE
 - [ ] mrt-ingest
 - [ ] mrt-inventory
 - [ ] mrt-oai
 - [ ] mrt-replic
 - [ ] mrt-s3-pub
 - [ ] mrt-store
 - [ ] mrt-sword
 - [ ] mrt-zoo

**Comment by terrywbrady** [comment]
@elopatin-uc3 , closing based on the build refactor work in progress
