### ISSUE TITLE
Test shorter timeout for synchronous ingests (phase out Apache Load Balancers)

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1121]
See #977 

Mark will change the timeout on the Apache Load Balancer to 15 minutes
- Send a large manifest and start a synchronous deposit via ingest curl client
  - Request should timeout before ingest completes 
  - Confirm that ingest completes
- Send a large manifest and start a synchronous deposit via sword client
  - Same tests as above
- Send a large manifest twice using the same local id
  - Ensure that the system gracefully generates an object with 2 versions

If these tests succeed, initiate the request for a new Amazon load balancer for ingest.
- Set timeout to 1hr (4000s is the max) or a lower value if Scott prefers it
- Re-use ingest.cdlib.org as the name
- decommission the apache configuration for ingest

Create a new ticket and begin work on replacing the Storage load balancer

- [x] Test using cURL client
- [x] Test using Sword client
- [ ] Test using concurrent clients

**Comment by elopatin-uc3** [comment]
Noting #1100 for reference.

**Comment by mreyescdl** [comment]
Submission success after a 5 minute Apache timeout drops connection.
Test was done using a cURL client

https://merritt-stage.cdlib.org/m/ark%253A%252F99999%252Ffk47m1t29r

**Comment by mreyescdl** [comment]
Sword client success:
https://merritt-stage.cdlib.org/m/ark%253A%252F99999%252Ffk4gx5tx78

**Comment by mreyescdl** [comment]
Concurrent Sword submission fails:

```
[info] PUT error: bad request - identifier already exists
```

URL endpoint must point to ADD, not UPDATE: http://uc3-mrtsword01x2-stg.cdlib.org:39001/mrtsword/collection/merritt_demo

**Comment by mreyescdl** [comment]
Talking with David.  We can not use cURL to test the concurrent submission as it only supports an ADD
From David:
```
The problem is that the update request requires java construction. It is a 15 year old multipart that is no longer supported by curl - its an old mail multipart.
```

**Comment by mreyescdl** [comment]
Starting switch to ALB
https://github.com/CDLUC3/mrt-doc/issues/1137
