### ISSUE TITLE
UCI Nuxeo feed: Athletics and Physical Education records, Athletics Press Releases series

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1124]
Source ticket: https://help.oac.cdlib.org/a/tickets/107089

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/26854

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_26854.atom

Root folder in Nuxeo:
https://nuxeo.cdlib.org/nuxeo/nxpath/default/asset-library/UCI/SCA_UniversityArchives/AS-063/UCI%20Athletics%20News%20Releases

Merritt collection:
UC Irvine SCA University Archives
ark:/13030/m5bk6qsm

**Comment by mreyescdl** [comment]
- Created script: production-26854-UC-Irvine-Athletics-and-Physical-Education-Records-uci_lib_sca_ua.csh
- Manually running script which will create 25 objects
- Scheduling weekly running of script at 03:15 Thursday
- Checking in script to config repo
