### ISSUE TITLE
UCI Nuxeo feed: Early Campus Photograph Albums

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1125]
Source ticket: https://help.oac.cdlib.org/a/tickets/107120

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/194

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_194.atom

Root folder in Nuxeo:
https://nuxeo.cdlib.org/nuxeo/nxpath/default/asset-library/UCI/SCA_UniversityArchives/AS-056/Publish/Photographs

Merritt collection:
UC Irvine SCA University Archives
ark:/13030/m5bk6qsm

**Comment by mreyescdl** [comment]
- Created script: production-194-UC-Irvine-Early-Campus-Photograph-Albums-uci_lib_sca_ua.csh
- Checking script into repo
- Running script manually: 370 objects
- Scheduling script for weekly run: 03:10 on Thursday
