### ISSUE TITLE
UCI Nuxeo feed: O'Donnell (Patrick) University California, Irvine Photographs

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1126]
Source ticket: https://help.oac.cdlib.org/a/tickets/107123

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/25889

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_25889.atom

Root folder in Nuxeo:
https://nuxeo.cdlib.org/nuxeo/nxpath/default/asset-library/UCI/SCA_UniversityArchives/AS-164/PUBLISH

Merritt collection:
UC Irvine SCA University Archives
ark:/13030/m5bk6qsm

**Comment by mreyescdl** [comment]
Ticket complete
