### ISSUE TITLE
UCI Nuxeo feed: Olin (Spencer) oral histories of University of California, Irvine faculty and staff

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1127]
Source ticket: https://help.oac.cdlib.org/a/tickets/107124

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/26855

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_26855.atom

Root folder in Nuxeo:
https://nuxeo.cdlib.org/nuxeo/nxpath/default/asset-library/UCI/SCA_UniversityArchives/AS-145

Merritt collection:
UC Irvine SCA University Archives
ark:/13030/m5bk6qsm

**Comment by mreyescdl** [comment]
Feed not yet available

**Comment by elopatin-uc3** [comment]
@mreyescdl We had the wrong feed URL. This is the correct one (updated above in the description):
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_16180.atom

Please update this in the cron, thanks!

**Comment by gamontoya** [comment]
@mreyescdl I gave Eric the wrong collection registry ID. It is:

https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_**25885**.atom

**Comment by mreyescdl** [comment]
@elopatin-uc3 
This feed has 8 entries.  Is this okay to set up?  I'll use the following name:

    UCI Nuxeo feed: Olin (Spencer) oral histories

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl . Yes, please go ahead and set this one up.

**Comment by mreyescdl** [comment]
Current collection in Merritt has 565 objects.
This new feed will add 8 more objects to it.
Script created and will run manually - production-26855-UC-Irvine-Olin-Spencer-oral-histories-uci_lib_sca_ua.csh

**Comment by mreyescdl** [comment]
Manual submission completed.  Checked script into repository and scheduled in Puppet for 02:10 Thursday

Ticket complete
