### ISSUE TITLE
UCI Nuxeo feed: Audio Recordings collection (University of California, Irvine)

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1129]
Source ticket: https://help.oac.cdlib.org/a/tickets/107127

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/1324

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_1324.atom

Root folder in Nuxeo:
https://nuxeo.cdlib.org/nuxeo/nxpath/default/asset-library/UCI/SCA_UniversityArchives/AS-152

Merritt collection:
UC Irvine SCA University Archives
ark:/13030/m5bk6qsm

**Comment by mreyescdl** [comment]
- Created script: production-1324-UC-Irvine-Audio-Recordings-Collection-uci_lib_sca_ua.csh
- Manually running script - 174 objects
- Check script into repo
- Weekly schedule of script via Puppet - 03:00 Thursday

**Comment by mreyescdl** [comment]
Ticket is complete
