### ISSUE TITLE
docker network on mrt-sandbox issue

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1134]
[Colin Thompson](https://app.slack.com/team/U026UM9834J)
  [8:47 AM](https://cdlib.slack.com/archives/C19KCRAEB/p1657554470083839)
I have a ticket to configure the address pool on uc3-mrtsandbox2-stg.  I've added the line to the config file, but the docker daemon needs to be restarted.  Please let me know if/when I can do that.  Looks like 
[@dloy](https://cdlib.slack.com/team/U0DEUQKH9)
 is logged in at the moment.

[dloy](https://app.slack.com/team/U0DEUQKH9)
  [8:49 AM](https://cdlib.slack.com/archives/C19KCRAEB/p1657554571727519)
Colin go for doing whatever you need on this 
[@Colin Thompson](https://cdlib.slack.com/team/U026VMXB4UA)
[8:52](https://cdlib.slack.com/archives/C19KCRAEB/p1657554769559789)
[@Colin Thompson](https://cdlib.slack.com/team/U026UM9834J)
 off uc3-mrtsandbox2-stg

[Colin Thompson](https://app.slack.com/team/U026UM9834J)
  [9:01 AM](https://cdlib.slack.com/archives/C19KCRAEB/p1657555268187309)
hmm... I think that broke it.  I'm gonna try rebooting, if that's okay with you.

[Colin Thompson](https://app.slack.com/team/U026UM9834J)
  [9:11 AM](https://cdlib.slack.com/archives/C19KCRAEB/p1657555869123929)
yeah, it's pretty broken.  I think whatever I did took out the whole network stack on the box.  ec2 doesn't seem to think it's stopping.  We're probably looking at a restore.
[9:12](https://cdlib.slack.com/archives/C19KCRAEB/p1657555943848219)
Well, now it seems to be in a stopping state.

[Ashley Gould](https://app.slack.com/team/U011A1ERK54)
  [9:15 AM](https://cdlib.slack.com/archives/C19KCRAEB/p1657556153558919)
by chance is this host in a different vpc or cidr block than the uc3-mrt-docker-dev hosts?

[Colin Thompson](https://app.slack.com/team/U026UM9834J)
  [9:22 AM](https://cdlib.slack.com/archives/C19KCRAEB/p1657556549624049)
same vpc, different subnet
[9:22](https://cdlib.slack.com/archives/C19KCRAEB/p1657556570538429)
it's back now, btw.  Fortunately the docker daemon didn't start on the reboot.
[9:23](https://cdlib.slack.com/archives/C19KCRAEB/p1657556590140959)
I suspect it will die again if we try to start it without removing that config.

[Colin Thompson](https://app.slack.com/team/U026UM9834J)
  [9:36 AM](https://cdlib.slack.com/archives/C19KCRAEB/p1657557400242489)
I've removed the address pool line and restart the docker daemon and it appears to be okay.  Let me know if/when you'd like me to try again.  docker is enabled in systemd, but it looks like it fails to start with a socket problem, which is probably a good thing for troubleshooting purposes.
Jul 11 08:39:20 uc3-mrtsandbox2-stg systemd: Reached target Timers.
Jul 11 08:39:20 uc3-mrtsandbox2-stg systemd: Starting Docker Socket for the API.
Jul 11 08:39:20 uc3-mrtsandbox2-stg systemd: Failed to chown socket at step GROUP: No such file or directory
Jul 11 08:39:20 uc3-mrtsandbox2-stg systemd: docker.socket control process exited, code=exited status=216
Jul 11 08:39:20 uc3-mrtsandbox2-stg systemd: Failed to listen on Docker Socket for the API.
Jul 11 08:39:20 uc3-mrtsandbox2-stg systemd: Dependency failed for Docker Application Container Engine.
Jul 11 08:39:20 uc3-mrtsandbox2-stg systemd: Job docker.service/start failed with result 'dependency'.
Jul 11 08:39:20 uc3-mrtsandbox2-stg systemd: Unit docker.socket entered failed state.
Jul 11 08:39:20 uc3-mrtsandbox2-stg systemd: Reached target Sockets.

---

## Notes from Feb 19-23, 2021

```

Here's what I think happened to mrtdocker03. There was a proliferation of "bridge" networks introduced by docker. Here's the output of netstat -r:
[ec2-user@uc3-mrtdocker03x2-dev ~]$ netstat -r
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
default         gateway         0.0.0.0         UG        0 0          0 eth0
instance-data.u 0.0.0.0         255.255.255.255 UH        0 0          0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U         0 0          0 docker0
172.18.0.0      0.0.0.0         255.255.0.0     U         0 0          0 br-7eb260682106
172.21.0.0      0.0.0.0         255.255.0.0     U         0 0          0 br-f61de1bfef8e
172.22.0.0      0.0.0.0         255.255.0.0     U         0 0          0 br-3e77537854ba
172.23.0.0      0.0.0.0         255.255.0.0     U         0 0          0 br-3a2097b8223b
172.24.0.0      0.0.0.0         255.255.0.0     U         0 0          0 br-10471b87e2dd
172.30.0.0      0.0.0.0         255.255.0.0     U         0 0          0 br-7573ff8abed1
172.31.59.0     0.0.0.0         255.255.255.0   U         0 0          0 eth0
Notice the second-to-last-entry: it's assigned itself to 172.30.0.0. That happens to be our main production network! So, the EFS home directories stopped working, curl from the maven repo stopped working, etc.
I did sudo docker network ls to find out all of Docker's networks, then I went through each one with sudo docker network inspect until I found the one on 172.30. I removed it with sudo docker network rm and suddenly everything is working again (as far as I can tell).
Now it might sound like I understand what the heck I'm talking about above, but I absolutely do not. I don't know what a bridge is, and I don't know what docker networks are nor the impact of my having removed them at random. I'm going to leave it to you Docker experts to take this data and come up with a theory of what happened so it doesn't happen again.

Based on the ServerFault link I provided, I added the following to my docker-desktop config
  "default-address-pools":
  [
    {"base":"10.10.0.0/16","size":24}
  ]
Note the result:
CDL-TBRADY-9M:~ tbrady$ docker network create tb3
0edb3a835fd3c3c577dd066368904bcac83a15ba25fe99ae65ab8fa0230cda4c
CDL-TBRADY-9M:~ tbrady$ docker network inspect tb3|grep Subnet
                    "Subnet": "10.10.1.0/24",
CDL-TBRADY-9M:~ tbrady$ docker network create tb4
bc91854942b990c0710fc03ded3e95e8483846658bb7a2d670ac64d9f52d0bdb
CDL-TBRADY-9M:~ tbrady$ docker network inspect tb4|grep Subnet
                    "Subnet": "10.10.2.0/24",

[@mreyes](https://cdlib.slack.com/team/U032L1M27)
, Martin just set the default network address that docker will use on docker03.
He also cleared up the network issue that you experienced on Friday.
-bash-4.2$ netstat -r
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
default         gateway         0.0.0.0         UG        0 0          0 eth0
10.10.0.0       0.0.0.0         255.255.255.0   U         0 0          0 docker0
10.10.1.0       0.0.0.0         255.255.255.0   U         0 0          0 br-7a8422a0554b
10.10.2.0       0.0.0.0         255.255.255.0   U         0 0          0 br-2da3dcb4a81d
10.10.3.0       0.0.0.0         255.255.255.0   U         0 0          0 br-881d9e235b89
10.10.4.0       0.0.0.0         255.255.255.0   U         0 0          0 br-f8ed3a333610
instance-data.u 0.0.0.0         255.255.255.255 UH        0 0          0 eth0
172.31.59.0     0.0.0.0         255.255.255.0   U         0 0          0 eth0
```

**Comment by ashleygould** [comment]
Issue fully resolved.  There were 2 problems:

### 1. NFS hangs when docker starts

symptoms - shortly after starting docker (about 3 minutes) the host can no longer access its NFS mounted home directories, because docker set up a bridge network on the 172.30.0.0/24 cidr block.  This brakes access to the EFS server in our production VPC.

resolution - force docker network to use a safe address pool when creating networkds by adding the following to `/etc/docker/daemon.json`:
`         "default-address-pools": [ {"base":"10.10.0.0/16","size":24} ]`

gothcha - initially, after setting this config and restarting docker, the entire system would hang.  Turns out there was a stale docker bridge network on 172.30.0.0/24.  We pruned a stopped container which was using this network and then deleted the network.  Docker ran properly after that.

### 2. Docker fails to start at boot 

symptom - systemd cannot create docker socket:
```
Jul 11 08:39:20 uc3-mrtsandbox2-stg systemd[1]: Starting Docker Socket for the API.
Jul 11 08:39:20 uc3-mrtsandbox2-stg systemd[2846]: Failed to chown socket at step GROUP: No such file or directory
Jul 11 08:39:20 uc3-mrtsandbox2-stg systemd[1]: docker.socket control process exited, code=exited status=216
Jul 11 08:39:20 uc3-mrtsandbox2-stg systemd[1]: Failed to listen on Docker Socket for the API.
Jul 11 08:39:20 uc3-mrtsandbox2-stg systemd[1]: Dependency failed for Docker Application Container Engine.
Jul 11 08:39:20 uc3-mrtsandbox2-stg systemd[1]: Job docker.service/start failed with result 'dependency'.
Jul 11 08:39:20 uc3-mrtsandbox2-stg systemd[1]: Unit docker.socket entered failed state.
```

resolution - group docker was provisioned via LDAP, but systemd did not recognize it at this point in startup, so it could not set group ownership when attempting to create the docker socket.  I created group docker locally in /etc/groups (using `vigr`).  All good now.
