### ISSUE TITLE
[Ingest] New ALB specs

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#1137]
Ingest ALB request

Stage
------
Replace existing Ingest Apache Load Balancer defined as endpoint 
`http://merritt-aws-stg.cdlib.org:33121`

ALB requirements
- Create new DNS entry to point at new ALB: `ingest-stage.cdlib.org`
- ALB listens on only port 33121
- Targets both hosts `uc3-ingest01x2-stg` and `uc3-ingest02x2-stg` port 33121
- Is NOT available to open internet, only to Merritt stage hosts (if possible)
- For testing, set idle timeout to 300 seconds.  After testing, set idle timeout to maximum (I believe this is 4000 seconds)

**Comment by ashleygould** [comment]
i've opened a ticket with IAS for new ALB
