### ISSUE TITLE
UCB Stone Rubbings Deposit Failures - Quick Enhancements

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1149]
- [x] Create a report to look up an object based on the container filename in inv_ingests
- [x] Link container filename in the queue report to the new report above
- [ ] Validate unique filenames (case insensitive) in manifest tool
  - [ ] Clarify case sensitivity issue with Mark
- [x] Manifest tool: URL -> CSV -> CheckM -- allow user to retain part of input path in the filename field

**Comment by elopatin-uc3** [comment]
Eric to send manifest to Mark and review errors; see if there was a separate condition being triggered, aside from case.

**Comment by elopatin-uc3** [comment]
Example object on stage: https://merritt-stage.cdlib.org/m/ark%253A%252F99999%252Ffk4cr7bm40

**Comment by elopatin-uc3** [comment]
Considering this complete per UCB's successful ingest of all Stone Rubbings objects. Terry's tests showed case sensitivity. Provided UCB file path info for ingest of files with the same names in one object.

**Comment by elopatin-uc3** [comment]
Investigate case sensitivity if/when an issue occurs again. Considering this ticket complete.
