### ISSUE TITLE
UCI Nuxeo feed: Fred L. Emmert collection of aerial photographs

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1153]
Source ticket:  https://help.oac.cdlib.org/a/tickets/107581

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/27898 

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27898.atom

Root folder in Nuxeo:
/asset-library/UCI/SCA_OrangeCountyRegionalHistory/MS-R208/FOR MERRITT

Merritt collection: NEW
UC Irvine SCA Orange County Regional History Collection
ark:/13030/m5vb5f2r

**Comment by mreyescdl** [comment]
- Created Nuxeo script 
- Ran manually - 1 object
- Create weekly schedule - Thursday at 02:55

Ticket complete
