### ISSUE TITLE
UCM Nuxeo feed: UC Merced Library Ernest Lowe Photography Collection

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1154]
Source ticket: https://help.oac.cdlib.org/a/tickets/107288

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/27647/

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27647.atom

Root folder in Nuxeo:
/asset-library/UCM/Ernest Lowe Photography Collection

Merritt collection: NEW:
UC Merced Library Ernest Lowe Photography Collection
ark:/13030/m52g4tf3

**Comment by mreyescdl** [comment]
- Created script, but not yet checked into repo
- Running manually - Over 2000 objects
