### ISSUE TITLE
UCM Nuxeo feed: UC Merced Library UCCE Fresno County

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1155]
Source ticket: https://help.oac.cdlib.org/a/tickets/107288

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/27767/

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27767.atom

Root folder in Nuxeo:
/asset-library/UCM/UCCE/Fresno

Merritt collection: NEW:
UC Merced Library UCCE Fresno County
ark:/13030/m5xq49ww

**Comment by mreyescdl** [comment]
- Create script: production-27767-UC-Merced-Library-UCCE-Fresno-County-ucm_lib_ucce_fresno.csh
- Manually running - Over 2000 objects
