### ISSUE TITLE
UCM Nuxeo feed: UC Merced Library UCCE Madera County

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1156]
Source ticket: https://help.oac.cdlib.org/a/tickets/107288

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/27809/

ATOM feed: 
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27809.atom

Root folder in Nuxeo:
/asset-library/UCM/UCCE/Madera

Merritt collection: NEW:
UC Merced Library UCCE Madera County
ark:/13030/m5sz3k61

**Comment by mreyescdl** [comment]
- Created script: production-27809-UC-Merced-Library-UCCE-Madera-County-ucm_lib_ucce_madera.csh
- Running script manually for testing - Over 2000 objects

**Comment by mreyescdl** [comment]
Noticed that new profiles have default priority which may lead to starvation to other collections.

- Will halt this job and raise priority to 50 in the AM.  (FYI @elopatin-uc3 )
