### ISSUE TITLE
UCM Nuxeo feed: UC Merced Library UCCE Mariposa County

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1157]
Source ticket: https://help.oac.cdlib.org/a/tickets/107288

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/27839/

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27839.atom

Root folder in Nuxeo:
/asset-library/UCM/UCCE/Mariposa

Merritt collection: NEW:
UC Merced Library UCCE Mariposa County
ark:/13030/m5p91hwx

**Comment by mreyescdl** [comment]
Feed not yet available

**Comment by mreyescdl** [comment]
Created script: production-27839-UC-Merced-Library-UCCE-Mariposa-County-ucm_lib_ucce_mariposa.csh
Running manually:  Expect 612 objects
