### ISSUE TITLE
UCM Nuxeo feed: UC Merced Library UCCE Modoc County

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1158]
Source ticket: https://help.oac.cdlib.org/a/tickets/107288

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/27803/

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27803.atom

Root folder in Nuxeo:
/asset-library/UCM/UCCE/Modoc

Merritt collection: NEW:
UC Merced Library UCCE Modoc County
ark:/13030/m5jj0s5m

**Comment by mreyescdl** [comment]
Created script: production-27803-UC-Merced-Library-UCCE-Modoc-County-ucm_lib_ucce_modoc.csh
Running manually - Almost 500 objects
