### ISSUE TITLE
UCM Nuxeo feed: UC Merced Library UCCE San Diego County

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1159]
Source ticket: https://help.oac.cdlib.org/a/tickets/107288

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/27851/

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27851.atom

Root folder in Nuxeo:
/asset-library/UCM/UCCE/San Diego

Merritt collection: NEW:
UC Merced Library UCCE San Diego County
ark:/13030/m5ds01dt

**Comment by mreyescdl** [comment]
- Created script: production-27851-UC-Merced-Library-UCCE-San-Diego-County-ucm_lib_ucce_san_diego.csh
- Running manually - expect 110 objects
