### ISSUE TITLE
UCM Nuxeo feed: UC Merced Library UCCE San Joaquin County

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1160]
Source ticket: https://help.oac.cdlib.org/a/tickets/107288

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/27600/

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27600.atom

Root folder in Nuxeo:
/asset-library/UCM/UCCE/San Joaquin

Merritt collection: NEW:
UC Merced Library UCCE San Joaquin County
ark:/13030/m59098q9

**Comment by mreyescdl** [comment]
- Created script: production-27600-UC-Merced-Library-UCCE-San-Joaquin-County-ucm_lib_ucce_san_joaquin.csh
- Running manually - Expect 1791 objects

**Comment by mreyescdl** [comment]
Only 1785 object ingested.  Investigation shows that feed duplicates nx:identifiers.
Notify Nuxeo folks
```
    <nx:identifier>2011.011.0300</nx:identifier>
    <nx:identifier>2011.011.0300</nx:identifier>
    <nx:identifier>2011.011.0300</nx:identifier>
    <nx:identifier>2011.011.0300</nx:identifier>
    <nx:identifier>2011.011.0300</nx:identifier>
    <nx:identifier>2011.011.0300</nx:identifier>
    <nx:identifier>2011.011.0300</nx:identifier>
```

**Comment by mreyescdl** [comment]
- Removed all objects from collection
- Feed has been fixed
- ZFS disk in place on production and this submission will test performance
- Resubmitted 1700+ objects in production

**Comment by mreyescdl** [comment]
Nuxeo server is down.  Stopping submission

**Comment by mreyescdl** [comment]
1791 objects submitted.
Scheduled for weekly processing at 02:05 on Thursdays

Ticket complete
