### ISSUE TITLE
UCM Nuxeo feed: UC Merced Library UCCE Sutter and Yuba Counties

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1161]
Source ticket: https://help.oac.cdlib.org/a/tickets/107288

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/27831/

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27831.atom

Root folder in Nuxeo:
/asset-library/UCM/UCCE/Sutter Yuba

Merritt collection: NEW:
UC Merced Library UCCE Sutter and Yuba Counties
ark:/13030/m5578hz4

**Comment by mreyescdl** [comment]
- Create script: production-27831-UC-Merced-Library-UCCE-Sutter-and-Yuba-County-ucm_lib_ucce_sutter_and_yuba.csh
- Running manually - Expect 68 objects
