### ISSUE TITLE
UCM Nuxeo feed: UC Merced Library UCCE Tulare County

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1162]
Source ticket: https://help.oac.cdlib.org/a/tickets/107288

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/27812/

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27812.atom

Root folder in Nuxeo:
/asset-library/UCM/UCCE/Tulare

Merritt collection: NEW:
UC Merced Library UCCE Tulare County
ark:/13030/m51g7s6c

**Comment by mreyescdl** [comment]
Created script: production-27812-UC-Merced-Library-UCCE-Tulare-County-ucm_lib_ucce_tulare.csh
Running manually - Expect 379 objects
