### ISSUE TITLE
Re-enable force replication feature - OR toggle the behavior using SSM

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1164]
https://github.com/CDLUC3/mrt-admin-lambda/blob/main/src-colladmin/actions/storage_action.rb#L134-L158
- SSM Control
- OR add node with replication / add node without replication

**Comment by elopatin-uc3** [comment]
https://github.com/CDLUC3/mrt-admin-lambda/commit/41334b4acad2820b6eb2d440d6db629559a4de84
