### ISSUE TITLE
Decommission mvn.cdlib.org

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1167]
- [ ] UC3 will create a new artifact repo, thinking in the future it will be just for UC3
- [x] D2D will need to migrate their artifacts - Marisa will reach out to Judy
- [ ] Terry and David will review existing builds and artifacts to see if UC3 has eliminated all dependencies

**Comment by marisastrong** [comment]
D2D retired the d2d-commons library and no longer utilize the mvn.cdlib.org server.  They thank us for allowing us to use the server and for its reliability.
