### ISSUE TITLE
[RELEASE] Prod Sword refactor + yaml deploy (8/3/2022)

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#1168]
# Overview of Release
See https://github.com/CDLUC3/mrt-doc/issues/1096

# Service(s)
Dryad - Merritt Sword service

# Github Issue Link(s)
https://github.com/CDLUC3/mrt-doc/issues/1096

# Servers affected
uc3-mrtsword01x2-prd.cdlib.org

# Source Code:
Link(s) to tagged release(s)
https://github.com/CDLUC3/mrt-sword/commit/a0e53adf708c672b341442de1e6b0e42c717bc84
https://github.com/CDLUC3/mrt-sword/commit/99d9c60cb5658e4b0056ec1a28a9e5672bddd72b
https://github.com/CDLUC3/mrt-sword/commit/a0e53adf708c672b341442de1e6b0e42c717bc84

# Source Code Tag
0.0.4

# Jenkins/Build Info: (if applicable)
http://builds.cdlib.org/view/Development/job/mrt-sword-refactor/4/

# Deployment Steps (if applicable)
- [ ] Dryad shutdown
- [ ] execute semantic deploy

# Infrastructure Changes to support deployment (ALB, EFS, etc)
- add semantic scripts for deploy on server
- add mrt-tomcat https://github.com/CDLUC3/mrt-tomcat/commit/b6bbf3c5f0dace4eca57a317a1e4c58d772d346f
- add tomcat https://github.com/CDLUC3/tomcat8_catalina_base/commit/97f168071ab2c48d0b01ad2b1e0f34e178c59be7

# Rollback Instructions

**Comment by elopatin-uc3** [comment]
Initial deploy 8/2 rolled back; redeploy on 8/3
