### ISSUE TITLE
[UI] Deployment UI 03 failed in deployment - No master branch in repo "mrt-dashboard-config"

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#1172]
Either Capistrano or Puppet is looking for branch master for checking out config repo.

To fix deployment, Terry created a "master" branch from "main"

Need to find root cause.

**Comment by mreyescdl** [comment]
Capistrano config file shows "master" branch defined in the mrt-dashboard repo, however config repo is "main"

```
set :repo_url,         ENV.fetch('REPO_URL', nil)        || 'https://github.com/cdluc3/mrt-dashboard.git'
set :branch,           ENV.fetch('BRANCH', nil)          || 'master'

set :config_name,      'mrt-dashboard-config'
set :config_repo_url,  ENV.fetch('CONFIG_REPO', nil)     || 'git@github.com:cdlib/mrt-dashboard-config.git'
set :config_branch,    ENV.fetch('CONFIG_BRANCH', nil)   || 'main'
```

**Comment by mreyescdl** [comment]
In the capistrano logs, found "master" being passed in - possible from Puppet.
```  INFO START 2022-07-27 16:42:25 -0700 cap puppet_automation deploy RAILS_ENV=production SSM_ROOT_PATH=/uc3/mrt/prd/ AWS_REGION=us-west-2 BRANCH=1.1.13-dev5 REPO_URL=https://github.com/CDLUC3/mrt-dashboard D
EPLOY_TO=/dpr2/apps/ui CONFIG_REPO=git@github.com:cdlib/mrt-dashboard-config.git CONFIG_BRANCH=master
```

**Comment by mreyescdl** [comment]
Found the issue.  In puppet module "uc3_mrt_ui", under the manifest definition, "master" branch is defined.

```
    $config_repo       = "git@github.com:cdlib/mrt-dashboard-config.git",
    $config_branch     = "master",
```

Will work with @ashleygould to change to main

**Comment by ashleygould** [comment]
This is fixed in puppet module uc3_mrt_ui.  I set the default value for hiera param `config_branch` to `main`.  This change is deployed on puppet master.
