### ISSUE TITLE
Replace synchronous ingest --> storage calls with a storage --> ingest callback mechanism

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1179]
- Ingest initiates a POST request to storage with manifest payload
- Ingest changes queue state from "Consumed" to "Uploading"
- Storage calls ingest callback mechanism with ???  as an identifier
- Interim resources (EFS or other ingest working storage) are deleted
- Ingest changes the state of job from "Uploading" to "Completed"

**Comment by elopatin-uc3** [comment]
Refer to #1062
