### ISSUE TITLE
[Build/Deploy] Generate baseline information of Merritt Software

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#119]
Merritt involves many services composed of varying technologies deployed on multiple servers.  We need to have a baseline of what software is deployed where and what source code it correlates to.  

Use deployment tools to generate baseline release information
Merritt Apache front end
Merritt audit
Merritt DataONE
Merritt Express
Merritt ingest
Merritt inventory
Merritt istatus
Merritt OAI
Merritt replication
Merritt storage
Merritt SWORD
Merritt UI

 - [ ] put together a list of requirements
 - [ ] meet with team to figure out what we need to do to get there

**Comment by terrywbrady** [comment]
Closing.  See #934
