### ISSUE TITLE
Microservices: update and install trimmed war with unit tests

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#1192]
## Goal
Update store, inventory, replic and audit microservices in stage and prod to
- use the trimmed core2 and cloud
- contain docker unit tests

Changes to mrt-core2 and mrt-cloud now support trimmed  microservice wars for: store, inventory, replic and audit. 

The trim process removed all aws java sdk jars except for ssm and s3 handling. I also removed an unused connector jar from core2.

Currently Terry's docker unit tests exist for these 4 microservices.

The store trim (see https://github.com/CDLUC3/mrt-doc/issues/1103) reduced the war size from 278M to 39.4M.

## Approach
- Regenerate war files for inventory, replic and audit without code modifications
- allow full unit test handling for regeneration
- Update stage and prod with the new war files

##  Size changes
- store: 278M to 39.4M
- inventory: 285M to 52,0M
- replic: 278M to 53.9M
- audit: 280M to 46.7M

**Comment by elopatin-uc3** [comment]
Remaining: Audit and Ingest. Audit redeploy planned for Sprint 77.
