### ISSUE TITLE
[RELEASE] Ingest - ZFS mounting and Cookie warning fix - 2022-08-25

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#1199]
# Overview of Release
- Nuxeo upgrade causes annoying warning messages in Ingest http requests to Nuxeo server.  Fix will eliminate these, as fixed in Core2 lib
- Piggybacking on this release will be the switch from EFS to ZFS disk for Ingest work area
- Also piggybacking is a fix for lost core2 dependencies with recent Core lib trimming

# Service(s)
Ingest

# Github Issue Link(s)
https://github.com/CDLUC3/mrt-doc/issues/1191
https://github.com/CDLUC3/mrt-doc/issues/1140

# Servers affected
uc3-ingest01x2-prd
uc3-ingest02x2-prd
uc3-ingest03x2-prd

# Source Code:
https://github.com/CDLUC3/mrt-ingest/commit/192aa743a2c2b4d2b0df473903e8fd69d8e8a18a

# Source Code Tag
0.0.27

# Jenkins/Build Info: (if applicable)
http://builds.cdlib.org/view/Development/job/mrt-ingest-refactor/125/

# Deployment Steps (if applicable)
- [x] Take ingest03 out of rotation
- [x]  Update SSM params and create ZFS dirs
- [x] Deploy to Ingest 03 and test
- [x] Deploy to other hosts

# Infrastructure Changes to support deployment (ALB, EFS, etc)
Remove Ingest workers from Apache LB as they are upgraded

# Rollback Instructions
deploy:rollback

**Comment by mreyescdl** [comment]
Production deployment complete

Still pending:
- Cleanup and removal of EFS disk for stage (fs-6fe432c4.efs.us-west-2.amazonaws.com)
- Cleanup and removal of EFS disk for production (fs-3b22fd91.efs.us-west-2.amazonaws.com)

**Comment by elopatin-uc3** [comment]
See latest comment from #1140 for status on pending items.
