### ISSUE TITLE
Repo Purge Party - Week of Sept. 26

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1201]
Review github repos and branches that are now obsolete.

Purge repos.
- mrt-conf-prv
- mrt-tomcat
- review mrt-repo-tagger settings

Other ones to include?

We would likely need a half day to look at things together and decide what actions to take.

**Comment by marisastrong** [comment]
The following repositories are being backedup by IAS.

[root@ias-admin2-ops github]# ls -1 CDLUC3/
cdluc3
cdl-zk-queue
ckan
ckanext-datagovtheme
ckanext-geodatagov
ckan.playbook
cloud9-briley
cloudhost-docker
cobweb
counter-hub-upload
counter-processor
dash
dash2-config-example
dash2-harvester
dash2-migrator
dash-brochure
dash-discovery
dash-harvester
dash-ingest
dashv2
dash-xtf
datacite-mapping
datarescue
datashare
datashare-ingest
dataup2
DataUp_Dataverse
dmp_aws
dmpbrochure
dmp-docker
dmp-docker-dev
dmpdocs
dmphub
dmphub_client
dmphub-json-schema
dmphub-v2
dmptool
dmptool_deploy
dmptool-docker
dmptool_late_2019
dmptool_v2
docker-tutorial
dotfiles
dryad
eoth-tools
eothxtf
Erfurt
etd-docker
etd-python-troubleshooting
ezid
ezid_admin_tools
ezid-ansible
ezid-client-tools
ezid-config
ezid-info-pages
ezid-service
ezid-shoulders
FAIRIsland
File-Analyzer
file-anvl
file-namaste
file-pairtree
file-value
maDMPs
Make-Data-Count
merritt-aws
merritt-docker
merritt-manifest
merritt-tinker
mrt-admin-collection
mrt-admin-lambda
mrt-admin-proto
mrt-audit
mrt-builds
mrt-cloud
mrt-cloud-config
mrt-cloudhost-pub
mrt-core2
mrt-cron
mrt-cshadmin
mrt-dashboard
mrt-dataONE
mrt-doc
mrt-doc-private
mrt-ingest
mrt-ingest-ruby
mrt-integ-tests
mrt-inventory
mrt-jenkins
mrt-jenkins-docker
mrt-maven-parent
mrt-oai
mrt-replic
mrt-repo-tagger
mrt-share
mrt-store
mrt-store-admin
mrt-store-config
mrt-sword
mrt-tind-harvester
mrt-tomcat
mrt-zoo
mxs_private
N2T
n2t-admin
n2t-eggnog
naan-registry
naan_reg_priv
nsf_award_scanner
OntoWiki
pidgraph-notebooks-python
RDA-DMP-Common-Standard
RDFauthor
resync
resync-client
spreadsheet-help
stash
stash_datacite
stash_engine
substance-rails
svu
sys-inventory
test_issue_import
tomcat8_catalina_base
uc3-aws-cli
uc3-citation
uc3-etds
uc3ops-ansible-inventory
uc3ops-ansible-patching
uc3ops_instance_inventory
uc3-service-inventory
uc3-ssm
uc3-tools
UC-code-camp
UDFR-Models
was
z-mxs-repo

**Comment by cfthompson** [comment]
Just FYI, as long as these repos exist on github and our script has access to them, it will continue to back them up.  We don't (currently) have an exclude list, the script will just grab all of the ones in the org that it can see.  The script will, apparently, fail to back up any repos for which the token doesn't have access though.  This seems to manifest itself in the log as a permissions error.  The following repos are currently experiencing this problem:

uc3ops-ansible-patching
uc3ops-ansible-inventory
sys-inventory
uc3-service-inventory
uc3ops_instance_inventory
etd-python-troubleshooting
mrt-doc-private
etd-docker
ezid_admin_tools
N2T
merritt-tinker
naan_reg_priv
dmp_aws
cloud9-briley

I suspect the user associated with the token we're using to connect to the CDLUC3 org and back these things up may not have permissions on these repos?  Can you remind me what that username was?  I'd like to make a note of it in the gitcloner documentation.

I'm also hoping to create a daily report that CDLers can view to show exactly which repos in which orgs the script tried to back up, and whether or not it succeeded, but that will take some time.  I have to architect a solution to somehow not expose that information to the whole world.  Hoping to be able to figure out how to do that with Cognito and AWS SSO.

**Comment by marisastrong** [comment]
@cfthompson i may have missed the final wrap up of this issue.  Are the UC3 backups working again?

**Comment by cfthompson** [comment]
I think so, the nightly backup reports on the repos it attempted to back up in the README.md file if this repo:

https://github.com/cdlib/ias-gitbackup-status

I'm not real sure what would happen in the event that there is a private repo for which it doesn't have a key, whether it tries to back it up and fails, or whether it just chugs along completely oblivious to the repo's existence.  But I'm fairly certain that if it's oblivious to the repo's existence, that repo won't show up in the report.

**Comment by marisastrong** [comment]
@marisastrong to review the list of repos being backed up now and ensure we're in good shape https://github.com/cdlib/ias-gitbackup-status

**Comment by marisastrong** [comment]
All looks good on my end @cfthompson
