### ISSUE TITLE
[Storage]  Visibility into current work in progress

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#1207]
Deployments and patching processing would benefit from being able to determine if a Storage worker is idle.

Possible ways we can determine workload:

- Examine Ingest lock queues
- Storage self reporting

**Comment by dloy** [comment]
One quick mechanism appears to be using
~~~
netstat | fgrep '35121' | fgrep 'ingest'
~~~
this will show something like
~~~
tcp6       0      0 uc3-mrtstore06x2-:35121 uc3-ingest03x2-pr:41426 ESTABLISHED
~~~
if ingest is currently using a storage server,

A remote script can also be used:
~~~
serv=$1
ssh loy@uc3-mrtstore0${serv}x2-prd <<'ENDSSH'
netstat | fgrep '35121'' | fgrep 'ingest'
ENDSSH
~~~

**Comment by elopatin-uc3** [comment]
@ashleygould Please see David's note above.
