### ISSUE TITLE
[Build] Replace manual Jenkins configuration with configuration-as-code YAML file

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#121]
Once we figure out how we want to manage/deploy Jenkins (#165259301), and once we straighten out our current Jenkins jobs (#165260443), we should get the Jenkins configuration and job configuration under source control using the [Configuration as Code plugin](#165260443). The [jenkins.yaml file used in @davidmoles3's Docker/Jenkins experiment](https://github.com/dmolesUC3/mrt-jenkins-docker/blob/master/casc_configs/jenkins.yaml) could be a starting point.
 - [ ]

**Comment by terrywbrady** [comment]
Closing.  Build refactor is in progress.
