### ISSUE TITLE
Intermittent 403 "Forbidden" client error when etd_submitter attempts to ingest ETDs

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1217]
Although it has access to all ETDs collections in Merritt, the etd_submitter user in LDAP is intermittently blocked from using the API /update endpoint. This most often happens with UCLA ETDs. 

```
2022-08-29 07:30:05,130 ERROR submitting to Merritt: 403 Client Error: Forbidden for url: https://merritt.cdlib.org/object/update/
Traceback (most recent call last):
  File "/etds/apps/uc3-etds/scripts/getetds.py", line 253, in submit_to_merritt
    req.raise_for_status()
  File "/apps/etds/lib/python2.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 403 Client Error: Forbidden for url: https://merritt.cdlib.org/object/update/
```

**Comment by terrywbrady** [comment]
@elopatin-uc3, I took a quick look in the 3 UI logs and I did not see any related messages.  There is a chance that the UI ALB is returning this.  Are you able to successfully re-run items?

**Comment by elopatin-uc3** [comment]
Thanks @terrywbrady . Per our discussion, perhaps we should consider:
- Order of ingests for different campuses: does UCLA come last?
- Does the separate SFTP account for UCLA make a difference?
- Does a manual re-run fix (assume no)?

**Comment by mreyescdl** [comment]
@terrywbrady Do we have the WAF connected to the UI ALB?  If so, then it seems this would be a likely culprit for the 403.

**Comment by terrywbrady** [comment]
@mreyescdl , good thinking.  I wonder if we can pull a log for this.

**Comment by elopatin-uc3** [comment]
No longer seeing this issue; closing.
