### ISSUE TITLE
Object Assembly Zips - Compress or Not?

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1222]
David has a change that will allow a client application to request an zip object assembly as compressed or uncompressed.
- zip -> create a .zip with compression
- zipunc -> create a .zip without compression

The Merritt UI and the Dryad UI will have an opportunity to continue to use zip or to migrate to use the uncompressed zip.

## Initial findings from Stage

- zip compression varies significantly by file type (-1% to 80%)
  - note that some tif files do compress significantly
  - some objects were marginally larger when compressed
- not compressing shows processing time improvements up to 3X to 4X
  - question: could the Access servers run more threads if compression was not occurring

## Additional Analysis 

- Select a common set of objects (esp Dryad objects) and analyze compression / performance in stage
- Determine if throughput (threads) can be improved by not compressing
- Temporarily change the setting in Dryad for 1 week and look at librato impacts to Access servers

**Comment by dloy** [comment]
## Stats values
Attached are some stats for large records in stage with different impacts for zip compression and processing time:
***Stats  - objectIDS=ark:/99999/fk4kh24s00 - diffpu=1.463983 - diffsz=1.0052843 - procUnc=178638 - procCmp=261523 - sizeUnc=5064624468 - sizeCmp=5038002331

 - objectIDS= ark  object identifier
 - diffpu= time for compressed zip / uncompressed zip
 - diffsz= uncompressed size / compressed zip
 - procUnc= Ms uncompressed processing
 - procCmp= Ms compressed processing
 - sizeUnc= uncompressed size
 - sizeCmp= compressed size

## extension entries
mp4*** - extension=mp4 - uncompress=5064618533 - compress=5037999703 - compressTime=199482 - cnt=1 - cratio=1.0052836 - byteMs=25388.8

mp4*** 
- extension= file extension
- uncompress= uncompressed bytes
- compress= compressed bytes
- compressTime= time for compression
- cnt= number of object files with this extension
- cratio= uncompressed bytes / compressed bytes
- byteMs= bytes / compression Ms
[stat-attach.txt](https://github.com/CDLUC3/mrt-doc/files/9561270/stat-attach.txt)

**Comment by terrywbrady** [comment]
## Dryad Meeting Notes

### Try Uncompressed Zips
- [x] Terry will document the process needed to download an uncompressed zip when Dryad is ready to test
  - [x] available in stage
  - [ ] available in prod
```
Merritt Stage (UI and Access Servers) now supports requests for uncompressed zip files.  Add "format=zipunc" to the assemble-obj and assemble-version endpoint calls.  If you have a chance to give it a try, let us know.
```
  - https://github.com/CDLUC3/mrt-dashboard/pull/135

### Consider caching assembled objects for a longer period of time
- Scott will examine log files to answer the following questions
  - how often is a specific object assembly re-requested?
  - is there an optimal window of time in which cached assemblies could be re-used?  (there is a storage cost to persist these)
  - if the answers look like this could be beneficial, Merritt should explore S3 lifecycle policy options to extend the cache based on creation date AND last access 

### Could the consumer daemon change we proposed for ingest help to make our Access configuration more flexible?
- This could be particularly beneficial if zips are not compressed (compressing pushes CPU to 100%)

### Other questions -- no immediate action items assigned
- For a typical Dryad submission, how effective is the current zip compression?
  - Would a user even notice the change in compression?
  - Would the lack of compression make a large file easier to handle on a local workstation?

**Comment by sfisher** [comment]
Dryad analysis for caching zips: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2069
