### ISSUE TITLE
Discuss FSx maintenance window

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1226]
```
[cloudshell-user@ip-10-0-2-11 ias-utility]$ aws fsx describe-file-systems | jq '.FileSystems[] | "\(.FileSystemId): \(.OpenZFSConfiguration.WeeklyMaintenanceStartTime)"'
"fs-042ed487a905677e2: 4:10:30"
"fs-0f6db4bb33dc4bbbe: 4:12:30"
[cloudshell-user@ip-10-0-2-11 ias-utility]$
```

**Comment by terrywbrady** [comment]
Ashley will request downtime to mactch ezid downtime

**Comment by marisastrong** [comment]
Add FSX maintenance window time adjustment when Daylight Savings happens @marisastrong

**Comment by marisastrong** [comment]
I requested ZFS, is this correct?

https://github.com/cdlib/cdlsys/issues/35

**Comment by marisastrong** [comment]
Advised by IAS to use UTC so we don't have to change for DST.  However this has downstream impacts (cron jobs, ZFS, etc)
Can ZFS be highly available?

**Comment by marisastrong** [comment]
Due to Service Level Agreements that would need to be updated and go through Legal, it is not advisable to make the UTC change at this time.  
Merritt has cron tabs that would need updating and addressing UTC would be an issue to resolve.
