### ISSUE TITLE
Feature locking in Storage for large Access queue

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#1229]
## Need
Right now a lock is deployed in Storage to prevent the access queue daemon from processing the current zookeeper queue for large content.

The lock is set based on the existence of a file - file exists lock, file does not exist no lock.

Problems of this approach:
- we are moving away from directory based locations for this content - the mrtHome configuration directory is disappearing. As we move to Docker this may become more critical
- directories are specific to a given server. Multiple servers may wish to access and set

Desirable features of such a lock:
- universally accessible - the lock can be viewed and set from one or more servers
- accessible in java
- dynamically based - a feature that is not a configuration setting 
- ease of setting, updating and deleting
- hopefully something independent of the local server architecture. 
- persists over one or more server failures

## Some options to investigate
- zookeeper
- S3
- SSM
- LaunchLightly, AppConfig,  or similar tool
- etc.

**Comment by terrywbrady** [comment]
See #1233
