### ISSUE TITLE
Moderate security upgrade: Tika-core

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#123]
CDLUC3/mrt-store
Known moderate severity security vulnerability detected in org.apache.tika:tika-core >= 1.7, < 1.22 defined in pom.xml.
pom.xml update suggested: org.apache.tika:tika-core ~> 1.22.
 - [ ] Update tika-core dependency in mrt-zoo pom.xml
 - [ ] Update tika-core dependency in mrt-store pom.xml
 - [ ] Update tika-core dependency in mrt-audit pom.xml
 - [ ] Update tika-core dependency in mrt-replic pom.xml
 - [ ] Update tika-core dependency in mrt-core2 pom.xml
 - [ ] Update tika-core dependency in mrt-inventory pom.xml

**Comment by elopatin-uc3** [comment]
Several Merritt repos have been flagged with this moderate severity security vulnerability by github. The latest version update suggested is Tika-core 1.7, so have amended the description accordingly. (Eric Lopatin - Aug 6, 2019)

**Comment by elopatin-uc3** [comment]
Other repos affected: mrt-zoo, mrt-audit, mrt-replic, mrt-core2, mrt-inventory. 

@davidloy, @markreyes2, a few related questions:
* Should we alter this ticket to include all affected repos/components, or create one ticket per affected component? either way is fine by me
* Does updating the tika-core require us to update the overall version of Tika that Merritt uses? If no, is this something we should consider anyway, due to support for a greater number of mime types? 

Thanks,
Eric (Eric Lopatin - Aug 6, 2019)

**Comment by elopatin-uc3** [comment]
@ericlopatin  I tend to agree with a single tracker for all effected components.  "Add a task" can be used to list all of the instances. jars in general are a nasty problem. Fortunately, with AWS internal security their usually not an issue. There are several problems on upgrading to newer jars: bad memory requirements, depricated code (especially bad). Getting the newer jars in requires a redeploy. Definitely something we should discuss because we some very old jars lying around. (David Loy - Aug 6, 2019)

**Comment by elopatin-uc3** [comment]
Thanks for the input @davidloy. I've added tasks for each component. Let's chat about this during our next sprint planning meeting. (Eric Lopatin - Aug 7, 2019)

**Comment by terrywbrady** [comment]
Closing.  Part of build refactor effort.
