### ISSUE TITLE
Resources for builds.cdlib.org - space and compute

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1231]
## New Goals for builds machine

- Ensure that integration test images are always up to date in ECR
- Run integration build tests daily (via Jenkins)
- Ensure that docker stack images are always up to date in ECR
    - simplify builds on DEV boxes
    - run end to end integration suite on a daily basis
        - or on-demand against docker via Jenkins
        - Jenkins box probably cannot run the whole stack at once
    - explore ECS
    - create contextual docker compose stacks that simplify the focus to the element under development
        - no need to maintain a working instance of all merritt-docker submodules

## Space Issue

Hey all, we got a Nagios alert for uc3-sourcex2-prd host that the /apps/devtools filesystem is at 96% full.  Can you please prune anything that isn’t necessary?  We can certainly expand the storage as well.  Open a ticket if you want to…. TIA (edited) 
[9:57](https://cdlib.slack.com/archives/C19KCRAEB/p1664384258056409)

```
uc3-sourcex2-prd(jsomonta)$ df -h
Filesystem                                    Size  Used Avail Use% Mounted on
devtmpfs                                      1.9G     0  1.9G   0% /dev
tmpfs                                         1.9G     0  1.9G   0% /dev/shm
tmpfs                                         1.9G  544K  1.9G   1% /run
tmpfs                                         1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/nvme0n1p1                                 12G  7.0G  5.1G  59% /
/dev/mapper/DEVTOOLS-devtools                 105G   95G  4.6G  96% /apps/devtools
tmpfs                                         389M     0  389M   0% /run/user/5153
ias-homesrv2-ops.cdlib.org:/homesrv/cdlinfra  8.0E  406G  8.0E   1% /home/cdlinfra
ias-homesrv2-ops.cdlib.org:/homesrv/jsomonta  8.0E  406G  8.0E   1% /home/jsomonta
tmpfs                                         389M     0  389M   0% /run/user/3321
```

**Comment by terrywbrady** [comment]
The .m2 directories are using a lot of the space.

```
builds@uc3-sourcex2-prd:/apps/devtools/builds$ du -s -m .m2*
5600	.m2
601	.m2-audit
478	.m2-cloud
282	.m2-ingest
772	.m2-inventory
1167	.m2-oai
175	.m2-refactor
653	.m2-replic
234	.m2-store
710	.m2-sword
```

/apps/devtools/docker-system-storage will also want to grow in size.

**Comment by elopatin-uc3** [comment]
Mark will have a look at if there are any resources that can be removed and Terry will look into possible different .m2 directory approaches.

**Comment by terrywbrady** [comment]
Explore if .m2 dirs can be shared or cleaned up

**Comment by mreyescdl** [comment]
Here are all Jenkins jobs sorted in size (MB)

```
1       example-pipeline
1       Merritt Production Submission (Full Stack Test)
1       Merritt Stage Submission (Full Stack Test)
2       terry-test
3       cdl-zk-queue
4       git-dataONE
5       mrt-cloud-int-test
6       docker_images
20      mrt-build-xoai
91      mrt-ingest-refactor
121     test-audit-refactor
122     test-audit-refactor2
242     test-adit-refector2
526     mrt-oai-refactor-dev
604     test-audit-refactor3
606     mrt-store-refactor-dev
612     mrt-audit-refactor-dev
617     test-audit-refactor4
672     mrt-inventory-refactor-dev
699     mrt-oai-refactor
777     mrt-ingest-refactor-dev
812     mrt-inventory-refactor
976     mrt-sword-refactor-dev
991     mrt-ingest-stage
1013    mrt-store-refactor
1023    mrt-audit-refactor
1096    mrt-replic-refactor-dev
1115    mrt-replic-refactor
1266    mrt-build-audit
1279    mrt-sword-refactor
1334    mrt-core-int-test-all
```

**Comment by mreyescdl** [comment]
Deleted Jenkins jobs

1       Merritt Production Submission (Full Stack Test)
1       Merritt Stage Submission (Full Stack Test)
4       git-dataONE
991     mrt-ingest-stage

**Comment by terrywbrady** [comment]
Ashley has added space.  Compute has not yet been altered.

**Comment by terrywbrady** [comment]
Closing for now.  Let's re-open if we are confident that this is needed.
