### ISSUE TITLE
Ashley refactor Tomcat deployment with puppet

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1232]
[Apache Tomcat Deployment for UC3 Merritt](https://github.com/CDLUC3/mrt-doc-private/blob/main/docs/tomcat/apache_tomcat_deployment_for_uc3_merritt.md)

### Deployment Schedule

- [x] Tues 10/11 - uc3-mrt-replic-prd
- [x] Thur 10/13 - uc3-mrt-store-stg
- [x] Tues 10/25 - uc3-mrt-store-prd - remove from LB; make sure currently processing jobs are complete (check Tomcat tmp to see if new files are being created there)
- [x] Thur 11/3 - uc3-mrt-access-stg
- [ ] Wed 11/16 - uc3-mrt-access-prd
- [ ] Tues 11/15 - uc3-mrt-inventory-stg
- [ ] Thurs 11/17 - uc3-mrt-inventory-prd
- [ ] Tues 11/29 - uc3-mrt-sword-stg, uc3-mrt-oai-stg
- [ ] Thurs 12/1 - uc3-mrt-sword-prd, uc3-mrt-oai-prd

Completed: Ingest, Audit
In process: Replic
Todo: Store, Access, Inventory, Sword, OAI

**Comment by dloy** [comment]
I suggest that no work be done on Sword and OAI until after our Dryad meeting 10/21.

As long as no dynamic restart is involved I would order the new deployment handling:
- storage
- access
- ingest

**Comment by terrywbrady** [comment]
- sword - No ALB, requires Dryad pause
- oai - No ALB, slight impact to Dryad, but may be tolerable

**Comment by ashleygould** [comment]
### Deployment Schedule

- [ ] Tues 10/11 - uc3-mrt-replic-prd
- [ ] Thur 10/13 - uc3-mrt-store-stg
- [ ] Tues 10/18 - uc3-mrt-store-prd
- [ ] Thur 10/20 - uc3-mrt-access-stg
- [ ] Tues 10/25 - uc3-mrt-access-prd
- [ ] Thur 10/27 - uc3-mrt-inventory-stg
- [ ] Tues 11/1  - uc3-mrt-inventory-prd
- [ ] Thur 11/3 - uc3-mrt-sword-stg, uc3-mrt-oai-stg
- [ ] Wed 11/9 - uc3-mrt-sword-prd, uc3-mrt-oai-prd

**Comment by elopatin-uc3** [comment]
Associate ticket: https://github.com/CDLUC3/mrt-doc/issues/1238

**Comment by ashleygould** [comment]
cleanup of obsolete tomcat files is done for all hosts.
