### ISSUE TITLE
[Storage] Timeout requesting hostname

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#1240]
Under load, Storage caused a few submission failures due to the 1 hour timeout exceeded when requesting a hostname.

```
org.cdlib.mrt.utility.HTTPUtil-getObjectEntity:220 EXTERNAL_SERVICE_UNAVAILABLE[Unavailable remote service] HTTPUTIL: getObject- Error during HttpClient processing - timeout:3600000 - URL:http://storage.cdlib.org:35121/hostname - responseCode:502
```

Maybe not an error, but it is something we should be aware of and discuss.

**Comment by elopatin-uc3** [comment]
This is a likely a sign that Storage was overwhelmed with significant submissions, to the point where it couldn't service the request for a hostname. The hostname call should be lightweight.

Q's:
- Why wouldn't the ALB take the host out of rotation per poor health?
- Is there an additional health check we could put in place? (maybe not)
- Is there a case where even if the Storage node was unhealthy, but it would still return a response to the hostname call?

Possible approach: >> Try this in Stage
- Set up another target group for the hostname API call; have a health check on that group. Modify the health check to reflect the actual API call.
- Send an alert when a host is not able to accept hostname calls.
- ALB: if neither worker is unhealthy, it will put both hosts back into rotation.

**Comment by mreyescdl** [comment]
Another instance of the Gateway Error (see below)
We still do not know root cause, but let's have Ingest be more resilient and catch this error and retry.
```
org.cdlib.mrt.utility.HTTPUtil-getObjectEntity:220 EXTERNAL_SERVICE_UNAVAILABLE[Unavailable remote service] HTTPUTIL: getObject- Error during HttpClient processing - timeout:3600000
 - URL:http://storage.cdlib.org:35121/hostname - responseCode:502
        at org.cdlib.mrt.utility.HTTPUtil.getObjectEntity(HTTPUtil.java:220)
        at org.cdlib.mrt.utility.HttpGet.build(HttpGet.java:128)
        at org.cdlib.mrt.utility.HttpGet.getFile(HttpGet.java:62)
        at org.cdlib.mrt.utility.FileUtil.url2File(FileUtil.java:69)
        at org.cdlib.mrt.utility.FileUtil.url2File(FileUtil.java:91)
        at org.cdlib.mrt.utility.FileUtil.url2File(FileUtil.java:119)
        at org.cdlib.mrt.ingest.handlers.HandlerTransfer.getStoreHost(HandlerTransfer.java:440)
        at org.cdlib.mrt.ingest.handlers.HandlerTransfer.handle(HandlerTransfer.java:134)
        at org.cdlib.mrt.ingest.handlers.HandlerTransfer.handle(HandlerTransfer.java:88)
        at org.cdlib.mrt.ingest.IngestManager.submit(IngestManager.java:611)
        at org.cdlib.mrt.ingest.service.IngestService.submit(IngestService.java:82)
```

**Comment by mreyescdl** [comment]
Two more failures at
- Sat Nov 05 01:10:15 PDT 2022

Ashley will request ALB Storage logging to examine routing of these requests.

I'll examine Storage ALB parameters

**Comment by mreyescdl** [comment]
The Ingest client uses the following core library, which accepts a retry parameter, but does not use it (David has confirmed)
```
   public static void url2File(LoggerInf m_logger, String urlS, File outFile, int retry)
        throws TException
    {
        url2File(m_logger, urlS, outFile);
    }
```

I think I'll rewrite the client logic to make sure we are doing the right thing.

**Comment by mreyescdl** [comment]
Fix deployed to Ingest stage workers
https://github.com/CDLUC3/mrt-ingest/pull/67
