### ISSUE TITLE
Timeline: 10/6/22 Storage not responding to hostname endpoint

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1244]
UCB sent a large collection (6.9T) starting on 10/5.  The content was processed quickly, but a separate ingest worker saw stalled "hostname" requests from storage workers.

## Last 100 days of ingests
Note that the peaks are steeper since late Aug when ZFS was introduced.
![image](https://user-images.githubusercontent.com/1111057/195908893-9c3f7d8e-6486-4fe3-9927-014261bfb1ac.png)

## Incident Timeline
- 8/22 ZFS Introduce late Aug
- ?/22 Hostname endpoint added to Storage to eliminate Apache RLB 
- 10/5/22 - Content ingest begins
- 10/6/22 - Hostname requests failed.  Ingest worker restarted.  The large UCB submission proceeded without issue

## Storage Performance
Key takeway - IOWait looks really good, High CPU due to fixity check on content added to S3

![image](https://user-images.githubusercontent.com/1111057/195908425-7dca13c7-db16-4e8b-9ec2-38654f42450e.png)

## Ingest Performance
Some IOWait during the incident.  Note the available headroom.

![image](https://user-images.githubusercontent.com/1111057/195908580-7b847a9f-2e95-4444-b34a-f51534b9dd63.png)

![image](https://user-images.githubusercontent.com/1111057/195908681-72777a27-6215-46f7-a939-5c19e466fb23.png)

See #1240

**Comment by terrywbrady** [comment]
Looking at objects added by date in the billing database, 10/5 was significant but not exceptional.
```
select ingest_date, sum(object_count) as oc 
from ingests_completed 
where ingest_date>'2022-07-01' 
group by ingest_date 
order by oc; 
```

Results (showing largest counts per day)
```
| 2022-07-11  |  2794 |
| 2022-07-12  |  2811 |
| 2022-07-20  |  2847 |
| 2022-07-27  |  2918 |
| 2022-08-30  |  2967 |
| 2022-08-11  |  3336 |
| 2022-07-19  |  3508 |
| 2022-08-06  |  3613 |
| 2022-08-12  |  3708 |
| 2022-07-15  |  3784 |
| 2022-08-19  |  3905 |
| 2022-08-22  |  4130 |
| 2022-08-08  |  4908 |
| 2022-07-30  |  5342 |
| 2022-07-28  |  5568 |
| 2022-07-26  |  5597 |
| 2022-10-05  |  5673 |
| 2022-09-26  |  5678 |
| 2022-07-29  |  5954 |
| 2022-07-22  |  7514 |
| 2022-07-18  | 12647 |
| 2022-07-25  | 16008 |
+-------------+-------+
```

**Comment by mreyescdl** [comment]
Error occurred 5 times, the last on Saturday, Oct. 08
Since then we have not seen the error.

Ingest 01
        - Sun Oct 02 10:47:14
Ingest 02
        - Thu Oct 06 02:28:01
        - Fri Oct 07 06:41:12
        - Sat Oct 08 00:41:48
Ingest 03
        - Thu Oct 06 06:40:23
