### ISSUE TITLE
Avoiding zip assembly on our servers

### ISSUE THREAD

**Issue by marisastrong** [CDLUC3/mrt-doc#1246]
Some possibilities we could look into.

1. Not compressing zips and just streaming or creating them uncompressed from a server.  I don’t mind if we do this.  IDK if Maria would have an opinion.
2. I believe some browsers allow multiple file downloads rather than creating zip files (this needs user permission but may be supported enough on new browsers to consider?).
3. I believe JavaScript has some severe size limitations for creating zip file  because of the integer size in JavaScript.  See https://stuk.github.io/jszip/documentation/limitations.html  Not sure if the zips created in a client’s browser would allow a big enough size for all our datasets.  “So, we have 53bits for integers and [bitwise operations treat everything as 32bits](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators). So if all the 64bits integers can fit into 32 bits integers, everything will be fine. If it’s not the case, you will have other problems anyway (see next limitation).”
4. Perhaps WebAssemby/WASM can get around some JavaScript limitations and increase performance by downloading individual files and streaming them into a zip for a user on their own machine.  I’m not sure how widely supported or robust it is since I’ve never tried it yet. https://webassembly.org/

See https://github.com/CDLUC3/mrt-doc/issues/1222

**Comment by sfisher** [comment]
Merritt
- Object assembly is segmented into small and large
- It uses a lot of CPU and has limited number of things it can process at once
- Largest is zip but text and csv and Excel are common

**Comment by sfisher** [comment]
https://github.com/bpajk/WasmZip may be a way to get individual files to stream into a zip with some modifications.

**Comment by sfisher** [comment]
There is also a way to use the Javascript files API to request access to a user's file systems and do downloads as well (as Terry demonstrated).  There are some concerns that this may not be available enough in all browsers (?).

**Comment by sfisher** [comment]
Update: We have moved to using uncompressed zips from Merritt as a first step, but this requires additional analysis and work when/if we'll do more about it.
