### ISSUE TITLE
Migrate Dryad 4001 backup from Wasabi to Dryad Glacier

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#1255]
Currently all backups for Dryad content on node 3041 (AWS) has been removed from 2001 (Wasabi) and added to 3641 (Dryad glacier). There is additional content on the Dryad node 4001 (old dataone) that also needs to be migrated from Wasabi to Dryad glacier.

This current content effects 231 objects on wasabi with15.44G bytes.

**Comment by terrywbrady** [comment]
Admin tool should be able to do this.

**Comment by elopatin-uc3** [comment]
@dloy @terrywbrady I will start this migration on Monday morning 11/7, after our team meeting.

**Comment by elopatin-uc3** [comment]
@dloy @terrywbrady I checked back on progress for replication of the objects in these two collections and so far coll admin indicates none have been replicated to 3641. Just wanted to mention this, in case I'm missing something:
https://merritt-colladmin.cdlib.org/web/storeCollNode.html?coll=312
https://merritt-colladmin.cdlib.org/web/storeCollNode.html?coll=62

If there's anything I can help with, let me know. Also, this isn't high-priority, so we can discuss further in Monday's team meeting.

**Comment by elopatin-uc3** [comment]
I see this replication issue was surfaced by today's consistency reports:
https://merritt-admintool.cdlib.org/web/index.html?path=report&report=consistency-reports%2F2022-11-10%2Fcon_secondary.FAIL

**Comment by elopatin-uc3** [comment]
A trivial change was needed to re-enable replication triggers via coll admin. A few notes:
- These two collections are unique, as a subset of objects appear in both collections
- Object deletions from a node are executed in batches of 25
