### ISSUE TITLE
UCJEPS Snowcone workflow for legacy content: IAS Estimate

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1261]
Kurt asked Eric to create a cost estimate for the working S3 bucket for this project.

Eric would need to report on actual costs vs estimate for the duration of this project.

AWS cost calculator would need to be used to estimate S3 transaction and storage costs.  Egress charges should not need to be tracked for this.

IAS recommended creating this new bucket in (1)the Merritt S3 account OR (2)in the new UC3 account.

**Comment by elopatin-uc3** [comment]
Estimate created in AWS calculator:
https://calculator.aws/#/estimate?id=5ffe0737f1c13766a55aa4fb6d7b5b5eb953055d

The calculator generates estimates for monthly costs. As we are planning to restrict the amount of time 8TB of data sits in the S3 bucket, we should divide the 4 week estimate by two:

(4 weeks: $190.41 / 2 = $95.20) + $60 for Snowcone rental = $155.20

$155.20 * four months = $620.80 total projected cost for UCJEPS legacy content transfer and ingest into Merritt.
