### ISSUE TITLE
core2 dependabot fixes

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#1266]
Update mrt-core2 pom.xml to later dependabot recommendations.

This is a partial step to providing a broader plan documented in "Plan how to address dependabot alerts after initial build refactor #994"

Problems with the Dependabot process:
- dependabot reports can make recommendations on jars that have known CVE vulnerabilities in the mvnrepository logs
- dependabot reports rarely document backwards compatibility on a recommended jar. Changing to a recommended jar can cause failures in code because of missing methods
- Using the latest version of a dependabot jar can result in vulnerabilities within a few months of the update 

Because of these problems, I recommend:
- meet general requirement for dependabot recommendation
- updated jar should be matched against mvnrepository.com for specific jar. If the jar has CVE vulnerabilities then find a more recent version that that does not have vulnerabilities
- use jars that hopefully have significant  mvnrepository usages and have a release date that is hopefully not less than 1 year.
- find a common location for documenting used jars
- use Terry's "Pipeline mrt-core-int-test-all" in Jenkins for getting a basic level of confidence for the replacements

At this time, I have not found any mechanism for including a jar only if the service uses the jar. Dependency trees do document that a jar is directly used based on compilation. Jars identified as not used in compilation may cause runtime exceptions - these are difficult to detect.

Not clear what should be considered the completion of this process:
- release of the core2 changes to main
- full prod update of all microservices using core2

**Comment by elopatin-uc3** [comment]
David is updating this process with the BOM approach.

**Comment by elopatin-uc3** [comment]
I'm opting to mark this ticket as Done, as it can be superseded by #1413
