### ISSUE TITLE
[RELEASE] Ingest timeout for Storage hostname - 11/09/22

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#1267]
# Overview of Release
No retry logic in core2 lib used for hostname.  Use HttpGet over FileUtil

# Service(s)
Ingest

# Github Issue Link(s)
https://github.com/CDLUC3/mrt-doc/issues/1240

# Servers affected
uc3-ingest01x2-prd
uc3-ingest02x2-prd
uc3-ingest03x2-prd

# Source Code:
https://github.com/CDLUC3/mrt-ingest/releases/tag/0.0.31

# Jenkins/Build Info: (if applicable)
http://builds.cdlib.org/userContent/mrt-ingest/mrt-ingest-0.0.31.war

# Deployment Steps (if applicable)
- [ ] Update Puppet repo for new tag
- [ ] remove worker from ALB
- [ ] stop Tomcat
- [ ] deploy using deploy script
- [ ] start Tomcat
- [ ] enable worker in ALB
- [ ] rinse and repeat for new workers

# Infrastructure Changes to support deployment (ALB, EFS, etc)
Remove worker from ALB uc3-mrt-ingest-prd-alb

# Rollback Instructions
Does new script support Rollback @ashleygould

**Comment by mreyescdl** [comment]
Complete

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl !
