### ISSUE TITLE
Update storage to support either path-based or DNS-based S3 access

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#127]
Amazon S3 has two bucket URL schemes, path-based and DNS-based:

- path-based: `https://<endpoint>/<bucket>/<key>`
- DNS-based: `https://<bucket>.<endpoint>/<key>`

Amazon has [deprecated path-based routing](https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/) and announced that while buckets created before 2020-09-30 will continue to work with it, buckets created after that date will require DNS-based routing.

Currently, [we're using the path-based scheme](https://github.com/CDLUC3/mrt-cloud/blob/62739213612e3eeb59cfb408dc88968d8ba95a81/s3-src/src/main/java/org/cdlib/mrt/s3/aws/AWSS3Cloud.java#L223) both for Minio and for Amazon S3. Minio can be configured to support DNS-based URLs but it [requires shenanigans](https://github.com/minio/minio/tree/master/docs/config#domain) and we shouldn't count on SDSC or anyone else to do it.

We should make the choice of DNS-based or path-based routing part of the S3 node configuration.
 - [ ]

**Comment by dloy** [comment]
Confirmed that the S3 java SDK used by our cloud interface (storage, replication, and audit) By default use the virtual form (DNS) for the AWS S3 URL. We're good on that.

The form of this URL includes the bucket name as part of the service name:
http://uc3-s3mrt5001-dev.s3.us-west-2.amazonaws.com/ark%3A/13030/mytest%7C1%7CSmall

In this URL:
uc3-s3mrt5001-dev = bucket 
us-west-2 = region
ark%3A/13030/mytest%7C1%7CSmall = key

For DNS/virtual form, the bucket is included before the first slash - part resolved by DNS.

**Comment by marisastrong** [comment]
Thanks for confirming.
________________________________

**Comment by elopatin-uc3** [comment]
@terrywbrady David confirmed this was done. Closing
