### ISSUE TITLE
Rails redirect to login controller occurs over http, rather than https.

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#128]
Note: I discussed this issue with David Moles prior to filing it. It was discovered while investigating a problem reported to us by Sarah Kansa, who is an editor at Open Context.

#### Summary
For guest login to the Merritt UI, it appears that Rails redirects traffic to the login controller over `http`, rather than `https`. This shouldn't be the case for any login action (guest or no). 

Additionally, for public, read-only consumption of images in Merritt (which is the case for Open Context), log in should not be necessary.

#### Acceptance Criteria
* The root cause pertaining to why `http` is being used during the log in process is uncovered.
* Apache+Rails setup is examined to determine if it's contributing to (or is the cause of) the problem.
* Log in is completed over `https`, post fix.

#### Additional request
(we may want to cut a separate ticket for this)
* Evaluate if we should put into place extant code that bypasses login for direct, read-only access to Merritt images.

#### Steps to reproduce
1. In Safari (cache cleared, new browser session), with the console open, navigate to: https://opencontext.org/media/7E2455C6-F37B-4616-9732-551EB5F84275/full
* Result: A redirect loop is reported in console, and the Merritt image in question never loads.
2. Navigate to https://merritt.cdlib.org/login and click the Guest button.
3. In a new tab, go to the Open Context page once again: https://opencontext.org/media/7E2455C6-F37B-4616-9732-551EB5F84275/full
* Result: Image loads

The same process can be followed in Chrome and Firefox, but only a Mixed Content warning will show up in Console, prior to being logged in as guest in Merritt.
 - [ ]

**Comment by terrywbrady** [comment]
@elopatin-uc3 , can you reproduce this error?  I cleared cache and opened this in Safari without issue.  I have not yet tried other browsers.

**Comment by elopatin-uc3** [comment]
@terrywbrady Here's a new example of the issue that was reported by OpenContext. With the console open in Safari, navigate to:
https://opencontext.org/media-search/Cyprus/PKAP+Survey+Area?proj=42-pyla-koutsopetria-archaeological-project-i-pedestrian#15/34.9889/33.7095/18/any/Google-Satellite

You'll see several "Failed to load resources: too many HTTP redirects" messages, as well as warnings about insecure content. 

Oddly, the thumbnails still load.

However if you use Chrome instead, you can see the lack of lack of image thumbnails for the last 8 items on the page (starting with 1485_2b, and ending with 1482_2).

**Comment by ekansa** [comment]
Hi All, this is @ekansa with Open Context.

Yes, we have this trouble. I'm currently mitigating the problem by having Open Context act as a proxy. On a webpage that has links to images in Merritt, I have a little javascript code that fetches these images via HTTPS from Open Context. This is not an ideal scenario, but it beats the images not showing up at all.

**Comment by terrywbrady** [comment]
When performing a guest login in Merritt with the Network Inspector enabled, note the redirect from **http**:/home/choose_login to **https**:/home/choose_login.

![image](https://user-images.githubusercontent.com/1111057/72382441-1dd6ca00-36ce-11ea-8265-928ca8a7c480.png)

**Comment by terrywbrady** [comment]
The redirect to `https:/home/choose_collection` does not work in Safari.

**Comment by elopatin-uc3** [comment]
@ekansa Thanks for your note on the javascript you've deployed to mitigate this issue. Today we tried deploying a fix to one of our UI servers and tested briefly against the Open Context site. We were able to address part of what appears to be the problem, but not all of it. Are you available for a 1/2 hour call to discuss this further?  
Thanks,
Eric

**Comment by terrywbrady** [comment]
https://github.com/CDLUC3/mrt-dashboard/pull/42

**Comment by terrywbrady** [comment]
Changes deployed Jan 30, 2020
