### ISSUE TITLE
Merritt End User Guidance - Capacity

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1285]
For prospective depositors, outline the following
- What is an optimal object conceptually
- What are the optimal guidelines for file sizes
- What are the optimal guidelines over overall object size
- Is there any other guidance about versioning

https://cdlib.org/wp-content/uploads/2022/09/merritt_gdo_v2022.pdf

- [ ] Post all recommendations to a single page on the Merritt wiki
- [ ] Add this guidance to FAQs

Category | Recommended | Largest Existing | Code Limitation | Note
-- | -- | -- | -- | --
Object Size Limit | 500GB | 2.7TB |   | Impacts ZFS file size in use, impacts the ability to download the full object or to replicate many of this size.  TODO: set explicit limit in code.
Object Size UI Upload Limit | 30GB | 30GB | [30GB](https://github.com/CDLUC3/mrt-dashboard/blob/main/config/app_config.yml#L23) | Need pre-signed upload option for larger files.  TODO: create presigned upload solution for outliers.
Nuxeo Upload Limit | 20GB | 30GB |   | Nuxeo has problems above 20GB.  TODO: set explicit limit in code.
Object Assembly Limit | 50GB |   | [322GB](https://github.com/CDLUC3/mrt-dashboard/blob/main/config/app_config.yml#L5) | Limit should be lower if Dryad concurs
File Count Limit | 50K | 360K |   | Inventory service can be impacted even for a small metadata change due to the size of the manifest object that is rewritten.  TODO: evaluate impact of the 50K and 360K and determine optimal memory to accommodate each.
Storage Manifest Size Limit (relates to file count limit or to excessive versioning) | 30MB | 222M |   | Affects inventory and object restoration from storage.  Calculated based on downloading a manifest with 50K files.
File Listing Limit in the UI | 1000 | (360K) |   | TODO: Limit + pagination should be applied
File Listing Limit in the API | 1000 | 1000 | [1000](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/CDLUC3/mrt-dashboard/main/swagger.yml#/experimental/get_api_object_info__ark_) |  
File Size Limit |   | 290G |   | Affects space on storage server and possibly ZFS size  TODO ask David about S3 limitations or fixity check limitations
Ingest Manifest Limit | 5MB | ? |   | Eric has seen some as large as 8-9MB
Daily Ingest Limit | 3.6T | 3.6T |   | ZFS limits and storage server bandwidth limits
Weekly Ingest Limit | 14T | 14.6T |   | To allow replication to catch up

**Comment by terrywbrady** [comment]
Make notes about ingest limitations: 5M for maniest body, 30G for individual file upload.

**Comment by elopatin-uc3** [comment]
Added above limitation notes to:
https://github.com/CDLUC3/mrt-doc/wiki/Adding-Objects#submitting-objects-through-the-merritt-user-interface

**Comment by elopatin-uc3** [comment]
To investigate:
#1521

**Comment by terrywbrady** [comment]
Migrated this content to https://github.com/CDLUC3/mrt-doc/blob/main/object_guidance.md
