### ISSUE TITLE
Cross microservice jar version consistency using Bill of Material (BOM)

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#1286]
### Problems
Each microservice (store,inventory, ...) uses its own maven pom.xml with varying jars included.  

Some of the jars included in each pom.xml have vulnerabilities detected by the GitHub dependabot service.

Because the versioning numbers are manually set independently in each microservice the specific version included in each pom.xml may differ. 

### Goal
- There is only one jar version used across all services
- No mechanism for standardizing the included version will bring in additional jars into the constructed war file that is not used
- if a specific version of a jar is needed (even with vulnerabilities) it may be overridden

### A solution
The Bill of Material (BOM) pom.xml is one technique for doing this.

For details of mechanism see:
- [Introducing Maven’s Bill of Material (BOM)](https://reflectoring.io/maven-bom/)
- [Introduction to the Dependency Mechanism](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#bill-of-materials-bom-poms)

### Example
- Example BOM
~~~
<project xmlns=...">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.cdlib.mrt</groupId>
    <artifactId>mrt-reflectoring-bom</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>
    <name>mrt-reflectoring</name>
    <dependencyManagement>
        <dependencies>

            <dependency>
                <groupId>com.google.code.gson</groupId>
                <artifactId>gson</artifactId>
                <version>2.8.9</version>
            </dependency>

            <dependency>
                <groupId>org.apache.components</groupId>
                <artifactId>httpclient</artifactId>
                <version>4.5.13</version>
            </dependency>
      
            <dependency>
              <groupId>org.apache.zookeeper</groupId>
              <artifactId>zookeeper</artifactId>
              <version>3.7.1</version>
           </dependency>
      
            <dependency>
                <groupId>org.yaml</groupId>
                <artifactId>snakeyaml</artifactId>
                <version>1.32</version>
            </dependency>

            <dependency>
                <groupId>xerces</groupId>
                <artifactId>xercesImpl</artifactId>
                <version>2.12.2</version>
            </dependency>

        </dependencies>
    </dependencyManagement>
</project>
~~~

- Example referencing pom.xml
~~~
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.cdlib.mrt</groupId>
    <artifactId>mrt-core</artifactId>
    <packaging>jar</packaging>
    <version>2.0-SNAPSHOT</version>
    <name>UC3-mrtcore</name>
    <url>http://uc3.cdlib.org</url>
  
    <!-- reference to BOM -->
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.cdlib.mrt</groupId>
        <artifactId>mrt-reflectoring-bom</artifactId>
        <version>1.0.0</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

    <dependencies>

        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>3.8</version>
        </dependency>
        
        <dependency>
            <groupId>xml-apis</groupId>
            <artifactId>xml-apis</artifactId>
            <version>1.4.01</version>
        </dependency> 
        
        <dependency>
            <groupId>xerces</groupId>
            <artifactId>xercesImpl</artifactId>
        </dependency>

    </dependencies>

</project>

~~~

### Notes
- The BOM 
      - in this example this is an included BOM and not a parent BOM
      - allows the automatic setting of a version number in a referencing pom.xml
      - is a pom.xml that uses normal maven functions (e.g. mvn clean install)
      - contains jar dependency's that will be used for resolving _version_ but will not necessarily be included in war

- The referencing pom.xml 
      - includes a dependencyManagement reference to the BOM as a dependency
      - resolves dependency's by exact string match on groupid and artifactid
      - does not contain a _version_ then the matching BOM version is used. See: xerces:xercesImpl
      - contains a _version_ then that _version_ overrides the BOM. See: org.apache.httpcomponent:httpclient3.8
      - contains a dependency not in the BOM then the _version_ must be included in that pom.xml

- Some issues when using
      - exact match groupid artifactid
      - a BOM reference may not work in the current service and _version_ override may be necessary

### Questions
- worth using
- usable in all IDE
- what to include in BOM: 
    - all cross service dependencies
    - only dependabot alert dependencies
    - all cross service dependencies present in two or more pom.xml's

**Comment by dloy** [comment]
The initial use of a BOM will initially be limited to mrt-core2 and mrt-cloud content. 

Currently an artifact repository is dynamically built with each release using the refactor architecture. The use of the BOM will hopefully provide us with experiences for how to deal with architecting new artifact repositories moving forward with Merritt.

**Comment by dloy** [comment]
## git changes
https://github.com/CDLUC3/mrt-core2/commit/ce8137eb44ab3d5c49a7c6372d99695f4a3f54c9
https://github.com/CDLUC3/mrt-cloud/compare/main...reflect

**Comment by mreyescdl** [comment]
Ingest dep01 branch updated to use BOM.
https://github.com/CDLUC3/mrt-ingest/tree/dep01

One outlier jar is Saxon.  I'm using a newer version than BOM and can't downgrade due to errors.
```
        <!-- BOM uses version 9.4.  Can not downgrade due to error -->
        <dependency>
            <groupId>net.sf.saxon</groupId>
            <artifactId>Saxon-HE</artifactId>
            <version>9.8.0-14</version>
        </dependency>
```

I'm going to deploy to Stage for testing.

**Comment by dloy** [comment]
## Using the BOM
### Merritt
As mentioned above the Merritt BOM (mrt-core/reflect/pom.xml) is used across the Merrritt java microservices to provide a common version for all external jars.
### BOM
- includes all pom.xml dependencies for external jars
- does not include groupId=org.cdlib.mrt jars
- order of dependencies in BOM is in groupId/artifactId

### local pom.xml for source, IT, and war files
#### order of dependencies
- all merritt jars dependencies are listed before in groupId/artifactId order before external jars
- all external jar dependencies are list in groupId/artifactId order
#### dependency
Example
~~~
        <dependency>
            <groupId>javax.mail</groupId>
            <artifactId>mail</artifactId>
            <scope>runtime</scope>
        </dependency>
~~~
- include all external jars in BOM
- if local version is different from BOM for processing reasons then include version in local version but only for a needed processing feature
- if the version in the local pom.xml dependency is greater than the BOM then update the BOM to higher version. 
- only include scope in local pom.xml and not in BOM

### What dependencies to include in local pom.xml
Use the
~~~
mvn dependency:analyze
~~~
command.

#### source pom.xml
For maven:  Unused declared dependencies found
- set scope=runtime - occasionally this may cause compile time errors and the scop should be removed
- optionally determine if dependency should be included but typically this work has been done in earlier testing

For maven: Used but undeclared dependencies
- these jars need to be declared as a dependency in the pom.xml

#### war pom.xml and IT pom.xml
For maven:  Unused declared dependencies found
- remove dependency with noted exception of the Merritt org.cdlib.mrt source jar
- for war files this may result in a single dependency for the Merritt sourse jar

For maven: Used but undeclared dependencies
- these jars need to be declared as a dependency in the pom.xml

### Adding dependency to BOM
Typically the latest version of a local pom.xml dependency should be added to the BOM

Before updating the BOM 
- confirm dependency as a whole does not exist
- confirm version number is not less than BOM version
- confirm there are no dependabot or problem features of updated version

Once the BOM has been updated then the core2/reflect project needs to be rebuilt

Additionally all BOM updates should be confirmed be rerunning full mvn clean installs across all java projects using the BOM.
