### ISSUE TITLE
Evaluate current INV prod hostname and whether or not to put a CNAME in front of the database host

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1292]

**Comment by elopatin-uc3** [comment]
Considerations:
- How quickly do DNS changes propagate? (likely pretty quickly)
- Is the database name useful/meaningful? Current db name with "-fresh" on it is not
- Our services generally recover from a db outage pretty quickly, so is a CNAME going to make things less convenient?

This would require testing on Stage to gauge application behavior and recovery.

nslookup and dig enable you to discover where a CNAME is pointing.

Put this off until the new year; not too many database rollovers to contend with currently.
Having a meaningful name would be good but would require an outage to fix.

See what Ashley's input on this in terms of recommend or not.

**Comment by ashleygould** [comment]
Ashley does not think cname  is needed.  It would be nice, but is not important.

**Comment by elopatin-uc3** [comment]
Thanks @ashleygould
