### ISSUE TITLE
[Dryad]  Fix objects with multiple Merritt ARKs

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#1294]
During outage and subsequent rebuilding of Merritt's production database, 2 Dryad submission were corrupted resulting in each Dryad object having multiple Merritt objects.

To fix, we'll use the Merritt object that has local ID as a base.  Then take payload of other objects and add new versions to it.  
Cleanup will involve removing Merritt objects that reference object, but have to local ID.  Finally, asking Dryad folks to sync with new objects.

**Comment by mreyescdl** [comment]
Here are the two Dryad local IDs that need attention

```
MySQL [inv]> select * from inv_dublinkernels where value like "%doi:10.5061/dryad.4qrfj6qdv%";
+----------+---------------+----------------+---------+---------+-----------+-----------------------------+
| id       | inv_object_id | inv_version_id | seq_num | element | qualifier | value                       |
+----------+---------------+----------------+---------+---------+-----------+-----------------------------+
| 28999499 |       3597262 |        5802024 |       5 | where   | local     | doi:10.5061/dryad.4qrfj6qdv |
| 29026799 |       3597360 |        5807484 |       5 | where   | local     | doi:10.5061/dryad.4qrfj6qdv |
+----------+---------------+----------------+---------+---------+-----------+-----------------------------+

MySQL [inv]> select * from inv_dublinkernels where value like "%doi:10.5061/dryad.rn8pk0pfm%";
+----------+---------------+----------------+---------+---------+-----------+-----------------------------+
| id       | inv_object_id | inv_version_id | seq_num | element | qualifier | value                       |
+----------+---------------+----------------+---------+---------+-----------+-----------------------------+
| 28999829 |       3597264 |        5802090 |       5 | where   | local     | doi:10.5061/dryad.rn8pk0pfm |
| 28999834 |       3597264 |        5802091 |       5 | where   | local     | doi:10.5061/dryad.rn8pk0pfm |
| 29027139 |       3597374 |        5807553 |       5 | where   | local     | doi:10.5061/dryad.rn8pk0pfm |
+----------+---------------+----------------+---------+---------+-----------+-----------------------------+
3 rows in set (51.28 sec)
```

**Comment by mreyescdl** [comment]
@sfisher 
Dryad object _doi:10.5061/dryad.4qrfj6qdv_ has been modified in Merritt.
Can you please sync to the following object?
```
https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm5452xt1
```
After this, the old object will be removed
```
https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm52p2cnq
```

**Comment by sfisher** [comment]
Thanks, Mark.

From: Mark Reyes ***@***.***>
Date: Wednesday, November 30, 2022 at 1:34 PM
To: CDLUC3/mrt-doc ***@***.***>
Cc: Scott Fisher ***@***.***>, Mention ***@***.***>
Subject: Re: [CDLUC3/mrt-doc] [Dryad] Fix objects with multiple Merritt ARKs (Issue #1294)

CAUTION: EXTERNAL EMAIL

@sfisher<https://github.com/sfisher>
Dryad object doi:10.5061/dryad.4qrfj6qdv has been modified in Merritt.
Can you please sync to the following object?

https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm5452xt1

After this, the old object will be removed

https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm52p2cnq

**Comment by sfisher** [comment]
The latest version of 10.5061/dryad.4qrfj6qdv looks good.

**Comment by mreyescdl** [comment]
@sfisher 
Next object is doi:10.5061/dryad.rn8pk0pfm
I've added the following files to the merritt object:
     https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm5k71vg2/2

```
    58320  11-30-2022 14:09   jakstis_et_al._2022_archieved_data.CSV
    13284  11-30-2022 14:09   jakstis_et_al._2022_data_dictionary.xlsx
     1438  11-30-2022 14:10   README.md
```

Can you sync this with Dryad?
After that I'll remove the old object

**Comment by mreyescdl** [comment]
@sfisher Last object Scott

Dryad object doi:10.25349/D9XW4D.
I added file Supporting_information.zip to Merritt object
https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm5g80r11/3

Can you sync with Dryad?

**Comment by sfisher** [comment]
Thanks @mreyescdl 

I've updated these in our database and verified that the latest version of these work and contain all the files they should.  I'll also let the curators know.

**Comment by mreyescdl** [comment]
Thanks @sfisher 
I'm going to download the old objects (in case of an emergency) and then delete the old objects so they do not show up in our report.
Is this okay?
The following will be deleted
```
https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm52p2cnq
https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm5c60x75
https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm55f6372
```

**Comment by mreyescdl** [comment]
Old Dryad objects removed now that Scott has synced with new versions.

ark:/13030/m52p2cnq
ark:/13030/m5c60x75
ark:/13030/m55f6372


Ticket is complete
