### ISSUE TITLE
Service Start/Stop Scripts - Revert to use of catalina scripts - Implement in 2023

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1302]
## Background

Over TG weekend, five of our services did not shut down as expected. Also evident when David was troubleshooting SDSC issue last Friday.

Need to ensure that systemd appropriately handles shut down (forces them to shut down).

Uses Tomcat to make calls to Java services to shut down.

bin start/stop commands try to make shutdown graceful - but we need to be able to really confirm a service is down.

Should be a completely separate function from deployment. That said, during deployments you do need to make sure Tomcat has stopped.

Schedule a separate meeting to discuss with Ashley (Terry will schedule)

## Discussion 12/6

Ashley, Mark, David, Terry, Marisa met.

- Currently, systemd cannot manage the process well because Merritt services send too much output to standard out.  This fills the journal when started by systemd.  
- Currently, systemd is calling a wrapper script to start java and to redirect output.  The call of this wrapper script makes it difficult for systemd to control the tomcat process.
- In 2023, Ashley will modify the start/stop and cdlsysctl commands to use the old catalina scripts.
- @dloy will document the service-specific calls that should be invoked before shutdown.  Services will be given a **brief** opportunity for a graceful shutdown and then they will be killed.

## Note

Our "restart" command is an invocation of a stop and then a start.  The catalina scripts have no notion of a "restart".

**Comment by ashleygould** [comment]
this is on hold while other projects with higher priority are active.
