### ISSUE TITLE
Dryad node scan issues

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1303]
One was a test object; to be removed.
Storage scan revealed one object that had two files: ark:/13030/m5g80r11
Catch up on this after the SDSC scan results

Eric will set up a meeting to discuss scan results later in the week.

**Comment by mreyescdl** [comment]
ark:/13030/m5g80r11 was one of the Dryad objects that needed work.

It looks like there was a rename of:
menuscript.zip to manuscript.zip

However, I never did see the mrt-delete.txt file (there may have been one, though)
 I asked Scott and he said to just copy "manuscript.zip" from version 1 of the old object to the new version.

Two issues flagged:
- manuscript.zip not in version 1.  This was originally menuscipt.zip
- mrt-delete.txt not in version 1.  New object did not perform the rename - thus no delete file

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl for looking into this.
