### ISSUE TITLE
Ingest State command: Add service start time to the state command output

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1304]
Look at the format used in Inventory, Replic, and Audit as an example.

https://merritt-colladmin.cdlib.org/web/collIndex.html?path=instances

**Comment by mreyescdl** [comment]
Added service start time to state response on stage Ingest workers.
This change will piggyback on top of Consumer Daemon branch.

```
    <ing:serviceStartTime>2022-12-09T18:10:35-08:00</ing:serviceStartTime>
```
