### ISSUE TITLE
UC Berkeley Jepson Herbarium: New collection and follow up tasks

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1309]
See #1187 for reference.

- [x]  Create new Merritt Owner Object
- [x] Create new Jepson SLA
- [x]  Create Merritt accounts for STAGE – UCJEPS submitter, JEPS staff
- [x]  Create Stage collection
- [x] Create Production collection
- [x]  Create Merritt accounts for PROD – UCJEPS submitter, JEPS staff
- [x] Work with JEPS to determine collection scheme (one or more collections, collecting areas)
- [x]  Configure profile callback

**Comment by elopatin-uc3** [comment]
Collection name requested: University and Jepson Herbaria Image Archive

Single collection for all objects, given metadata fields in CSpace that will enable discovery via Merritt ARK.

Create Stage and Production collections. Stage will be used to test the callback.

**Comment by terrywbrady** [comment]
See #1340
