### ISSUE TITLE
Annual: Check LDAP Certificate

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1311]
- Is Sword is gone, do we have an ability to use Let's Encrypt?

**Comment by elopatin-uc3** [comment]
Confirm UI doesn't have any issues with autorotation of certificate.
new certificate into java keystore, but could probably do this programatically: what are our options for this?

**Comment by terrywbrady** [comment]
@ashleygould will initiate request for 1yr cert.  In the next cycle, we should explore Let's Encrypt.

**Comment by ashleygould** [comment]
cert has been updated for uc3-mrt-ldap-stg.

we will updated cert for uc3-mrt-ldap-prd on April 5 after I return from vacation.  IAS has already provided me with the new cert.
