### ISSUE TITLE
Updates to annual Billing report to support more granular reporting based on ownership 

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1314]
In order to enable the billing report to display prorated dollar amounts specific to each owner, Terry and Eric discussed the following modifications to the annual billing report format:

- [ ] Build in conditional logic that takes into account the main library on each campus and show the annual 10TB discount applied under the Adjusted Cost column.
- [ ] Add a prorated dollar total for each owner roll-up row under the Cost/TB 150 column
- [ ] Add a new column that shows the 10TB discount amount applied to each owner roll-up row

**Comment by terrywbrady** [comment]
All non-campus collections will report under Other.  No discount will be applied to "Other" collections.

The library owner will be hard-coded into code.  A couple of campuses have a library owner that has not fully utilized the discount. Other owners will be included in the list.

**Comment by terrywbrady** [comment]
https://github.com/CDLUC3/mrt-admin-lambda/commit/8d7ab1cf2368ff4949756ccb38b641ac59483898
