### ISSUE TITLE
[Ingest] Storage hostname error (502 Bad Gateway)

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#1315]
Somewhat related to ticket https://github.com/CDLUC3/mrt-doc/issues/1244

Ingest fails to get a Storage hostname from the Storage service.  This request is routed through ALB.

Timeline of failures
==============
- Fri Dec 09 23:07:22 PST 2022 (from Ingest01)
- Mon Dec 12 11:51:22 PST 2022 (from Ingest03)
- Thu Dec 15 11:38:12 PST 2022 (from Ingest03)

Note:  Ashley has switched the ALB health check to use the `hostname` command as of 12/7
Checks are occurring every 30 seconds

**Comment by mreyescdl** [comment]
Here are ALB uc3-mrtstore-pvt-prd-alb attributes:

```
    "Attributes": [
        {
            "Value": "false",
            "Key": "access_logs.s3.enabled"
        },
        {
            "Value": "",
            "Key": "access_logs.s3.bucket"
        },
        {
            "Value": "",
            "Key": "access_logs.s3.prefix"
        },
        {
            "Value": "4000",
            "Key": "idle_timeout.timeout_seconds"
        },
        {
            "Value": "true",
            "Key": "deletion_protection.enabled"
        },
        {
            "Value": "true",
            "Key": "routing.http2.enabled"
        },
        {
            "Value": "false",
            "Key": "routing.http.drop_invalid_header_fields.enabled"
        },
        {
            "Value": "false",
            "Key": "routing.http.xff_client_port.enabled"
        },
        {
            "Value": "false",
            "Key": "routing.http.preserve_host_header.enabled"
        },
        {
            "Value": "append",
            "Key": "routing.http.xff_header_processing.mode"
        },
        {
            "Value": "true",
            "Key": "load_balancing.cross_zone.enabled"
        },
        {
            "Value": "defensive",
            "Key": "routing.http.desync_mitigation_mode"
        },
        {
            "Value": "false",
            "Key": "waf.fail_open.enabled"
        },
        {
            "Value": "false",
            "Key": "routing.http.x_amzn_tls_version_and_cipher_suite.enabled"
        }

**Comment by mreyescdl** [comment]
Creating a client script that will issue similar requests and record response times

Script running on ingest01-aws at `/apps/dpr2/tools/storage_hostnames`

**Comment by mreyescdl** [comment]
Another 502 from Storage ALB.  Cross-referencing time with client script running does not show any delays.
Very hard to explain why Ingest client is seeing an issue.

**Comment by elopatin-uc3** [comment]
Noting the latest failure: 
```
	Primary ID: ark:/13030/qt9n81h428
	Filename: qt9n81h428.checkm
```

**Comment by elopatin-uc3** [comment]
Mark is going to take on creating a Java client to try to replicate this issue. He's been running tests via command line to replicate but no luck so far after a week of letting the process run.

Possibly review ALB logs at the time these issues occur.

**Comment by mreyescdl** [comment]
Found a bug in the hostname retry logic.  This will be deployed as part of the Consumer Daemon branch
https://github.com/CDLUC3/mrt-ingest/commit/ce3d423fa21d3f76fbb4065ba77073702026520c

We still do not know why the ALB responds with a 502, but this fix should prevent this from bubbling up to the surface.

**Comment by mreyescdl** [comment]
Continue to try and replicate 502 error from ALB by running Java client on ingest01 at "/dpr2/tools/storage_hostnames/java"  
This makes a hostname call every 10 seconds and will email if there is an error.  Note, this code is not the buggy code as mentioned above, but a fixed version.
