### ISSUE TITLE
Replic, Inventory, BOM, small war, start time

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#1316]
This project is to do the following:
- address any new dependabot issues with Replic and Inventory
- Use the core2 and mrt-cloud BOM versions
- reduce the overall size of replic removing the unused AWS java jars
- add start time to state
- review deploy, start, stop

Replic is a good starting point for the above changes:
- uses both core2, mrt-cloud and MySQL
- can be easily deployed without impacting other services

Inventory code is used by Replic so this code will also be updated. Release may be separate.

**Comment by dloy** [comment]
Questions on this process:
- should replic jars also use BOM

**Comment by elopatin-uc3** [comment]
@ashleygould suggested that she and @dloy review which dependencies are unnecessary. 

We should also document our way through all Dependabot-referenced dependencies. We need to figure out what can and can't be removed - and if something needs to stay, what is our take on use/version/etc.
