### ISSUE TITLE
[RELEASE] UI fix worker count / thread count in UI

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1320]
# Overview of Release
Fix worker count/thread count in ui
# Service(s)
ui
# Github Issue Link(s)
https://github.com/CDLUC3/mrt-doc/issues/1321
# Servers affected
ui03, ui04, ui05
# Source Code:
Link(s) to tagged release(s)
https://github.com/CDLUC3/mrt-dashboard/pull/136/files
# Source Code Tag
1.2.6

# Jenkins/Build Info: (if applicable)

# Deployment Steps (if applicable)
- [ ] Action Step 1

# Infrastructure Changes to support deployment (ALB, EFS, etc)

# Rollback Instructions
fallback to 1.2.4

**Comment by mreyescdl** [comment]
Found bug that exhausted open file limit.  Ashley increase limit from 4K to 54K, but a fix is warranted as well.
https://github.com/CDLUC3/mrt-ingest/pull/71
