### ISSUE TITLE
eSchol syncOut timestamp mismatches

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1327]
Related eSchol code:
https://github.com/cdlib/pub-eschol-xtf/blob/5cecfb25f1ceda4304da97a02fd6a03f255e1a0c/control/tasks/syncOut.py

Example object:
https://merritt.cdlib.org/m/ark%253A%252F13030%252Fqt07v1t51g/1
- Version 1 and 10 have different meta.xml dateStamp and stateDate values. Version 1 has a later stamp than version 10...

**Comment by terrywbrady** [comment]
What actions will be needed to resolve this issue?

**Comment by elopatin-uc3** [comment]
Mahjabeen is going to review the syncOut logic (linked to above). We can briefly discuss this today, but I've already noted to her that I don't see how this issue could have involved Merritt. There is no expectation of further investigation until January. What's next depends on what she finds.

**Comment by elopatin-uc3** [comment]
As of 1/9, syncOut queue has approximately 33% fewer items in it. Mahjabeen is busy with a high-priority PLOS task this week and next, so we will determine if we need to meet about this issue when she has more bandwidth.

**Comment by elopatin-uc3** [comment]
Mahjabeen has found that these are slowly cleaning themselves up, likely because of updates to jschol metadata. 
Closing
