### ISSUE TITLE
[Cleanup] Add command to Inventory service to pick up new storage node

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#133]
w/o creating dummy objects in storage or putting dummy jobs on ZooKeeper

After this is in place, update #162552690 (Minio checklist template ticket) to document how to use it
 - [ ]

**Comment by elopatin-uc3** [comment]
Process exists as inventory filenode command:
curl -X POST 'http://uc3-mrtinv-stg.cdlib.org:36121/mrtinv/filenode/2111?t=xml'
Previous version only updated existing MySQL entry. This version, now stage, will create a new entry from an existing storage node. (David Loy - May 28, 2019)

**Comment by elopatin-uc3** [comment]
@dloy can you  specify what is meant by inventory database?  i.e. which table and which fields are affected?   (Marisa Strong - May 28, 2019)

**Comment by elopatin-uc3** [comment]
inv/inv_nodes entries are modified as a result of calling a storage node state request - all inv_nodes columns are updated.
 (David Loy - May 28, 2019)

**Comment by elopatin-uc3** [comment]
Change is now available on:
uc3-mrtinv-stg
uc3-mrtinv2-stg (David Loy - May 28, 2019)

**Comment by elopatin-uc3** [comment]
Low priority change - needed for adding new node 
Not in prod as of this date (David Loy - Jul 10, 2019)

**Comment by dloy** [comment]
Command added (filenode/{nodeNum}) as part of later prod commit
