### ISSUE TITLE
[Zookeeper] Inventory queue cleanup (deleted, completed states)

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#1338]
Inventory queue in Zookeeper is used for async. Ingest to Inventory communication.
Ingest will write data to this queue and set each entry to "pending" state.
Inventory reads these entries and processes, resulting in a completed or failed state.  The admin tool can be used to set any entry to a deleted state.
Entries are not cleaned up by any Java service, but instead done by a cronjob on one of the Zookeeper hosts (uc3-mrtzk01x2-prd).  This cron only removes completed states.  

Currently, Ingest cleans up its own queue hourly.  Each worker has its own queue, which differs from a single Inventory queue.
This ticket will explore cleaning up the Inventory queue.
This work can be done by either 
- Inventory worker (1 only)
- Ingest worker (1 only)
- Admin tool

**Comment by mreyescdl** [comment]
Looking at the Zookeeper tool code shows that we call a CDL ZK lib method named "cleanup" with a state argument.
This method really should be exposed in the Ingest admin API.  With this, we can fully eliminate the need for the tools used on the ZK hosts.  Also, it can allow for manual cleanup of tools.  Note: we still can have a Ingest or Inventory worker process the cleanup, but having the API will be additionally useful.  It may even allow the Admin tool to take over the task.

I propose the following API where the only states that can be cleaned are "deleted" and "completed"

POST admin/cleanup/{queue}/{state}

@terrywbrady If this sounds okay, I can create a ticket for this API addition.  Thanks.

**Comment by terrywbrady** [comment]
@mreyescdl , this makes sense to me.  Please do create this ticket.

**Comment by elopatin-uc3** [comment]
Associated ticket: #1339

**Comment by terrywbrady** [comment]
removing myself.  I have a separate ticket for the admin tool.

**Comment by elopatin-uc3** [comment]
Enable batch cron to use new API as well.
