### ISSUE TITLE
Create S3 bucket for Merritt Snowcone usage

### ISSUE THREAD

**Issue by ashleygould** [CDLUC3/mrt-doc#1340]
Merritt wants an S3 bucket for use with large ingests coming in by way of AWS Snowcone devices.  

Bucket is needed **by 2/2** so that Snowcone order can be completed
- [x] Determine AWS account - `cdl-uc3-dev`
- [x] Determine bucket name - `uc3-mrt-snowcone-jepson`
- [x] Determine Resource Tags:
    - Program: uc3
    - Service: mrt
    - Subservice: snowcone
    - Environment: jepson
- [ ] Determine and Set bucket permissions
- [x] Create Bucket
- [ ] Create retrieval lambda

Retrieval Service should be available by **2/9** to ensure that loaded data can be retrieved by UCJEPS and ingested into Merritt
- [ ] Expose retrieval lambda as web service
- [ ] Provide credentials for lambda

**Comment by ashleygould** [comment]
notes from call with Eric and Terry

- https://github.com/CDLUC3/pal-museum-metadata/blob/main/src-ruby/app.rb#L639
- https://github.com/CDLUC3/merritt-docker/blob/main/mrt-inttest-services/pm-server/app.rb

**Comment by terrywbrady** [comment]
@ashleygould , @elopatin-uc3 , I added some TODOs for the creation of the web service as well.

**Comment by ashleygould** [comment]
S3 bucket for snowcone is in account `cdl-uc3-dev`.  BucketName is `uc3-mrt-snowcone-jepson`

**Comment by elopatin-uc3** [comment]
Thanks @ashleygould !
