### ISSUE TITLE
Audit failures ark:/13030//m59g71tt

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#1345]
Two audit problems occurred on object with inv_objects.ark="ark:/13030/m59g71tt" and inv_versions.ark="ark:/13030//m59g71tt" as status="unverified"

The manifest for the object contains: ark:/13030//m59g71tt
  <object id="ark:/13030//m59g71tt">

Because the ark contains "//" the minio version of this object fails because minio uses an underlying file system and "//" is invalid. 

Issues:
- the object.ark differs from the version.ark
- the manifest ark is the invalid version.ark
- only two of the audits indicate an error ("unverified")  when all files should have failed on audit
- all audits for object at minio contain 404 exception in note
- a single audit issued on a file containing status='verified' with a minio node returned "verified" but the note of the audit contains the note:
~~~
org.cdlib.mrt.s3.tools.CloudChecksum-getMeta:138 REQUESTED_ITEM_NOT_FOUND[Request contains element that cannot be located] CloudChecksum: object not found: - service=AWS_S3 - bucket=cdl.sdsc.prod - key=ark:/13030//m59g71tt|1|producer/README
~~~

Actions:
- try to determine origin of "//" in ark
- fix audit bug of a status='verified' with a 404 missing response
- determine if there are any additional status="verified" and note is not null

**Comment by dloy** [comment]
Audit change is needed to trap all TExceptions from cloud handling as an "unverified" error. The current code is only trapping specific exception types.  Any new type (here a 400 from Minio) was not detected and the update removed. To fail all TExceptions in the audit table is straightforward.

The failure to mark the errors as verified is related to the transaction being backed out.

**Comment by dloy** [comment]
Note 'ark:/13030/m59g71tt' is a curatorial object place holder for the "UCSC Library Grateful Dead Archive" collection. Deleting and re-adding should be possible
~~~
SELECT *
FROM inv_objects
WHERE ark='ark:/13030/m59g71tt'

850768	3	ark:/13030/m59g71tt	2ec	MRT-curatorial	MRT-content	MRT-collection	2	(:unas)	UC Santa Cruz Library: Grateful Dead Archive	(:unas)	ark:/13030//m59g71tt ; (:unas)	2014-04-14 12:50:25	2014-12-03 18:16:40

SELECT *
FROM inv_collections
WHERE ark='ark:/13030/m59g71tt'

298	850768	ark:/13030/m59g71tt	UCSC Library Grateful Dead Archive	ucsc_lib_grateful_dead	restricted	restricted	restricted	standard	none
~~~

**Comment by dloy** [comment]
The following are some of the problems related to
- current profile ucsc_lib_grateful_dead: Collection.1: ark:/13030/m59g71tt
  - ark used inv_collections.ark
  - ark used in inv_objects.ark

- ark:/13030//m59g71tt - not clear if used in previous ingest profile
  - saved in each inv_version.ark
  - save in each inv_audits.url
  - as saved in each collection 1/system/mrt-membership.txt:ark:/13030//m59g71tt
    - Because all collection objects have the // saved as part of the system/mrt-membership.txt any attempt to rebuild for each object will create a dummy collection with //

Because of minio the // version cannot be created. Creating an object with the single slash will not correspond to the locally saved mrt-membership.txt in each collection member. 

Not clear what next steps on this should be.

**Comment by terrywbrady** [comment]
Notes from meeting on 1/23
- [ ] clean up  ark:/13030/m59g71tt (admin object)
  - [ ] Clean up S3 key on Minio
  - [ ] Clean up S3 key on secondary storage 
  - [ ] Clean up database entries for this admin object (identified above)
- [ ] Clean up mrt-membership system files for 104 real objects

**Comment by elopatin-uc3** [comment]
David, Mark and Eric will meet on 1/25 to discuss and divide up tasks.

**Comment by dloy** [comment]
Proposed Fix:
- [ ] add object to prod minio (9501) - ark:/13030/m59g71tt - with // correction in all system files and only one version
- [ ]  change ark in db.inv_objects to ark:/13030//m59g71tt - this will then become the searchable ark for the bad object
- [ ]  change ark in db.inv_collections to ark:/13030//m59g71tt - set to bad searchable ark
- [ ]  add object to db using corrected object - ark:/13030/m59g71tt
- [ ] in Grateful Dead collection entry (inv_collections) change inv_object_id to corrected object
- [ ] in Grateful Dead collection entry (inv_collections) change ark back to corrected object
- [ ]  delete ark:/13030//m59g71tt on store5
- [ ]  validate deletion worked for db, glacier and wasabi
- [ ]  force replic for ark:/13030/m59g71tt
- [ ] confirm replication

**Comment by dloy** [comment]
Done:

update inv_objects
set ark = 'ark:/13030//m59g71tt'
where id=850768
and ark = 'ark:/13030/m59g71tt'

update inv_collections
set ark = 'ark:/13030//m59g71tt'
where id=298
and ark = 'ark:/13030/m59g71tt'

DELETE FROM `inv_collections` WHERE `id`=509;

UPDATE `inv_collections` 
SET `inv_object_id`=3620175, `ark`='ark:/13030/m59g71tt'
where `id`=298
and `inv_object_id`=850768
and `ark`='ark:/13030//m59g71tt'

From uc3_mrtstore01x2_prd

Delete:ark:/13030//m59g71tt
ark:/13030//m59g71tt REPLIC=OK STORE=NONE INV=OK LOCAL=NONE

**Comment by elopatin-uc3** [comment]
Thanks @dloy !
