### ISSUE TITLE
UCB search by file name request

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1349]
Recently there was a need (UCB) to update the erc_what field with file information in order to enable easier discovery of certain objects in a collection. This was actually a workaround and was completed. However the key request is to be able to search by file name.

How often is there a path in the file name? e.g. Should we address objects that contain multiple files with the same name, but in different directories (to discuss at Jan 31 meeting).

## Potential Solution
- create new table: https://github.com/CDLUC3/merritt-tinker/blob/main/fileindex/README.md
  - [x] DEV
  - [ ] STG
  - [ ] PRD 
- index all content (see above)
  - [x] DEV
  - [ ] STG
  - [ ] PRD 
- [ ] modify UI code: https://github.com/CDLUC3/mrt-dashboard/pull/138
- [ ] modify UI unit tests
- [ ] design process to keep content up to date: 
  - modify INV code?
  - create trigger?
  - create nightly indexing process?
- [ ] modify delete process to delete from the new tables
- [ ] modify docker images containing tables
- [ ] modify admin tool queries

## Alternative Solution
- Add index to inv_files table

**Comment by elopatin-uc3** [comment]
It would be ideal to add the relevant parts of files into the full text index (being created by a mysql trigger). 
Add file name into the index when a new object is created?

Assume they would not want to specify the entire path, but ask about this (per some objects containing more than one file named the same.

**Comment by terrywbrady** [comment]
Notes from John K about the search explanation.

> Unfortunately, the tool tip is not accessible to keyboard-only or screen-reader users. The “i” icon doesn’t accept keyboard focus, so there is no way to see (or hear) the tip. I don’t have a specific implementation to point to, but on-click is generally easier to do in an accessible way than on-hover. Alternately, you could expand the text under the search box to get rid of the tool tip. Something like….
> 
>  
> 
> Search with:
> 
> Identifier (exact match)
> File name (exact match)
> Author, title, or date
>  
> 
>  
> 
> …might give your users enough information to understand their search results without cluttering the page too badly.
