### ISSUE TITLE
Jepson retrieval service needed

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1358]
Ashley has a plan for future requests for this workflow that will involve creating a bucket and supplying the retrieval service together (Ruby rake installation). 
- Bucket name will be hard coded into the service. 
- The user will need to supply each key that needs to be retrieved.
- The retrieval service will be a lambda that calls the Sinatra app.
- The retrieval service will supply basic auth.
- Should be low cost per call.
- API gateway to start; no load balancer initially.
- Will be easier to test once we have some content to work with on Stage using different size manifests.

To consider:
- If ingest calls the lambda, ensure the lambda can handle this type of load, e.g. for a 1K object manifest

**Comment by elopatin-uc3** [comment]
Current schedule:
- First Snowcone should arrive on 2/4. Likely to be returned on 2/17.
- Ashley has most of the parts in place already; will need to perform a "hello world" test.

**Comment by terrywbrady** [comment]
@elopatin-uc3 , closing... no longer relevant
