### ISSUE TITLE
After Sword Replacement, do we need to coordinate HA load balancer calls for the UI?

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1362]
- add register/de-register to puppet deploy scripts
- add special mechanisms to control puppet during deployment
- consider Ansible for more control of the load balancers as well

**Comment by elopatin-uc3** [comment]
Mark chatted with Scott about switching over to being a normal depositor. In terms of timing, nothing concrete right now. We should coordinate on their switch. Mark's provided documentation. We should coordinate on testing on stage.
