### ISSUE TITLE
Eliminate hp-jena from mrt-core, Ingest and Storage

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1368]
Currently using 2.6.4. Blocking us from updating log4j version accordingly.

- [x] remove Ingest dependency on Core mrt-jena library
- [ ] remove hp-jena from mrt-core, Ingest and Storage (David) - this will break ingest
- [ ] Check wiki docs and remove any references to Turtle files

Impacts of removing hp-jena are:
- Turtle file created by Ingest will no longer be created (system/mrt-object-map.ttl)
- RDF Turtle format type will no longer be supported (e.g. obtaining their content in XML)

Deploy notes:
- This change for hp-jena in and of itself may not merit immediate deployment, but deployment would be preferred if we can update log4j version.

**Comment by mreyescdl** [comment]
Confirmed that Ingest does not use mrt-jena

**Comment by mreyescdl** [comment]
Status

- Core library changes merged to main branch
- cdl-zk-queue changes merged to main branch
- mrt-ingest changes in "nojena" branch and tagged as 1.0.4.dev01 
- Ingest changes deployed to Stage and tested
