### ISSUE TITLE
Investigate BOX connector idea

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1375]
Colin mentioned the possibility of obtaining, admin permissions to the entire tree of content in order to download. Then use a util like Robocopy to download everything.

Possible to treat as another drive in the Windows file system (samba)
Or maybe an NFS mounted device, like a Snowcone?
Consider storage gateway?

**Comment by terrywbrady** [comment]
David implemented this.  Closing as presumed duplicate
