### ISSUE TITLE
Admin tool menu tweaks

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1381]
Requests, observations:
- Add Recent bytes ingested by hour to System Status
- Submit Admin object page buttons need to be greyed out after click
- Manage Storage Nodes for a Collection: it would be helpful to have this appear on the list links of that's surfaced by choosing Administer Merritt > Collection Creation

**Comment by terrywbrady** [comment]
Done.  I am unable to test the button grey out.  Let me know if you have any issues with this in the future.

https://github.com/CDLUC3/mrt-admin-lambda/commit/5dd62684ba09c4f1a604a79018c6c2f2eb76486a

Let me know if you want any additional changes.
