### ISSUE TITLE
Merritt UI - Extra Wide Display of Search Results

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1384]
https://merritt.cdlib.org/s/ucb_indochina_archives?utf8=%E2%9C%93&terms=%22Yu+yin+cong+hua%22&group=ucb_indochina_archives&commit=Go

<img width="1250" alt="image" src="https://user-images.githubusercontent.com/1111057/220774470-adb6fa30-9bc2-484a-9031-bb8689bedde1.png">

With `white-space: no-wrap` disabled

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/1111057/220774839-5e456d6d-9e44-469d-8120-dbbb8fe9edfa.png">

**Comment by elopatin-uc3** [comment]
Thanks for working on this @terrywbrady . I'm curious how the decision was reached by the depositor to include such extensive metadata. Some of it looks like its erroneous. I'll follow up.

**Comment by terrywbrady** [comment]
Terry met with Joel.  The following settings should be used for the search results page.

- text-overflow: ellipsis,
- overflow: hidden,
- width: 400px, 
- display: inline-block

Note that the display issues also apply to the item page.  We will need to adjust that as well

<img width="1252" alt="image" src="https://user-images.githubusercontent.com/1111057/221045064-b5fb5949-9e89-4f1e-b61f-9bb0ef2ab8a8.png">

**Comment by terrywbrady** [comment]
From Joel:

> Terry, here's a post that explains more about truncating strings with ellipses: https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/
One of the examples there uses min-width: 0  for the width property. You might try that instead of the fixed width we were using and see if that works.

**Comment by terrywbrady** [comment]
Alternate proposal... rather than having the "no-wrap" what if we just use an inline-block to force the item to its own line?

@elopatin-uc3 , I would like to chat about this option with you.

**Comment by elopatin-uc3** [comment]
Thanks @terrywbrady , let me know when you'd like to hop on zoom. Also, I pinged UCB LIT about the metadata to confirm whether or not they intended it to be this way.

**Comment by terrywbrady** [comment]
Eric and Terry met and descided on display: inline:  https://github.com/CDLUC3/mrt-dashboard/commit/0544ce1abf1243983dd4a44f4ab16585c895f80f
