### ISSUE TITLE
Create “Large Data Report” Solution

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1385]
## Immediate Needs

- match PalMu inventory to the list of ingested files (too big for existing report infrastructure)
- Jepson inventory validation

## Opportunities

- this could be the core of a campus-facing “admin tool” in which pre-generated reports could be made accessible
  - Campus user -> ALB -> Cognito -> SAML -> Lambda (Sinatra) -> Html page that loads presigned reports as json

## Report structure
- reports would exist in a report bucket - would not use production  Merritt buckets
- Reports could exceed lambda payload size, would need to be limited to some resonable default for a browser download.  Report data would be made available via presigned url.
- report data would be loaded and with bootstrap tables.  Content would be paginated and filtered.

## Access
- a public-facing website would exist to authorize access to specific reports
- In the short term, basic auth could be implemented as a proof on concepts
- Ultimately, Cognito/SAML authorization should be used to limit access to specific reports

## Report generation / re-generation
- where possible, generate via lambda.  Allow admin tool user to trigger the re-generation of a report.
- Cron generated for regular reports 
- Manual creation by script for one-time generated reports

## Initial steps
- generate PM inventory match to files on disk
- Preview merge report in browser using bootstrap tables
- Script re-generation of PM inventory match
- Make file accessible via admin tool
- Consider making a similar report accessible via the jepson web service

**Comment by elopatin-uc3** [comment]
Thanks @terrywbrady, This is a great idea. Let's chat about it during our next 1:1.

**Comment by terrywbrady** [comment]
@elopatin-uc3 , closing... this was done with our PM rule
