### ISSUE TITLE
Multiple install microservices with working backout

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#1391]
### Problem
The specific problem for this Issue is the install into both stage and production of multiple interacting micro-services using the BOM pom.xml with possible backout if install fails.

#### Install
The current approach for an install requires:
- tested version of microservice
- upload of changes to mrt-* repository
- semantic tagging of branch or main (in stage) or main (in prod) - 
__Note__ if a tag has not been completely uploaded when tag is created then the non-uploaded content will be uploaded as part of uploading the tag. This content is not accessible remotely except as a change token if it can be located
  - add all content to a single remote main or branch remote
  - create tag and push tag remote to mrt-*
  - use created semantic tag as part of Jenkins to build a war associated with tag
 - update uc3-data/fqsn entry for either stage or prod with updated fqsn
   - update specific yaml service_release: to new semantic tag
   - push change to uc3-data to uc3devops
   - ssh to uc3devops - pull change
 - puppet changes occurs on microservice
   - can occur by time or forced
 - update deployed changes to server
   - stop server
   - deploy changes
   - start server

#### Backout
It is not clear there is working backout mechanism. 
- the "current" tomcat pointer needs reset to previous working state
- the puppet environment needs to be restored to previous working state

### Steps
- confirm status of Backout
- ???

**Comment by elopatin-uc3** [comment]
There are a error messages noted by Capistrano on the rollback command. The command worked, but it gave us an impression that it didn't. Let's look into what these errors mean.
