### ISSUE TITLE
Service management: Complexity

### ISSUE THREAD

**Issue by dmolesUC** [CDLUC3/mrt-doc#14]
Apache

- 65 distinct rewrite rules
- multiple roles: load balancer, front end, URL munger...?
- leads to double or triple encoding/unencoding

LDAP

- authentication (username/password)
- authorization (user permissions by collection)
- user profile metadata (name, phone, etc.)
- UI (`mrt-dashboard`) code is inconsistent in its use of LDAP vs. database for collections

## Questions/Action Items

Apache:

- are there any rewrite rules we can already remove?
- is anything going through Apache that doesn't need to?
- what are the obstacles to eliminating Apache entirely?

LDAP:

- is there an auth/auth solution that:
  1. can be based on the inv database
  2. can work with Rails (ideally with Devise, cf. DMPTool)
  3. can replace LDAP auth/auth in `mrt-sword` and `mrtexpress`?
- if `mrt-sword` and `mrtexpress` already talk to the inv database,
  maybe we can move the authorization piece and keep LDAP just for
  authentication, as a first step

**Comment by terrywbrady** [comment]
Closing, ideas captured elsewhere
