### ISSUE TITLE
Merritt UI - evaluate additional WAF rules to activate - 04/19/2023

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1401]

**Comment by elopatin-uc3** [comment]
Complexity maximum: We can add rules until we hit this max. Can't count what we block. 

Mark is planning to reach out to IAS to obtain logs to analyze.

**Comment by terrywbrady** [comment]
Terry, Mark and Colin should meet.

**Comment by mreyescdl** [comment]
Request made to IAS for counting of the following regex for WAF - uc3-mrtui-prd-waf
```
WORDPRESS
---------
'(/wp-content/|/wp-content/|/wordpress/)'

PHP and CGI
-----------
'(/cgi-bin/|\.php)'

WINDOWS
-------
'(boot.ini|win.ini)'

UNIX
----
'(/etc/passwd|%2Fpasswd)'

ESCAPE
------
'(\\\\\\|/////)'
```

**Comment by terrywbrady** [comment]
@elopatin-uc3 , closing... this was implemented.  Any additional work should be done in a new ticket
