### ISSUE TITLE
BOX URL generation

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1409]
Objective:
Automate the acquisition of file URLs from BOX. URLs will then be manually added to an ingest manifest that is configured for either single or multiple files per object. 

Run from command line:
- Input a BOX folder URL as a parameter
- Generate and fetch a URL for each file in the specified folder via API calls and use of required authentication
- Alter URLs to replace /s/ with /public/static/
- Output URLs to a CSV

Next steps:
- Determine if an application running on a standalone workstation will be able to access more than one BOX installation, or if this is dependent on user permissions or installations at each campus.
- Determine preferred program language. Java, python? Use of the program on Linux and Mac workstations should be considered a priority.

Notes:
- Our understanding is that Campus content to be ingested must in a publicly accessible BOX directory (at ingest time).

**Comment by dloy** [comment]
Currently I have not been able to get needed authorization to get this process to work without requiring some type of authorization on the part of our Box users ahead of time - even if the box folder link is publicly shared.

A stackoverflow was issued on this: https://stackoverflow.com/questions/75838802/download-boxfiles-in-a-shared-boxfolder-using-box-developers-app-in-java

Currently I am backing off this approach and moving to a normalization process for the URL used for requesting shared content. 

A shared link to a Box folder takes the form:
https://ucop.box.com/s/rrhyfocytx652kfsher8lvq........
https://[box service]/s/[file authentication for share]
This format is used to bring up a web page with the content displayed in the page.

The download format for a shared file link:
https://[service]/public/static/[file authentication for share]
or 
https://[service]/shared/static[file authentication for share]

I’m proposing using a new method in core2/org.cdlib.mrt.core.FileComponent
fileComponent.getURLNorm()

This method modifies a Box shared link to a Box download link. Note this approach is currently used in Dryad.

I believe the only call change is a modification in Ingest HandlerRetrieve.

In HandlerRetrieve
// launch download
               Future<String> future = executorService.submit(new RetrieveData(fileComponent.getURL(), targetDir, fileComponent.getIdentifier()));
                tasks.add(future);

The proposed change is the call
.getURL()
To
.getURLNorm

**Comment by elopatin-uc3** [comment]
The team has decided to stop work on this until we have more time to explore use of OAuth and the BOX API.

**Comment by marisastrong** [comment]
A meeting has been setup with the UCOP Box admin to better understand other workflows.

**Comment by dloy** [comment]
## Downloading a Box Folder
### Approach
This mechanism allows the authorization for downloading a BoxFolder.

#### Box Developer App
- create a box developer app using App Token (Server Authentication)
  - this requires box administration authorization for the app (sent automatically)
- from the Configuration tab screen generate a Private Token - this is treated by Box as an AuthToken on the part of the app
  - be sure to copy this value

#### Remote source user
- Request remote user of content you want to download to add the developer app as a collaborator on the directory to be downloaded
- the developer app email to be used is in the developer App/configuration/ServiceAccountInfo - Service ID
- Request remote user to generate a shared link on the specific Box Folder to be downloaded

#### Running Download
This directory is used for running downloading content from remote box hosts.

## Setup
Each download has a directory on /apps/dpr2/ingest_home/queue/boxContent specific to the download.

Download directory examples include .../2_2_2_screenshots, vaccine_screenshots

For each download directory will eventually contain 2 directories and 1 file:
- data - contains the downloaded box files
- log - includes TLogs documenting each downloaded file
- boxconfig.prop - configuration information needed to run download

## boxconfig.prop

### Example
~~~
privateAccess=bSZXPImxxxxxxxxxxxxxx...
downloadURL=https://ucsf.box.com/s/kbuqkszl0dfwhtalhfnnwngqsxm4fzgm
dumpFreq=200
~~~

### Description
privateAccess - is a box private access key take from a box developers app using App Token (Server Authentication)
downloadURL - is a shared link for the BoxFolder to be used for download. The link needs public authorization
dumpFreq - is used to dump additional stats into the logs on a regular basis

### Note
Before this process can work - the developer app email needs to be added as a view contributor for this specific
directory. The developer app emai name is available under General Settings as the Service Account ID.

## running download
From ~/ingest_home/queue/boxContent/boxrun

Issue
./runbox.sh vaccine_screenshots

This looks for /apps/dpr2/ingest_home/queue/boxContent/vaccine_screenshots to begin processing.

## logs
Example
~~~
Fri Apr 28 15:45:16 PDT 2023    (08) [box] ok|IA-20210507-010634.png|306359|sha1|cd3ed3b4658e4583288644257c957d7f69780e47|1050
----------------------------               -- ---------------------- ------ ---- ---------------------------------------- ----
|                                          |     |                     |     |           |                                  |
Date                                    Status   Name                Length Dtyp       Digest                          processMs
~~~
