### ISSUE TITLE
Java Dependabot upgrade cycle

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#1413]
## Goal
On a regular scheduled basis update core2/reflect/pom.xml (the BOM) to include all new dependabot alerts.

### Github dependabot alerts
- identify the problem version
- for each suggested version
  - confirm with [global maven repository](https://mvnrepository.com/) that alerts exist 
  - confirm that the suggested version in dependabot does not have already existing vulnerabilities
  - determine at what point recommended jar became available - for some jars earlier than a given date hold on update
  - update core2/reflect/pom.xml with a recommended version
  
 ### Jenkins
- use mrt-core-int-test-all to confirm IT validation for Merritt java services - ? names of created war branches

#### Handling semantic version
- what is semantic token value
  - only change is core2/reflect/pom.xml
  - source code of microservice jars do not change 
- is uc3-data/fqsn/uc3-mrt* modified for the  service_release: yaml semantic tag or is the token added through bin/cap_deploy.sh for each service?
- do all services keep the same semantic tag on reflect release

#### Update service
- puppet update or global 
-

**Comment by elopatin-uc3** [comment]
@dloy Please note that I have scheduled a regular dependency review meeting on Thursdays, every three weeks, starting 4/6.
