### ISSUE TITLE
Librato review - ask Ashley to evaluate Access instance types before/after Dec 8 (zip change)

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1422]
Nothing conclusive from discussion with IAS on 3/21.  It would be interesting to look at the CPU IO Wait with Ashley. Compare before Dec 8 and after Dec 8.

**Comment by ashleygould** [comment]
I took these sar captures just for one day. I still need to do longer trend analysis.

sar command used:
```
sar -d -p| egrep "DEV|nvme3n1"
```

Hosts in uc3-mrt-access-prd suffer from spikes of iowait.  I've determined this IO is with the scratch volume in all three cases. the scratch volume is mounted on local disk (i3en instance - Non-Volatile Memory Express (NVMe) SSD instance storage).

There are two workload types: large and basic.

```
Basic:
uc3-mrtaccess01x2-prd   i3en.large      1.1 TB Non-Volatile Memory Express (NVMe) SSD
uc3-mrtaccess03x2-prd

Large:
uc3-mrtaccess02x2-prd   i3en.xlarge     2.1 TB Non-Volatile Memory Express (NVMe) SSD
```


While the basic nodes see disk iowait spikes, average %utilization is low:

```
12:00:01 AM       DEV       tps  rd_sec/s  wr_sec/s  avgrq-sz  avgqu-sz     await     svctm     %util
Average:      nvme3n1     49.06   4558.26   7896.93    253.89      0.97     20.23      0.42      2.05
Average:      nvme3n1    142.66  11302.97  15506.65    187.93      2.00     14.32      0.30      4.30
```


The large node experiences long periods of high IOwait. not just spikes, and %utilization is much
higher on average, sometimes becoming fully saturated:

```
12:00:01 AM       DEV       tps  rd_sec/s  wr_sec/s  avgrq-sz  avgqu-sz     await     svctm     %util
Average:      nvme3n1   1653.78 283058.91 139557.07    255.55      7.94      4.95      0.14     22.50

Full io saturation spikes:
12:00:01 AM       DEV       tps  rd_sec/s  wr_sec/s  avgrq-sz  avgqu-sz     await     svctm     %util
12:30:01 AM   nvme3n1   2422.64  55168.64 564018.89    255.58     34.00     14.37      0.34     81.81
12:40:01 AM   nvme3n1   4578.99 579265.93 590413.03    255.44     56.06     12.43      0.22     99.80
12:50:01 AM   nvme3n1   5245.06 911870.38 428453.08    255.54     23.82      4.67      0.16     81.84
---
11:40:01 AM   nvme3n1   1553.43  27316.99 369675.96    255.56     14.15      9.35      0.25     38.94
11:50:01 AM   nvme3n1   4286.09 484301.06 610856.36    255.51     39.88      9.48      0.22     92.60
12:00:01 PM   nvme3n1   5797.95 847782.82 633001.29    255.40     56.89      9.94      0.17     99.99
12:10:01 PM   nvme3n1   3755.80 693275.30 266381.07    255.51     23.24      6.32      0.13     47.33
---
02:10:01 PM   nvme3n1   1998.56 198063.06 310996.86    254.71      7.29      3.83      0.16     32.04
02:20:01 PM   nvme3n1   3044.76 160670.58 617574.30    255.60     44.30     14.85      0.31     94.56
02:30:01 PM   nvme3n1   4494.82 784749.47 364502.29    255.68     21.95      5.01      0.17     74.66
02:40:01 PM   nvme3n1   5965.21 995848.72 529145.58    255.65     42.52      7.24      0.16     97.93
02:50:01 PM   nvme3n1   4196.31 802204.48 270928.74    255.73     23.31      5.67      0.15     61.22
```

For the large workload instance, we should explore other instance types.  Here are excepts from AWS docs for [Storage Optimized Instances](https://aws.amazon.com/ec2/instance-types/?trk=36c6da98-7b20-48fa-8225-4784bced9843&sc_channel=ps&ef_id=Cj0KCQjw27mhBhC9ARIsAIFsETE-FYvxxlM-zt9fegUg7bDLDNsfUCl5rUEAW7_UD6AGzpZ-PnoiCiEaAiWmEALw_wcB:G:s&s_kwcid=AL!4422!3!536392622533!e!!g!!ec2%20instance%20types!11198711716!118263957108)

Amazon EC2 Im4gn instances are powered by AWS Graviton2 processors and provide the best price performance for storage-intensive workloads in Amazon EC2. They provide up to 40% better price performance, up to 44% lower cost per TB of storage over I3 instances.

Features:

    Powered by AWS Graviton2 processors that enable the best price performance for workloads in Amazon EC2
    Featuring up to 30 TB of NVMe SSD instance storage with AWS Nitro SSDs that provide up to 60% lower I/O latency and up to 75% reduced latency variability compared to I3 and I3en instances and feature always-on encryption
    Optimized for workloads that map to 4 GB of memory per vCPU
    2x NVMe SSD storage density per vCPU compared to I3 instances

```

Instance Size   vCPU    Memory (GiB)    Instance Storage (GB)   Network Bandwidth (Gbps)***     EBS Bandwidth (Gbps)
Im4gn.large     2       8       1 x 937 AWS Nitro SSD   Up to 25        Up to 9.5
Im4gn.xlarge    4       16      1 x 1875 AWS Nitro SSD  Up to 25        Up to 9.5
```

**Comment by ashleygould** [comment]
in slack with IAS we know that to migrate instance type to Im4gn requires a full rebuild.  Graviton processors require a different kernel and binary rpms.

**Comment by terrywbrady** [comment]
From Martin: mentioned the other day that you needed faster local storage for some Merritt hosts. Looks like maybe the newer "i4i" instance types might be up your alley: https://aws.amazon.com/about-aws/whats-new/2022/04/amazon-ec2-i4i-instances/

**Comment by elopatin-uc3** [comment]
Closing. We'll determine next steps after the Dryad transition.
