### ISSUE TITLE
Test RLB with exotic UTF-8 characters with necessary fix RLB

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#143]
Test that this comes back out okay
 - [ ]

**Comment by elopatin-uc3** [comment]
do a database access to see if there is UTF8 and an access test
query on metadata with UTF8
@scottfisher1 had submitted some emojis (Marisa Strong - Jun 10, 2019)

**Comment by elopatin-uc3** [comment]
we now have test data and found that this is an issue.
 (Marisa Strong - Sep 16, 2019)

**Comment by elopatin-uc3** [comment]
The RLB failed  on filepath names containing UTF-8.  

The MySQL search for these names:

SELECT f.id,f.inv_object_id,v.ark,v.NUMBER,f.pathname
  FROM inv_files AS f,
  inv_versions AS v
 WHERE f.billable_size > 0
 AND f.inv_version_id=v.id
 AND f.pathname <> CONVERT(f.pathname USING ASCII)

A generic RLB is now being tested that preserves the original unencoded part of the URL.

The complete form of the non-log conf is only:
Listen *:35222
<VirtualHost *:35222>
   RewriteEngine on
   AllowEncodedSlashes NoDecode
   RewriteMap  lb       "rnd:conf/conf.d/rndmap.map"
   RewriteCond %{THE_REQUEST} " /(.+) HTTP"  [NC]
   RewriteRule "^/(.*)" "http://${lb:servers}/%1"     [N,NE,L,R=307]
</VirtualHost> 

The encoded part of the URL is extracted from an Apache variable THE_REQUEST which contains the original form of the extracted URL: e.g.
GET /state/... HTTP

The RewriteCond extracts this content and saves it in a %1 variable used by RewriteRule
   
 (David Loy - Sep 17, 2019)

**Comment by elopatin-uc3** [comment]
This unencode RLB is now running on stage. (David Loy - Sep 18, 2019)

**Comment by elopatin-uc3** [comment]
Additional tests have shown that the old RLB fails on: #&?%{}

Other tests show that the old RLB can handle:
,@>+":
AT least through curl

Avoiding Apache decoding is critical to retrieving file keys containing the problem characters (David Loy - Sep 20, 2019)

**Comment by dloy** [comment]
/dpr2/apps/apache/conf/storeredir.conf
stage added to puppet: 20191009
prod added to puppet: 20191009
