### ISSUE TITLE
Consider a different day for the meetings (or before 3pm)

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1430]
Current time is in conflict with David's commute.  

IAS is open to a change of time: Not Wed, Not Thurs AM

Possible: Mon 1p or Thu 2p

**Comment by terrywbrady** [comment]
@marisastrong and @elopatin-uc3 , could you pick a new time for the meeting?

**Comment by elopatin-uc3** [comment]
@marisastrong It looks like we're all normally free at 1pm on Mondays. My vote would be for that time slot. What do you think?

**Comment by marisastrong** [comment]
changed to 1pm on Tuesdays.  So far this seems to work for most!
