### ISSUE TITLE
[INGEST] Queue redesign (Part 1) - HP Consumer daemon no requeuing

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#1439]
1) HighPriorityConsumer daemon uses a requeue process when it consumes a non-HP entry.
        - Test granular consuming to eliminate requeue
        - Need to add HP boolean during Ingest queue creation

**Comment by elopatin-uc3** [comment]
ZK supports ACLs. Mark has a working solution now, but is exploring use of ACLs which may be a preferred approach.

**Comment by mreyescdl** [comment]
Altered Zookeeper ID to hold high priority status
e.g. mrtQ-490000392416

The first 2 numeric digits represent the Job priority
The 3rd numeric represents the high priority status (1 = high priority)

This allows Zookeeper library to quickly determine HP status without having to process the payload data

**Comment by mreyescdl** [comment]
Deployed to stage workers as a branch (priorityDaemonQueueFix)
Integration tests pass

**Comment by mreyescdl** [comment]
Production release complete - tag 1.0.5
