### ISSUE TITLE
Box: Document process to create developer credentials for box download

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1451]
Documentation should go into the Troubleshooting Guide
- https://github.com/CDLUC3/mrt-doc-private/tree/main/docs/system-recovery
- Document so that anyone of the Merritt team could repeat the process

Questions
- can the existing approved app be shared by the team or can it only be administered by David
- does the application need to be recreated or renewed on a regular basis?

**Comment by dloy** [comment]
See:
https://github.com/CDLUC3/mrt-doc-private/blob/main/docs/system-recovery/box-share-dev-app.md
