### ISSUE TITLE
Box: Document process for configuring download files for a specific project

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1456]
- Where should the files be created
- Any notes about token expiration
- Any notes about SSM variables and when they need to be refreshed
- Any notes about how to run/monitor/rerun a download
- Cleanup instructions

**Comment by dloy** [comment]
See https://github.com/CDLUC3/mrt-cloud/blob/main/box-src/README.md

**Comment by terrywbrady** [comment]
I would like this documentation to go into our documentation repository.  When we meet, we can discuss where to place this information.
