### ISSUE TITLE
UCM ANR Nuxeo collection is not receiving updates

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1459]
The UC Merced Library UCCE ANR collection currently has 201 objects, with the most recent object dating to 2022-08-16. 
UCM has notified us that there are 236 objects in Nuxeo, the latest dating to 2023-04-12, so it appears the harvest for this feed has not occurred in a while. 

- [x] Determine cause for missed harvests between 8/22 and 4/23

**Comment by mreyescdl** [comment]
@elopatin-uc3 

This feed as well as 2 others are not set for weekly processing.
Should I enable weekly processing?

```
# end of weekly processing

exit
# Do not harvest weekly
ATOM_ENV=production \
        /usr/bin/flock -n /dpr2/apps/atom/LockFile/production-27754-UCM-UCANR-UC-Cooperative-Extension-Records.lock \
        /bin/csh -f /dpr2/apps/atom/bin/production-27754-UCM-UCANR-UC-Cooperative-Extension-Records-ucm_lib_ucce_anr.csh > /dev/null 2>&1
ATOM_ENV=production \
        /usr/bin/flock -n /dpr2/apps/atom/LockFile/production-8534-UCSF-Library-A-Stanton-Glantz.lock \
        /bin/csh -f /dpr2/apps/atom/bin/production-8534-UCSF-Library-A-Stanton-Glantz-ucsf_lib_stantonglantz.csh > /dev/null 2>&1
ATOM_ENV=production \
        /usr/bin/flock -n /dpr2/apps/atom/LockFile/production-UCM_Ramicova.lock \
        /bin/csh -f /dpr2/apps/atom/bin/production-UCM_Ramicova.csh > /dev/null 2>&1
```

**Comment by elopatin-uc3** [comment]
@mreyescdl Thanks for noting these. I didn't realize the ANR collection wasn't set up for a weekly harvest. Please go ahead and enable it to run weekly. The other two, Ramicova and Glantz can remain as is (no weekly harvesting).

**Comment by mreyescdl** [comment]
Now set up for weekly processing.
I'm running it manually today as well so that the backlog will clear
