### ISSUE TITLE
Add Eric to notification email for Large Object Download

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#146]
When a user requests to download an object larger than 4GB, it is handled asynchronously.  The user enters their email address and is sent an email when the compressed tar file is ready for download .  Marisa, Mark, Jim and Perry are all cc'ed on this email.  This email is generated from the storage service and sent from the storage servers.

Please remove Perry and add Eric L to these emails.

Obtains data from UI/frontend re: notification email.
 - [ ] Remove Perry from notification list
 - [ ] Add Eric Lopatin to notification list

**Comment by elopatin-uc3** [comment]
here is an example email (Marisa Strong - Jun 25, 2019)

**Comment by marisastrong** [comment]
We should remove Perry and DMoles from the Exception handling list along with this change.

https://github.com/CDLUC3/mrt-dashboard/blob/76ec78217e48cf530e8f4ae77304d9afe784b633/config/environments/production.rb

**Comment by elopatin-uc3** [comment]
This has been done. Closing
