### ISSUE TITLE
Consider migration from org.jdom.jdom to org.jdom.jdom2

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1462]
<img width="1266" alt="image" src="https://github.com/CDLUC3/mrt-doc/assets/1111057/aa978bcb-bf4a-4a3a-8313-998bc1366818">

- https://mvnrepository.com/artifact/org.jdom/jdom2
- http://www.jdom.org/

**Comment by terrywbrady** [comment]
@dloy and @elopatin-uc3 , I found this ticket on the board.  Is this ticket still open or did this get covered already?

**Comment by elopatin-uc3** [comment]
Removing jdom references was part of BOM 1.5 #1668, because jdom2 jars were found to have vulnerabilities, #1605.
