### ISSUE TITLE
UCSF Nuxeo feed: CTP Oral Histories

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1464]
Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/28036/

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_28036.atom

Root folder in Nuxeo:
asset-library/UCSF/MSS 2022-74 COVID Tracking Project records/

Merritt collection: NEW:
The COVID Tracking Project Records
ark:/13030/m5c03tq8

**Comment by elopatin-uc3** [comment]
When the feed becomes available, we should set this up to harvest once, but not weekly. In July new updates should be available, so one other run will be needed.

**Comment by mreyescdl** [comment]
@elopatin-uc3 Nuxeo script created.
Is it okay to run and submit 68 objects from feed to collection "The COVID Tracking Project Records"

**Comment by elopatin-uc3** [comment]
@mreyescdl Yes, please go ahead and run the script. Thanks for checking in first.

**Comment by mreyescdl** [comment]
Submission complete.
Not scheduled for weekly processing.

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl !
