### ISSUE TITLE
[Fixity Report] Add Eric to the notification email list

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#147]
Fixity: periodic report: ERROR(S) detected - this report currently gets sent to Marisa, Perry, and David.  Should be updated to include Eric

Audit Periodic Report
 - [x] add Eric.lopatin@ucop.edu to notification list
 - [x] remove Perry.Willett@ucop.edu from notification list
 - [ ] ~~Can we rename this report so it reflects that it's an audit report?  and not report.html which is the same name as other reports that are run?~~ Moved to #350

**Comment by marisastrong** [comment]
audit-info.txt is where this configuration is set and lives on each one of the audit servers /dpr2/mrtHomes/audit

**Comment by elopatin-uc3** [comment]
@dloy I can see the changes you've made to `audit-info.txt` on `uc3-mrtaudit1-prd.cdlib.org`, and have received two reports thus far. Can we call this ticket done? If so, I'll pull it into the sprint and move it over to the Deployed/Done column. Thanks!

**Comment by marisastrong** [comment]
do we have documentation on this file?  does it only live on mrtaudit1-prd?  Since it doesn't live under source control just want to ensure we understand how it's maintained and that it gets migrated over with other files to Linux2 ( we don't overwrite it some earlier version).  thanks!
________________________________

**Comment by elopatin-uc3** [comment]
Not sure about documentation. However there are copies on audit02, 03, and 04. These only include David's email for notifications.

**Comment by elopatin-uc3** [comment]
@dloy Can you comment on configuration of the report? Thanks!

**Comment by elopatin-uc3** [comment]
Moved task to change attachment name to a new ticket: #350
