### ISSUE TITLE
Storage state check - add timeout to node state check and report error

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1470]

**Comment by dloy** [comment]
The easiest process for doing this is to have a storage specific nodes table that removes secondary content:
contain only (for prod):
5001 - standard AWS
9501 - SDSC minio
7001 - temp content bucket
4001 - oneshare
3041 - Dryad

A failure on any of these nodes could seriously impact store

Change would require:
- add new nodes table as nodes-prod-store
- modify setenv.sh to point to the new environment variable 

Problem with change is that state not made for all nodes by staorage.
Advantage - failure of a secondary node will not cause Nagios errors

**Comment by terrywbrady** [comment]
@dloy , for a routine state check, would it be possible to implement a forced timeout on the request?  If any one node takes longer than 5-10 seconds to respond, return an error.  We could then set the Nagios thresholds to escalate if a problem persists?

**Comment by elopatin-uc3** [comment]
David plans to piggyback this on his current log4j-2 work for Storage.

**Comment by dloy** [comment]
Have a new jsonstatus (as opposed jsonstate) that issues a list command for 2 keys from bucket. If bucket fails returns around 1 second.

Timing comparison:
Node jsonstate jsonstatus
6001 216  105
3042 184   75
2002 733  104
3043 179   61
4101 567  245
5001 175   64
7001 193   82
3642 969  316
9502 531  258
