### ISSUE TITLE
Merritt Migration to Open Search

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1476]
# Prioritized List of Merritt Log Sources

## Already Migrated
- Merritt UI WAF (Kinesis)

## Available Logs
- HighPriority
  - ALB Logs (S3)
    - UI
    - Ingest
    - Storage
    - Inventory
    - Access
- Medium Priority
  - Lambda Logs (Cloud Watch)
    - Admin Tool
    - Collection Admin Tool 
- Low Priority (how valuable would these be?)
  - Tomcat Catalina logs (file system)
  - Tomcat Access logs (file system) - mostly redundant if ALB logs can be ingested

## Work Needed to Prepare Logs for Ingest
  - High Priority
    - Rails Application Log (formatted as json)
    - Java Microservices Application Logs (formatted as json)

## Other items to consider in the future
- Journal logs
- Puppet logs (done)
- RDS logs
- LDAP logs
- ZK logs (low value based on experience)

**Comment by elopatin-uc3** [comment]
Closing; will focus on adding logs at a more granular level; piece and microservice basis
