### ISSUE TITLE
Support fast HEAD request to minimize large file download delay

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#148]
From Scott...

Hey Merritt folks, it seems the reason for the slow start to streaming some files from Merritt Express is our head request taking a long time to complete. (edited) 

I'll look and see if there is a better way to stream, but we're doing a HEAD first in order to appropriately set some headers and also set content-disposition and some other stuff.
These are large 4.5 GB files directly from ME.
So curious how much the head requests needs to be a long request only for returning headers and content-type, content-length and other stuff. (edited) 
`curl --user dash_demo_user:<set-pwd-here> --head http://mrtexpress-stage.cdlib.org/dv/1/ark:/99999/fk48k8jp86/Asha_G.tar.gz`
It does eventually return, just more than a minute.
I think we stole our streaming code from Merritt UI, though slightly modified.  Maybe I can find some other way.
 - [ ]

**Comment by elopatin-uc3** [comment]
We've added a workaround to our code to not rely on this HEAD request since it results in file downloads timing out for some large files.

We are relying on cached info in our database for filenames, size, etc.  It should be right, but I'd rather rely on Merritt for the most up-to-date info, since I think Merritt should be the canonical copy of the file technical metadata rather than our cached copy of metadata from our database.

Let us know when you work on this and it is fixed and we'll revert our workaround code.

I don't think it's critical for our release, but would be nice to do before too long. (Scott Fisher - Sep 3, 2019)

**Comment by elopatin-uc3** [comment]
@mreyescdl Is it correct to assume this ticket has been addressed by the optimization that was deployed last week (Express + Inventory – https://github.com/CDLUC3/mrt-doc/issues/171)?

cc @sfisher

**Comment by dloy** [comment]
Completed with inventory change for file specific versions file.

Now handled as part of UI lookup for active key for presign generation.
