### ISSUE TITLE
Meet with eScholarship to understand the Merritt workflows

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1483]
Why are there so many submissions in one day?  Is there any churn in the systems?

```
MySQL [inv]> select profile, count(*) from inv_ingests where submitted > '2023-06-05' and submitted < '2023-06-06' group by profile order by count(*);
+----------------------------+----------+
| profile                    | count(*) |
+----------------------------+----------+
| cdl_uc3_etdreports_content |        1 |
| ucm_lib_ucce_anr_content   |        1 |
| ucsf_lib_etd_content       |       63 |
| cdl_dryad_content          |      129 |
| ucla_pal_museum_content    |     2756 |
| escholarship_content       |    16639 |
+----------------------------+----------+
```

Do we need to give eSchol more priority to prevent churn?  What considerations do we need to make when there items start to queue up?

@elopatin-uc3 , I think this discussion makes sense to have once you are back.

**Comment by elopatin-uc3** [comment]
@terrywbrady Meeting scheduled for 6/29 at 4pm.

**Comment by elopatin-uc3** [comment]
Documentation sent to eSchol regarding callback and endpoints. Primary challenge is the number and frequency of changes made upstream for eSchol publications in Element. Need to determine how consolidate or batch these in order to reduce deposit and versioning frequency in Merritt.
