### ISSUE TITLE
Storage - evaluate, upgrade to log4j2, parent-properties

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#1484]
### log4j2
- Update Storage to use log4j2 instead of the original TFileLogger
- Experiment with approaches for using log4j2 to mix both debug message based logging with json logging for use by logstash/opensearch
- Evaluate JSONLayout, EcsLayout ...

### parent-properties pom
- Use initial parent-properties to evaluate mechanism for globally setting maven plugin versions

**Comment by elopatin-uc3** [comment]
David will be opening a new issue for the log4j2 portion of this ticket (plus added logging for OpenSearch)
