### ISSUE TITLE
[Admin Interface] Consolidated Ingest queue support

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#1487]
All Ingest workers will soon use only a single ZK queue to queue their submissions.

Was: 
   /ingest.ingest01.1
   /ingest.ingest02.1
   /ingest.ingest03.1
Now:
   /ingest

API call for queues list has not changed, but it will now only report the single queue.  No need to iterate across entries.
  - http://localhost:33121/admin/queues

However, let's change the Admin jobs listing page a bit.  The first column now shows "Queue Node" which is now static (see below)
Let's change that to "Ingest Worker" and derive the worker ID from 9th column of "<que:id>"

```
<que:iD>mrtQ-03120000000063</que:iD>
```

![Screen Shot 2023-06-15 at 2 53 56 PM](https://github.com/CDLUC3/mrt-doc/assets/8884928/2d6efbf0-d597-482e-958a-5b729b5a3dbf)

**Comment by terrywbrady** [comment]
https://github.com/CDLUC3/mrt-admin-lambda/commit/fc9ec71fc4139f685cbe84d0c79c99d3e1ff0694
