### ISSUE TITLE
New Nuxeo deposit: UCI Community photographs

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1496]
Source ticket: https://help.oac.cdlib.org/a/tickets/122904

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/28045

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_28045.atom
(confirmed this feed is available as of 7/10/23)

Root folder in Nuxeo:
asset-library/UCI/SCA_UniversityArchives/AS-111

Merritt collection: EXISTING:
UC Irvine SCA University Archives
ark:/13030/m5bk6qsm

**Comment by mreyescdl** [comment]
Nuxeo script created and run once for testing.... 1 record submitted.

Weekly scheduled.   
Ticket complete

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl ! I will inform the depositor at UCI.
