### ISSUE TITLE
New Nuxeo deposit: UCR Eaton Fanzine Collection

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1497]
Source ticket: https://help.oac.cdlib.org/a/tickets/122672

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/27080

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27080.atom

Root folder in Nuxeo:
/asset-library/UCR/Special Collections & University Archives/Bibliographic/Eaton fanzine collection

Merritt collection: NEW:
UC Riverside Library Eaton Fanzine Collection (#1498)
ARK: **ark:/13030/m53011m5**

**Comment by elopatin-uc3** [comment]
@mreyescdl the new Eaton Fanzine Collection has been set up. ARK: ark:/13030/m53011m5

I've asked Gabriela to update the collection registry entry, so a new Nuxeo feed should become available next Tuesday, 7/25.

**Comment by mreyescdl** [comment]
Created script and prepped for scheduling.
Waiting for feed update.  From Barbara...
```
It might not be ready until later this week, even Sunday.
```

**Comment by mreyescdl** [comment]
Feed has been updated to reflect new collection.
Starting a manual run which should submit 1194 objects.

**Comment by mreyescdl** [comment]
Correction: 1193 objects in feed.  Ran once and no problems.
Scheduled for weekly harvest.

Ticket complete
