### ISSUE TITLE
Admin: clear audit batches - flexible timeframe for clearing

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1507]

**Comment by terrywbrady** [comment]
https://github.com/CDLUC3/mrt-admin-lambda/commit/43697a78ebdc0f96a99227be09012dc055720fbc



![Image](https://github.com/CDLUC3/mrt-doc/assets/1111057/87b7dfd1-938e-4214-8df5-aebaa06a0762)
