### ISSUE TITLE
Delete ingest queue entries currently 404's in Coll Admin

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1532]
![Screenshot 2023-07-17 at 10 28 02 AM](https://github.com/CDLUC3/mrt-doc/assets/49419424/fed98af8-fb4e-4863-a141-0d377e52f6ee)

**Comment by terrywbrady** [comment]
This should fix it https://github.com/CDLUC3/mrt-admin-lambda/commit/1f3b15199a4566154f885863b20edd03ba45a287
