### ISSUE TITLE
Coll admin: 500 error when attempting to delete an Access queue entry

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1546]
A 500 occurs when attempting to delete an entry from the access queue:
https://merritt-colladmin.cdlib.org/web/collIndex.html?path=acc-queues

![Image](https://user-images.githubusercontent.com/49419424/257609227-7370144b-4c9f-4758-b4b5-0e16b46d52da.png)

**Comment by terrywbrady** [comment]
@elopatin-uc3 , this should now be fixed.  https://github.com/CDLUC3/mrt-admin-lambda/commit/1096050220037c7a89557f0f4c7e37d6b5a0afa6 

Please keep an eye out around the access requeue button.  Let me know if you see any issues with that button.

**Comment by elopatin-uc3** [comment]
Thanks @terrywbrady , will do. Regarding the delete fix, I'll test when a failure occurs in the future.
