### ISSUE TITLE
JP2 and DPX files are grouped into the octet-stream mime type but should be individually recognized

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1552]
When looking through the Collection Health prototype files export using OpenSearch, we discovered that many file types are grouped into a larger "octet-stream" bucket by Tika. JP2 (JPEG2000) and DPX files are two of these mime types. Investigate why this is happening and whether it would be beneficial to update Tika.

**Comment by elopatin-uc3** [comment]
"application/octet-stream" is used by Tika when it cannot find a more specific mime type to associate a file with.

As of today, in the "Merritt Files Dashboard" the DPX format is being correctly identified in the UCCE ANR collection as "image/x-dpx". I have not yet been able to find JP2 examples to check.

On a related note, this tool provided by digipres.org looks to be an excellent aggregator of format recognition tools:
https://www.digipres.org/formats/

**Comment by dloy** [comment]
## Test with no mime_type
First thing to note is that with the current tika an empty mime type is correctly resolved:
~~~
#%checkm_0.7
#%profile | http://uc3.cdlib.org/registry/store/manifest/mrt-add-manifest
#%prefix | nfo:<http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
#%prefix | nie:<http://www.semanticdesktop.org/ontologies/2007/01/19/nie/#>
#%prefix | mrt:<http://uc3.cdlib.org/ontology/mrt/mom#>
#%columns | nfo:fileURL | nfo:hashAlgorithm | nfo:hashValue | nfo:fileSize | nfo:fileLastModified | nfo:fileName | nie:mimeType
http://storage.cdlib.org:35121/content/9501/ark%3A%2F13030%2Fm5423w3j/1/producer%2FUCCE_UCANR_AV_0005_00037435.dpx?fixity=no | sha256 | 6eb657e899ee45a47f6129a6e6306f4750d21d0ee712399d7cd8f47a0cd10546 | 12750848 | 2017-10-03T15:29:19-07:00 | producer/UCCE_UCANR_AV_0005_00037435.dpx
http://storage.cdlib.org:35121/content/9501/ark%3A%2F28722%2Fbk0009r625b/1/producer%2FFID2.jp2?fixity=no | sha256 | dc2cfb0f01cbb600b8f87a81f773e90a5f940d45d78324177f316e96f0484acf | 1106827 | 2017-10-03T15:29:19-07:00 | producer/FID2.jp2
#%eof
~~~

RESULT
dpx -> image/x-dpx
jp2 -> image/x-dpx

~~~
<?xml version="1.0" encoding="UTF-8"?>
<fil:fileState xmlns:fil='http://uc3.cdlib.org/ontology/mrt/store/file'>
    <fil:identifier>producer/UCCE_UCANR_AV_0005_00037435.dpx</fil:identifier>
    <fil:messageDigest>sha256=6eb657e899ee45a47f6129a6e6306f4750d21d0ee712399d7cd8f47a0cd10546</fil:messageDigest>
    <fil:localID>ark:/13030/testmime5001|1|producer/UCCE_UCANR_AV_0005_00037435.dpx</fil:localID>
    <fil:created>2017-10-03T15:29:19-07:00</fil:created>
    <fil:size>12750848</fil:size>
    <fil:mimeType>image/x-dpx</fil:mimeType>
    <fil:versionState>http://store-stage.cdlib.org:35121/state/5001/ark%3A%2F13030%2Ftestmime5001/1</fil:versionState>
    <fil:file>http://store-stage.cdlib.org:35121/content/5001/ark%3A%2F13030%2Ftestmime5001/1/producer%2FUCCE_UCANR_AV_0005_00037435.dpx</fil:file>
</fil:fileState>

<?xml version="1.0" encoding="UTF-8"?>
<fil:fileState xmlns:fil='http://uc3.cdlib.org/ontology/mrt/store/file'>
    <fil:identifier>producer/FID2.jp2</fil:identifier>
    <fil:messageDigest>sha256=dc2cfb0f01cbb600b8f87a81f773e90a5f940d45d78324177f316e96f0484acf</fil:messageDigest>
    <fil:localID>ark:/13030/testmime5001|1|producer/FID2.jp2</fil:localID>
    <fil:created>2017-10-03T15:29:19-07:00</fil:created>
    <fil:size>1106827</fil:size>
    <fil:mimeType>image/jp2</fil:mimeType>
    <fil:versionState>http://store-stage.cdlib.org:35121/state/5001/ark%3A%2F13030%2Ftestmime5001/1</fil:versionState>
    <fil:file>http://store-stage.cdlib.org:35121/content/5001/ark%3A%2F13030%2Ftestmime5001/1/producer%2FFID2.jp2</fil:file>
</fil:fileState>
~~~

## Why application/octet-stream
For dpx:
- tika support dpx: Release 1.18 - 4/20/2018
- latest dpx with application/octet: 2022-02-09 18:54:30
- move from org.apache.logging.log4j:log4j-core:1.17 to 2:17:1 was BOM: Dec 6, 2022

For jp2:
- tika support jp2: Release 1.15 - 05/23/2017
- latest jp2 with application/octet-stream: 2017-04-17 14:14:41
- the earlier move history is unknown - several mime changes occurred before.

It appears that dpx was definitely an upgrade by BOM. The jp2 is not so clear but octet disappeared earlier in 2017.

## Conclusion
application/octet exist  for several files. If necessary the db can be upgrade by adding a dummy version WITH changes in mrt_inventory to reset mime-type based on last version.
