### ISSUE TITLE
End-to-end test failure: Unauthenticated Access Verify that a permalink is traversable

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1555]
This recently added test failed after patching on 8/8:
```
  1) basic_merrit_ui_tests Unauthenticated Access Verify that a permalink is traversable for an object
     Failure/Error: expect(@session.text).to have_content("ABOUT THE IDENTIFIER")
       expected to find text "ABOUT THE IDENTIFIER" in "My collections\nCollection home\nDownloads: None\nLogged in as Guest\nObject: ark:...
```

![image](https://github.com/CDLUC3/mrt-doc/assets/1111057/5a66c670-9180-4e4a-8e25-90aca100a8df)

![image](https://github.com/CDLUC3/mrt-doc/assets/1111057/20b26602-f6d9-4825-ac95-daa63ad06e34)

**Comment by mreyescdl** [comment]
Changing the targeted URL from domain name "merritt-aws.cdlib.org" to "merritt.cdlib.org" results in the correct page being displayed.

Somewhere in the chain "merritt-aws.cdlib.org" is not being honored.
From the entry point...
- The Certificate is showing it as an Alternate Subject, so that seems to be okay.
- Need to look at ALB
- Need to look at UI

**Comment by mreyescdl** [comment]
Previous message about merritt-aws vs. merritt were wrong.  Both provide the same behavior (I had a cookie that auto logged me into "merritt.cdlib.org"

"merritt_demo" is a private collection.  Are we passing credentials in the request to retrieve the permalink?

**Comment by terrywbrady** [comment]
We do not pass credentials, but the session at merritt.cdlib.org should still be active.  Since the domain switches to merritt-aws.cdlib.org, I think that is the source of the confusion.

**Comment by mreyescdl** [comment]
"merritt-aws.cdlib.org" is an A record
"merritt.cdlib.org" is a CNAME targeting above

Switching DNS entries will not fix Permalink issue, but should be done.  "merritt.cdlib.org" SHOULD be the A record and all other entries should reference it.

Let's discuss with IAS how this switch can be done and what impact it may have on availability

**Comment by mreyescdl** [comment]
@jsjiang mentioned that the changing of the domain name could possibly be done as a batch update on the server-side.
She will investigate.  Thanks!

**Comment by mreyescdl** [comment]
Probably a good idea to stop using merritt-aws.cdlib.org as a Target for all current and future submission.

@elopatin-uc3 Is it okay to start using "merritt.cdlib.org" ?

It is an SSM change.

```
/uc3/mrt/prd/ingest/config/target       http://merritt-aws.cdlib.org
```

**Comment by elopatin-uc3** [comment]
That makes sense to me @mreyescdl .

**Comment by mreyescdl** [comment]
SSM parameter has been changed.

**Comment by mreyescdl** [comment]
Submitted IAS request to alter merritt.cdlib.org from a CNAME to an Alias

**Comment by elopatin-uc3** [comment]
@mreyescdl @terrywbrady 
I'm now seeing what I think is expected behavior for the object permalinks in both private and public collection:

- Private: user is sent to an EZID page titled, "The URL for this identifier cannot be resolved. Reason: Object in restricted Merritt collection" (it includes a table of ERC data as well)
- Public: user is redirected to the object page: 302 nt2.net and the a 301 to merritt.cdlib.org
