### ISSUE TITLE
[Ingest]: Validate manifest prior to content download

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1558]
In order to surface syntax errors in submitted manifests, validate manifest prior to downloading content. This will cause submissions with problematic manifests to fail sooner (for diagnosis), and avoid potential accumulation of content on the ZFS.

**Comment by mreyescdl** [comment]
Branch "validateManifest" with tag 1.0.11.dev02 addresses issue.
- Will fail fast for object manifests
- Will fail fast for Batch manifests

Running and tested in Docker and on Stage
Will merge branch to main and deploy to Stage.

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl
