### ISSUE TITLE
[RELEASE] Ingest - Held to Delete state for ZK queue - 2023-08-23

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#1561]
# Overview of Release
Add the ability to delete a HELD job 

# Service(s)
Ingest

# Github Issue Link(s)
https://github.com/CDLUC3/mrt-doc/issues/1085

# Servers affected
uc3-ingest01x2-prd
uc3-ingest02x2-prd
uc3-ingest03x2-prd

# Source Code:
https://github.com/CDLUC3/mrt-ingest/pull/85

# Source Code Tag
1.0.9

# Jenkins/Build Info: (if applicable)
http://builds.cdlib.org/view/New%20Build%20Config/job/Merritt_Build_Config/71/

# Deployment Steps (if applicable)
- [ ] Remove worker from rotation
- [ ] Deploy worker
- [ ] repeat

# Infrastructure Changes to support deployment (ALB, EFS, etc)
Remove worker from uc3-mrt-ingest-prd-alb2

# Rollback Instructions
Use Capistrano Rollback

**Comment by UDFR** [comment]
Deployment complete
Integration tests pass

**Comment by mreyescdl** [comment]
Above comment was from mreyes.
Logged into wrong account

**Comment by mreyescdl** [comment]
Deployed to production
Integration test pass
