### ISSUE TITLE
OpenSearch: determine the best way to link between dashboards (unless notebooks are the right thing to use instead)

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1565]

**Comment by terrywbrady** [comment]
Pushing out to a later sprint.  I hope to learn more about this at the opensearch conference.

**Comment by elopatin-uc3** [comment]
Keep this ticket and 1582 open until after the OpenSearch conference at the end of September.

**Comment by terrywbrady** [comment]
Closing.  Will need to wait for OpenSearch enhancement.

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1308
