### ISSUE TITLE
Automatically pause ingest at 90% ZFS capacity

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1568]
Pause at 90%, but do not subsequently unpause if space frees up. Manual intervention to unpause required.

Use existing distribution list in SSM.

**Comment by mreyescdl** [comment]
Created, tested and cron'd

Will run hourly
dpr2@uc3-mrtbatch01x2-prd:/dpr2/tools/zfs_monitor/monitor.csh
