### ISSUE TITLE
Create placeholder images for tomcat and maven to manage JDK and OS in one spot

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1571]
## Create standard maven base image `${ECR_REGISTRY}/merritt-maven`

```dockerfile
FROM public.ecr.aws/docker/library/maven:3-amazoncorretto-11

RUN yum -y update

RUN mkdir -p /build/static
```

### TODO
- Define the new image here: https://github.com/CDLUC3/merritt-docker/tree/main/mrt-inttest-services
- Build the new image in the daily build
- Update 5 Dockerfile FROM to use this approach
- Update 5 pom.xml files to references this new base image

## Create standard tomcat base image `${ECR_REGISTRY}/merritt-tomcat`

```dockerfile
FROM public.ecr.aws/docker/library/tomcat:9-jdk11-corretto

# RUN apt-get update -y && apt-get -y upgrade
RUN yum -y update

EXPOSE 8080 8009

ENV CATALINA_OPTS="-Dfile.encoding=UTF8 -Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true -XX:+UseG1GC"

# https://serverfault.com/questions/683605/docker-container-time-timezone-will-not-reflect-changes
ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
```

### TODO
- Update 1 Dockerfile FROM to use this approach
- Define the new image here: https://github.com/CDLUC3/merritt-docker/tree/main/mrt-inttest-services
- Build the new image in the daily build

**Comment by terrywbrady** [comment]
@elopatin-uc3 , this was done in the last sprint

**Comment by elopatin-uc3** [comment]
Thanks @terrywbrady
