### ISSUE TITLE
ECR Cleanup -- After JDK11 refactor

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1572]
- [x] remove dep-cdlmvn
- [ ] determine if simulate-lambda-alb is still needed

**Comment by elopatin-uc3** [comment]
Mark mentioned dep-cdlmvn is no longer available.

**Comment by terrywbrady** [comment]
I commented rather than deleted the simulate-alb-image.  @elopatin-uc3 Closing.

https://github.com/CDLUC3/merritt-docker/commit/6f61954d7f868d6d48256dfc950aa1e97a5e52ba
