### ISSUE TITLE
UCR Nuxeo feed: Trailfinders

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1575]
Source ticket: https://help.oac.cdlib.org/a/tickets/126063

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/22838

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_22838.atom

Root folder in Nuxeo:
asset-library/UCR/SCUA/Archival/MS353/

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

Object count:
75 

Approximate storage needed: 
549G

**Comment by mreyescdl** [comment]
Manually ran script which submitted 75 objects.
Scheduled for weekly harvesting
