### ISSUE TITLE
UCR Nuxeo feed: African Student Programs

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1576]
Source ticket: https://help.oac.cdlib.org/a/tickets/126063

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/27940

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27940.atom

Root folder in Nuxeo:
asset-library/UCR/SCUA/Archival/UA388/

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

Object count:
232 

Approximate storage needed: 
132G

**Comment by mreyescdl** [comment]
Created script: production-UCR_African_Student_Programs.csh

Feed not yet available.

**Comment by mreyescdl** [comment]
Manually submitted content.

Scheduled weekly processing.

Complete
