### ISSUE TITLE
UCR Nuxeo feed: Tomás Rivera archive

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1577]
Source ticket: https://help.oac.cdlib.org/a/tickets/126063

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/85

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_85.atom

Root folder in Nuxeo:
asset-library/UCR/SCUA/Archival/UA253/

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

Object count:
176

Approximate storage needed: 
244G

**Comment by mreyescdl** [comment]
Created script: production-UCR_Tomas_Rivera_archive.csh

@elopatin-uc3 Feed seems to be available.  Should I run?

**Comment by mreyescdl** [comment]
Manually ran script which submitted 176 objects

Scheduled for weekly harvest
