### ISSUE TITLE
UCR Nuxeo feed: Alfred M. North

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1586]
Source ticket: https://help.oac.cdlib.org/a/tickets/126063

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/27470

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27470.atom

Root folder in Nuxeo:
asset-library/UCR/SCUA/Archival/MS085/

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

Object count:
20

Approximate storage needed:
293G

**Comment by mreyescdl** [comment]
- Created script
- Manually submitted 20 objects
- Scheduled for weekly processing

Complete
