### ISSUE TITLE
UCR Nuxeo feed: Collection on race, ethnicity, and student activism

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1587]
Source ticket: https://help.oac.cdlib.org/a/tickets/126063

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/27967

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27967.atom

Root folder in Nuxeo:
asset-library/UCR/SCUA/Archival/UA133/

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

Object count:
98

Approximate storage needed:
54G

**Comment by mreyescdl** [comment]
- Created script
- Manually submitted 98 objects
- Scheduled for weekly processing

Complete
