### ISSUE TITLE
UCR Nuxeo feed: Charles McGee

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1588]
Source ticket: https://help.oac.cdlib.org/a/tickets/126063

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/27414

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27414.atom

Root folder in Nuxeo:
asset-library/UCR/SCUA/Archival/MS272

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

Object count:
16

Approximate storage needed:
5.6G

**Comment by mreyescdl** [comment]
- Created script
- Manually submitted 98 objects
- Scheduled for weekly processing

Complete

**Comment by mreyescdl** [comment]
- Created script
- Manually submitted 16 objects
- Scheduled for weekly processing

Complete
