### ISSUE TITLE
UCR Nuxeo feed: Avery E. Field

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1590]
Source ticket: https://help.oac.cdlib.org/a/tickets/126063

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/92

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_92.atom

Root folder in Nuxeo:
asset-library/UCR/SCUA/Archival/MS146

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

Object count:
4340

Approximate storage needed:
344G

**Comment by mreyescdl** [comment]
- Created script
- Ran manually, submitting 4340 objects
- Scheduled for weekly processing

Complete
