### ISSUE TITLE
UCR Nuxeo feed: Catherine Clark Papers

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1592]
Source ticket: https://help.oac.cdlib.org/a/tickets/126063

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/27403

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27403.atom

Root folder in Nuxeo:
/asset-library/UCR/SCUA/Archival/MS384

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

Object count:
37

Approximate storage needed:
18G

**Comment by mreyescdl** [comment]
- Script created and checked into git repo
- Added to weekly production script, but not enabled

Need to: Run manually (waiting for Avery E. Field) and enable scheduling

**Comment by mreyescdl** [comment]
- Ran Manually (37 objects) 
- Scheduled for weekly processing

Complete
