### ISSUE TITLE
UCR Nuxeo feed: David Bratman Collection on Hour 25

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1594]
Source ticket: https://help.oac.cdlib.org/a/tickets/126063

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/27941

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27941.atom

Root folder in Nuxeo:
/asset-library/UCR/SCUA/Archival/MS163/

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

Object count:
7

Approximate storage needed:
35G

**Comment by mreyescdl** [comment]
- Script created and checked into git repo
- Added to weekly production script, but not enabled

Need to: Run manually (waiting for Avery E. Field) and enable scheduling

**Comment by mreyescdl** [comment]
- Manually ran (7 objects)
- Scheduled for weekly processing

Compete

**Comment by elopatin-uc3** [comment]
Thanks for finishing all of these up @mreyescdl !
