### ISSUE TITLE
UCR Nuxeo feed: Edith Hipkins

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1596]
Source ticket: https://help.oac.cdlib.org/a/tickets/126063

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/10001

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_10001.atom

Root folder in Nuxeo:
/asset-library/UCR/SCUA/Archival/MS268

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

Object count:
51

Approximate storage needed:
7G

**Comment by mreyescdl** [comment]
- Script created and checked into git repo
- Added to weekly production script, but not enabled

Need to: Run manually (waiting for Avery E. Field) and enable scheduling

**Comment by mreyescdl** [comment]
- Ran manually (51 objects)
- Scheduled for weekly processing

Complete
