### ISSUE TITLE
Improve administration

### ISSUE THREAD

**Issue by dmolesUC** [CDLUC3/mrt-doc#16]
We want it to be easy for customers to monitor the progress of their ingest
jobs and/or be notified when problems occur, and we don't want Perry to
have to keep an eye on the ingest pipeline himself; we also want better
tools for tracing jobs through the workflow, and some sort of an
administrative dashboard.

## Questions/Action Items

- what are the limitations of our current ability to trace jobs through the
  workflow? do we need to attach more metadata, job IDs, etc. somehow?
- how can we improve notifications?
- how can we improve workflow visibility?
- what features do we want in a dashboard?

**Comment by dloy** [comment]
I see this as one of the more important features we need.

Some issues related to it include:
Having a status table could be very useful but must not become a failure point for processing
Currently Storage and Ingest do not have direct inv db access.

**Comment by dmolesUC3** [comment]
We have a lot of manual processes that are only semi-documented and could be better automated, e.g. [suspending ingest](https://confluence.ucop.edu/display/UC3/Suspending+Production+Ingest) and managing the [Nuxio Atom feeds](https://confluence.ucop.edu/display/UC3/Nuxeo+Atom+harvesting).

**Comment by terrywbrady** [comment]
Now a duplicate
