### ISSUE TITLE
UCR Nuxeo feed: Andrae B. Nordskog papers

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1600]
Source ticket: https://help.oac.cdlib.org/a/tickets/126063

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/26746

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_26746.atom

Root folder in Nuxeo:
asset-library/UCR/SCUA/Archival/WRCA058

Merritt collection: EXISTING:
**UC Riverside WRCA: Los Angeles Aqueduct**
**ark:/13030/m52b920p**

Object count:
9

Approximate storage needed:
11.4G

**Comment by mreyescdl** [comment]
- Created script
- Ran manually (9 objects)
- Scheduled for weekly processing

Complete
