### ISSUE TITLE
UCR Nuxeo feed: California Bureau of Sanitary Engineering papers

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1601]
Source ticket: https://help.oac.cdlib.org/a/tickets/126063

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/26747

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_26747.atom

Root folder in Nuxeo:
/asset-library/UCR/SCUA/Archival/WRCA095

Merritt collection: EXISTING:
**UC Riverside WRCA: Los Angeles Aqueduct**
**ark:/13030/m52b920p**

Object count:
2 

Approximate storage needed:
6.4G

**Comment by mreyescdl** [comment]
- Created script
- Manually ran (2 objects)
- Scheduled for weekly processing

Complete
