### ISSUE TITLE
UCR Nuxeo feed: Charles Gilman Hyde

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1602]
Source ticket: https://help.oac.cdlib.org/a/tickets/126063

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/26748

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_26748.atom

Root folder in Nuxeo:
asset-library/UCR/SCUA/Archival/WRCA046

Merritt collection: EXISTING:
**UC Riverside WRCA: Los Angeles Aqueduct**
**ark:/13030/m52b920p**

Object count:
1

Approximate storage needed:
1.8G

**Comment by mreyescdl** [comment]
- Created script
- Ran manually (1 object)
- Scheduled for weekly processing

Complete
