### ISSUE TITLE
UCR Nuxeo feed: Charles H. Lee

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1603]
Source ticket: https://help.oac.cdlib.org/a/tickets/126063

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/88

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_88.atom

Root folder in Nuxeo:
/asset-library/UCR/SCUA/Archival/WRCA071

Merritt collection: EXISTING:
**UC Riverside WRCA: Los Angeles Aqueduct**
**ark:/13030/m52b920p**

Object count:
236

Approximate storage needed:
125.75G

**Comment by mreyescdl** [comment]
- Created script
- Ran manually (236 objects)
- Scheduled for weekly processing

Complete
