### ISSUE TITLE
UCI Nuxeo feed: Academic and Professional Women of UCI records

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1607]
Source ticket: https://help.oac.cdlib.org/a/tickets/127466

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/28075

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_28075.atom

Root folder in Nuxeo:
/asset-library/UCI/SCA_UniversityArchives/AS-223

Merritt collection: EXISTING:
UC Irvine SCA University Archives collection
ark:/13030/m5bk6qsm

**Comment by elopatin-uc3** [comment]
This feed should be available on 9/26.

**Comment by mreyescdl** [comment]
- Created script
- Will wait for feed availability to run manually
- Added to weekly processing script, but not enabled

**Comment by elopatin-uc3** [comment]
Feed should be available

**Comment by mreyescdl** [comment]
Still receiving an "Access Denied" message from the feed endpoint

**Comment by mreyescdl** [comment]
- Feed now available
- Ran manually (1 object)
- Scheduled for weekly processing

Complete

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl, I'll notify the depositor.
