### ISSUE TITLE
Ingest - OpenSearch json, log4j2

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1609]

**Comment by mreyescdl** [comment]
Ingest Stage now is logging
- Callback
- Retrievals
- EZID mint and update

**Comment by mreyescdl** [comment]
Need to log Storage requests and then we can move to production.

**Comment by mreyescdl** [comment]
Deployed to production.

Let's keep this ticket open in case we need additional information that would help our Opensearch queries/graphs
