### ISSUE TITLE
Obsolete merritt docs in ui code

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1619]
The following links are supported in Merritt
- docs/merritt_handout.pdf
- docs/merritt_user_guide.pdf

What is linking to these pages?

Consider redirecting these links to the Merritt wiki.  Eliminate the obsolete PDFs.

Note that these docs live in the public folder, so they are served up without routing through the rails routes file.

<img width="643" alt="image" src="https://github.com/CDLUC3/mrt-doc/assets/1111057/d03ecdd7-49ec-4978-9a43-256a6d907b54">2">

The files should be removed and then a proper redirect should be added for each.

Also, the process of these requests does not appear in the rails log.

**Comment by terrywbrady** [comment]
Search WAF logs for the following to find examples of referers.

```
merritt_handout.pdf AND httpRequest.headers.name: Referer
```

**Comment by elopatin-uc3** [comment]
Corresponding links on cdlib.org have been removed. These were located by cdlib.org WP Link Checker tool which enables searching text in all links on the site. Links for the handout and user guide were replaced with a link to the current user documentation wiki. Pages affected: 
"UC Electronic Theses and Dissertations (ETDs) Now Have Preservation and Access"
"Deposit, save, share, find that content and data: new UC3 services launch"
