### ISSUE TITLE
UCR Nuxeo feed: Edward Hyatt Papers

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1621]
Source ticket: https://help.oac.cdlib.org/a/tickets/127696

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/26750

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_26750.atom

Root folder in Nuxeo:
asset-library/UCR/SCUA/Archival/WRCA045

Merritt collection: EXISTING:
**UC Riverside Library Nuxeo collection**
**ark:/13030/m5qg11t8**

**Comment by mreyescdl** [comment]
- Created script
- Manually ran (10 objects)
- Scheduled for weekly processing

Complete
