### ISSUE TITLE
UCR Nuxeo feed: Historical Artifacts Collection

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1622]
Source ticket: https://help.oac.cdlib.org/a/tickets/127696

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/27117

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27117.atom

Root folder in Nuxeo:
/asset-library/UCR/SCUA/Bibliographic/HMC

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

**Comment by mreyescdl** [comment]
- Created script
- Ran manually (77 objects)
- Scheduled for weekly processing

Complete
