### ISSUE TITLE
[Ingest/IAS] Eliminate unauthentic email sender

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#1633]
From IAS:

> I just had a discussion with some UCOP email people (Andy Liu and Mario Nakane). They noticed that a fair number of Merritt hosts are sending unsigned emails with "[uc3@ucop.edu](mailto:uc3@ucop.edu)" as the sender. From what I saw, they look like routine status notifications about job completion and the like, and are typically sent to UC3 staff.
> Soon email providers are going to begin dropping unsigned emails entirely. So we'll need to migrate these.
> The easiest thing to do from my point of view is if you could switch to sending from a [cdlib.org](http://cdlib.org/) address, e.g. [uc3@cdlib.org](mailto:uc3@cdlib.org), and I can add postfix configuration to automatically route those through AWS SES and add DKIM and SPF headers to they come through as signed.
> An alternative if you really like them coming from that address is for me to work with UCOP to obtain an SES key that sends through their account as [uc3@ucop.edu](mailto:uc3@ucop.edu), but this would require more cross-team communication every year.
> Thoughts?
> [1:44](https://cdlib.slack.com/archives/C86U0VBLH/p1696538664852409)
> I should say "unauthenticated" rather than "unsigned". Relatedly, gmail is going to start dropping these shortly: https://blog.google/products/gmail/gmail-security-authentication-spam-protection/
> 

Follow-up:
```
Terry
if these emails start routing through SES, do we need to worry about damaging our sender reputation?  In a large submission failure situation, it is possible that Merritt will send out a large number of messages in a short period of time. Do we need to be cautious about the volume that pushes through SES?

Martin
Depends on the volume; if it's in the tens of thousands, that could be a problem.
A larger issue if we start using SES is if users report the messages as spam. That can hurt the overall email reputation of CDL.

Terry
Do we have a way to isolate the merritt messages to not hurt repuation?  Or, can we throttle these in SES?
I could imagine that a user gets frustrated in a failure situation.
```

**Comment by mreyescdl** [comment]
From the Ingest side.  The "from:" email address is hard-coded in the Notification handler as well as the Callback.
Let's make this an SSM parameter

**Comment by marisastrong** [comment]
https://ucopedu.atlassian.net/wiki/spaces/CUG/pages/47187600/Email+User+Guide

**Comment by terrywbrady** [comment]
10/17 -
- Goal, provide authenticated email (for recipients)
- Our existing postfix service does not authenticate - not a registered domain
- SES credentials can be added to the postfix configuration.

**Comment by terrywbrady** [comment]
Joe will follow up

**Comment by mreyescdl** [comment]
Summary of meeting with Joe.

SES may not be appropriate for Merritt to use to authenticate:
- SES has CDL wide quotas which Merritt may exhaust due to user submissions
- Same goes for Spam being flagged.  We may affect other SES users.

Joe showed how SES is tied into Postfix which enables email to authenticate.  The underlying technology is DKIM.
We looked into using open source software - OpenDKIM (http://www.opendkim.org)

Joe will investigate this software as an alternate to SES.
Also of note, we found that Amazon Linux 2023 will no longer support the EPEL repository.  This may be of note to @ashleygould

**Comment by mreyescdl** [comment]
After discussion with IAS, we will validate email through SES.
This will require a Postfix configuration change as well as some DNS records created.
Will work with @jsomontan to get this started on Ingest stage

**Comment by mreyescdl** [comment]
Joe has updated our Stage Ingest servers to now use SES authentication.
Testing was successful.  Here are the email header from a pre/post fixed host...
```
Authentication-Results: spf=none (sender IP is 54.244.52.17)
 smtp.mailfrom=uc3-ingest01x2-stg.cdlib.org; dkim=none (message not signed)

Authentication-Results: spf=pass (sender IP is 54.240.27.193)
 smtp.mailfrom=us-west-2.amazonses.com; dkim=pass (signature was verified)
```

**Comment by mreyescdl** [comment]
Ingest stage notification is not working with the Merritt service.
I checked the S3 buckets and there is no record of submission notification.
`https://ucopedu.atlassian.net/wiki/spaces/CUG/pages/47187600/Email+User+Guide#EmailUserGuide-AmazonSES`

I'll need to investigate why the change is not working.
For now, let's hold any further changes to Postix on host @jsomontan

**Comment by mreyescdl** [comment]
Confirmed that command line "mailx" can send email under new Postfix rules, but Merritt app can not.

**Comment by jsomontan** [comment]
Great catch Mark!  Yes, the SES credential is for the cdlib.org domain and ucop.edu.

+ Joe

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl. I've added this to our list of tickets to discuss at the team meeting on Tuesday.

**Comment by mreyescdl** [comment]
@jsomontan 
The above error message indicates that the email was bounced, yet I do not see evidence of this in the S3 bucket.  There is only a Delivery/ bucket.
Can you check on this?  Thanks

**Comment by jsomontan** [comment]
Hey Mark,

    I can’t seem to find the details to your uc3 issue in here.  https://github.com/CDLUC3/mrt-doc/issues

Can you send me the link to where the errors are at?

Thanks

**Comment by mreyescdl** [comment]
Hi Joe,
Here is the message that the `journalctl` process shows.  Notice that the status is "bounced"

"status=bounced (host email-smtp.us-west-2.amazonaws.com[44.236.53.234] said: 554 Message rejected: Email address is not verified. "

**Comment by elopatin-uc3** [comment]
We decided to change the from address to "merritt at cdlib.org". 

We'll want to reach out to depositors to let them know of this address change.

**Comment by mreyescdl** [comment]
It was discovered that ETD and other processes use the HelpDesk email of "uc3 at ucop.edu"
We want to be consistent with our contact email address across Merritt.  Thus, it would be better to support "merritt @ cdlib.org" as a valid email address.

@marisastrong @ashleygould Is it possible that "merritt at cdlib.org" could be directed to our existing HelpDesk target??

**Comment by terrywbrady** [comment]
## Merritt Email Use
https://github.com/search?q=org%3ACDLUC3%20uc3%40ucop.edu&type=code

Repositories
- mrt-dashboard (UI) 
  - has footer link to help desk email (no sending)
  - has link on maintenace page to help desk email (no sending)
  - has DUA email... does this still function?
    - https://github.com/CDLUC3/mrt-dashboard/blob/380adad1648a15b32df9618a616433cd7b5e6f3d/app/mailers/dua_mailer.rb#L4
  - in atom feed (no send)
- merritt-docker 
  - has default address in ldap test (any sent email is purely a test)
  - mail sent from DEV host - no FROM specified - daily build
- mrt-cron
  - multiple cron jobs send mail from mrtbatch host. no FROM specified 
- uc3-etds - from address for etd reports sent to campuses
- mrt-ingest - hard-coded in 4 spots, will move to SSM

LOTS of references to uc3@ucop.edu in puppet modules

**Comment by terrywbrady** [comment]
I think the email from ETD and from Ingest are the main things to focus on.  If we make the mail come from cdlib.org, do we have a way for users to reply?  Or, could we specify `uc3@ucop.edu` as a reply-to address?  Should we make the from address `no-reply-uc3@cdlib.org`?

**Comment by mreyescdl** [comment]
@terrywbrady I'll test this out after Wed. release.
There is a setReplyTo() method in the email library.  My only concern is that SES will see the difference and bounce the email.

**Comment by mreyescdl** [comment]
Ingest production email is now authenticated.

For command line email, we'll need to supply a reply to field as well.

For example
```
mailx -s "test email" -r 'merritt@cdlib.org' -S 'replyto=uc3@ucop.edu' <target email>
```
