### ISSUE TITLE
UCR Nuxeo feed: James D. Schuyler Papers

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1634]
Source ticket: https://help.oac.cdlib.org/a/tickets/127696

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/26753

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_26753.atom

Root folder in Nuxeo:
/asset-library/UCR/SCUA/Archival/WRCA063

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

**Comment by mreyescdl** [comment]
- Created script (production-James_D_Schuyler_Papers.csh)
- Ran manually (16 objects)
- Scheduled for weekly processing
- Tested new Nuxeo password

Complete

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl
