### ISSUE TITLE
UCR Nuxeo feed: Jay Kay Klein Papers & photographs

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1635]
Source ticket: https://help.oac.cdlib.org/a/tickets/127696

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/26943

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_26943.atom

Root folder in Nuxeo:
/asset-library/UCR/SCUA/Archival/Klein

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

**Comment by mreyescdl** [comment]
- Created script (production-Jay_Kay_Klein_Papers_Photographs.csh)
- Submitted manually (5227 objects)
- Scheduled for weekly processing


Complete
