### ISSUE TITLE
UCR Nuxeo feed: John Barlow Lippencott

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1638]
Source ticket: https://help.oac.cdlib.org/a/tickets/127696

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/13109

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_13109.atom

Root folder in Nuxeo:
/asset-library/UCR/SCUA/Archival/WRCA052

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

**Comment by mreyescdl** [comment]
- Created script (production-John_Barlow_Lippencott.csh)
- Ran manually (1142 objects)
- Scheduled for weekly processing
- Checked code into GitHub repo


Complete
