### ISSUE TITLE
UCR Nuxeo feed: Juan Silvano Godoi papers 

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1639]
Source ticket: https://help.oac.cdlib.org/a/tickets/127696

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/8590

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_8590.atom

Root folder in Nuxeo:
/asset-library/UCR/SCUA/Archival/MS003

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

**Comment by mreyescdl** [comment]
- Created script (production-Juan_Silvano_Godoi_Papers.csh)
- Ran manually (888 objects)
- Scheduled for weekly processing
- Checked code into repo

Complete
