### ISSUE TITLE
[INGEST]  Callback encoding issue

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#1644]
Mahjabeen noticed that UTF-8 was not supported in the payload for a callback request.
I found that while the JobState we create was UTF-8 encoded, the String Entity we create as part of the HTTP Post was not.

This has been fixed and will piggyback its way to production deployment with the Opensearch Ingest changes

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl

**Comment by mreyescdl** [comment]
Deployed to prod.

Mahjabeen has tested fix and it is working.

Complete
