### ISSUE TITLE
[RELEASE] Ingest opensearch support - 2023-10-19

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#1646]
# Overview of Release
- Support for open search with external calls: callback, storage, retrieve and EZID.
- Callback encoding bug fix

# Service(s)
Ingest

# Github Issue Link(s)
https://github.com/CDLUC3/mrt-doc/issues/1609
https://github.com/CDLUC3/mrt-doc/issues/1644

# Servers affected
- uc3-mrtingest01x2-prd
- uc3-mrtingest02x2-prd
- uc3-mrtingest03x2-prd

# Source Code:
https://github.com/CDLUC3/mrt-ingest/pull/89

# Source Code Tag
1.0.12

# Jenkins/Build Info: (if applicable)
http://builds.cdlib.org/view/New%20Build%20Config/job/Merritt_Build_Config/117/

# Deployment Steps (if applicable)
- [x] Remove Ingest worker from ALB
- [x] Deploy tag 1.0.12
- [x] Add worker to ALB and repeat for other workers

# Infrastructure Changes to support deployment (ALB, EFS, etc)
Remove workers from ALB uc3-mrt-ingest-prd-alb2

# Rollback Instructions
Use Capistrano rollback action

**Comment by mreyescdl** [comment]
Deployed to production Ingest.
Will monitor volume of data we are providing to Opensearch.  If too much we will alter LOG4J level from INFO to WARN

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl !

**Comment by mreyescdl** [comment]
Additional work needed after review of data.  Also, adding stack trace logging to open search.
https://github.com/CDLUC3/mrt-ingest/pull/90

**Comment by mreyescdl** [comment]
Deployed to stage (1.0.13)
Testing successful

**Comment by mreyescdl** [comment]
Deployed to prod (1.0.13)
One integration error (perma-link issue)
