### ISSUE TITLE
Brainstorm Nagios Improvements per 10/30 Dev Coffee

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1654]
- ZFS Check - check / alert from only one box rather than from ALL store and ingest boxes
   Triggered when usage reaches various thresholds
- Ingest Queue alert - check/alert from only one ingest box
   Triggered when Merritt submissions are paused

**Comment by ashleygould** [comment]
The nagios service_check `uc3_chk_zfs_prd` now is only active for host uc3-ingest01x2-prd.

**Comment by ashleygould** [comment]
the service check `uc3-mrt-ingest-prd_status-thawed_7x16` should remain on all uc3-mrt-ingest-prd hosts, because it is possible for only one host to be frozen.  this check ensures all 3 hosts are in the thawed state.

**Comment by terrywbrady** [comment]
@ashleygould , when the queue is frozen, it is frozen for all hosts not for just one.

**Comment by ashleygould** [comment]
ok, i'll update this check to only run for one host.
