### ISSUE TITLE
File names generated via Nuxeo harvest include unneeded characters

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1655]
```
It seems like the harvester is deriving the filename from an href value in the feed, instead of using the dc:title field. 

For example:

<link href="https://nuxeo.cdlib.org/Nuxeo/nxfile/default/273d436f-7036-4354-a1f8-0ba5c7855a2b/file:content/MS-F044_accn2022_005_bag.zip?changeToken=4-0" rel="alternate" title="Main content file">
      <opensearch:checksum algorithm="MD5">210648d666d520d81a9c5725aed79106</opensearch:checksum>
    </link>
    <dc:creator>Parham, Thomas A.</dc:creator>
    <dc:title>MS-F044_accn2022_005_bag</dc:title>

Note changeToken=4-0 at the end of the zip file URL

Unfortunately the .zip extension is not present in dc:title
```

**Comment by elopatin-uc3** [comment]
@elopatin-uc3 to file separate issue for a different Nuxeo harvest file name issue where ARK is included and file extension is excluded.

**Comment by terrywbrady** [comment]
We will investigate if the compose plugin can be installed on linux

**Comment by dloy** [comment]
Comment:
The S3 key used by these files includes the query portion of the URL.
~~~
<key>ark:/13030/m5r89gbn|1|producer/nuxeo.cdlib.org/Nuxeo/nxfile/default/cede1001-e4f1-4223-9a34-243da2296bcd/file:content/highlander_19731004_027.tif?changeToken=6-0</key>
~~~

Doing an ingest change on the pathname handling to remove the URL property will generate content under the correct pathname/key but original key and content will remain with the earlier version.

**Comment by elopatin-uc3** [comment]
@elopatin-uc3 should set up a separate meeting to discuss. Consider inviting AT for Nuxeo details.

**Comment by elopatin-uc3** [comment]
Discussed on 1/12. Subsequent meeting to be scheduled to talk about possible solutions. Initial work should include fixing the harvester so it disregards URL parameters and excludes them from file names.

**Comment by mreyescdl** [comment]
Work is being scheduled for eliminating the change token data currently in S3.
In tandem, we will need to eliminate the creation of new data with query parameters.

Will modify Nuxeo client to eliminate any query parameter in filename.

**Comment by mreyescdl** [comment]
Nuxeo client change to eliminate changeToken
https://github.com/CDLUC3/mrt-atom/pull/8

**Comment by elopatin-uc3** [comment]
@mreyescdl @dloy @terrywbrady just capturing what we discussed this morning:

- Currently Nuxeo processing is stopped
- Run harvester with fix on Stage collections to test that changetoken string is no longer introduced
- Assuming tests pass, move fix to production harvester
- Resume Nuxeo harvests to continue working through backlog until one harvest has been completed for all Nuxeo direct deposit collections (for all campuses).

Ahead of when the backlog is processed, let's review Stage object update test results via OpenSearch when they're available there.

Once we're confident of the updates on Stage, let's create a schedule for running object updates in production.

**Comment by mreyescdl** [comment]
Restarting production Nuxeo

**Comment by mreyescdl** [comment]
Here is a production example of an object with versions that span the upgrade.
Version 1 has "changeToken" while version 2 does not

https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm5j78b9z

**Comment by mreyescdl** [comment]
One note.
The change is hardcoded to only remove "changeToken" query string.
In the future if Nuxeo decides to change the query string, then we will still have an issue.
This was done to prevent modifying data which may have a question mark in the filename
