### ISSUE TITLE
[RELEASE] Ingest opensearch support update - 2023-10-30

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1656]
# Overview of Release
- Log error when retrieval fails
- Allow for integer opensearch datatype
- Allow for stack traces in opensearch (from dloy)
- Add stack trace logging to opensearch

Note: This update allows all external requests (except local ID Service) to log their data to open search.  This is true even for error conditions.

# Service(s)
Ingest

# Github Issue Link(s)
https://github.com/CDLUC3/mrt-doc/issues/1609

# Servers affected
- uc3-mrtingest01x2-prd
- uc3-mrtingest02x2-prd
- uc3-mrtingest03x2-prd

# Source Code:
https://github.com/CDLUC3/mrt-ingest/pull/90

# Source Code Tag
1.0.13

# Jenkins/Build Info: (if applicable)
http://builds.cdlib.org/view/New%20Build%20Config/job/Merritt_Build_Config/117/

# Deployment Steps (if applicable)
- [x] Remove Ingest worker from ALB
- [x] Deploy tag 1.0.13
- [x] Add worker to ALB and repeat for other workers

# Infrastructure Changes to support deployment (ALB, EFS, etc)
Remove workers from ALB uc3-mrt-ingest-prd-alb2

# Rollback Instructions
Use Capistrano rollback action

**Comment by mreyescdl** [comment]
Deployed to stage and production.

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl!
