### ISSUE TITLE
Unexpected status from Merritt for asynchronous download query

### ISSUE THREAD

**Issue by sfisher** [CDLUC3/mrt-doc#166]
This is a giant dataset when I look at it at 478 GB.  The relevant dataset links are these:

https://datadryad.org/stash/dataset/doi:10.5061/dryad.gn001

https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm5b61mt4

Before we allow downloads we check with a Merritt API to see if the download will be synchronous or if needs to be asynchronous and we need to collect an email from the user and make them wait for an email.  This one is obviously asynchronous based on the size.

We query the URL http://merritt.cdlib.org/async/ark%3A%2F13030%2Fm5b61mt4/1 with a GET request.  Per Mark we should expect one of these two response status codes and this is what they mean.

200 = asynchronous download
406 = synchronous download

Instead we throw errors if Merritt gives us an unexpected status code.  This one is returning a status code of 403 instead (Forbidden).  Yet other items in the Dryad collection download for us fine, so I don't think it's a username or password issue.  IDK, maybe this is a flag or something that needs to be set in Merritt.

Currently in our UI this download is broken since we can't decide what method we would allow for download.  I think it only affects this particular dataset.

@dlowenberg and @elopatin-uc3 , I'll let you decide how important this is or how quickly it needs to be looked at.

**Comment by mreyescdl** [comment]
Here is the problem code and data.  Not sure why we put this limit in, maybe due to Storage processing constraints.  Need to ask David

    if @version.exceeds_download_size?
      render nothing: true, status: 403

  max_download_size:    322122547200  # 322122547200 bytes = 300 GiB

**Comment by elopatin-uc3** [comment]
Consider making a change to the status code for this ticket. Perhaps 413? TBD

Will leave 300GB limit in place.

**Comment by elopatin-uc3** [comment]
No longer an issue per pre-signed URL implementation; closing.
