### ISSUE TITLE
[INGEST] Submission failure due to WAF rejection

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#1660]
WAF is rejecting a zip file submitted by eschol.
Dataset is located at
```
/home/mreyes/merritt/teak/594.zip
```

Blocking from WAF is from rule `PHPHighRiskMethodsVariables_BODY` 
This rule is documented as:
```
Inspects the values of the request body for PHP script code injection attempts. Example patterns include functions like fsockopen and the $_GET superglobal variable.
```

ELB response code:
```
< HTTP/2 403
< server: awselb/2.0
< date: Tue, 31 Oct 2023 22:39:17 GMT
```

I rezipped the two files using the Linux info-ZIP and encountered no error during submission.
I renamed the original zip file and still encounter the error.
The elapsed time that it fails is
```
real    0m0.116s
```
It is hard to believe that the WAF is unpacking the zip and running a scanner in that small time.
It is unclear what is going on with this zip file and the WAF.

**Comment by terrywbrady** [comment]
Mark will try to temporarily disable.

He will send a ticket to IAS to ask AWS for an explanation.

**Comment by mreyescdl** [comment]
I disabled the PHP ruleset on stage WAF and was able to submit the payload.
Note: PHP Ruleset contains three rules
```
AWSManagedRulesPHPRuleSet
        PHPHighRiskMethodsVariables_HEADER
        PHPHighRiskMethodsVariables_QUERYSTRING
        PHPHighRiskMethodsVariables_BODY
```

**Comment by mreyescdl** [comment]
Working with Mahjabeen to coordinate rule removal and submission on production

**Comment by mreyescdl** [comment]
IAS request: https://github.com/cdlib/cdlsys/issues/292

**Comment by mreyescdl** [comment]
Disabled the rule in production and Mahjabeen successfully sent submission through.
Re-enabled the rule.

Joe and I will meet with AWS rep on next week to discuss.  At that time we'll make a decision whether to permanently disable

**Comment by elopatin-uc3** [comment]
Mark uploaded the sample payload that triggered this to the AWS representative, who has reproduced the issue. Hopefully this can be addressed server side. Otherwise the recommendation was to investigate further and add exceptions for problem files. Given this has occurred only twice, we've re-enabled the rule.
