### ISSUE TITLE
fix1.5 - bom1.5 +

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#1668]
## Description
fix1.5 is a tag associated with a variety of additions and modifications across several Merritt microservices. Many of these features are specifically described in other items.

### Items covered in these changes
- [BOM 1.5](https://github.com/CDLUC3/mrt-doc/issues/1662)
- [Storage: hitting the kms:Decrypt API thousands of times an hour #1650](https://github.com/CDLUC3/mrt-doc/issues/1650)
- [2 mrt-core2 dependency update needed: jdom #1485](https://github.com/CDLUC3/mrt-doc/issues/1485)
- [mrt-cloud - TransferManager error #1661](https://github.com/CDLUC3/mrt-doc/issues/1661)
- [inventory - update log4j2.xml #1663](https://github.com/CDLUC3/mrt-doc/issues/1663)
- [Storage state check - add timeout to node state check and report error - JsonStatus #1470](https://github.com/CDLUC3/mrt-doc/issues/1470)
- (start) - [JsonStatus follow up tasks #1665](https://github.com/CDLUC3/mrt-doc/issues/1665)
- (hopefully!) - [presign object retrieval 500 errors - is retry logic needed? #1611](https://github.com/CDLUC3/mrt-doc/issues/1611)

### core2
- BOM 1.5
- remove jdom references

### cloud
- fix TransferManager download 500 to 404
- intermediate jsonstatus routines

### Storage and Access
- BOM 1.5
- add jsonstatus
- remove jdom references
- cleanup of Token api intializations of NodeIO (see #1650)
- Access 500 errors in token handling should now be returned as 404

### Inventory
- BOM 1.5
- update to current log4j2.xml

### Audit
- BOM 1.5
- add jsonstatus

### Replic
- BOM 1.5
- add jsonstatus
- remove jdom references

**Comment by mreyescdl** [comment]
Ingest branch for fix1.5 did not contain changes made to Ingest in Sept. and Oct.
Created new branch named "fix1.5a" which removes JDOM, but retains changes.  Also in included in this branch is a fix for a logic bug in the HandlerRetrieve download code.  Discovered during the Nuxeo processing, if a failed download is successful on the 2nd attempt, it was still flagged as a failure.  One line fix
