### ISSUE TITLE
UCR Nuxeo feed: Mono Lake Committee Collection

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1671]
Source ticket: https://help.oac.cdlib.org/a/tickets/127696

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/26756

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_26756.atom

Root folder in Nuxeo:
/asset-library/UCR/SCUA/Archival/WRCA204

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

**Comment by mreyescdl** [comment]
- Created script (production-Mono_Lake_Committee_Collection.csh)
- Ran manually (3 objects)
- Scheduled for weekly processing
- Checked code into repo

Complete
