### ISSUE TITLE
UCR Nuxeo feed: Nellie Suydam Cowley Papers

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1672]
Source ticket: https://help.oac.cdlib.org/a/tickets/127696

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/5222

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_5222.atom

Root folder in Nuxeo:
/asset-library/UCR/SCUA/Archival/MS158

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

**Comment by mreyescdl** [comment]
- Created script (production-Nellie_Suydam_Cowley_Papers.csh)
- Ran manually (65 objects)
- Scheduled for weekly processing
- Checked code into repo


Complete

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl!
