### ISSUE TITLE
UCR Nuxeo feed: Patent Model Collection

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1674]
Source ticket: https://help.oac.cdlib.org/a/tickets/127696

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/27686

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27686.atom

Root folder in Nuxeo:
/asset-library/UCR/SCUA/Archival/WRCA110

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

**Comment by mreyescdl** [comment]
- Created script (production-Patent_Model_Collection.csh)
- Manually ran (12 objects)
- Scheduled for weekly processing
- Checked code into repo

Complete

**Comment by mreyescdl** [comment]
Actually, 2 failures during submission.  Investigating

**Comment by mreyescdl** [comment]
Requeued successfully.
