### ISSUE TITLE
UCR Nuxeo feed: Patricia Ortlieb collection on Eliza L. Tibbets

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1675]
Source ticket: https://help.oac.cdlib.org/a/tickets/127696

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/16349

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_16349.atom

Root folder in Nuxeo:
/asset-library/UCR/SCUA/Archival/MS374

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

**Comment by mreyescdl** [comment]
- Created script (production-Patricia_Ortlieb_Collection.csh)
- Ran manually (187 objects)
- Scheduled for weekly processing
- Checked code into repo

Complete
