### ISSUE TITLE
[RELEASE] Fix1.5 - bom 1.5, jsonstatus, ...

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#1680]
# Overview of Release
- See [fix1.5 - bom1.5 + #1668](https://github.com/CDLUC3/mrt-doc/issues/1668)
- See [Tomcat AJP error #1677](https://github.com/CDLUC3/mrt-doc/issues/1677)

# Service(s)
- store/access
- inventory
- audit
- replic
- (ingest - added separately)

# Github Issue Link(s)
See [fix1.5 - bom1.5 + #1668](https://github.com/CDLUC3/mrt-doc/issues/1668)
See [Tomcat AJP error #1677](https://github.com/CDLUC3/mrt-doc/issues/1677)

# Servers affected
## Stage
- uc3-mrtstore01x2-stg
- uc3-mrtstore02x2-stg
- uc3-mrtaccess01x2-stg
- uc3-mrtaccess02x2-stg
- uc3-mrtinv01x2-stg
- uc3-mrtinv02x2-stg
- uc3-mrtreplic01x2-stg
- uc3-mrtreplic02x2-stg
- uc3-mrtaudit01x2-stg
- uc3-mrtaudit02x2-stg

## Prod
- uc3-mrtstore05x2-prd
- uc3-mrtstore06x2-prd
- uc3-mrtaccess01x2-prd
- uc3-mrtaccess02x2-prd
- uc3-mrtinv01x2-prd
- uc3-mrtinv02x2-prd
- uc3-mrtreplic01x2-prd
- uc3-mrtreplic02x2-prd
- uc3-mrtaudit01x2-prd
- uc3-mrtaudit02x2-prd
- uc3-mrtaudit03x2-prd
- uc3-mrtaudit04x2-prd

# Source Code:
Link(s) to tagged release(s)
https://github.com/CDLUC3/mrt-core2/commit/4c8ea8d040eb223c020f84046d878a5a037745fc
https://github.com/CDLUC3/mrt-cloud/commit/63697f7043902d268bc7d79e561e0f94fd076ceb
https://github.com/CDLUC3/mrt-store/commit/495b24ec6f8e2e77f5447f9fc44439d21645342e
https://github.com/CDLUC3/mrt-inventory/commit/bab312766ba0b3cc9ce959832c3afa2d574b93c9
https://github.com/CDLUC3/mrt-audit/commit/8e40de1bcff0f14065134eeeeb2acdcd959edafd
https://github.com/CDLUC3/mrt-replic/pull/27/commits/4ebb7f0467b934522b70ab199abb442b92a8a628
https://github.com/CDLUC3/mrt-replic/pull/27/commits/5a5711a6a90a63f18c9dd60ce5b17249ccbfb99f

# Source Code Tag
- Access/store - 1.5.7
- Audit - 1.5.6
- Inv - 1.5.2
- Replic - 1.5.6

# Jenkins/Build Info: 
All services built using [Merritt_Build_Config](http://builds.cdlib.org/view/New%20Build%20Config/job/Merritt_Build_Config/)

- Access/store - 1.5.7
- Audit - 1.5.6
- Inv - 1.5.2
- Replic - 1.5.6

# Deployment Steps (if applicable)
- [x] Stage - Standard  deployment - complete 11/16/2023
- [ ] Standard Prod live system deployment - after 11/23/2023

# Infrastructure Changes to support deployment (ALB, EFS, etc)

# Rollback Instructions

**Comment by elopatin-uc3** [comment]
Thanks for filing this release ticket @dloy
