### ISSUE TITLE
get mime tools available on uc3-mrtsandbox2-stg

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#1682]
Would like to get xdg-mime and gvfs-info tools installed on uc3-mrtsandbox2-stg.

Also, __mimetype__, if possible.

From:  https://linuxcommando.blogspot.com/2014/03/how-to-find-mime-type-of-file.html
Some [MIME types](https://en.wikipedia.org/wiki/Internet_media_type) can be intuitive - application/pdf for PDF files. However, not all MIME types are that easy to get exactly right - application/vnd.ms-excel for xls or Excel files.

The following are different ways, using the command line, to identify the MIME type of a file.

__xdg-mime__
~~~
$ xdg-mime query filetype somefile.xls
application/vnd.ms-excel
file
~~~

__gvfs-info__
~~~
$ gvfs-info -a standard::content-type somefile.xls
attributes:
  standard::content-type: application/vnd.ms-excel
~~~

**Comment by ashleygould** [comment]
updated puppet hiera fqsn/uc3-ops-dloy-dev.yaml to install packages xdm-utils and gvfs-client.
