### ISSUE TITLE
UCR Nuxeo feed: Sadakichi Hartmann papers 

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1688]
Source ticket: https://help.oac.cdlib.org/a/tickets/129981

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/9513

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_9513.atom

Root folder in Nuxeo:
/asset-library/UCR/SCUA/Archival/MS068

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

**Comment by mreyescdl** [comment]
- Created script (production-Sadakichi_Hartmann_Papers.csh)
- Ran manually
- Scheduled for weekly processing
- Checked into GitHub

Complete
