### ISSUE TITLE
UCR Nuxeo feed: Samuel C. Evans collection on the Riverside Land and Irrigation Company 

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1689]
Source ticket: https://help.oac.cdlib.org/a/tickets/129981

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/7007

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_7007.atom

Root folder in Nuxeo:
/asset-library/UCR/SCUA/Archival/MS001

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

**Comment by mreyescdl** [comment]
- Created script (production-Samuel_C_Evans_Collection.csh)
- Ran manually (10 objects)
- Scheduled for weekly processing
- Checked into GitHub

Complete
