### ISSUE TITLE
Repurpose a recently added Replic server to Audit

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#169]
### Summary
During the Minio migration, two addition Replic servers were set up to expedite the process. Now that the migration is complete, we'll be repurposing one of these instances into an Audit server.

### Tasks
- [x] Repurpose replic-xx to audit-xx

**Comment by dloy** [comment]
uc3-mrtreplic4-prd is now running an audit microservice. The replication service has been turned off
