### ISSUE TITLE
UCR Nuxeo feed: Ted McKown collection of flamenco sound recordings 

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1690]
Source ticket: https://help.oac.cdlib.org/a/tickets/129981

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/26392

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_26392.atom

Root folder in Nuxeo:
/asset-library/UCR/SCUA/Archival/MS394

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

**Comment by mreyescdl** [comment]
Waiting for feed to become available

**Comment by mreyescdl** [comment]
- Created script (production-Ted_McKown_Flamenco_Sound_Recordings.csh)
- Ran manually (7 objects)
- Scheduled for weekly processing
- Checked code into git repo

Complete
