### ISSUE TITLE
UCR Nuxeo feed: Tuskegee Airmen collection 

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1691]
Source ticket: https://help.oac.cdlib.org/a/tickets/129981

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/23034

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_23034.atom

Root folder in Nuxeo:
/asset-library/UCR/SCUA/Archival/MS176

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

**Comment by mreyescdl** [comment]
Waiting for feed to become available

**Comment by mreyescdl** [comment]
- Created script (production-Tuskegee_Airmen_collection.csh)
- Ran manually (14 objects)
- Scheduled for weekly processing
- Checked into git repo

Complete
