### ISSUE TITLE
UCR Nuxeo feed: University of California, Riverside Chicana/o/x student newspapers 

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1692]
Source ticket: https://help.oac.cdlib.org/a/tickets/129981

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/27876

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27876.atom

Root folder in Nuxeo:
/asset-library/UCR/SCUA/Bibliographic/csp

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

**Comment by mreyescdl** [comment]
Waiting for feed to become available

**Comment by mreyescdl** [comment]
- Created script (production-Chicana_o-x_student_newspapers.csh)
- Ran manually (95 objects)
- Scheduled for weekly processing
- Checked into git repo

Complete
