### ISSUE TITLE
UCR Nuxeo feed: University of California, Riverside Highlander student newspaper 

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1693]
Source ticket: https://help.oac.cdlib.org/a/tickets/129981

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/82

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_82.atom

Root folder in Nuxeo:
/asset-library/UCR/SCUA/Bibliographic/y2_r5_h53/

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

**Comment by mreyescdl** [comment]
- Created script
- Running manually (2043 objects)
