### ISSUE TITLE
Dev env for Terry / Docker-ize Merritt Services 

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#170]
### Summary 
This ticket is meant to be a place for keeping notes about initial development environment setup tasks, as well as recording an order in which to set up microservices locally, testing, etc.

## Existing Merritt Operations page:
https://confluence.ucop.edu/display/UC3/MerrittOperations

## Work in progress
- https://github.com/cdluc3/merritt-docker

## Research/Conversations 
- [x] Create a table in confluence with microservice entries to record relevant notes
  - https://confluence.ucop.edu/display/UC3/Merritt+Micro-service+Test+Strategy+By+Service
- [x] Meet with Mark to understand how he tests individual components
- [x] Meet with David to understand how he tests individual components

## Application Testing

- [x] Open the UI home page: http://localhost:9292/
  - [x] Build UI image
- [x] Log into Merritt from the home page
- [x] View the status of the ingest service: http://localhost:8080/ingest/help
  - [x] Build ingest image
  - See Use Cases for specific issues
- [x] View the status of the storage service: 
  - [x] http://localhost:8081/store/state
  - [x] http://localhost:8081/store/state/9001
  - [x] http://localhost:8081/store/state/9502 - clarify settings with David
  - [x] Build storage service
  - [x] Error: org.cdlib.mrt.inv.service.InvServiceProperties-<init>:104 INVALID_OR_MISSING_PARM
  - [x] Configure minimal mrtHomes store and repository directory
  - [x] David will help me assemble the minimal files needed
- [x] View the status of the inventory service: http://localhost:8082/inventory/state
  - [x] Build inventory service
  - [x] Error: InvServiceProperties: inv service directory does not exist:/apps/replic/tst/inv

## Docker Container View
```
$ docker ps -a
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                                                  NAMES
39349a7ec76c        cdluc3/mrt-ingest      "catalina.sh run"        7 minutes ago       Up 7 minutes        8009/tcp, 0.0.0.0:8080->8080/tcp                       ingest
ae53745be1fa        cdluc3/mrt-inventory   "catalina.sh run"        7 minutes ago       Up 7 minutes        8009/tcp, 0.0.0.0:8082->8080/tcp                       inventory
d9d72b998461        cdluc3/mrt-store       "catalina.sh run"        10 minutes ago      Up 7 minutes        8009/tcp, 0.0.0.0:8081->8080/tcp                       store
3b249ccfc2d2        cdluc3/mrt-dashboard   "bundle exec puma -C…"   54 minutes ago      Up 7 minutes        3000/tcp, 0.0.0.0:9292->9292/tcp                       ui
17aa486c43c0        zookeeper              "/docker-entrypoint.…"   54 minutes ago      Up 7 minutes        2888/tcp, 3888/tcp, 0.0.0.0:2181->2181/tcp, 8080/tcp   zoo
9c21a25926f4        cdluc3/mrt-database    "docker-entrypoint.s…"   54 minutes ago      Up 7 minutes        0.0.0.0:3306->3306/tcp, 33060/tcp                      db-container

```

## [ ] Use Case 1A: Ingest File from UI, No Local Id (Async)
  - [x] View demo collection in the UI
  - [x] Confirm creation of queue folder
  - [x] Confirm queue addition
  - [x] Confirmation e-mail: org.apache.commons.mail.EmailException: Sending the email to the following server failed : localhost:25
    - [x] Error: SEVERE [pool-1-thread-1] com.sun.jersey.api.client.ClientResponse.getEntity The registered message body readers compatible with the MIME media type
  - [x] Track item into storage 
  - [ ] [info]IngestManager: error detected, skipping handler: class org.cdlib.mrt.ingest.handlers.HandlerInventoryQueue
  - [x] Error: rg.cdlib.mrt.ingest.utility.LocalIDUtil-fetchPrimaryID:149 EXTERNAL_SERVICE_UNAVAILABLE[Unavailable remote service] [error] LocalIDUtil: local ID service: http://inventory:8080/mrtinv/primary/
    - [ ] curl to staging inventory service port is not accessible

## Configuration Options
| Config Name | LDAP | DB | Storage Node | Note |
| ------------- | ------ | -- | --------------- | ---- |
|Staging DB & Storage | Staging | Staging | Staging - single node recommended by David | In Progress |
|Docker DB - Staging Storage | Staging | Docker | Staging - single node recommended by David | In Progress | 
|Docker DB - Isolated Storage | Staging | Docker | Isolated storage node that is distinct from Staging | TBD |
|Isolation| Docker | Docker | Isolated storage node that is distinct from Staging | TBD, create standalone or mock LDAP |

**Comment by terrywbrady** [comment]
Moving this issue to the "Done" pile.  More specific issues can be created for merritt-docker enhancements.
