### ISSUE TITLE
UC Irvine Nuxeo feed: Collection on the Anteater mascot and other university symbols

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1702]
Source ticket: https://help.oac.cdlib.org/a/tickets/130619

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/28152

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_28152.atom

Root folder in Nuxeo:
/asset-library/UCI/SCA_UniversityArchives/AS-144

Merritt collection: EXISTING:
UC Irvine SCA University Archives collection
ark:/13030/m5bk6qsm

**Comment by elopatin-uc3** [comment]
Feed should be available by 12/12.

**Comment by mreyescdl** [comment]
- Created script (production-28152-UCI-Collection_Anteater_Mascot_University_Symbols-uci_lib_sca_ua_content.csh)
- Ran manually (12 objects)
- Scheduled for weekly processing
- Checked into git repo
Complete
