### ISSUE TITLE
Ongoing replication operations appear to be flagged as failures by the Admin tool

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1706]
It appears that in-process replication operations are picked up by the Admin tool's Replication Failed report until they are complete. This is new (as of approximately 12/1) and evidenced by a rolling list of objects that appears in this report at any given time. 

https://merritt-admintool.cdlib.org/web/index.html?path=replication_failed

**Comment by elopatin-uc3** [comment]
This issue was observed again on 12/15 as submissions were being processed for a new collection.

**Comment by terrywbrady** [comment]
I saw evidence of this again on 1/3.  `ark:/13030/m5d61jbn`

**Comment by terrywbrady** [comment]
This should resolve the issue.

https://github.com/CDLUC3/mrt-admin-lambda/commit/da281b2b3aa1b3883cb349c0ced125b560d4ef87
