### ISSUE TITLE
UCSF Nuxeo feed: MSS 86-54 Leona Meyer Beyer Collection

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1707]
Source ticket: https://help.oac.cdlib.org/a/tickets/130823

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/1796

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_1796.atom

Root folder in Nuxeo:
asset-library/UCSF/MSS 86-54 Leona Mayer Bayer Correspondence

Merritt collection: NEW:
UCSF Library MSS 86-54 Leona Meyer Beyer Collection
ark:/13030/m5qs5zjg

**Comment by elopatin-uc3** [comment]
@mreyescdl the feeds for these new UCSF collections (tickets 1707 through 1711) are going to be manually generated by the PAD team. They'll let us know when they're ready.

**Comment by mreyescdl** [comment]
- Created script (production-MSS_86-54_Leona_Meyer_Beyer_Collection.csh)
- Ran manually (9 objects)
- Scheduled for weekly processing
- Checked code into repo

Complete

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl !
