### ISSUE TITLE
UCSF Nuxeo feed: MSS 83-9 Selma Fraiberg Papers

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1708]
Source ticket: https://help.oac.cdlib.org/a/tickets/130823

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/28064

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_28064.atom

Root folder in Nuxeo:
asset-library/UCSF/MSS 83-9 Selma Horwitz Fraiberg papers

Merritt collection: NEW:
UCSF Library MSS 83-9 Selma Fraiberg Papers
ark:/13030/m5m156s0

**Comment by mreyescdl** [comment]
- Created script (production-MSS_83-9_Selma_Fraiberg_Papers.csh)
- Ran manually (508 objects)
- Scheduled for weekly processing
- Checked into github

Complete
