### ISSUE TITLE
UCSF Nuxeo feed: MSS 2014-17 Helen Fahl Gofman Papers

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1709]
Source ticket: https://help.oac.cdlib.org/a/tickets/130823

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/28068

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_28068.atom

Root folder in Nuxeo:
asset-library/UCSF/MSS 2014-17 Helen Fahl Gofman Papers

Merritt collection: NEW:
UCSF Library MSS 2014-17 Helen Fahl Gofman Papers
ark:/13030/m50976pk

**Comment by mreyescdl** [comment]
- Created script (production-MSS_2014_17_Helen_Fahl_Gofman_Papers.csh)
- Ran manually (341 objects)
- Scheduled for weekly processing
- Checked into github

Complete
