### ISSUE TITLE
UCSF Nuxeo feed: MSS 83-18 Carol Hardgrove Papers

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1710]
Source ticket: https://help.oac.cdlib.org/a/tickets/130823

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/28044

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_28044.atom

Root folder in Nuxeo:
asset-library/UCSF/MSS 83-18 Carol Hardgrove Papers

Merritt collection: NEW:
UCSF Library MSS 83-18 Carol Hardgrove Papers
ark:/13030/m5vj6q7r

**Comment by mreyescdl** [comment]
- Created script (production-MSS_83-18_Carol_Hardgrove_Papers.csh)
- Ran manually (97 objects)
- Scheduled for weekly processing
- Checked into git repo

Complete
