### ISSUE TITLE
UCSF Nuxeo feed: MSS 89-67 Hulda Evelyn Thelander Papers

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1711]
Source ticket: https://help.oac.cdlib.org/a/tickets/130823

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/28040

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_28040.atom

Root folder in Nuxeo:
asset-library/UCSF/MSS 89-67 Hulda Evelyn Thelander papers

Merritt collection: NEW:
UCSF Library MSS 89-67 Hulda Evelyn Thelander Papers
ark:/13030/m5g84g0s

**Comment by mreyescdl** [comment]
- Created script (production-MSS_89-67_Hulda_Evelyn_Thelander_Papers.csh)
- Ran manually (80 objects)
- Scheduled for weekly processing
- Checked into git repo

Complete
