### ISSUE TITLE
Update maven plugins to current version

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1729]
Every plugin we use is out of date.

https://github.com/CDLUC3/mrt-doc-private/blob/main/docs/dependency_scans.md#maven-plugin

**Comment by elopatin-uc3** [comment]
See also, for maven update: https://github.com/CDLUC3/uc3sys/issues/55

**Comment by mreyescdl** [comment]
https://github.com/CDLUC3/mrt-core2/pull/42
