### ISSUE TITLE
UCR Nuxeo feed: University of California, Riverside student yearbooks 

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1736]
Source ticket: https://help.oac.cdlib.org/a/tickets/129981

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/26677

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_26677.atom

Root folder in Nuxeo:
/asset-library/UCR/SCUA/Bibliographic/Student Yearbook

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

**Comment by mreyescdl** [comment]
- Created script (production-UCR_Student_Yearbooks_collection.csh)
- Ran manually (22 objects)
- Checked into code repo
- Scheduled for weekly processing

Complete
