### ISSUE TITLE
UCR Nuxeo feed: University of California, Riverside, Citrus Research Center and Agricultural Experiment Station records 

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1737]
Source ticket: https://help.oac.cdlib.org/a/tickets/129981

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/27141

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27141.atom

Root folder in Nuxeo:
/asset-library/UCR/SCUA/Archival/UA042/published

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

**Comment by mreyescdl** [comment]
- Creates script (production-UCR_Citrus_Research_Center_Agricultural_Experiment_Station_collection.csh)
- Ran manually (93 objects)
- Checked into code repo
- Scheduled for weekly processing

Complete
