### ISSUE TITLE
UCR Nuxeo feed: University of California, Riverside, photographs 

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1738]
Source ticket: https://help.oac.cdlib.org/a/tickets/129981

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/23407

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_23407.atom

Root folder in Nuxeo:
/asset-library/UCR/SCUA/Archival/UA282/

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

**Comment by mreyescdl** [comment]
- Created script (production-UCR_Photographs_collection.csh)
- Ran manually (238 objects submitted)
- Scheduled for weekly processing
- Checked code into repo

Complete
