### ISSUE TITLE
UCR Nuxeo feed: University of California, Riverside, sound and video recordings 

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1739]
Source ticket: https://help.oac.cdlib.org/a/tickets/129981

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/27299

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27299.atom

Root folder in Nuxeo:
/asset-library/UCR/SCUA/Archival/UA373

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

**Comment by mreyescdl** [comment]
- Created script (production-UCR_Sound_and_Video_collection.csh)
- Ran manually (8 objects)
- Checked code into repo
- Scheduled for weekly processing

Complete
