### ISSUE TITLE
UCR Nuxeo feed: William B. Ellis papers 

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1740]
Source ticket: https://help.oac.cdlib.org/a/tickets/129981

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/27939

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27939.atom

Root folder in Nuxeo:
/asset-library/UCR/SCUA/Archival/MS347

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

**Comment by mreyescdl** [comment]
- Created script (create_atom_scripts_production.csh)
- Ran manually (19 objects)
- Checked into code repo
- Scheduled for weekly processing

Complete
