### ISSUE TITLE
UCI Nuxeo feed: Student Outreach and Retention (SOAR) Center records

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1755]
Source ticket: https://help.oac.cdlib.org/a/tickets/132540

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/28195

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_28195.atom

Root folder in Nuxeo:
asset-library/UCI/SCA_UniversityArchives/AS-233

Merritt collection: EXISTING:
UC Irvine SCA University Archives 
ark:/13030/m5bk6qsm

**Comment by mreyescdl** [comment]
- Created script (production-28195-UCI-Student_Outreach_Retention-uci_lib_sca_ua_content.csh)
- Ran manually (1 object)
- Checked into code repo
- Scheduled for weekly processing

Complete

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl !
