### ISSUE TITLE
Separation of stage and dev/demo environment

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#176]
Tests with handling Minio flip on stage environment have indicated that stage does not accurately represent the storage environment. Here are some basic problems:
1. the handling of an earlier migration of stage was viewed as an afterthought and a number of objects currently shown in the inv db are no longer in storage
2. with the removal of dev, stage became the primary location for testing local change before moving them to prod. In some cases testing involved trying out configurations that are not in prod - examples replication to non-prod storage nodes: public 5001-9001, private 9001-6001.

A test environment is essential and may not be completely possible on local machines because of firewall issues and the ability to link a modified module into a working microservice environment.

A stage environment is essential for providing an alpha/beta level changes into something similar enough to production to confirm both load and size limitations. Also, this environment should be used for external services needing something close to production (i.e. Dryad)

The use of docker may help with this model but it may be necessary to provide something before docker and it's use (i.e best practices) have been ironed out.

**Comment by elopatin-uc3** [comment]
Closing as Obsolete.
