### ISSUE TITLE
Switch Nagios check from /state to /jsonstatus?

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1768]
1/29/24 - David indicated that we should not yet do this because the state command can automatically bring a storage node back online after a period of temporary unavailability.

## Challenge
- `state` command can timeout, so it is a poor choice for the nagios check
- `jsonstatus` does not bring a node back online, but it has an efficient timeout process

## Options
- Run `state` command by cron independent of the Nagios check.  Switch Nagios to use `jsonstatus`
- Modify `jsonstatus` to be able to bring a node back online
- Switch Nagios to use `jsonstatus`.  Run `state` command as needed after a temporary outage (either manually or scripted)

**Comment by dloy** [comment]
Reviewing current process - suggest using the underlying timeout present in jsonstatus for doing state commands. This allows a timeout to occur and the existing reset option of state command to continue to work.  Easy to implement without impacting Nagios etc.
