### ISSUE TITLE
Determine if the merritt-docker dockerfiles can be built without the CDL maven repo

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#178]
I am going to revert the following commit and re-visit this when I have more time to focus on the issue.

https://github.com/CDLUC3/merritt-docker/commit/21336802724c8e51cc3976f9ccd55323df6813e6

"http://mvn.cdlib.org/content/repositories/" is referenced in several pom.xml files.

**Comment by terrywbrady** [comment]
@dloy shared the background on this issue.  This dependency was created in order to support the OAI service.  The jars were put in the private repo because it was unclear if these could be published publicly.

https://github.com/CDLUC3/merritt-docker/blob/01cdd7c97906efdb648cd1a307b86f1da9b0389d/mrt-dependencies/Dockerfile#L42-L46

Revisit this after fixing #390

**Comment by terrywbrady** [comment]
I was attempting to test merritt-docker in GitHub CodeSpaces before our trial runs out, but this issue became a blocker.

- lynecode dependencies - we could avoid this by not building OAI
- ingest, store, zoo, mrt-cloud, core2 have this dependency - we should break it or explain why it is needed
- there is some dependency on jargs 1.1.1 that does not exist at mvn central.  I hope we could work around this.

**Comment by elopatin-uc3** [comment]
Terry will set up a meeting with David and Mark to review dependencies in the Maven repo.
