### ISSUE TITLE
Resolve n2t url used in Merritt UI Stage

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1781]

**Comment by mreyescdl** [comment]
We now use the production EZID service to mint stage ARKs with "fake" shoulder (ark:/99999/fk4)
Production EZID registers this with the production resolver (n2t.net), not the stage (n2t-stg.n2t.net)

Note:  Merritt does have some data in the N2T stage resolver, but it is wither replicated in prod N2T or obsolete.

Let's change the Stage permalink to have the domain "n2t.net"
