### ISSUE TITLE
Bulk correct n2t entries that resolve to merritt-aws.cdlib.org

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1782]

**Comment by mreyescdl** [comment]
We need to switch the "target" of ARKs that are defined with a domain name of "merritt-aws.cdlib.org"
The new target will be "merritt.cdlib.org"

Jing can provide us with a list of ARKs that have the wrong Target, but it will be up to us to make the API calls.
The EZID API docs state that we can modify the Target as follows:
```
curl -u username:password -X POST -H 'Content-Type: text/plain'
  --data-binary '_target: url' https://ezid.cdlib.org/id/identifier
```

**Comment by mreyescdl** [comment]
The timeframe where we used a domain name ofmerritt-aws.cdlib.org is:
```
   Start: 2021-07-19 16:21:38 
   End: 2023-09-10 04:16:39
```

There are 1.27M arks created in this timeframe.

I'll create a one-time update script that will be used to iterate through the list.
We can then discuss with EZID folks on the update frequency.  We do not want to create any issues for them by taxing their service.

**Comment by terrywbrady** [comment]
I wonder what had us switch to merritt-aws in 2021.

**Comment by mreyescdl** [comment]
I think this was when by migrated from the original Amazon Linux to Amazon Linux 2.
We must have used the merritt-aws.cdlib.org CNAME to facilitate the migration.

When we go to Amazon Linux 2023 we should remember not to change the target for EZID.

**Comment by terrywbrady** [comment]
I understand that the target url is not an indexed field, but I am wondering if it would be possible to iterate over all records created between `2021-07-19 16:21:38` and `2023-09-10 04:16:39` perhaps in batches of 10K or 50K records and conditionally replace `merritt-aws.cdlib.org` with `merritt.cdlib.org`.  

While this would require some batch updating in SQL, would this proposed process be less taxing than submitting 1.3M API calls?

**Comment by sfisher** [comment]
I'm not sure what query interfaces EZID presents to find a target through the API, though I see the target url in the database in at least one table (`ezidapp_identifier`).

If nothing else, it seems like we could do a LIKE query to find these if it's not a readily available option from public interfaces.

I started looking at it, but stopped my query after it ran for about 10 seconds out of caution. It doesn't seem like that field is full-text indexed in MySQL which probably means it was doing a full scan and I don't want to monopolize the database.

It seems to me there are better solutions than submitting 1.3M api calls. If this is indeed the correct table, worst case, I could probably dump it to a local mysql, full-text  windex the field and then run the LIKE query which I assume could run quickly.

Jing may know better ways since I'm not all the familiar with EZID APIs and internals at this point.

**Comment by terrywbrady** [comment]
@sfisher , I have sometimes done things like this... iterating the start/end numbers with a script.

It can be tedious but it can prevent stressing out the database.

```
update table x
set foo='bar'
where foo like '%meow%'
and id >= 1001000 and id < 1002000
```

**Comment by datadavev** [comment]
@sfisher - what was the count of entries you have with target like `http://merritt-aws.cdlib.org`? A recent dump counts 1222050.

Note that with the current connection to n2t, it is necessary to use the API to perform the target update. Direct edits to the database would be risky. Unfortunately the update process would be pretty slow - with that number of entries and a script throttled to about 10/sec, you're looking at about 1.5 days.

**Comment by jsjiang** [comment]
@terrywbrady Thank you for providing the time frame for affected records. I assume these records are all under the Merritt user account, right?
The target url field is not indexed so querying the database to get the IDs is a little bit tricky. As you suggested, we can try small batched based on created time frame and user id. Once we get the list of IDs, updating the target urls still need to go through API to trigger updates to all related tables/fields.

Jing

**Comment by terrywbrady** [comment]
@sfisher , @jsjiang , @datadavev , thanks for the considering this.  We'll plan to move forward with the API calls.

I presume we know the list of records that likely need a change (based on creation date on our end).  Jing, these would all be from the Merritt account.  

We'll likely schedule the work to batch up API calls after the Dryad data has been removed from Merritt.  We'll plan to alert you all when we schedule the work.

@mreyescdl and @elopatin-uc3 , fyi.

**Comment by sfisher** [comment]
@terrywbrady I've updated and emailed you a list in CSV.

There are 1,085,951 under the merritt account with merritt-aws.cdlib.org in the target.

**Comment by jsjiang** [comment]
We will not update or save UC ARKs in N2T after the upcoming N2T migration. How about we hold off this batch update to after the N2T migration has completed to avoid unnecessary network and processing activities.

**Comment by mreyescdl** [comment]
I'm removing Dryad objects from list provided by Scott.
The Dryad ARKs will be tombstoned soon so there is no need to update Target.

**Comment by mreyescdl** [comment]
The scripts to modify the Target in EZID is set up on the production Batch host (uc3-mrtbatch01x2-prd.cdlib.org)
If this host is upgraded to AL2023 before executing, then we must ensure that we copy over the `/dpr2/tools` directory to the new host.

The scripts are located under the `dpr2` account at `/dpr2/tools/ezid_target/ezid_target/production`

**Comment by mreyescdl** [comment]
I will start batch processing of 1M+ requests after production patching on 8/6.
At a submission rate of 1 request every 2 seconds, it will take about 25 days to complete

**Comment by mreyescdl** [comment]
@elopatin-uc3 
Existing EZID records that we are to modify are double-encoded in the ark.
To confirm, we want to NOT have the arks encoded??

IS
_target: http://merritt-aws.cdlib.org/m/ark%253A%252F13030%252Fj22f7609

WANT
_target: http://merritt-aws.cdlib.org/m/ark:/13030/j22f7609

**Comment by elopatin-uc3** [comment]
Talked about this during the team meeting and decided to go without the double encoding.

**Comment by mreyescdl** [comment]
After testing, Merritt only supports single or double encoded ARKs in access URL
I'll provide single to EZID

**Comment by mreyescdl** [comment]
Stopped for patching.
Resubmitted 63 Gateway error objects

Added a pause feature to script.

730K left to process

**Comment by mreyescdl** [comment]
Update: 530K left to process

**Comment by elopatin-uc3** [comment]
~400K+ left to go

**Comment by mreyescdl** [comment]
300k+ left to process.
Paused processing in preparation for Production patching.
Batch host is exempt from patching.

**Comment by mreyescdl** [comment]
50k left to process

**Comment by mreyescdl** [comment]
Processing complete.
Total number of updated records: 1,085,951

**Comment by mreyescdl** [comment]
Outlier were reprocessed.
