### ISSUE TITLE
[RELEASE] Access - Disable X-Large EC2 Access Server based on Dryad Traffic

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1785]
# Overview of Release
Dryad no longer uses Merritt for its retrievals.  Thus, we no longer need 3 Access workers.  
We will remove the largest worker which is an X-large (uc3-mrtaccess02x2-prd)

# Service(s)
Access

# Github Issue Link(s)
https://github.com/CDLUC3/mrt-doc-private/issues/73

# Servers affected
uc3-mrtaccess02x2-prd

# Source Code
Not applicable 

# Source Code Tag
Not applicable 

# Jenkins/Build Info: (if applicable)
Not applicable 

# Deployment Steps (if applicable)
- Alter SSM variable "AccessQSize" from 10GB to 3GB
- Alter SSM variable "AccessLarge" from uc3-mrtaccess02x2-prd to uc3-mrtaccess03x2-prd and restart Tomcat on worker 03.
- Remove Access 02 from access ALB uc3-mrt-access-prd-alb
- Add node level Hiera file to control xlarge worker. Do not start consumer daemon (-DAccessDaemon=1)
- Restart Access workers

# Infrastructure Changes to support deployment (ALB, EFS, etc)
- Noted above

# Rollback Instructions
Rollback changes in deployment step

**Comment by mreyescdl** [comment]
Deployment complete.
Integration test passed.
