### ISSUE TITLE
Analyze/normalize Java API Paths

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1786]
## Paths in use

https://github.com/CDLUC3/mrt-admin-lambda/blob/main/src-colladmin/config/database.ssm.yml#L71-L111

- Inventory, Audit, Replic: path contains the service name
- Ingest, Store, Audit: path does not contain the service name

## Service to Service Configuration

- Merritt UI to Ingest ALB and Access ALB
  - https://github.com/CDLUC3/mrt-dashboard/blob/main/config/app_config.yml#L13-L24 
- Ingest to Storage ALB and Inventory ALB
  - https://github.com/CDLUC3/mrt-ingest/blob/main/ingest-conf/src/main/yaml/ingestConfig.yaml#L22-L25 
  - note that inventory has "mrtinv" embedded
- Inventory calls to Storage
  - https://github.com/CDLUC3/mrt-inventory/blob/main/inv-conf/src/main/yaml/inventoryConfig.yml#L4

## Ensure that the WAR file is always expanded  
- Storage and Access do not currently get expanded

### Option 1: Normalize API path to NOT include the service Name
- Pros: easier to remember
- Cons: would make it more difficult to co-locate 2 services on the same host
- Changes
- [ ] use ingest as a model of deployment for other services
- [ ] modify Audit, Replic, Inventory deployment to not include service path
- [ ] expand storage and access war on deployment
- [ ] modify SSM `ingest/config/localID`
- [ ] modify SSM `colladmin/inventory-service`
- [ ] modify documentation
- [ ] modify collection admin config
- [ ] check if collection admin invokes calls to replic
- [ ] Nagios change for Audit, Replic, Inv

### ~Option 2: Normalize API path to include service Name always~
- ~Pros: could co-locate services on the same host~
- ~Cons: more components to change, determine how to handle store and access~

**Comment by mreyescdl** [comment]
Update:
@ashleygould has deployed AL2023 stage workers
Workers for Ingest, Storage and Access now do not use service name in URL path e.g.
```
was: http://uc3-mrtstore-stg01:35121/mrtstore/state
is: http://uc3-mrtstore-stg01:35121/state
```

Audit, Replic and Inventory still use the service pathname in the URL. e.g,
```
http://uc3-mrtaudit-stg01:37001/mrtaudit/state
```

We'll need to add a "Context" line in the service file for these services
```
    server_xml_context: 'path="" docBase="<war file name>"'

uc3-mrt-audit-stg-2023.yaml
uc3-mrt-replic-stg-2023.yaml
uc3-mrt-inventory-stg-2023.yaml
```

After deployment, this will alter the endpoint that is used by Nagios, Admin Tool and Integration report and possibly the ALB health check for Inventory.
We'll need to update these client URLs

@ashleygould

**Comment by mreyescdl** [comment]
Note:  This is related to ticket https://github.com/CDLUC3/mrt-doc/issues/1793

When fixing the double deployment by adding the "deployOnStartup="false" to the server.xml we broke Audit/Replic and Inventory.   The above changes will address this issue.

**Comment by mreyescdl** [comment]
Puppet updates to allow "deploy on startup" a hierarchy parameter.  We have set it to false for all Tomcat services
Adjusted Hiera for all services to on create a ROOT/ web apps directory which will remove the service name from the API endpoint.

- Adjusted Start/Stop endpoint for Audit and Replic
- Modified the following SSM variables for new Inventory endpoint
```
/uc3/mrt/dev/integ-tests/for-stage/state-urls-lb
/uc3/mrt/stg/colladmin/inventory-service
/uc3/mrt/stg/ingest/config/localID
```
- Adjusting health check for Inventory ALB
- Adjusted Nagios check for Replic/Audit/Inventory


At this point all Tomcat endpoints should be unified in Stage

**Comment by mreyescdl** [comment]
Running Integration test...
Integration tests failed to retrieve "build.content.txt" data.

Need to update SSM
```
/uc3/mrt/dev/integ-tests/for-stage/state-urls
```

**Comment by mreyescdl** [comment]
Updated final SSM parameter and Integration test now pass

```
95 examples, 0 failures, 3 pending
```
