### ISSUE TITLE
[INGEST] Move Ingest profiles from local disk to ZFS

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#1787]
Ingest profiles are housed in a private repo on Github and cloned on Ingest worker's local disk
```
https://github.com/cdlib/mrt-ingest-profile
```

Every worker must run a cron to sync with repo.  Moving profiles to ZFS will simplify syncing.  An additional benefit is that when bootstrapping a new Ingest host, cloning is not needed to be performed by Puppet.

Currently we only use ZFS as a work area for Ingest, called the "queue"
```
$ ls -ld /dpr2/ingest_home/*
drwxrwxr-x 5 dpr2 dpr2 20480 Dec 20 11:45 /dpr2/ingest_home/profiles
lrwxrwxrwx 1 dpr2 dpr2    38 Aug 11  2022 /dpr2/ingest_home/queue -> /apps/ingest-stg-zfs/ingest_home/queue
```

**Comment by elopatin-uc3** [comment]
@elopatin-uc3 to set up time to discuss further.
