### ISSUE TITLE
Reconcile Storage Bytes Added with OpenSearch Log Byte Counts from Storage Logs

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1790]
## Billing Database Values: 7TB

<img width="1139" alt="image" src="https://github.com/CDLUC3/mrt-doc/assets/1111057/dedfc46b-d3d3-4f0c-be8d-4fbbf20b6897">

## OpenSearch Logs Same Approx Dates: 16TB

_I presume replication is not included in these reports._

<img width="1623" alt="image" src="https://github.com/CDLUC3/mrt-doc/assets/1111057/c3dd2e83-4e09-4394-8d4c-e8c4a86b7666">

**Comment by dloy** [comment]
A review of both Storage logging indicates:
- storage logs return full version content size instead of bytes added to S3 for a version - combining multiple versions add redundant content sizes

Action: change to only return add S3 content for a version
