### ISSUE TITLE
[Tomcat - AL2023] Double deployment of services

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#1793]
The recent Tomcat 9 deployment on the new AL2023 hosts have services double deployed.
That is, two instances of the application are running.

Looking at the webapps directory shows both ROOT/ and service/ directories.
Each is an instance of deployment.  For example, for Storage:

```
drwxr-xr-x. 5 dpr2store dpr2store     4096 Feb 14 08:53 ROOT
drwxr-xr-x. 2 dpr2store dpr2store     4096 Feb  2 14:59 storage
-rw-r--r--. 1 dpr2store dpr2store 39086211 Feb  2 14:57 storage.war
```

**Comment by mreyescdl** [comment]
I think the following server.xml property change fixes the issue

Was:
```
            unpackWARs="true" autoDeploy="false">
```

is:
```
            unpackWARs="true" autoDeploy="false" deployOnStartup="false">
```

**Comment by mreyescdl** [comment]
The above works for all services that require a "Context" field (Storage, Access and Ingest)
It does not work for other services.
I suggest that we use the Context field for all services do unify the web apps directory
With this, the webapps will contain only:
```
ROOT/
service.war
```
The URL pathname will not contain the service.

**Comment by dloy** [comment]
The following are a few "areas" that will require changes when service urls drop the war name as part of the request. This will occur with tomcat normalization.

Services impacted:
 - inv - /mrtinv/
- audit - /mrtaudit/
- replic - /mrtreplic/

This is not a comprehensive list!

### admin tool
- scan
- replic retry
- audit retry
- ...

### capistrano
- pause (audit, replic)
- shutdown (inv)
- zoohold (inv)

### admin shell
- delete

### nagios
- everything except access and store

### ssm
- inv
