### ISSUE TITLE
Support large objects and more concurrent access

### ISSUE THREAD

**Issue by dmolesUC** [CDLUC3/mrt-doc#18]
We want to be able to handle very very large objects -- currently 500 GB is
hard, 1 TB can't be downloaded; 10 TB is nearly impossible. We also want to
be able to handle the volume of requests/submissions we'd get if we could
provide libraries with free storage.

Issues include:

- factors out of our control on the submitter's side
- local copies for ingest, storage, audit & replication
- lack of scalability testing / load testing
- ????

## Questions/Action Items

- don't make local copies
- look at [Dat](http://datproject.org/) and/or other alternatives to straight HTTP
  for large file transfers
- support incremental deposit w/o "versioning"
- scalability/load testing (UI, Ingest, …?)
- other issues?

**Comment by dloy** [comment]
Comment:
Local copy is required especially if multiple simultaneous segment uploads are being used.

Our current system is build around object versioning where object has one or more files. Any update to a file in the object is an update to the object: a new object version. 

All files are saved to a cloud using the key: <ark>|<version>|<file path> A specific version of a file is saved only once. The object manifest file is used to unravel the relation of a file to it's inclusion in an object.

**Comment by dloy** [comment]
Cloud Key format: ark | version number | file path
