### ISSUE TITLE
Experiment with serializing ingest queue jobs as json rather than using java property serialization

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1802]
https://github.com/CDLUC3/mrt-ingest/blob/main/ingest-src/src/main/java/org/cdlib/mrt/ingest/QueueEntryState.java

https://docs.oracle.com/javase/8/docs/technotes/guides/serialization/index.html

**Comment by mreyescdl** [comment]
Ingest ZK queue data now in JSON format on stage.
No changes were made to the ZK library thought the Item.toString() method will now fail.
With JSON data, we do not need or used this method.  Let's schedule for deprecation.
