### ISSUE TITLE
Clean Up Project Board Views

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1817]
## Recommended Views
- By Sprint
- Category and Sprint
- Ops and Releases

## Keep for Investigation/Triage of Tickets
- No Sprint
- Recurring
- Releases

## Delete -  Use Category and Sprint instead
- By project
- Storage Admin
- Maintenance
- Ingest Priority
- Preservation Practices
- Tickets 

## Delete - Use By Sprint Instead
- David
- Mark
- Terry
- Eric

## Delete - Use Ops and Releases instead
- PAD

## Question
- Do we need an additional Category View that includes closed tickets?

**Comment by terrywbrady** [comment]
Fyi, I continued the ticket review that we had started last week and I linked a category to every open ticket/item on the board.  Hopefully, this will make the new slices more useful.  In that process, I did need to add a handful of new categories.  We can review those and decide if any need to be renamed or collapsed.

**Comment by elopatin-uc3** [comment]
I deleted most views as recommended, but kept the By Project (now sliced and renamed to Categories) and Tickets views. The latter is there simply to have another place to search for any ticket. I also added a Closed by Category view, which is now next to the Categories view. We may want to combine these two in the future.
