### ISSUE TITLE
Place untracked Docker assets into private repo to ensure replicability for other users

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#183]
Staff would overlay these files into cdluc3/merritt-docker.

```
DL-TBRADY-9M:mrt-services tbrady$ find no-track/ -type f | grep -v "/log/" | grep -v "/0="
no-track//store-info.txt
no-track//nodes/repository/node9001Distributed/can-info.txt
no-track//nodes/repository/node9502SDSCMinio/can-info.txt
no-track//nodes/nodes.txt
no-track//database-stg.yml
no-track//pom.xml
no-track//README.md
no-track//ldap-stg.yml
no-track//ingest-info.txt
```

Could this go into a new folder in mrt-conf-prv?

**Comment by terrywbrady** [comment]
Private repo exists.  

https://github.com/cdlib/merritt-docker-prv

It would be good to verify that this works for another member of the team.

**Comment by elopatin-uc3** [comment]
@terrywbrady at the moment I can't access this repo. Perhaps @dloy or @mreyescdl can?

**Comment by terrywbrady** [comment]
Thanks @elopatin-uc3 .  I gave the UC3 team Admin rights to the repo.
