### ISSUE TITLE
[RELEASE] BOM 1.7

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#1836]
__In Process__

# Overview of Release
- See [BOM 1.7 to fix - 1823](https://github.com/CDLUC3/mrt-doc/issues/1823)

# Service(s)
- Storage - tag 1.7.15
- Access - tag 1.7.15
- Inventory - tag 1.7.3
- Audit - tag 1.7.8
- Replic - tag 1.7.7

# Github Issue Link(s)
[BOM 1.7 to fix - 1823](https://github.com/CDLUC3/mrt-doc/issues/1823)

# Servers affected
## Stage
uc3-mrtstore01x2-stg
uc3-mrtstore02x2-stg

uc3-mrtaccess01x2-stg
uc3-mrtaccess02x2-stg

uc3-mrtinv01x2-stg
uc3-mrtinv02x2-stg

uc3-mrtaudit01x2-stg
uc3-mrtaudit02x2-stg

uc3-mrtreplic01x2-stg
uc3-mrtreplic02x2-stg

## Prod
uc3-mrtstore05x2-prd
uc3-mrtstore06x2-prd

uc3-mrtaccess01x2-prd
uc3-mrtaccess02x2-prd

uc3-mrtinv01x2-prd
uc3-mrtinv02x2-prd

uc3-mrtaudit01x2-prd
uc3-mrtaudit02x2-prd
uc3-mrtaudit03x2-prd
uc3-mrtaudit04x2-prd

uc3-mrtreplic01x2-prd
uc3-mrtreplic02x2-prd

# Source Code:
## mrt-core2
- https://github.com/CDLUC3/mrt-core2/commit/9734fdc0632d725ac8da6a3f00dcc01b594c95f6

# Jenkins/Build Info: (if applicable)
- Inventory
https://builds.cdlib.org/view/New%20Build%20Config/job/Merritt_Build_Config/199/console

- Audit
https://builds.cdlib.org/view/New%20Build%20Config/job/Merritt_Build_Config/198/console

- Store/Access
https://builds.cdlib.org/view/New%20Build%20Config/job/Merritt_Build_Config/197/console

- Replic
https://builds.cdlib.org/view/New%20Build%20Config/job/Merritt_Build_Config/200/console

# Deployment Steps (if applicable)
- [ ] [Puppet changes for support of appropriate microservice tag](https://github.com/CDLUC3/uc3-ops-puppet-hiera/tree/main/fqsn-os)

# Infrastructure Changes to support deployment (ALB, EFS, etc)

# Rollback Instructions

**Comment by mreyescdl** [comment]
Ingest production is already using the new Common Compress file:

commons-compress-1.26.0.jar
