### ISSUE TITLE
IDE Usage for Merritt Repos

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#185]
## Eclipse Setup Instructions

https://confluence.ucop.edu/display/UC3/Eclipse+Setup+for+Merritt+Repos

## Repository Preparation
- Libraries
  - [x] mrt-core2: https://github.com/CDLUC3/mrt-core2/pull/3
  - [x] cdl-zk-queue: https://github.com/CDLUC3/cdl-zk-queue/pull/1
  - [x] mrt-zoo: https://github.com/CDLUC3/mrt-zoo/pull/1
  - [x] mrt-cloud: https://github.com/CDLUC3/mrt-cloud/pull/1
- Services
  - [x] mrt-ingest: https://github.com/CDLUC3/mrt-ingest/pull/5
  - [x] mrt-inventory: https://github.com/CDLUC3/mrt-inventory/pull/1
  - [x] mrt-store: https://github.com/CDLUC3/mrt-store/pull/3
  - [x] mrt-replic: https://github.com/CDLUC3/mrt-replic/pull/2
  - [x] mrt-audit: https://github.com/CDLUC3/mrt-audit/pull/1
  - [x] mrt-oai: https://github.com/CDLUC3/mrt-oai/pull/1
  - [x] mrt-sword: https://github.com/CDLUC3/mrt-sword/pull/2

## Other Issues (whitespace, line endings, formatting)

- What whitespace practices do we have in place
  - preserve whitespace exactly as in the repo
  - consolidate to a specific standard
  - do whatever works (git diffs may show extra changes)
- What line ending practices do we have in place?
  - Does David ever edit files on his PC?

**Comment by terrywbrady** [comment]
@elopatin-uc3 , since this does not require deployment, should I move it to done?

**Comment by elopatin-uc3** [comment]
Yes, please move it to done. Thanks @terrywbrady
