### ISSUE TITLE
Unable to reach the collection admin object submission page in Coll Admin

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1863]
In Coll Admin, attempting to navigate to the Submit Merritt Collection Admin Obj page results in an error, "no time information".

In console, two messages are shown:
```
GET https://merritt-colladmin.cdlib.org/web/collAdminObjs.html?type=collection 500 (Internal Server Error)
```
```
Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
```

Steps to reproduce:
01 Visit https://merritt-admintool.cdlib.org/web/index.html#.nav_manage_coll;.bp_ingest
02 Click the "Submit Merritt Collection Admin Obj" link

Result:
- In the browser window, the message, "no time information" is displayed.
- Console shows the above error messages

Note: 
In step 01, the console shows the following (unsure if this is related):
```
sorttable.js:47 Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at Object.makeSortable (sorttable.js:47:11)
    at VM382 sorttable.js:36:19
    at Array.forEach (VM382 sorttable.js:454:10)
    at forEach (sorttable.js:493:11)
    at HTMLDocument.init (VM382 sorttable.js:34:5)
```

**Comment by terrywbrady** [comment]
https://github.com/CDLUC3/mrt-admin-lambda/commit/58135616fec75c41dd28be0a7bb7fdd7f887f878

**Comment by elopatin-uc3** [comment]
Working as expected now in production. Thanks @terrywbrady
