### ISSUE TITLE
Release – Production ALB change for Merritt Inventory

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#187]
### Tasks
- [ ] ALB target change to point to Merritt Inventory servers

The production ALB for inv is:
  inv-aws.cdlib.org:36221

points to the 2 severs:
  uc3-mrtinv-prd.cdlib.org:36221
  uc3-mrtinv2-prd.cdlib.org:36221

The targets of this ALB needs to be changed to:
  uc3-mrtinv-prd.cdlib.org:36121
  uc3-mrtinv2-prd.cdlib.org:36121

(e.g. port change on target from 36221 to 36121)

Using the following health checks - returns 200 status for up server
curl http://uc3-mrtinv-prd.cdlib.org:36121/mrtinv/state?t=xml
curl http://uc3-mrtinv2-prd.cdlib.org:36121/mrtinv/state?t=xml

The stage cdlsys for a request identifying this problem was: Issue 13233

#### Services:
mrt-inv – Merritt Inventory

#### Servers:
Production:
uc3-mrtinv-prd.cdlib.org
uc3-mrtinv2-prd.cdlib.org

#### Change description
This change directs the load balancer request from a failing front-end Apache server, directly to the Merritt inventory service on these target hosts. This change is needed to optimize Merritt Express requests for large objects.

#### Infrastructure Changes to support software (ALB, EFS, etc) 
CDL-SYS ticket submitted:
- Modification to production ALB, inv-aws.cdlib.org

#### Github Issues:
https://github.com/CDLUC3/mrt-doc/issues/171

**Comment by dloy** [comment]
Correct:
The production ALB for inv is:
inv-aws.cdlib.org:36221

to

The production ALB for inv is:
inventory.cdlib.org:36221

This corresponds to the named ALB:
inventory.cdlib.org => internal-uc3-mrtinv-prd-alb-2113176972.us-west-2.elb.amazonaws.com
(from Debra)
