### ISSUE TITLE
Release - Deploy new inventory service code to support db versions / Express update to support this change

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#188]
## Release inventory redeploy - file level versions

Install new inventory service code to support file level information for accessing data files: ark, version number, file path.

This release is specific to moving the inv source code to the production inv servers.

### Steps
- Build Jenkins production war for mrt-inv
- Drain ALB for specific server to be updated
- Do capistrano update for specific server
- Reconnect server on ALB
- Test sepecific server

### Redeploy production servers
uc3-mrtinv-prd.cdlib.org

uc3-mrtinv2-prd.cdlib.org

uc3-mrtexpressx2-prd-2a

uc3-mrtexpressx2-prd-2c

### Source code changes
**Github**: Fix quote handling: https://github.com/CDLUC3/mrt-inventory/commit/a74d942521a25a6edc0897b2d60a87a4800a4d90

**Github**: Support file level versions: https://github.com/CDLUC3/mrt-inventory/commit/d38f57bd23687cfb37d9cdc9754f162029e81d7d

**Github**: private IAS github repo.  redirect.rb is an Apache redirect program and it will now request specific file manifest instead of large object manifest

### Jenkins Build
http://builds.cdlib.org/job/mrt-build-inv/48/console

### Issue trackers:
[Prototype alternative method for file location handoff to Express #171](https://github.com/CDLUC3/mrt-doc/issues/171)
https://github.com/CDLUC3/mrt-doc/issues/189

**Comment by dloy** [comment]
2:34 p.m. redeploy complete - inventory reset in progress

Test curl:
curl http://uc3-mrtinv-prd.cdlib.org:36121/mrtinv/versions/ark%3A%2F13030%2Fm5dv6mr9/1/producer%2FNormal-%E8%A3%82%E9%9A%99%E7%81%AF2.jpg?t=xml

**Comment by mreyescdl** [comment]
Both Linux 2 Express workers upgraded and redeployed.
