### ISSUE TITLE
Download obsolete items report and note the owners and collections that should be deleted

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1891]
https://merritt-admintool.cdlib.org/web/index.html?path=obsolete

**Comment by elopatin-uc3** [comment]
@elopatin-uc3 will review the list of collections to determine which ones should have their content removed; note collections for removal as well

**Comment by elopatin-uc3** [comment]
See mrt-doc-private #105 for Stage and Production collections and owners to clean up. 

Note that Production Dash collections are not mentioned here. 
Removal of these are tracked in:
https://github.com/CDLUC3/mrt-doc/issues/1560

One object in the UCB Dash collection is not present in Dryad:
https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm5993v7w
