### ISSUE TITLE
Make Merritt more affordable

### ISSUE THREAD

**Issue by dmolesUC** [CDLUC3/mrt-doc#19]
Cost is a barrier to Merritt adoption for campuses, and particularly for
libraries, leading to bad preservation decisions.

We've seen some outside interest in providing free storage for open
research data but little to none for library data, esp. dark archives.

## Questions/Action Items

- why are outside providers interested in free storage for research data, but
  not for libraries?
- what can we do to bring on-line storage costs down?
  - SDSC QF2 / Minio: ca. $70/TB/year (projected)
  - [Backblaze B2](https://www.backblaze.com/b2/cloud-storage-pricing.html): $60/TB/year
- what can we do to bring dark-archive storage costs down?
  - [Glacier](https://aws.amazon.com/glacier/pricing/): $48/TB/year
  - [IBM Regional Cold Vault](https://www.ibm.com/cloud-computing/bluemix/pricing-object-storage): $72/TB/year
  - [Oracle Archive Storage](https://cloud.oracle.com/storage/pricing): $32/TB/year
  - SDSC QF2 / Minio: ca. $70/TB/year (projected)

**Comment by dloy** [comment]
Comment:
Any data migration should be looked at in terms of risk to successfully performing the migration and integrating that migration into all existing services (audit, replication, inv).

Any new remote storage should be viewed with lots of skepticism that they are really doing what they claim - especially levels of preservation.

Dark archives are dangerous for preservation especially in an OAIS model. Costs for fixity validation are prohibitive. There is a general assumption that the remote service (e.g. Glacier) has done the right thing. This content is not immediately available.

**Comment by marisastrong** [comment]
[SDSC Qumulo/Minio call notes](https://docs.google.com/document/d/11XwJeWMlcjibv-HbnAfT0A9aeU-6Rpb3HUjSosQrwsQ/edit)
