### ISSUE TITLE
Interim EFS staging volume - define the request

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1901]
This is a subset of what we have defined in https://github.com/CDLUC3/mrt-doc/issues/1767

## Needs
- Store content to be sent to ingest
- Mounted to ingest and to DEV boxes
- Not mounted to storage

## TBD
- How much space? (Eric)
  - or should we choose a completely dynamic/elastic filesystem type? 
- Preferred file system type? (Ashley and Mark)

**Comment by elopatin-uc3** [comment]
I would vote for a relatively low bandwidth, elastic file system type. If we instead opt for a volume with a specific capacity, 2TB would likely be sufficient.

**Comment by elopatin-uc3** [comment]
@elopatin-uc3 Will set up a separate meeting for this. For reference:
https://github.com/CDLUC3/mrt-doc/tree/main/design/content-ingest-2024
