### ISSUE TITLE
EZID is now high-availability - reconsider Thursday AM pause?

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1914]
Discussion item from 5/20 dev coffee

Why do we pause?
- [ ] ezid
- [ ] rds downtime
- [ ] zfs downtime
- [ ] other???

**Comment by elopatin-uc3** [comment]
We're considering increasing the duration of the pause in order to handle daylight savings. Decide on final time window: 

Decision: 4-6am

RDS maintenance window:
rds-uc3-ezid5-prd | Thu:05:00-Thu:05:30 |

@elopatin-uc3 to add note to user docs regarding the pause.

**Comment by mreyescdl** [comment]
All Ingest workers were pausing the queue from 4:30-6 on Thursday AM.
I increased the window from 4-6 and now only Ingest 01 does the work.
