### ISSUE TITLE
Socket timeout - uc3-mrtinv-prd01

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#1921]
~~~
Notification Type: PROBLEM

Service: uc3-mrt-inventory-prd_state_7x16
Host: uc3-mrtinv-prd01
Address: uc3-mrtinv-prd01.cdlib.org
State: CRITICAL

Date/Time: Thu May 23 09:39:11 PDT 2024

Additional Info:
CRITICAL - Socket timeout
~~~

ACK investigating 

Investigation showed no exceptions during time frame on catalina.out for uc3-mrtinv-prd01

Potential ALB issue caused Alert. Suggestion to investigate ALB logs

~~~
Notification Type: RECOVERY

Service: uc3-mrt-inventory-prd_state_7x16
Host: uc3-mrtinv-prd01
Address: uc3-mrtinv-prd01.cdlib.org
State: OK

Date/Time: Thu May 23 09:49:11 PDT 2024

Additional Info:
HTTP OK: Status line output matched HTTP/1.1 200 - 986 bytes in 0.038 second response time
~~~

**Comment by mreyescdl** [comment]
Ashley says that Nagios talks directly to Inventory workers.  This takes ALB out of the equation.
We looked at Librato and saw no issues with the Inventory workers.

Could be a latency issue.  Or network.
Closing issue for now.
