### ISSUE TITLE
Create Nagios check that's triggered if Inventory doesn't start fully

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#194]
### Summary
Merritt microservices are restarted after each round of security patching. During two recent patching cycles, it was found that the Inventory service did not start up fully. This has the effect of leaving jobs that are ready to be processed, in a hanging state, and can negatively impact dependent services such as Dryad.

- [x] Ensure a Nagios check exists, which can alert us if Inventory is not fully running.

**Comment by mreyescdl** [comment]
uc3-mrtinv-stg has a second Nagios check for the string "invsv:systemStatus>running<"
Checking with David to see if this is all we need for notification

**Comment by mreyescdl** [comment]
Extra checks have been enabled on the both prod hosts and request for Nagios submitted to IAS...

Can you add an additional check for Inventory service which will notify if
the service is not fully operational?  We have done this for stage and would like to
do so for production now.

The following URLs will return a http response of 200 and a message body of "OK"

Host: uc3-mrtinv-prd.cdlib.org
URL:  http://uc3-mrtinv-prd.cdlib.org:8888/http_check_mrt_inv_layer2.ok

Host: uc3-mrtinv2-prd.cdlib.org
URL:  http://uc3-mrtinv2-prd.cdlib.org:8888/http_check_mrt_inv_layer2.ok

**Comment by mreyescdl** [comment]
Also, here is the old Pivotal tix for this
https://www.pivotaltracker.com/n/projects/386181/stories/154147705

**Comment by mreyescdl** [comment]
Nags check is in place on both production hosts

**Comment by mreyescdl** [comment]
Nagios check in place for both production hosts
