### ISSUE TITLE
Ensure Dryad tombstone in EZID

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1995]
See also: https://github.com/CDLUC3/mrt-doc-private/issues/71

**Comment by elopatin-uc3** [comment]
Adding Mark's comments from #71:

[mreyescdl](https://github.com/mreyescdl) commented [last week](https://github.com/CDLUC3/mrt-doc-private/issues/71#issuecomment-2270084620)
Ready to start script to Tombstone Dryad EZID records.
77K requests at 10 second interval will require about 9 days to complete.
Will launch after Tuesday 8/6 production patching.

Launching from uc3-mrtstore-stg02:/dpr2store/admin/deletestg/TombstoneDryadArks

mreyescdl commented [2 hours ago](https://github.com/CDLUC3/mrt-doc-private/issues/71#issuecomment-2286704513), 8/13:
Launched script Monday PM. Expect completion Friday PM
Rate is 12/minute

As of Tuesday 12K EZID records updated with no errors.

**Comment by mreyescdl** [comment]
Update on Dryad Tombstone
28K completed with 3 "Bad Gateway" errors.
```
https://ezid.cdlib.org/id/ark:/13030/m54r2v9b
https://ezid.cdlib.org/id/ark:/13030/m54r4npj
https://ezid.cdlib.org/id/ark:/13030/m55250dw
```
