### ISSUE TITLE
Miscellaneous Ingest questions

### ISSUE THREAD

**Issue by dmolesUC** [CDLUC3/mrt-doc#20]
1. if we stop making local copies, what else do we need to do to stop locking
   jobs to ingest servers?
2. what would we need to do to ingest and inventory to support ingesting
   multiple versions of the same object out of order? (simplifying
   assumption: the start of each ingest job is ordered correctly by
   version, it's the finish that isn't, e.g. when the first version is
   large and subsequent versions are small)

**Comment by dmolesUC3** [comment]
3. why does Ingest get stuck in a state where we have to manually restart it? ⚽️

**Comment by cpwillett** [comment]
I'm not sure what you mean about restarting ingest--do you mean inventory? Inventory on dev and stage seem to fail silently, and we still don't have a monitor that can tell us when it's down.

**Comment by dmolesUC3** [comment]
Oops, yes, I meant inventory. I'll add that as a separate issue.
