### ISSUE TITLE
GUEST login has no collections for merritt.cdlib.org

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#2010]
![Image](https://github.com/user-attachments/assets/cc0725f6-cf4e-42f8-bd0c-82d30ee712fd)

**Comment by elopatin-uc3** [comment]
Related to: 1) Upcoming accessibility audits, which will occur with or without public collections. 2) Past efforts to contact owners of remaining public collection content have gone unanswered or stalled.

End to end test that browses after Guest login is triggered will be disabled. Guest login button will continue to be tested.
