### ISSUE TITLE
[RELEASE] mrt-ui gem updates - 8/27

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#2014]
# Overview of Release
gem updates
# Service(s)
ui
# Github Issue Link(s)

# Servers affected
ui01, ui02, ui03
# Source Code:
Link(s) to tagged release(s)

# Source Code Tag

# Jenkins/Build Info: (if applicable)

# Deployment Steps (if applicable)
- [ ] deploy 1.6.2

# Infrastructure Changes to support deployment (ALB, EFS, etc)

# Rollback Instructions
- rollback to 1.6.0

**Comment by terrywbrady** [comment]
@elopatin-uc3 , it looks like this did not get closed

**Comment by elopatin-uc3** [comment]
Thanks @terrywbrady , I just added this to the releases page and will close.
