### ISSUE TITLE
stage cleanup script to be run weekly

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#2021]
As we ramp up data load testing in stage, David offered to script a weekly cleanup for 3 STAGE collections

- merritt_benchmark
- cdl_wasabi
- merritt_demo

We will completely purge the content in each of these 3 collections on a weekly basis to prevent an accumulation of storage costs.

**Comment by dloy** [comment]
## Issue
A large amount of end-to-end regression tests will be run on stage to: 
- push usage on stage to something close to production. This will better replicate the fail conditions that do not normally show upr with the light lode normally seen on these servers
- allow testing of more regression content for unusual but occurring content in production.

These tests will generate a large amount of content that will require periodic and on-going deletion.

## Discussion
### Collection
Specific content collection(s) used for this content:
- guarantee that non-load content is protected
- allow differentiation for secondary services:
  - replic - control external duplication of this content
  - audit - specifically identify to possibly bypass audit of this content

### Frequency
This content will most likely be created on an ongoing basis (e.g. triggered daily or more frequently)

Deletion should occur regularly to prevent content of a certain age from remaining on the system.

### Validations
Validation checks to confirm that content has successfully been removed form both storage and inv db is critical

## Implementation
### Steps
- periodic cron job will run and trigger the deletion process
- identify the content to be written by noting all inv db content remaining after a specific date (collection will help in this process)
- ark lists for deletion will be automatically saved as delete ark lists used in deletion process
- background deletions will be run preserving pid
  - multiple deletions can be run concurrently if needed - may require tweaking to prevent overlap of content
  - tuning will be critical
- use inv_tasks to confirm completion of run

__Note__ this process should self correct if deletion is failed.

### Manual confirmation
- This should only (hopefully) be required while this process is tuned
-
