### ISSUE TITLE
UCI Nuxeo feed: Ways of Being: The Black Experience on the UC Irvine Campus

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#2028]
Source ticket: https://help.oac.cdlib.org/a/tickets/143733
https://cdl.freshdesk.com/a/tickets/144100

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/28309/

ATOM feed:
https://pad-nuxeo.s3.us-west-2.amazonaws.com/nuxeo_merritt/atom_feeds/ucldc_collection_28309.atom

Root folder in Nuxeo:
asset-library/UCI/SCA_UniversityArchives/AS-239/For Merritt

Merritt collection: EXISTING:
UC Irvine SCA University Archives
ark:/13030/m5bk6qsm

**Comment by elopatin-uc3** [comment]
Feed is not yet ready

**Comment by elopatin-uc3** [comment]
Script should be updated with new ATOM feed URL noted above

**Comment by mreyescdl** [comment]
Created script: production-28309-UCI-Black-Experience-uci_lib_sca_ua_content.csh
Ran manually: 1 object
Added to weekly processing
