### ISSUE TITLE
Production steps flip swift to minio

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#204]
# Swift to Minio Flip - Stage and Production
These are the steps need for phase 1 flip of migrating Merritt from using SDSC Swift content to Minio.

With this process:
* Dryad will remain fully functional. Sword issues ingest requests through sword (no freeze). No db changes will occur to impact Dryad data.
* During process no updates to Merritt will take place

Time:
* Completion of activity on ingest after freeze (2-3 hours)?
* Flip - 2 hours
## Steps
* Extension
* Shutdown all new changes swift
* Flip
* Restart
## Extension (hopeful)
- [x] (Marisa) See if we can get an extension to (preferred) end February (OK) mid-February

This will help get better confirmation things are working. Current hope is flip last week Jan.
## Shutdown all new changes swift
Requires that all swift changes have completed on system 
- [x] (Eric) Request to block large non-Dryad submissions
- [ ] (Mark) Pause Puppet on uc3-etdx2-prd and comment out ETDs crons
- [ ] (Mark) Pause ingest
This will need to be done maybe 2 hours before flip to guarantee that no non-Dryad processing is taking place.

Mark confirmed that queued profiles do not contain node info - this allows for a soft flip as opposed to a hard flip that requires more elements of Merritt to be down.
- [ ] (David) Confirmation that all ingest complete through replication
This requires running tests to guarantee that all swift content has been replicated to minio
- [ ] (Mark) Shutdown monitors
* Monitors for replication
* Monitors for inventory
- [ ] (Debra) Database checkpoint issued
This step needs to be confirmed with IAS
- [ ] (David) Shutdown replication
This is to guarantee no further caching of changes
## Flip
- [ ] (David) build new inv_nodes_inv_objects table.
* replace all primary swift with primary minio
* replace all secondary swift with secondary minio
* retain all non-swift
* add secondary for all swift (phase 1)
- [ ] (David) confirm alternate nodes_objects tables are accurate
- [ ] (David) build new inv_collections_inv_nodes table.
This:
* retains non-swift
* replaces as secondary swift with minio
* retains all swift as secondary to continue preserving content
- [ ] (David) confirm new inv_nodes_inv_objects table.
- [ ] (David) confirm new inv_collections_inv_nodes table.
- [ ] (Mark) flips ingest profiles
## Restart
- [ ] (David) restart replication
- [ ] (Mark) server restarts on inventory
This is to guarantee no db caching. Also it will force inv to work with latest Minio content moving forward
### (Mark,David) _?test ingest flip_
Not clear if this can be done with frozen ingest
Includes:
- [ ] (Mark) - add new archive content (Minio)
- [ ] (David) - confirm inv updated inv_nodes_inv_objects
- [ ] (David) - confirm replication of minio content to glacier
- [ ] (Mark) - add new public content (AWS)
- [ ] (David) confirm inv updated
- [ ] (David) - confirm replication of AWS content to both minio
- [ ] (David) - confirm replication of AWS content to swift (phase 1)
- [ ] (Mark) unfreeze ingest
- [ ] (Mark) restore (or use timeout) monitors

# Profile Node Flip
## Stage
Swift 2111, 9901, 9001 
to
Minio 9502
## Prod
Swift 9103, 9001
to
Minio 9501

# Issues to resolve
- [ ] (David) rename on tables will work for flip - confirmed with Debra
- [ ] (David) Aim for 1/15 for stage
- [ ] (David) Aim for 1/22 for prod
- [ ] (David) Use slack for communication on change with Debra
- [ ] (David) Do db checkpoint either before or after table creations but before rename
- [ ] (David) Joe is modifying machine types on RDS - we need to make sure of his process
- [ ] (David) cdlsys ticket needed with calendar set

**Comment by marisastrong** [comment]
SDSC can extend content in Swift for $1500/month.  If we don't pay fee, we could possibly stll access content, would need to work with SDSC on this.  We will know more definitively after the flip if we will need it and will decide then
