### ISSUE TITLE
Button for submitting a Collection, Owner or SLA admin object should indicate it has been triggered

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#2040]
Currently the button used to submit an admin object on these pages (in the Actions column) does not deactivate and turn gray if clicked:

https://merritt-colladmin.cdlib.org/web/collAdminObjs.html?type=collection
https://merritt-colladmin.cdlib.org/web/collAdminObjs.html?type=owner
https://merritt-colladmin.cdlib.org/web/collAdminObjs.html?type=sla

This makes it easy to accidentally submit two admin objects of the same type when setting up a collection, which then requires removing the record for one directly from the inv database.

Request: The action buttons on these pages should deactivate and turn gray when initially clicked.

**Comment by terrywbrady** [comment]
@elopatin-uc3 , I deployed a fix for this.  Please verify

**Comment by elopatin-uc3** [comment]
Thanks, will do @terrywbrady . I'll have a chance to do that when I set up a series of new collections that Berkeley has requested.
