### ISSUE TITLE
UCI Nuxeo feed: Vicki Ruiz Papers

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#2047]
Source ticket: https://help.oac.cdlib.org/a/tickets/144101

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/28314/

ATOM feed:
https://pad-nuxeo.s3.us-west-2.amazonaws.com/nuxeo_merritt/atom_feeds/ucldc_collection_28314.atom

Root folder in Nuxeo:
asset-library/UCI/SCA_SpecialCollections/MS-503/For Merritt

Merritt collection: EXISTING:
UC Irvine SCA Special Collections
ark:/13030/m5gb7gff

**Comment by elopatin-uc3** [comment]
Feed is not yet ready

**Comment by elopatin-uc3** [comment]
Script should be updated with new ATOM feed URL noted above

**Comment by mreyescdl** [comment]
Created script: production-28314-Vicki-Ruiz-papers-uci_lib_sca_sc.csh
Ran manually: 1 object
Added to weekly processing
