### ISSUE TITLE
Ingest host is not surfaced in List Ingest Queues report

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#2053]
When reviewing jobs in individual job states, the Ingest worker is not available in the List Ingest Queues report:

<img width="595" alt="ingest_host" src="https://github.com/user-attachments/assets/955276af-7e4b-4488-8bd2-0ae7fdb7fa21">

**Comment by terrywbrady** [comment]
@elopatin-uc3 , there is no longer a host assigned to a job.  When I remove support for the legacy queues from the admin tool, I will remove this column.  It will be an interesting time for us to brainstorm the fields that we would like to see instead.

**Comment by elopatin-uc3** [comment]
Got it, thanks @terrywbrady . I thought perhaps there was a host identifier in the queue data for which host picked up a job that could be noted in the report. Yes, brainstorming sounds good about potential fields.
