### ISSUE TITLE
Test Nuxeo harvest on Stage - feeds available

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#2062]

**Comment by mreyescdl** [comment]
@elopatin-uc3 Do you have some specific feeds that have been updated?  I poked around in prod and stage batch servers and did not see any.  Thanks

**Comment by elopatin-uc3** [comment]
@mreyescdl thanks for having a look. I was expecting feeds to be updated based on how much time has passed and any related curation that's occurred in Nuxeo, so will check in with Adrian and Barbara in case there's an issue on their side.

**Comment by elopatin-uc3** [comment]
@mreyescdl can you check the feed for the UC Riverside Library Nuxeo collection on stage? The latest object we have there is from 2022-10-12. However the corresponding production collection shows a much newer object (2024-01-25).

**Comment by elopatin-uc3** [comment]
Also, Adrian is going to check with Barbara about two of the new feeds requested by UCI which haven't yet appeared for deposit in production.

**Comment by elopatin-uc3** [comment]
Tested successfully with feed 9513 on Stage.
