### ISSUE TITLE
SSL Connection for INV database 

### ISSUE THREAD

**Issue by marisastrong** [CDLUC3/mrt-doc#207]
IAS is in the process of updating all the RDS instances (dev/stg/prd) for inv db to support new SSL certificates.  Currently none of our applications connect to the db using SSL.  need to update for Merritt UI and other applications that connect to INV db.

**Comment by terrywbrady** [comment]
I presume this was completed

**Comment by elopatin-uc3** [comment]
Going to mention this in Monday's team meeting to confirm.
