### ISSUE TITLE
UCI Nuxeo feed: University of California, Irvine, Collection of Zines

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#2073]
Source ticket: https://help.oac.cdlib.org/a/tickets/144525

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/27817/

ATOM feed:
https://pad-nuxeo.s3.us-west-2.amazonaws.com/nuxeo_merritt/atom_feeds/ucldc_collection_27817.atom

Root folder in Nuxeo:
asset-library/UCI/SCA_UniversityArchives/AS-219/For Merritt

Merritt collection: EXISTING:
UC Irvine SCA University Archives
ark:/13030/m5bk6qsm

**Comment by elopatin-uc3** [comment]
Feed is available as of 10/15.

**Comment by mreyescdl** [comment]
I ran this feed in production and it contains three entries.
It appears that none of the entries needed updating in Merritt and no submissions occurred.

**Comment by elopatin-uc3** [comment]
Interesting. I'll let the depositor know.

**Comment by elopatin-uc3** [comment]
@mreyescdl Could you retry with the revised feed at the following URL?
https://pad-nuxeo.s3.us-west-2.amazonaws.com/nuxeo_merritt/atom_feeds/ucldc_collection_27817.atom

I diffed the feed data from the old URL with this one and there were several changes. Note the new feed is missing the initial xml version and encoding spec/line:

**Comment by mreyescdl** [comment]
@elopatin-uc3 Still no processing.
I'll need to look at the DB to see why it is not triggered
```
Getting https://pad-nuxeo.s3.us-west-2.amazonaws.com/nuxeo_merritt/atom_feeds/ucldc_collection_27817.atom (tries: 0)
Reading last update time from /dpr2/apps/atom/LastUpdate/lastFeedUpdate_27817-m5bk6qsm
Feed update date 2024-09-20 21:40:22 +0000 newer than last_feed_update 2023-12-01 09:52:47 +0000
Processing batch 0 of 3 (1 entries)
Attempting to process id: aa975181-ab15-4d66-9552-779952b6b087
Processing batch 1 of 3 (1 entries)
Attempting to process id: 9aa62391-f9f9-4461-88fe-acba8f9bc7b1
Processing batch 2 of 3 (1 entries)
Attempting to process id: 73034441-0254-4d6e-a6b9-ff93d46a64c8
```

**Comment by elopatin-uc3** [comment]
The depositor confirmed with me via a screenshot from Nuxeo that two new zip files reside in the same directory (as of 10/8/2024):
![2024-10-24_AS-219_ForMerrit](https://github.com/user-attachments/assets/07f70a07-0d46-41a1-8250-8dcc1e2457aa)

These should be in the feed. I will check with BH and AT.

**Comment by elopatin-uc3** [comment]
The depositor confirmed via a screenshot from Nuxeo that two new zip files were added to the Nuxeo collection on 10/8. However, they do not appear in the most recent feed. I'll follow up with the Nuxeo team on this.

**Comment by elopatin-uc3** [comment]
@mreyescdl Barbara fixed a bug in the feed generator and the two new objects be available in the latest feed that was generated over the weekend.

**Comment by mreyescdl** [comment]
Two object were submitted after rerunning. 
```
Ready to submit id: 65f799af-732a-43fd-912f-25d8326a97e5
Ready to submit id: f385eee7-0b8e-4c26-a07d-240e31019d56
```
