### ISSUE TITLE
Nuxeo feed URL updates across all collections

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#2078]
With the release of the updated feed generation service by PAD, feed URLs have changed to point to a different S3 bucket. 

OLD: 
```
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/...
```
NEW:
```
 https://pad-nuxeo.s3.us-west-2.amazonaws.com/nuxeo_merritt/atom_feeds/
```

We'll need to change all existing scripts to use the new bucket URL

**Comment by mreyescdl** [comment]
Added a couple new feeds to batch processor and started processing the backlog.
Collection `UC Merced Library UCCE Fresno County` requires all objects to be updated (~3K)
