### ISSUE TITLE
[RELEASE] INGEST - Local ID Lock, New State, bug fixes

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#2082]
# Overview of Release
- Need for a local ID lock is needed. Lock is initialted at start of ProcessMgr and continues till end
- New State transition Job Pending to Failed.  Needed for Manifest processing errors
- Email Subject bug fix for failures
- Acquire Bug fix.  Make sure to delete lock on error
- Notification Local ID bug fix when multiple LIDs are submitted

# Service(s)
Ingest (with changes to ZK lib)

# Github Issue Link(s)
https://github.com/CDLUC3/mrt-doc/issues/2071
https://github.com/CDLUC3/mrt-doc/issues/2051
https://github.com/CDLUC3/mrt-doc/issues/2029
# Servers affected

# Source Code:
https://github.com/CDLUC3/mrt-ingest/pull/108

# Source Code Tag
2.1.4

# Jenkins/Build Info: (if applicable)
Now using CodeArtifact

# Deployment Steps (if applicable)
- [ ] Ansible deployment

# Infrastructure Changes to support deployment (ALB, EFS, etc)
N/A (Ansible takes care of ALB details)

# Rollback Instructions
Ansilble rollback

**Comment by mreyescdl** [comment]
Update complete.

Running integration test...
No failures.

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl !
