### ISSUE TITLE
Update ETDs config with new EZID credentials

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#209]
### Summary
EZID is used by our ETDs service scripts. Configuration for associated credentials is managed by Puppet. We need to update EZID credentials for the ETDs scripts in the following config file:
`/apps/etds/apps/uc3-etds/config/app_config.yml`

Tasks:
- [x] Update line 67 with new EZID password:
```
 65 ezid:
 66     eschol_shoulder: 'ark:/13030/qt'
 67     credentials: 'USER:AUTHCODE'
```

**Comment by elopatin-uc3** [comment]
@mreyescdl The file in question (managed by Puppet) as it resides on `uc3-etdx2-prd.cdlib.org` is `/apps/etds/apps/uc3-etds/config/app_config.yml`. Could you update the EZID credentials entry in the Puppet repo? Thanks!

**Comment by mreyescdl** [comment]
Password updated.  Puppet agent will push out this change to the host

**Comment by elopatin-uc3** [comment]
Thanks Mark! The new config has been pushed to `uc3-etdx2-prd.cdlib.org`; looking at it now.
