### ISSUE TITLE
UCI Nuxeo feed: School of Social Ecology Living Archive of Poetic Justice collection

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#2090]
Source ticket: https://help.oac.cdlib.org/a/tickets/145055

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/28327/

ATOM feed:
https://pad-nuxeo.s3.us-west-2.amazonaws.com/nuxeo_merritt/atom_feeds/ucldc_collection_28327.atom

Root folder in Nuxeo:
/asset-library/UCI/SCA_OrangeCountyRegionalHistory/MS-R215/FOR MERRITT

Merritt collection: EXISTING:
UC Irvine SCA Orange County Regional History Collection
ark:/13030/m5vb5f2r

**Comment by elopatin-uc3** [comment]
Feed should be available on 11/4

**Comment by mreyescdl** [comment]
- Created script
- Ran manually (1 object)
- Scheduled for weekly processing
