### ISSUE TITLE
Linux 2 - UI/Ingest/Zookeeper steps

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#210]
Six Linux 2 servers, hosting Ingest, UI and Zookeeper services to be enabled

uc3-mrtui01x2-prd
        CNAME:  ui01-aws
uc3-mrtui02x2-prd
        CNAME:  ui02-aws
uc3-mrtui03x2-prd
        CNAME:  ui03-aws
uc3-ingest01x2-prd
        CNAME:  ingest01-aws
        CNAME:  ingest01
uc3-ingest02x2-prd
        CNAME:  ingest02-aws
        CNAME:  ingest02
uc3-ingest3x2-prd
        CNAME:  ingest03-aws
        CNAME:  ingest03

UI - All clients reference UI through "merritt.cdlib.org" and this reverse proxies to workers using CNAMES.  Maybe need to "re-hup" apache?

Ingest - All clients use "merritt.cdlib.org:33121" to access ingest?  Sword, yes. 

Zookeeper - All clients use CNAMES for connect string?  Ingest, yes.  Inventory, David says yes.  Need to restart these services to flush connection pool?  Yes, only for Inventory. (Do through ALB)

STEPS
- CNAME change
- Restart Apache gracefully to ensure no DNS caching (merritt.cdlib.org)
- Restart Inventory
- Turn off Nuxeo harvesting on Linux 1 host and enable on Linux 2 host (ui01-aws)

**Comment by mreyescdl** [comment]
Debra has bumped up the throughput on the EFS volume
From Debra...
It was set to the default bursting mode, I have updated efs-uc3-ingest-prd to Provisioned (10 MiB/s) to match stage. The throughput bill can be up to $60.00/month. Note: This work was done in stage on Footprints 12935

**Comment by mreyescdl** [comment]
Nuxeo harvesting is disabled on Linux 1 host ( uc3-mrtui01-prd)
Must enable on uc3-mrtui01x2-prd after switch

**Comment by elopatin-uc3** [comment]
Switch to Linux2 hosts occurred from approximately 11am-11:30am today.
