### ISSUE TITLE
UCR Nuxeo feed: Sidney T. Harding papers 

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#2110]
Source ticket: https://help.oac.cdlib.org/a/tickets/133623

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/26757

ATOM feed:
https://pad-nuxeo.s3.us-west-2.amazonaws.com/nuxeo_merritt/atom_feeds/ucldc_collection_26757.atom

Root folder in Nuxeo:
/asset-library/UCR/SCUA/Archival/WRCA041

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

**Comment by mreyescdl** [comment]
- Created script (production-UCR_Sidney_T_Harding_Papers.csh)
- Ran manually (1 object)
- Scheduled for weekly processing

Completed
