### ISSUE TITLE
UCR Nuxeo feed: Walter L. Huber papers and photographs

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#2112]
Source ticket: https://help.oac.cdlib.org/a/tickets/133623

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/26759

ATOM feed:
https://pad-nuxeo.s3.us-west-2.amazonaws.com/nuxeo_merritt/atom_feeds/ucldc_collection_26759.atom

Root folder in Nuxeo:
/asset-library/UCR/SCUA/Archival/WRCA044

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

**Comment by mreyescdl** [comment]
- Created script (production-UCR_Walter_L_Huber_Papers_Photographs.csh)
- Manually ran (225 objects)
- Scheduled for weekly processing

Completed
