### ISSUE TITLE
UCR Nuxeo feed: Water Resources Collections & Archives sound and moving image recordings 

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#2113]
Source ticket: https://help.oac.cdlib.org/a/tickets/133623

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/27895

ATOM feed:
https://pad-nuxeo.s3.us-west-2.amazonaws.com/nuxeo_merritt/atom_feeds/ucldc_collection_27895.atom

Root folder in Nuxeo:
/asset-library/UCR/SpecialProjects/wrca_films

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

**Comment by mreyescdl** [comment]
- Create script (production-UCR_Water_Resources_Collections_Archives.csh)
- Manually submitted (9 objects)
- Scheduled for weekly processing

Completed
