### ISSUE TITLE
UCR Nuxeo feed: 2017 Riverside Plane Crash Tweet Set

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#2115]
Source ticket: https://help.oac.cdlib.org/a/tickets/133623

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/26946

ATOM feed:
https://pad-nuxeo.s3.us-west-2.amazonaws.com/nuxeo_merritt/atom_feeds/ucldc_collection_26946.atom

Root folder in Nuxeo:
asset-library/UCR/Test Space/DocNow

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

**Comment by mreyescdl** [comment]
- Created script (production-UCR_2017_Riverside_Plane_Crash_Tweet_Set.csh)
- Manually ran (2 objects)
- Scheduled for weekly processing

Complete
