### ISSUE TITLE
Prod only steps flip swift to minio

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#213]
# Swift to Minio Flip - Production
This issue is specific to the Production flip done on 1/22/20 between 2-4 p.m.

These steps are specific to Production Phase 1 flip of migrating Merritt from using SDSC Swift content to Minio.

With this process:
* Dryad will remain fully functional. Sword issues ingest requests through sword (no freeze). No db changes will occur to impact Dryad data.
* During process no updates to Merritt will take place

Time:
* Completion of activity on ingest after freeze (18 hours)?
* Flip - 2 hour
## Steps
* Extension
* Shutdown all new changes swift
* Flip
* Restart

This will help get better confirmation things are working. Current hope is flip last week Jan.

Modified inv database: _uc3db-inv.cdlib.org_

## Shutdown all new changes swift
Requires that all swift changes have completed on system
- [x] (Mark) Pause ingest – pause at approximately Tues 1/21 by 6 p.m.
This will need to be done 18 hours before flip to guarantee that no non-Dryad processing is taking place.

Mark confirmed that queued profiles do not contain node info - this allows for a soft flip as opposed to a hard flip that requires more elements of Merritt to be down.
- [x] (David) Confirmation that all ingest complete through replication
This requires running tests to guarantee that all swift content has been replicated to minio
- [x] (Mark) Shutdown monitors
* Monitors for prod replication:
uc3-mrtreplic1-prd
uc3-mrtreplic2-prd
* Monitors for prod inventory:
uc3-mrtinv-prd
uc3-mrtinv2-prd
- [x] (Debra) Issue checkpoint to datase
See-Issue checkpoint to uc3db-inv.cdlib.org for SDSC prod flip ISSUE=13334 PROJ=2
- [x] (David) Shutdown prod replication:
uc3-mrtreplic1-prd
uc3-mrtreplic2-prd
uc3-mrtreplic3-prd
This is to guarantee no further caching of changes
## Flip
- [x] (David) build new alternate inv_nodes_inv_objects table.

This:
* replace all primary swift with primary minio
* replace all secondary swift with secondary minio
* retain all non-swift
* add secondary for all swift (phase 1)

- [x] (David) confirm alternate inv_nodes_inv_objects tables are accurate

- [x] (David) build new inv_collections_inv_node stable.

This:
* retains non-swift
* replaces as secondary swift with minio
* retains all swift as secondary to continue preserving content

- [x] (David) confirm new inv_collections_inv_nodes table are accurate.

- [x] (David) renames alternate nodes-objects, and collections-nodes to prod version

This:
* Does inv flip

- [x] (David) confirm proper rename (sanity check)

- [x] (Mark) flips ingest profiles
Swift 9103, 9001
to
Minio 9501
## Restart
- [x] (David) restart replication
- [x] (Mark) server restarts on inventory using ALB drains and restarts
uc3-mrtinv-prd
uc3-mrtinv2-prd

To guarantee no db caching on inventory, a system restart of each server is necessary. During this restart of the inventory servers it will be necessary that inventory continue to be available for Express. This requires a load balancer shutdown. This will guarantee the db is using the latest Minio content. moving forward
### (Mark,David) _?test ingest flip_
Not clear if this can be done with frozen ingest
Includes:
- [ ] (Mark) - add new archive content (Minio)
- [ ] (David) - confirm inv updated inv_nodes_inv_objects
- [ ] (David) - confirm replication of minio content to glacier
- [ ] (Mark) - add new public content (AWS)
- [ ] (David) confirm inv updated
- [ ] (David) - confirm replication of AWS content to both minio
- [ ] (David) - confirm replication of AWS content to swift (phase 1)
- [ ] (Mark) unfreeze ingest
- [ ] (Mark) restore (or use timeout) monitors

## Prod Profile Node Flip
Swift 9103, 9001
to
Minio 9501

**Comment by mreyescdl** [comment]
Hi David,

As you mention, with Ingest paused it will be difficult to test writing to the new Minio node.
However, we can test reading with both Express and the Merritt UI.  This will confirm that the DB has the correct node entries.

**Comment by dloy** [comment]
Hi Mark - Sounds good Mark

**Comment by mreyescdl** [comment]
Storage 01 is the only Storage server in operation while we analyze the Minio propagation issue.
To return Storage 02, modify the following file on "merritt.cdlib.org" and the restart Apache gracefully.
/dpr2/apps/apache/conf/conf.d/rndmap.map
