### ISSUE TITLE
Hotfix: Add buffer for Storage and Inventory handshake

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#219]
### Summary
After flipping all restricted access collections to use Minio/Qumulo as primary node storage, we are observing an issue where the use of two, load-balanced Storage servers is prohibiting a handshake between Storage and Inventory. 

David has proposed adding a 2 second sleep between the two associated operations, in order to enable data to be established and available via either Storage server. This should serve as an intermediate hotfix, until we can root cause the actual problem with SDSC.

### Tasks
- [ ] Implement 2s buffer and test on Stage
- [ ] Deploy hotfix and reinstate second Storage server in load balancer config

**Comment by dloy** [comment]
All tests indicate running including forced delay.

Hopefully Eric could resubmit failed request from before on prod to confirm original failure

**Comment by elopatin-uc3** [comment]
Thanks for releasing this yesterday. I will run some test deposits to confirm.

**Comment by elopatin-uc3** [comment]
Tested with an individual file, and a zip. The first versions of each of these is fine. However updating the single file object with a new text file is causing an issue. There a 500 being returned in the UI when I attempt to view the second version's file.

https://merritt.cdlib.org/d/ark%3A%2F13030%2Fm5091cgp/2/producer%2Fminio_flip%20test%204.txt
