### ISSUE TITLE
EFS Settings and Cost - Have Team Discussion of Options 

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#221]
I'm bringing our Slack discussion back into this ticket for possible follow up. You are observing variable latency whenaccessing your EFS ingest file system. This command shows 0-21 seconds from different ingest hosts and at differenttimes: time df -h /apps/ingest-prd-shared
We are using the mount helper with the recommended defaults. Your EFS ingest file systems are set to provisionedthroughput (10 MiB/s) to match stage. This work was done in stage on Footprints 12935 and might need a fresh look.
These are the only EFS file systems with Provisioned throughput. We generally use the default (Burstable).
I added EFS Metrics for Librato: https://metrics.librato.com/s/public/qa2plfs4i?source=%2Afs-3b22fd91 and you can finddocumentation in the Librato User Guide (including how to find the identifier for your specific EFS file system).
You noted correctly the permitted throughput changed when we made the change on Wednesday to this setting, but itlooks like it went from 100M/s down to 10M/s. Provisioned does not offer higher throughput, just guaranteed throughputand this may not be the best setting for you.
Please continue to monitor on the application side and in Librato and we can discuss next steps.

**Comment by elopatin-uc3** [comment]
We've gone back to burst mode on EFS production Ingest, as the 10MiB/s higher tier/setting cost us $60/mo. without a clear benefit (seemed slower according to Librato metrics).

**Comment by elopatin-uc3** [comment]
May want to re-open this if/when we consider EFS for Storage.

**Comment by mreyescdl** [comment]
It is difficult to test disk I/O on stage using standard benchmark testing.  This is due EC2 host type variation from stage to host.  That is, stage Ingest uses t2.small and prod uses M5.large.

I'm going to revert Ingest stage EFS to "Burst throughput" to save money.
Then, I will reduce Ingest EFS production from 100MB/s to 50MB/s and monitor performance

**Comment by mreyescdl** [comment]
We are now at 50MB/s on production and it looks like it may be okay.
I ran a benchmark submission (1000 small objects) on both 100 and 50 MB/s and results acceptable.  100MB/s takes 25 minutes to complete and 50MB/s 31 minutes.

At half the price ($600/month vs $300/month) this is an acceptable trade-off in my opinion.

**Comment by marisastrong** [comment]
haven't seen large submissions to really see how things are going, but so far we haven't had issues with the smaller allocation of 50MB
