### ISSUE TITLE
Swift to Minio Flip - Stage - Phase 2

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#222]
# Swift to Minio Flip - Stage - Phase 2
This issue is specific to the the Stage Flip for 1/29/2020

These steps are specific to Stage Phase 2 flip of migrating Merritt from using SDSC Swift content to Minio.

With this process:
* All references to Swift content in the inv database are removed

Time:
* several days - tests on a copied database indicate timing issues removing large amounts of content especially in the mrt_audits table (prod > 159M). This indicates that using multiple script (10M?) will be required.

## Steps
* Shutdown 
* Flip
* Restart

This will help get better confirmation things are working. Current hope is flip last week Jan.

Modified inv database: _uc3db-inv.cdlib.org_

## Shutdown
Remove references to swift content in inv_collections_inv_nodes table
This step removes any further growth for swift content and eliminates the need  for taking mrtreplic offline.
- [x] (David) run delete script to eliminate copies to swift

Take down mrtaudits for duration of removing content in flip process - for prod this will take several days and multiple scripts
- [x] (Mark) pause Nagios monitors for audit: uc3-mrtaudit-stg

- [x] (David) stop servers for: uc3-mrtaudit-stg

## Flip
- [x] (David) Run multiple delete scripts for inv_audit to remove swift
- [x] (David) Run multiple delete scripts for inv_nodes_inv_objects to remove swift
- [x] (David) Run status test to guarantee all SDSC swift content off db

## Restart
- [x] (David) restarts servers:
uc3-mrtaudit-stg
- [x] (Mark) restarts monitors:
uc3-mrtaudit-stg

**Comment by dloy** [comment]
Stage Phase 2 is complete.

I've attached the delete script with some ongoing stats during the run.
[stage-multi-delete.txt](https://github.com/CDLUC3/mrt-doc/files/4140804/stage-multi-delete.txt)
[stage-stats.txt](https://github.com/CDLUC3/mrt-doc/files/4140805/stage-stats.txt)

**Comment by elopatin-uc3** [comment]
Thanks David!
