### ISSUE TITLE
Prototype an admin UI to query for collection/owner stats

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#223]
## Interface will be for staff-only
    - query inventory database
    - merge/validate with deployed config files to verify system understanding.

As useful queries are introduced, they may be candidates to add to user-facing "object status api"

Tasks
- [x] Create rails implementation, deploy to Docker: https://github.com/cdluc3/mrt-admin-proto
- [x] Determine optimal deployment strategy for this application
  -  Per meeting on 4/7/2020, we think the optimal approach is to deploy with Lambda (details below)
- [ ] Prototype lambda implementation
  - I created an RDS instance in my personal AWS account
  - I cloned the content from my docker version of the Merritt db to that tiny RDS
    - In order to populate the database, I created a mysql session from Cloud9
  - I created a lambda written in Ruby to access the database and return query results as JSON
    - The code is here: https://github.com/terrywbrady/lambda-mysql-ruby. 
    - The following doc explained the deployment process: https://medium.com/@hsdeekshith/using-mysql2-gem-in-aws-lambda-for-ruby-7f9456bf2ca5
    - The lambda needed LambdaVPCExecution rights
    - The credentials for the database are entered as environment variables in the Lambda
  - I created an API gateway pointing to that Lambda
    - I deployed the API (link shared in slack)
- [ ] Request sandbox lambda implementation + stage db access
- [ ] Request lambda access for main aws account + prod db access

![image](https://user-images.githubusercontent.com/1111057/79943134-fbff8880-841c-11ea-8ea6-9e4a3c16243a.png)

**Comment by terrywbrady** [comment]
https://github.com/terrywbrady/mrt-admin-proto

**Comment by terrywbrady** [comment]
Moved code to public repo
- https://github.com/CDLUC3/mrt-admin-proto
Deploying to
- http://uc3-mrtdocker2-stg.cdlib.org:8085/menu/index

**Comment by terrywbrady** [comment]
I updated the admin tool prototype to utilize a database clone that @dloy provided to me.  The underlying database content is approx 8 months old.

http://uc3-mrtdocker2-stg.cdlib.org:8085/

I simplified the queries to make things run in a reasonable amount of time.  For links that point to a collection of 1M+ files, the queries can get a bit sluggish.

**Comment by terrywbrady** [comment]
Terry will request a meeting with IAS to see if we can connect to PROD from the docker EC2.

**Comment by terrywbrady** [comment]
4/7/2020:  Marisa, Ashley, Terry, Brian T met to discuss options.

We discussed the concepts of pets vs cattle approaches to deployment.

- Run as rails app (pet)
- Run docker on ec2 (as we have in stage) (pet)
- Run as beanstalk/fargate (cattle)
- Run as ECS or EKS (cattle)
- Re-engineer and deploy as lambda (cattle)

Given the frequency of use for this application, we decided to explore this as a Lambda application.

**Comment by terrywbrady** [comment]
The following article looks like a helpful start for working with a lambda and mysql.

https://medium.com/@hsdeekshith/using-mysql2-gem-in-aws-lambda-for-ruby-7f9456bf2ca5

**Comment by terrywbrady** [comment]
Moving this ticket to the Done column.  Replacing this ticket with a new one to track our goals for the admin tool.  https://github.com/CDLUC3/mrt-doc/issues/301

**Comment by elopatin-uc3** [comment]
Thanks @terrywbrady. Looking through 301 now.
