### ISSUE TITLE
Add ingest config to private repo 

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#224]
### Summary
We currently can't use ssh key, as we already have access through the mrt-ingest-profile repo. Can't add a second ssh key. Investigate alternatives to get around this.

**Comment by terrywbrady** [comment]
@mreyescdl , This may not be a best practice, but here is a possible option.
- Create a "merritt-deploy" github account to be used by the team
- Grant this credential read access to our private repos
- Generate an ssh key named github_rsa/github_rsa.pub for our server role accounts
- Configure this key for github
```
...> cat ~/.ssh/config 
Host github.com
    IdentityFile ~/.ssh/github_rsa
```
- Add this ssh key to the ssh key list for "merritt-deploy"

**Comment by terrywbrady** [comment]
Note that an account such as this might also be useful for automated repository tagging.  See https://github.com/CDLUC3/mrt-doc/issues/225

**Comment by terrywbrady** [comment]
@mreyescdl , I forget the history of this ticket.  It seems like this could be closed.
