### ISSUE TITLE
UI Exception emails need to be updated with correct To: list

### ISSUE THREAD

**Issue by marisastrong** [CDLUC3/mrt-doc#232]
https://github.com/CDLUC3/mrt-dashboard/blob/master/config/environments/production.rb

defines who is sent exception emails which originate from  the Merritt UI application.

- [ ] remove perry.willett@ucop.edu
- [ ] remove david.moles@ucop.edu
- [ ] add terrence.brady@ucop.edu

**Comment by terrywbrady** [comment]
This looks done
