### ISSUE TITLE
Implement the presign-file endpoint in the Storage Service

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#236]
## Details
- https://github.com/CDLUC3/mrt-doc/blob/endpoints/endopoints/inventory/presign-file.md

## Overall Design
- https://github.com/CDLUC3/mrt-doc/blob/endpoints/endopoints/storage/presign-file.md

**Comment by elopatin-uc3** [comment]
Noting a recent PR: https://github.com/CDLUC3/mrt-cloud/pull/2
