### ISSUE TITLE
Review Merritt Configuration Approaches

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#241]
https://confluence.ucop.edu/pages/viewpage.action?spaceKey=~tbrady&title=Merritt+Configuration+Approaches

- [ ] Test SSM Parameter Store in the Sandbox
- [x] Migrated to https://github.com/cdlib/mrt-conf-prv/tree/config-refactor-proto
- [x] Prototype Java library
- [ ] Prototype Ruby library
- [ ] Consider GitHub Actions Secrets
  - https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
  - also, consider the yaml format for github action parameters
  - https://www.linkedin.com/learning/learning-github-actions-2/using-secrets?autoplay=true&u=76816210

**Comment by terrywbrady** [comment]
Note that there is also an IAS ticket open (ISSUE=13351).  As that ticket gets feedback, we should compile recommendations.

**Comment by terrywbrady** [comment]
Sample Yaml processing code in Java: https://github.com/terrywbrady/yaml

**Comment by terrywbrady** [comment]
https://confluence.ucop.edu/display/~tbrady/Tracing+the+Node+Table+Configuration

**Comment by terrywbrady** [comment]
https://github.com/terrywbrady/mrt-conf-prv-refactor

**Comment by elopatin-uc3** [comment]
Planning to move this work into a branch in mrt-conf-prv

**Comment by terrywbrady** [comment]
Moved this work to https://github.com/cdlib/mrt-conf-prv/tree/config-refactor-proto

**Comment by terrywbrady** [comment]
```
aws ssm put-parameter --name /demo/service1/dev/merritt --value "hello" --type String
aws ssm get-parameter --name /demo/service1/dev/merritt
```

**Comment by terrywbrady** [comment]
Sample config code is working in the sandbox.

https://github.com/terrywbrady/yaml

**Comment by terrywbrady** [comment]
Moved back to the TODO column knowing there is limited bandwidth for this work right now.
