### ISSUE TITLE
ETD abstract update

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#244]
### Summary 
An ETD's abstract in eScholarship has an incomplete sentence, as compared to its ProQuest counterpart. https://cdl.freshdesk.com/a/tickets/68859

- [x] Correct Merritt metadata for the ETD; to be harvested following day to eScholarship

**Comment by alainna** [comment]
@elopatin-uc3 Here's the ETD: 
>eScholarship: qt4c81w4nr
> ProQuest ID: Brown_ucla_0031D_18469
> http://dissertations.umi.com/ucla:18469
> Merritt ID: ark:/13030/m53r60sg

Per author report (Freshdesk ticket #68859), eScholarship's abstract has a cutoff in paragraph 1, while ProQuest correctly has P1 displayed correctly: 

eScholarship/Merritt abstract: 

> As key locations for impacts and benefits associated with biodiversity, urban areas are a critical frontier for improved stewardship. While cities across California have long been global leaders in managing threatened and endangered species, Los Angeles recently embarked on a more comprehensive approach to biodiversity when the Los Angeles City Council passed the May 10, 2017 Biodiversity Motion (Motion 25A, Council File No. 15-0499). The motion directed the development of a customized biodiversity index focused on conservation and access to biodiversity, among other products. The motion was in line with the City’s official goal of no-net-biodiversity loss by 2035. Together, this goal and motion suggest that biodiversity in LA shall not only be protected, but that its benefits will also be maximized to support urban resiliency and livability. This doctoral dissertation

> is organized into three chapters describing key analysis tools and results associated with the LASAN Biodiversity Team’s process of implementing the Biodiversity Motion. [....] 

ProQuest: 

> As key locations for impacts and benefits associated with biodiversity, urban areas are a critical frontier for improved stewardship. While cities across California have long been global leaders in managing threatened and endangered species, Los Angeles recently embarked on a more comprehensive approach to biodiversity when the Los Angeles City Council passed the May 10, 2017 Biodiversity Motion (Motion 25A, Council File No. 15-0499). The motion directed the development of a customized biodiversity index focused on conservation and access to biodiversity, among other products. The motion was in line with the City’s official goal of no-net-biodiversity loss by 2035. Together, this goal and motion suggest that biodiversity in LA shall not only be protected, but that its benefits will also be maximized to support urban resiliency and livability. This doctoral dissertation is organized into three chapters describing key analysis tools and results associated with the LASAN Biodiversity Team’s process of implementing the Biodiversity Motion. [....]

**Comment by elopatin-uc3** [comment]
Change has been made to Merritt metadata @alainna . Should be picked up by Martin's harvest process tomorrow.

**Comment by elopatin-uc3** [comment]
Paragraph issue resolved now in eScholarship. Moving to Done
