### ISSUE TITLE
Release: Merritt Inventory Linux2 cutover

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#247]
### Deployment Steps/Tasks
- [x] [ ALB Switch ]  Remove Linux 1 hosts from ALB uc3-mrtinv-prd-alb and add Linux 2 hosts 
- [x] [ DNS CNAME Switch ]  Alter CNAMEs inv01-aws and inv02-aws

#### Services:
mrt-inventory

#### Servers:
Stage:
N/A

Production:
uc3-mrtinv01x2-prd.cdlib.org
uc3-mrtinv02x2-prd.cdlib.org

#### Change description
- Move Inventory production Linux 2 hosts into production

#### Infrastructure Changes to support software (ALB, EFS, etc) 
CDL-SYS tickets submitted:
[CDL VM Server Request (uc3-mrtinv01x2-prd uc3-mrtinv02x2-prd) ISSUE=13354 PROJ=2]

#### Travis:
[build name/number]

#### Github or Pivotal Issues:
[https://www.pivotaltracker.com/story/show/170936684]

#### Source Code:
[https://github.com/CDLUC3/mrt-inventory]:
[Latest master]

**Comment by mreyescdl** [comment]
Confirmed that test for Local ID service and Manifest service is working for Linux 2 hosts.

**Comment by mreyescdl** [comment]
Linux 2 Manifest service and Local ID service was not exposed during the mis-configuration that caused the population of the Stage Inv DB.  No work is necessary

**Comment by mreyescdl** [comment]
Will schedule Inventory switch on Wednesday afternoon, working with Debra.
In preparation, will pause Ingest in the early afternoon.

**Comment by mreyescdl** [comment]
Cut-over is scheduled for 2:30 today.  I'll pause Ingest @ 2:00

**Comment by mreyescdl** [comment]
Cut over to Linux 2 is now complete.

It looks to be working, but I'll continue to monitor

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl !
