### ISSUE TITLE
Stage node 4101 migration

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#248]
## Stage node 4101
Stage node 4101 is used for dataone content on stage.

Originally this content was saved at the UNM test site. With earlier migrations, access to the test site from stage was not possible. The original UNM test site was on the dev (development) hosts that did have access, but were later shutdown.

The original stage 4101 node was migrated to the SDSC swift site.

With the Flip from SDSC swift to SDSC Minio, this specific node (4101) was overlooked. With the closure of the SDSC swift this content would be lost. This is not critical because the content is Stage but needing to have some parallel to production, keeping this content is useful.

## Steps
- [x] Add new bucket to Minio specific to node 4101 (cdl.sdsc.stg4101)
- [x] Create local (sandbox2-stg) storage service that includes both swift 4101 and minio 4101
- [x] Copy all swift 4101 to minio 4101 if still available
- [x] Update new nodes-stage table to contain updated minio node information
- [x] Update existing nodes-stg-store to to reference cdl.sdsc.stg4101 content
- [x] Redeploy stage store1
- [x] Redeploy stage store2

**Comment by marisastrong** [comment]
Running successfully at SDSC
