### ISSUE TITLE
URL Encoding in Ingest->Storage Manifest

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#26]
Backslashes in object path name creates a problem for the Core library routine that creates Storage manifest
 - [ ]

**Comment by elopatin-uc3** [comment]
Problem lies with Tomcat not being able to serve backslashed files (Mark Reyes - Apr 21, 2015)

**Comment by elopatin-uc3** [comment]
Quick fix for Merced, who's data triggered the problem: renaming the backslashes to underscore.
Script to do this is at ingest01.cdlib.org:/dpr2/tools/rename_backslash (Mark Reyes - Apr 24, 2015)

**Comment by terrywbrady** [comment]
Reopen as a new issue if needed
