### ISSUE TITLE
Release: Merritt Audit Linux2 cutover

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#262]
### Deployment Steps/Tasks
- [x] [ DNS CNAME Switch ]  Alter CNAMEs audit01-aws,  audit02-aws, audit03-aws and audit04-aws

#### Services:
mrt-audit

#### Servers:
Stage:
N/A

Production:
uc3-mrauditv01x2-prd.cdlib.org
uc3-mrtaudit02x2-prd.cdlib.org
uc3-mrtaudit03x2-prd.cdlib.org
uc3-mrtaudit04x2-prd.cdlib.org

#### Change description
- Enable Audit production Linux 2 hosts into production

#### Infrastructure Changes to support software (ALB, EFS, etc) 
CDL-SYS tickets submitted:
CDL VM Server Request (uc3-mrtaudit01x2-prd, 02, 03, 04) ISSUE=13385 PROJ=2

Route 53 CNAME changes

#### Travis:
[build name/number]

#### Github or Pivotal Issues:
[https://www.pivotaltracker.com/story/show/170936684]

#### Source Code:
[https://github.com/CDLUC3/mrt-audit]:
[Latest master]

**Comment by mreyescdl** [comment]
Request for DNS change made.

**Comment by mreyescdl** [comment]
Cutover is complete.

The 4 Linux 1 hosts are shutdown, but not yet decommissioned. 
David would like to wait a week to make sure everything is working okay.
We'll keep CDLSYS tix open until the final decommission.

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl for getting these four new Linux 2 hosts online! (and thank you for the notes on this ticket). I'll move it over to the Done column once the Linux 1 hosts are shut down.
