### ISSUE TITLE
Ensure Mime Type compatibility for Presigned URL's

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#264]
PDF files are not displaying after a presigned retrieval.

Review other common Merritt mime types and validate support.

## Changes
- Endpoint Contract: https://github.com/CDLUC3/mrt-doc/commit/83d505826696447860f612db78bd51314f303a42
- UI Change: https://github.com/CDLUC3/mrt-dashboard/pull/52
- Lib/Storage Chagne: 
  - https://github.com/CDLUC3/mrt-cloud/pull/3
  - https://github.com/CDLUC3/mrt-store/pull/5

**Comment by terrywbrady** [comment]
Thanks David.  This will be useful to add to the investigation.  I will copy this into the ticket.

For some of the objects, I found that the download option in Merritt did work once we reverted the release.  

I plan to take a closer look at the headers that we generate when a download is initiated.  Perhaps we can instruct chrome to fully download the file before attempting to open it.

Terry
From: David Loy 
Subject: Chrome, pdf and presigned
 
I'm not clear if this is the problem people ran into yesterday(!).

I created a pre-signed URL on a pdf document:
curl -v
'http://uc3-mrtstore2-prd.cdlib.org:35121/presign-file/9501/ark%3A%2F13030%2Fm5xd680g%7C1%7Cproducer%2FDiTucci_berkeley_0028E_17550.pdf?expire=120'

I used the resulting URL on my office windows Firefox and Chrome browsers.

With Firefox (my local settings) it downloaded the file and opened it
using Adobe. It worked.

With Chrome, it attempted to open the PDF locally on Chrome and failed:
Error
Failed to load PDF document.

After some hunting found the following:
https://appuals.com/fix-error-failed-to-load-pdf-document-in-chrome/

"The built-in PDF viewer is not equipped to view protected PDFs
– A lot of users have been reporting problems with the built-in PDF viewer
when trying to open protected PDF documents.
In this case, the solution is to re-configure Google Chrome to avoid
using the PDF viewer
  and open the document with a different PDF viewer app."

I reset Chrome to not attempt to open PDFs directly but download and
then open using Adobe - it worked.

Again, not sure if this is what people ran into yesterday.  But for this
specific case there is a solution.

Thanks
David

**Comment by terrywbrady** [comment]
https://github.com/CDLUC3/mrt-doc/blob/master/meetings/2020-03-12-presigned-ContentType.md

**Comment by dloy** [comment]
The java presign function provides a mechanism for over-riding headers returned as part of the S3 presign response:

                ResponseHeaderOverrides headerOverrides = new ResponseHeaderOverrides();
                headerOverrides.setContentType(contentType);
                generatePresignedUrlRequest.setResponseHeaders(headerOverrides);

**Comment by terrywbrady** [comment]
@dloy , I recommend that keep the issue open until this is deployed to Prod.

**Comment by terrywbrady** [comment]
I linked the cloud and storage PR's to this ticket.
