### ISSUE TITLE
Retention Policy/Costs for Merritt Async Object / Version Retrieval

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#274]
Once the presigned Object/Version assembly is completed, **all** object/version requests will be async.

This has many performance advantages.  This also means that objects/versions will be retained for an extended period of time.  (When these objects were streamed, they were discarded after delivery).

We need to ensure that the retention policy for these objects does not cause a significant increase in storage costs.

**Comment by terrywbrady** [comment]
@elopatin-uc3 , we will want to chat about this with the Dryad team.  The 4 week retention for the email based deliveries may be too much time for standard object/version downloads.  If we need a custom retention for Dryad content, that would increase complexity.

**Comment by terrywbrady** [comment]
https://confluence.ucop.edu/display/~tbrady/Presigned+Calculations

**Comment by terrywbrady** [comment]
TODO: Meet with Kurt, Marisa, Eric, Terry to review and validate the calculations.

**Comment by terrywbrady** [comment]
Information reviewed.  This should be complete.

**Comment by elopatin-uc3** [comment]
Agreed; moving over to the Done column.
