### ISSUE TITLE
SDSC Compute Option to move 3rd copy content to Wasabi - Trial

### ISSUE THREAD

**Issue by marisastrong** [CDLUC3/mrt-doc#299]
Once Merritt’s corpus of content is moved to Wasabi as our 3rd copy we will incur ongoing costs moving newly ingested content to Wasabi.  
- [ ] Do we understand what AWS cost is to move?  
- [ ] How much content will be added on a regular basis?  25-50T a year?  

**Trial approach**  
- [ ] Investigate using SDSC Cloud compute to provide some benchmarks for cost comparison to manage costs for 3rd copy transfers.  
- [ ] Understand how client could be maintained/managed in SDSC Compute.  

**Client software** 
client application would copy content directly from SDSC Minio to Wasabi. It probably would use an http trigger (HTTP function that you invoke with an HTTP command)  for which objects to copy (e.g. storage).
- [ ] Provide High level design of copy HTTP Trigger

**Questions**
- [ ] Is additional storage (1 TB) off the compute instance to store content locally before copy operation?  
- [ ] How would software be deployed onto/managed within SDSC compute environment?  
The big one was Berkeley. This is much closer to UNM but we have the advantage that it is UC. Some other issues of whether we would have ROOT access to allow for maintenance, and also the specifics for operating system. At this point not even clear if this is a headless server (typical AWS). Personally I have done my own admin stuff with Ubuntu. Been pretty restricted on the AWS EC2s. Some details are needed.

If favorable results from benchmarks result from trial analysis, we would need to further investigate how we manage this going forward to support 3rd copy

**SDSC Costs/Admin**
* one m1.medium instance with 1 TB of volume storage running costs roughly $105/month. Exact costs will vary due to billing being based on uptime hours per month.
* We probably don’t have a compute environment set up with SDSC.  Do we want to create  one for the 2 month trial period?

**Option of utilizing [Wasabi Ball](https://wasabi.com/wasabi-ball/)?**  
Needs more analysis on cost, execution, etc.  Our current 3rd copy transfer is in progress, given that we are at least 25% completed, may not need to invest time and resources into utilizing an appliance to save  ~$5K.

**Comment by elopatin-uc3** [comment]
Thanks for creating this @marisastrong .

**Comment by terrywbrady** [comment]
The one caution I have on this approach is that we be careful that this cost savings measure does not increase our operational costs elsewhere.  We have many tickets on the board that are designed to simplify the system architecture.  This has the risk of making things more complex.

I gave David a call to understand this in more detail.  If we decide to implement this approach, I would hope that we could make this approach a supported mechanism of the replication service.  The replication configuration would know about this mechanism and direct requests to trigger this copy method.

**Comment by terrywbrady** [comment]
@elopatin-uc3 , is this still open?

**Comment by elopatin-uc3** [comment]
Thanks for the ping @terrywbrady . The latest AWS statement from Kurt indicates that we have been reimbursed for S3 storage fees related to the Wasabi replication. What is still an unknown is the data transfer charges we're experiencing, and if those will be reimbursed. That said, Kurt has continued to reiterate that we're clear to proceed with the replication as we're doing so now. 

That said, I'm going to close this ticket. We can re-open if for some reason data transfer charges cause concern from a financial standpoint. But we'll need to consider development and complexity costs incurred by the work and ideas recorded in this ticket, against those.
