### ISSUE TITLE
Make SWORD manifest deposits asynchronous

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#30]
Dash submit to Merritt using SWORD. These submissions are synchronous, which is fine for normal push submissions, but now Dash also offers submission  by manifests (or pulls). The SWORD connection stays open until the Merritt ingest is complete, which can take 12 hours or longer, since they can be up to 100 GB. 
 - [ ]

**Comment by terrywbrady** [comment]
@elopatin-uc3 , I think this can be closed

**Comment by elopatin-uc3** [comment]
Active discussions of switching Dryad to becoming a regular depositor vs. use of SWORD. Closing
