### ISSUE TITLE
Establish feeds for two UCI collections in Nuxeo to one collection on Merritt Stage 

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#303]
### Summary
The UCI Library would like to get a test harvest in place, for 2 collections in Nuxeo to 1 collection in Merritt Stage. They have some objects in Nuxeo comprised zipped files -- and want to see what the results look like in Merritt.  

Collection details and ATOM feeds:

#### Collection 1
Latino Business Student Association records: https://registry.cdlib.org/admin/library_collection/collection/27565
Nuxeo source: /asset-library/UCI/SCA_Nuxeo-Merritt_testing/Latino Business Student Association records/For Merritt deposit
ATOM URL: https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27565.atom
Merritt -stage collection: ark:/13030/m5v71sk2

#### Collection 2
Artists' books collection: https://registry.cdlib.org/admin/library_collection/collection/26147/
Nuxeo source: /asset-library/UCI/artists_books
ATOM URL: https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_26147.atom
Merritt -stage collection: ark:/13030/m5v71sk2

### Tasks:
- [x] Establish feeds from these Nuxeo collection that harvest and deposit content into the existing UC Irvine Library Nuxeo collection (ark:/13030/m5v71sk2)

**Comment by mreyescdl** [comment]
Harvest of both feeds complete on Merritt stage.
Script names are:
   stage-27565-UCI_library.csh
   stage-26147-UCI_library.csh
