### ISSUE TITLE
Merritt-Sword to return stable URLs for updates in SWORD response

### ISSUE THREAD

**Issue by sfisher** [CDLUC3/mrt-doc#306]
Right now Merritt-Sword is returning URLs such as this for sword update URLs. `http://uc3-mrtsword-stg.cdlib.org:39001/mrtsword/edit/cdl_dryaddev/doi%3A10.5072%2Fdryad.t76hdrd0`  The ones on production are machine names, also.

The idea with SWORD is that the URLs should be used to update that dataset later, but using a specific machine name in the URL makes them break every time we change the machine name and breaks the API contract of a stable update URL.  It's probably better practice to use a CNAME that we can register and move to each new machine that is returned as part of the update URL.

Dryad can get around this problem by coordinating and updating all of our ~40k URLs every time Merritt changes machines, but probably better to give out stable URLs instead if we expect them to be used long into the future.

**Comment by terrywbrady** [comment]
Putting in TODO to make sure this is reviewed.

**Comment by elopatin-uc3** [comment]
@sfisher Was this addressed during the SWORD host migration to Linux2?

**Comment by sfisher** [comment]
Yes, this is now fixed and Ashley got a machine name we can use into the future that's not tied to a machine name which might change.  👍

**Comment by elopatin-uc3** [comment]
Great, thanks for confirming @sfisher 
Closing this out.
