### ISSUE TITLE
Presigned URL's from Merritt are http, should be https

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#309]
> Mixed Content: The site at ‘https://merritt-stage.cdlib.org/’ was loaded over a secure connection, but the file at ‘http://uc3-s3mrt1001-stg.s3.us-west-2.amazonaws.com/b6b7e5f7-a115-4e4d-9ef9-d8bd8624dbf1/data…’ was redirected through an insecure connection. This file should be served over HTTPS. This download will be blocked in future versions of Chrome.

If I make calls to the aws s3 api directly, I see that an https url is returned.

```
[ec2-user@ip-... ~]$ aws s3 presign twb-test-bucket/Lily.jpg
https://twb-test-bucket.s3.amazonaws.com/Lily.jpg?
```

I see the same results when I run the same command on Merritt Stage or Prod.

**Comment by dloy** [comment]
The http urls are generated from the java code specifically running on AWS. 

If the AWS presigned URL is modified http -> https. The behavior is the same for running the presigned. 

Neither SDSC Minio nor Wasabi generate http presigns. The code change to support this http -> https is made only on AWS URLs. The code needs to support Minio http generated by the docker version.
