### ISSUE TITLE
Clean up ingest servers ingestqueue dirs

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#31]
There are a lot of obsolete directories for successful (?) submissions in the /apps/ingest33121/tomcat/webapps/ingestqueue directory. Most of these contain only system files and are left over from successful submissions. They should be cleaned out if they're more than, say, 2 weeks old. I think there's already a script to do this--it just needs to be run routinely as a cronjob.
 - [ ]

**Comment by terrywbrady** [comment]
Reopen as a new issue if this persists
