### ISSUE TITLE
Feature request: Provide file hashes in UI and/or RSS feed

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#318]
Occasionally we find a batch of files sitting around that were supposed to have gone to Merritt, while on Merritt we find files with similar but not identical filenames. In order to determine whether the files are in fact the same, it would be handy to be able to get the hashes of the files in Merritt without having to download the files.

There are some tricks one can use to get it now, like following the presigned URL redirect chain till we get to the final S3 or MinIO link, sending a range request for zero bytes, and then getting a hash out of the ETag or the X-Amz-Meta-Sha256 header. But especially for large files, it would be handy just to be able to get the hash stored in the Merritt inventory database.

**Comment by terrywbrady** [comment]
This feature is visible to the demo user at the following URL: https://merritt-stage.cdlib.org/m/ark%253A%252F99999%252Ffk47h2xf3k/1

![image](https://user-images.githubusercontent.com/1111057/91613863-39c56e00-e935-11ea-9a31-a469cffaddc1.png)

**Comment by elopatin-uc3** [comment]
Comments from Rachael: We should check in with David Moles on the actual use case for noting digests in the UI. 

For myself, I think having them there with the ability to copy the non-truncated string is useful. For the hover text, a cursor change could be beneficial.

**Comment by terrywbrady** [comment]
@elopatin-uc3 , I am inclined to release this as is.  We can then get feedback on the feature after the release.  Since the field can be copy/pasted, is the existing cursor icon actually useful to convey that?  We might instead want to add a copy/paste button.

**Comment by elopatin-uc3** [comment]
@terrywbrady Okay, let's release this as is. Is it correct to assume the copy/paste button displayed here would show up as a cursor change, akin to the how a hand pointer appears? That could be useful.
