### ISSUE TITLE
Make manifest parsing in mrt-core more robust against extra blank lines etc.

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#32]
A manifest was rejected several times with this error message: 

Status message: [error]: HandlerDisaggregate: [error] HandlerDisaggregate: unpacking manifest file: /dpr2/ingest_home/queue/bid-8d23d961-da96-4270-a40c-935b0c5ed8e5/etd.checkm

I looked at it very closely and could see nothing wrong with it. I noticed that the line endings were only LF. I changed them to CR+LF and resubmitted and it succeeded. I wonder if this is yet another recent issue with the Rails upgrade. 
 - [ ]

**Comment by elopatin-uc3** [comment]
It turns out that there is an extra blank line at the end of the manifest.  The tailer "#%eof" should be the last line of the manifest.
Removal of the blank line fixes the submission.

Should I resubmit to production? (Mark Reyes - Jun 12, 2017)

**Comment by elopatin-uc3** [comment]
No, it's already in production. Could we ignore anything after the #%eof tailer? (Perry Willett - Jun 12, 2017)

**Comment by elopatin-uc3** [comment]
Yes, but it will involve David L. modifying the core library (org.cdlib.mrt.core.Manifest)
Ingest uses this library to do all its checkm processing. (Mark Reyes - Jun 12, 2017)

**Comment by terrywbrady** [comment]
@elopatin-uc3 , perhaps we should close this and create a new ticket based on feedback from the manifest tool

**Comment by elopatin-uc3** [comment]
Agreed; closing
