### ISSUE TITLE
Two temporary production replic servers for Wasabi

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#321]
## Temporary replic servers
This Issue involves getting two new linux2 replic servers to help process the backload of files being backed up to Wasabi. These servers will be used, hopefully, only until the end of June at which point the initial backup for Wasabi will be complete. The servers can then be decommissioned

### New Servers
uc3-mrtreplic05x2-prd
uc3-mrtreplic06x2-prd

All size and cofiguration for these machines will be the same as uc3-mrtreplic01x2-prd

No monitoring for these servers by Nagios will be required

**Comment by elopatin-uc3** [comment]
Closing as obsolete.
