### ISSUE TITLE
Return 4_x_x code on token requests that are close to the storage purge time

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#323]
@sfisher is working on a cache of presigned storage tokens.

Caching on the Dryad side will save both Merritt and Dryad some processing and storage costs.  It will also create a better use experience.

There is one risk associated with the cache support.  If the get by token request is made close to the purge date for the object, we could return a presigned url for an object that will be purged.

Assume the following
- One day retention: 24 hours
- Presigned expiration: 4 hours

If the request is made 0-20 hours after the object is constructed, the token status should be 200.  If the request is make 20-24 hours after the object is constructed, the 4xx (expired) status should be returned.

This would require one of the following changes
- Storage needs to be aware of the retention period in order to calculate the expiration time (24 hours - 4 hours)
- Could storage "renew" the retention period for high demand objects?  In this case, any time an object is requested, the object would be renewed for a new retention period.

**Comment by dloy** [comment]
Some comments. The AWS S3 does returns the expiration as part of both a meta request and as part of saving an object.  This expiration is a Date long value.

So a 410 status could be generated as part of a presign request where the timeout value > than the expiration time used for the saved content.

I'll take this on hopefully for the 5/13 sprint

**Comment by elopatin-uc3** [comment]
Had to alter the ticket title to get past a new spam feature in github

**Comment by terrywbrady** [comment]
https://raw.githubusercontent.com/CDL-Dryad/dryad-app/quick-presign-obj-test/documentation/presign-version/presignversion.png
