### ISSUE TITLE
Merritt Web host cleanup

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#326]
Production Linux 1 host is a m4.xlarge instance which currently looks over-provisioned.

A couple years back we had some SEVERE throughput issues with production Merritt.  Increasing this host size was part of a short term solution.  Since then we have reduced the network traffic through this host and thus we do not need such a large host.  
Still, all Ingest to Storage traffic is routed through Web.  This is no longer necessary now that Ingest has an EFS disk.  Any Merritt Ingest server can serve the data to Storage, not just the host that created it.  e.g.  Ingest01 processes the submission, but Ingest02 hosts it for Storage to gather.  This is achieved with the use of an RLB type round robin LB.

This would reduce traffic through web as well as simplify the Apache Web rewrite rules.

Needs more investigation.

**Comment by terrywbrady** [comment]
Old.  Recreate if needed
