### ISSUE TITLE
PDF docs (and other objects in public collections?) not available when signed in

### ISSUE THREAD

**Issue by dmolesUC** [CDLUC3/mrt-doc#329]
## Steps to reproduce

1. log in to Merritt as `ucbroa` (or user with equivalent privileges)
2. in the mrt-doc wiki, navigate to the article "[Adding Objects](https://github.com/CDLUC3/mrt-doc/wiki/Adding-Objects)"
3. Under "Submitting objects through the Merritt API", click the [Ingest specification document](https://merritt.cdlib.org/d/ark%3A%2F13030%2Fm55t8dtz/0/producer%2FMerritt-ingest-service-latest.pdf) link

## Expected

- Ingest specification is displayed

## Actual

- **Unauthorized (401)**

## Workaround

- Open the [URL](https://merritt.cdlib.org/d/ark%3A%2F13030%2Fm55t8dtz/0/producer%2FMerritt-ingest-service-latest.pdf) in an incognito window, triggering automatic guest login

## Notes

There's a branch of `mrt-dashboard`, [`public-permissions`](https://github.com/CDLUC3/mrt-dashboard/compare/public-permissions), that might fix this. IIRC it was basically feature-complete, but Perry never got around to testing it.

**Comment by terrywbrady** [comment]
@elopatin-uc3 , we resolved this some time ago.  During the CoreTrust documentation effort?

**Comment by dmolesUC** [comment]
I can confirm that when logged in as `ucbroa`, `https://merritt.cdlib.org/d/ark%3A%2F13030%2Fm55t8dtz/0/producer%2FMerritt-ingest-service-latest.pdf` works, via a redirect to `/api/presign-file` and from there to S3.

I think it's a little quirky that the first redirect is a 308 rather than a 302, as it implies that `/api-presign-file/<ark>/<version>/<path>` is the canonical URL for the file, but it does work.
