### ISSUE TITLE
Rewrite Merritt help for endusers

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#33]
A lot of the webpages, confluence pages, and other reports about Merritt purposed for endusers are out of date.
 - [ ] Compile list of pages to edit
 - [ ] Update pages

**Comment by elopatin-uc3** [comment]
Merritt site:
https://merritt.cdlib.org/
https://merritt.cdlib.org/docs/merritt_handout.pdf
https://merritt.cdlib.org/docs/merritt_user_guide.pdf
https://merritt.cdlib.org/help (not sure how this is related to user guide)

Confluence:
https://confluence.ucop.edu/display/Curation/Merritt+Enhancements+and+Developments
https://confluence.ucop.edu/display/Curation/Microservices (check how current any of these microservice specs are)
https://confluence.ucop.edu/display/Curation/Cost+Modeling

CDL website:
http://www.cdlib.org/services/uc3/merritt/
http://www.cdlib.org/services/uc3/merritt/merritt_faq.html
http://www.cdlib.org/services/uc3/docs/Merritt_handout_final_campus_contacts.pptx


 (Perry Willett - Jun 21, 2017)

**Comment by elopatin-uc3** [comment]
After GitHub migration (David Moles - Jun 15, 2018)

**Comment by terrywbrady** [comment]
@elopatin-uc3 Closing, this was updated for the core trust effort
