### ISSUE TITLE
Audit Report Errors

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#337]
### Summary
On 5/24/20-5/26/20, the Audit service reported a total of 377 item failures.

### Tasks
- [x] Root cause source of recent Audit errors
- [ ] Add Terry and Mark to the report distribution

**Comment by elopatin-uc3** [comment]
From @dloy: Fix passing accessMode to prevent attempts at Glacier reads in audit:
https://github.com/CDLUC3/mrt-cloud/pull/6

**Comment by elopatin-uc3** [comment]
Closing as duplicate of #345
