### ISSUE TITLE
SSL updates for Merritt LDAP stage and production

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#348]
### Summary
An expired intermediate SSL certificate has caused refusals of connection attempts to the Merritt LDAP service.

### Tasks
- [x] LDAP service update
- [x] Associated UI code change
- [x] Documentation updates

**Comment by mreyescdl** [comment]
Updated LDAP docs to reflect what I did to import the new Intermediate cert

https://confluence.ucop.edu/display/UC3/LDAP+operations?focusedCommentId=236063361#comment-236063361

**Comment by mreyescdl** [comment]
Updated all LDAP Nagios service checks scripts to NOT trust all certificates.
Doing so allowed the INT cert issue to go unnoticed.
