### ISSUE TITLE
Objects with multiple versions with same version number

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#36]
Some objects have multiple versions with same version number, eg "version 2". The multiple versions have the same or close timestamp. Same as https://www.pivotaltracker.com/story/show/72807160
 - [ ]

**Comment by elopatin-uc3** [comment]
See attached screenshot for ark:/28722/bk0005m1w4b (Perry Willett - May 28, 2015)

**Comment by elopatin-uc3** [comment]
See also ark:/28722/bk0005m1z28 for another example
 (Perry Willett - May 28, 2015)

**Comment by elopatin-uc3** [comment]
Reassigning to @pwillett to find some test cases (David Moles - Jun 15, 2018)

**Comment by terrywbrady** [comment]
Closing ... open new issue if this is still occurring
