### ISSUE TITLE
Refine object addition and metadata documentation

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#361]
### Summary
Several sections of our documentation related to ingesting new content, and updating metadata could be refined through introduction of additional context, and more detailed examples.

Adding objects:
https://github.com/CDLUC3/mrt-doc/wiki/Adding-Objects
Metadata:
https://github.com/CDLUC3/mrt-doc/wiki/Metadata

### Tasks
- [ ] Add examples to each of the above sections (...)
- [ ] Add context as well (...)

**Comment by terrywbrady** [comment]
Closing.  Core Trust documentation refresh
