### ISSUE TITLE
UNM Migration: dealing with overlapping collections

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#362]
## Problem
We are looking at moving the Merritt content now stored at UNM to the Dryad storage at AWS.

There are currently 2 collections at UNM:
- oneshare_dataup with 90 objects
- dataone_dash with 208 objects

The problem is that 62 of the oneshare_dataup objects are also part of the dataone_dash collection. Also, that there are 23 objects in the oneshare_dataup collection that are not part of the dataone_dash collection.

This overlap was the result of an error that occurred back in 2016.  The intent of the fix was to treat all oneshare_dataup as dataone_dash - so content in both collections could be accessed regardless of which collection the user came in on.

Right now the issues are
- the overlap of oneshare_dataup is not completely in dataone_dash so not all content can be found from either collection
- since there is only one mrt-membership.txt file for any object, an object will only be in a single collection when processed by inv.  If the object is new it will be put into that collection and no duplicate will appear in the inv_collections_inv_objects.

## Some possible solutions
_Goal_: 
- Avoid any re-ingesting of old content
- Find some mechanism where Dryad users can find the content regardless of which collection the user comes in on

### Dryad mapping?
If Dryad can do any mapping of a users collection to another then only allow dataone_dash as a collection in Merritt. All oneshare_dataup not currently in dataone_dash would be added to data_one.

_Problem_: the mrt-membership.txt file will be wrong for a number of objects. As long as we do not need to build the inv databases from scratch this is not an issue.

### Set collection table based on mrt-membership.txt
Use the mrt-membership.txt entry to define which collection the object goes in.  This would keep Merrit consistent.
_Problem_: 
- this reintroduces the problem we had before of 2 collections
- it would make some collection content unavailable (or searchable?) in Dryad from another collection

### Something else?

**Comment by dloy** [comment]
Another potential problem that needs to be resolved is how billing will be done on the Dryad with overlapping collections

**Comment by sfisher** [comment]
We have some flexibility in how we access things.  Every dataset is only in one collection in Merritt through the tenant_id.  But we can make more than one tenant if we need to.

No new datasets are coming into these collections in Dryad.  However we DO allow updates to existing content for these legacy things.

I'm not quite sure I understand the problems here in much depth, but we can re-associate datasets with different tenants in our database and each tenant can have its own merritt collection.  If we need to duplicate tenants with slightly different settings, we can and then assign different datasets to different tenants.

So if it's complicated then you can specify how we should map things and we can map them to different collections however you specify.

If it is helpful, I can get you a list of the objects/versions we have in our database associated with DataONE (which I think is both of these collections).  I'm not sure how it is mapping two merritt collections into one in Dryad but I believe it was some trickery Perry or someone set up.

**Comment by elopatin-uc3** [comment]
I can confirm that the "dataone_dash_submitter" account in LDAP has read/write/download permissions to both the DataONE Dash and ONEShare DataUp collections in Merritt.

**Comment by sfisher** [comment]
This file should be the items our database is tracking.  IDK if those Merritt collections also contain some garbage that we just don't care about.

[merritt_dataone_stuff.txt](https://github.com/CDLUC3/mrt-doc/files/4766751/merritt_dataone_stuff.txt)

**Comment by sfisher** [comment]
These are the DataONE datasets that show in our stage system.

[dataone_stage_datasets.txt](https://github.com/CDLUC3/mrt-doc/files/4783099/dataone_stage_datasets.txt)

**Comment by dloy** [comment]
Overlapping collections is not a problem. Dryad handles successfully and because of a single user for the prod collections there should not be any additional billing based on the overlap being charged twice.
