### ISSUE TITLE
Investigate options that would allow Merritt to deprecate use of SWORD 

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#372]

**Comment by elopatin-uc3** [comment]
https://github.com/CDL-Dryad/dryad-product-roadmap/issues/809

**Comment by terrywbrady** [comment]
@elopatin-uc3 , I think this is a duplicate of #939

**Comment by elopatin-uc3** [comment]
Yes, agreed @terrywbrady. Closing
