### ISSUE TITLE
Billing Campus Taxonomy

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#376]
The FY2018 invoices had 3 separate items for UCB: Library, Env Design, and Transportation.

- Does that need to continue?
- Does each get a free 10TB?

When generating mime usage reports, can the "campus" taxonomy be the same as the taxonomy used for invoices or are different groupings needed?

What is the "campus" for Dryad, DataOne, Open Context, and UC Press?

**Comment by elopatin-uc3** [comment]
@terrywbrady I will be discussing this with John and Catherine tomorrow during our weekly catch-up meeting.

**Comment by elopatin-uc3** [comment]
@terrywbrady John was unable to attend our weekly check-in today. Catherine and I talked about this, and are leaning toward some sort of proportional distribution of the 10TB across campus owners, along with a content threshold per owner to consider. I've set up some dedicated time to discuss this approach (7/8@1:30pm).

**Comment by elopatin-uc3** [comment]
@terrywbrady We had a good, almost two hour conversation about this on Wednesday 7/8. The upshot is, we are going to use a very simple approach, for which the billing reports are already optimized. We will keep all charges for a campus rolled up to one total, multiple owners included. A bill will be sent to UCB Library, which includes content from all 7 owners. Going forward, we should focus on getting dashboards up and running, so we can go back to campuses and walk through content.

**Comment by elopatin-uc3** [comment]
With regard to the "Other" ownership group, I think this can stay as it is. Open Context is the largest unknown there, and we'll need to talk to them directly if they begin to add more content. 

Also, it will be good to remove the old Dash collections soon, so we can exclude these numbers from local campus ownership (and then provide a Dryad dashboard for them).

**Comment by terrywbrady** [comment]
@elopatin-uc3 - I recommend closing this one

**Comment by elopatin-uc3** [comment]
Yes, agreed; closing
