### ISSUE TITLE
SSM + Personal Database Credential Migration Follow Up

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#377]
- [x] Get reply from IAS on cdlsys ticket on 6/23
- [x] Create credentials for David
- [x] Create credentials for Marisa
- [x] Develop scripts to access mysql CLI using SSM parameters (Terry and Ashley)
  - ideally without displaying the credential
- [ ] Create prod accounts

**Comment by elopatin-uc3** [comment]
@terrywbrady I saw your message in slack asking if I needed access. Until we have all of the collection automation in place, I still need `invro` and `invrw` access from my local box.
