### ISSUE TITLE
Delete content from obsolete storage node on merritt-stage

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#38]
Node 2111 doesn't seem to have been migrated to SDSC for merritt-stage. There are 36,421 objects stored in node 2111. If this content is no longer available, it should be deleted. 
 - [ ]

**Comment by elopatin-uc3** [comment]
Not sure--I can retrieve object with ARK: ark:/28722/bk0003d653t
which according to the database is stored in node 2111. (Perry Willett - Jun 27, 2017)

**Comment by terrywbrady** [comment]
Close as obsolete
