### ISSUE TITLE
SSM Params: Create MySql Wrappers

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#384]
- [x] Create repo: https://github.com/cdluc3/uc3-aws-cli
- [x] Create mysql wrapper code (Terry)
- [x] Deploy jq to all boxes (Ashley)
- [x] Deploy uc3-aws-cli to all boxes (Ashley)
- [ ] Deploy Merritt Billing cron (stage)
- [ ] Deploy Merritt Billing cron (prod)
- Retire old billing process <-- Moved to #431 
```
./uc3-mysql.sh billing readwrite -- -e 'call update_billing_range();' 
./uc3-mysql.sh billing readwrite -- -e 'call update_object_size();' 
```
```

**Comment by terrywbrady** [comment]
Some duplication of #393

**Comment by terrywbrady** [comment]
In the interim, I have setup a cron in my home account on the ops box. 

```
bash-4.2$ crontab -l
0 1 * * * ~/dbSyncCron.sh
bash-4.2$ cat dbSyncCron.sh 
#!/bin/bash

uc3-mysql.sh billing -rp /uc3/mrt/stg/ -- -e 'call update_billing_range();'
uc3-mysql.sh billing -rp /uc3/mrt/stg/ -- -e 'call update_object_size();'
uc3-mysql.sh billing -rp /uc3/mrt/prd/ -- -e 'call update_billing_range();'
uc3-mysql.sh billing -rp /uc3/mrt/prd/ -- -e 'call update_object_size();'
```

**Comment by ashleygould** [comment]
This tool set has been deployed to all uc3 merritt hosts via puppet.

**Comment by terrywbrady** [comment]
@ashleygould , will you create the cron entries within the dpr2 account or is that something that I can do?

**Comment by ashleygould** [comment]
@terrywbrady I will do it.  You don't have write access to puppet.
