### ISSUE TITLE
Burst credits have been consumed several days in a row, starting on 7/2, through 7/6.

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#391]

**Comment by terrywbrady** [comment]
@dloy paused the workload for each of the audit servers.  Within 3 hours, the credits were restored to 100%.

David put one server back into service, and the credits drained to 50% in less than an hour.

- [ ] Is there a bug in the audit queries that is causing items to be reprocessed?
- [ ] Is there a bug in some object content that is putting the audit service into this state?  
  - if the current objects being processed were skipped, would processing resume normally?
- [ ] If audit was restarted with fewer active threads, would that help?
- [ ] Is a queue/time delay needed in the audit service?
- [ ] Is a database transaction needed to isolate work being served up to audit?
- [ ] Are there any recent coding changes (around Jun 5) that could account for this recent problem?

**Comment by elopatin-uc3** [comment]
Are the changes for #345 at all related?

**Comment by terrywbrady** [comment]
I recommended the following query change to @dloy :

```
select 
  count(*) 
from 
  inv.inv_audits 
where 
  verified <= (
    select 
      date_add(min(verified), interval 30 day) 
    from 
      inv.inv_audits
  ) 
order by 
  verified desc 
limit 250;
```

**Comment by terrywbrady** [comment]
Issue resolved with Audit2
