### ISSUE TITLE
What process is draining 50% of RDS IOPS credits daily at 12:30pm?

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#392]
From Martin: The backup window is configured as 4:00 am - 5:00 am each day.

**Comment by elopatin-uc3** [comment]
@terrywbrady can you let me know if this is still happening? I can't find evidence of it in Librato, but may not have appropriate parameters plugged in.

**Comment by terrywbrady** [comment]
@elopatin-uc3 , I do not think this is still happening.

**Comment by elopatin-uc3** [comment]
Okay, thanks. I'm going to go ahead and close this.
