### ISSUE TITLE
[Inventory] Error - Malformed \uxxxx encoding.

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#403]
Inventory fails in processing object due to encoding issue.

Start thread:http://storage.cdlib.org:35121/manifest/9501/ark%3A%2F13030%2Fm5r269bc
EXception:SaveObject: Exception for entry id=ark:/13030/m5r269bc - Exception:org.cdlib.mrt.inv.extract.StoreIngest-setNewIngestProperties:166 GENERAL_EXCEPTION[Unexpected Programmic exception] java.lang.IllegalArgumentException: Malformed \uxxxx encoding.

**Comment by mreyescdl** [comment]
Full stack trace is:

`ZooHandler consume(48691): - item:mrtQ-000001117587
Start thread:http://storage.cdlib.org:35121/manifest/9501/ark%3A%2F13030%2Fm5h470x5
***Start[0]:2020-07-13T10:16:36-07:00
ZooHandler sleep:60000
Virtual: none - inputseq == targetseq:16
java.lang.IllegalArgumentException: Malformed \uxxxx encoding.
        at java.util.Properties.loadConvert(Properties.java:574)
        at java.util.Properties.load0(Properties.java:391)
        at java.util.Properties.load(Properties.java:341)
        at org.cdlib.mrt.inv.extract.StoreIngest.setNewIngestProperties(StoreIngest.java:159)
        at org.cdlib.mrt.inv.extract.StoreIngest.extract(StoreIngest.java:137)
        at org.cdlib.mrt.inv.extract.StoreIngest.<init>(StoreIngest.java:127)
        at org.cdlib.mrt.inv.extract.StoreIngest.getStoreIngest(StoreIngest.java:103)
        at org.cdlib.mrt.inv.action.SaveObject.setInvIngests(SaveObject.java:1139)
        at org.cdlib.mrt.inv.action.SaveObject.setCurrent(SaveObject.java:1097)
        at org.cdlib.mrt.inv.action.SaveObject.setInvVersions(SaveObject.java:1075)
        at org.cdlib.mrt.inv.action.SaveObject.setObject(SaveObject.java:529)
        at org.cdlib.mrt.inv.action.SaveObject.process(SaveObject.java:381)
        at org.cdlib.mrt.inv.action.SaveObject.process(SaveObject.java:363)
        at org.cdlib.mrt.inv.action.ProcessItem.saveObjectRetry404(ProcessItem.java:188)
        at org.cdlib.mrt.inv.action.ProcessItem.process(ProcessItem.java:165)
        at org.cdlib.mrt.inv.action.ProcessItem.run(ProcessItem.java:142)
        at java.lang.Thread.run(Thread.java:748)`

**Comment by mreyescdl** [comment]
Another failure with the same error message

```EXception:SaveObject: Exception for entry id=ark:/13030/m5r269bc - Exception:org.cdlib.mrt.inv.extract.StoreIngest-setNewIngestProperties:166 GENERAL_EXCEPTION[Unexpected Pro
grammic exception] java.lang.IllegalArgumentException: Malformed \uxxxx encoding.
ProcessItem: process  - manifestURLS=http://storage.cdlib.org:35121/manifest/9501/ark%3A%2F13030%2Fm5r269bc - processStatus=failed```

**Comment by mreyescdl** [comment]
The 2 failures show up in Zookeeper as
```
mrtQ-000001117587: [failed: Tue Jul 21 09:28:32 PDT 2020] {manifestURL=http://storage.cdlib.org:35121/manifest/9501/ark%3A%2F13030%2Fm5f81nds}
mrtQ-000001133635: [failed: Tue Jul 21 09:28:34 PDT 2020] {manifestURL=http://storage.cdlib.org:35121/manifest/9501/ark%3A%2F13030%2Fm5r269bc}
```

**Comment by mreyescdl** [comment]
The following object was resubmitted by user, but still triggers the error.  This is because there are 3 versions and versions 1 and 2 still have the *\U* in the title.  These two version still trigger the error in Inventory.

David is looking at a fix.

```http://storage.cdlib.org:35121/manifest/9501/ark%3A%2F13030%2Fm5r269bc

version 3
title:  Kurzgeschichten unserer Zeit / [fumur den Schulgebrauch zusammengestellt von Wilhelm Helmich und Paul Nentwig]. 67350632D-B3632752.pdf

version 2
title:  Kurzgeschichten unserer Zeit / [fum\ur den Schulgebrauch zusammengestellt von Wilhelm Helmich und Paul Nentwig]. 67350632D-B3632752.pdf
```

**Comment by dloy** [comment]
Since inv process all existing versions of an object, we ran into the problem Mark notes above.

I have a fix to inventory to remove all "\" characters that appear in system/mrt-ingest.txt. I was able to test his locally in StoreIngest.java and it works.

We will need to discuss when to make this update

**Comment by elopatin-uc3** [comment]
@dloy @mreyescdl to collaborate to move David's fix onto stage. Run test suite to help detect if this change impacts any other microservices.

**Comment by dloy** [comment]
Mechanism exists to prevent inv from failing on these bad characters "\u". Reviewing this again, I feel that recreating this object using Mark's 3rd version is a better approach. Allowing this record in with the "\u" in the "what" entry could cause some potential rippling in other objects.

Proposal - recreate using different ark with corrected data- delete old object when successful.

**Comment by terrywbrady** [comment]
I recommend putting this investigation on hold and restart the investigation with ingest. See #716

**Comment by mreyescdl** [comment]
Resubmitted object after downloading data and fixing metadata

https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm5xh6p0g

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl. Moving this over to Done.

**Comment by terrywbrady** [comment]
It is exciting to see this in the Done column!
