### ISSUE TITLE
Explicitly verify that the storage service is cleaning up (or at least zeroing out) archive files once the transfer to cloud storage is complete.

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#404]
This is a follow up from the 7/13 team meeting
- Mark suggested zeroing out the files if Java is not releasing them.
- Terry has had some past luck by forcing garbage collection to free file handles.

**Comment by dloy** [comment]
Tracked this problem down to a partial deletion of content. The storage code would remove the component directory created for building the zip file but not the zip file itself after it had been uploaded to AWS. 

The change:
https://github.com/CDLUC3/mrt-store/commit/7673b93c56e6f9f96b14a968e2a67871d74e58d5

Stage Jenkins:
http://builds.cdlib.org/job/mrt-store-pub/126/console

Stage install: Jul 20 16:24
