### ISSUE TITLE
On the collection home page in Merritt, provide a total size metric for "unique" collection content.

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#412]
#### Summary
Recent correspondence with UCI (Adrian Petrisor), alongside byte counts reported in the Digital Preservation Strategy Working Group phase 2 report, has brought an issue to the team's attention – that the difference between the "total size" metric on a collection home page, and actual billable size for unique content, (that which exists across versions) is not captured or articulated. While "total size" measures the overall size of all objects in a collection, regardless of deltas between object versions, based on this feedback, it would be useful to provide a total size metric related to what we internally refer to billable size/unique content. 

#### Tasks
- [ ] Provide a "total unique size" metric on the collection home page in the UI, and include a brief explanatory string.

**Comment by terrywbrady** [comment]
As the guest user, you can preview this feature here: https://merritt-stage.cdlib.org/m/merritt_demo

![image](https://user-images.githubusercontent.com/1111057/91613536-91170e80-e934-11ea-9169-f20ef7c7cfbc.png)

**Comment by elopatin-uc3** [comment]
Comments from Rachael: As the top three items in the Overview table do not have hover text, this makes it less likely for users to find this text for the "total size" and "unique size" entries. If possible, she suggested sticking with modified labels, rather than the addition of hover text. e.g. "total size (all versions)" and "total size (excl. duplicates)". Using these labels will also benefit screen readers for accessibility purposes. That said, I think we still need to come up with what we think is a good name/phrase for the unique size entry.
