### ISSUE TITLE
Prod install archive temp fix on storage 3 and 4

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#413]
## Problem
archive temp files for presign object requests have not been completely removed after content has been uploaded to AWS S3.

## Producion Install
The initial install of this fix will be to the new storage production servers that are dedicated to UI handling, including presign object creation. 

These servers currently are not running in production and do not required additional down time except for installation of link for the UI. Later mrtstore01x2 and mrtstore02x2 changes can be handled separately at later date. This code should not impact these servers when used by ingest.

### Servers
- uc3-mrtstore03x2-prd
- uc3-mrtstore04x2-prd

### Github code change
https://github.com/CDLUC3/mrt-store/commit/7673b93c56e6f9f96b14a968e2a67871d74e58d5

### Jenkins
http://builds.cdlib.org/job/mrt-store-pub/128/console

### Steps
- [x] deploy uc3-mrtstore03x2-prd
- [x] deploy uc4-mrtstore03x2-prd

**Comment by elopatin-uc3** [comment]
Mark is going to adjust the cron associated with removing archive temp files so deletions occur after three days, rather than 24hrs.
