### ISSUE TITLE
UCLA MARC record XSL changes for encoding level and field 856 OA indicator

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#415]
#### Summary
Akin to recent changes for UCSD, update the encoding level in the MARC record leader to 7, from OCLC's level K (which is being retired); and add subfield $7 value zero (0) to the field 856 eScholarship link to indicate that an item is open access, if not embargoed.

##### Code references
https://github.com/CDLUC3/uc3-etds/pull/2/files (changes for UCSD)
https://github.com/CDLUC3/uc3-etds/blob/master/xsl/PQ2MARC.xsl

#### Tasks
- [ ] Change encoding level in record leader to 7 (line 262)
- [ ] Add 856 subfield (line 472)

**Comment by terrywbrady** [comment]
@elopatin-uc3 - still applicable?

**Comment by elopatin-uc3** [comment]
No recent requests from UCLA for this; closing
