### ISSUE TITLE
July 22 - doi:10.5068/D16T06 

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#417]
See David's email about the clobbered update

**Comment by terrywbrady** [comment]
@dloy , I read your email about this issue.  I am unclear if additional action is needed for this issue.

**Comment by elopatin-uc3** [comment]
Sounds like we should ask Dryad to resubmit the current/unchanged version, per Scott:
"Thanks, David.
It seems OK from our UI.  I think if we want to be sure the metadata is correct in Merritt, we could just submit it again without any file changes.
--Scott"

**Comment by elopatin-uc3** [comment]
Noting this dataset is on version 6 now:
https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm56459xb/6
https://datadryad.org/stash/dataset/doi:10.5068/D16T06

Closing
