### ISSUE TITLE
Create UI preview load balancer for verifying code changes in progress

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#418]
This would be a duplication of the Apache load balancer for merritt.cdlib.org and merritt-stg.cdlib.org.  It would be infrequently used, but it would be useful when verifying Merritt ui deployments.

merritt-preview.cdlib.org
merritt-preview-stg.cdlib.org

By default, this would point to the same ui instances as the primary load balancer.

As UI servers are taken out of the main load balance for redeployment, this DNS could be used to verify changes to newly deployed code.

Question: restrict this to the CDL network?
- [x] prod preview available
- [x] stage preview (still needed)

**Comment by terrywbrady** [comment]
https://www.pivotaltracker.com/n/projects/2157590/stories/174266216

**Comment by terrywbrady** [comment]
Mark and Martin created a solution using our Nagios Apache server.

I documented our preview URL here: https://confluence.ucop.edu/display/UC3/Merritt+UI

**Comment by mreyescdl** [comment]
Stage preview is complete
https://ui02-aws-stg.cdlib.org
