### ISSUE TITLE
Research: Shared EFS ingest storage with Merritt Storage

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#421]
### Proposal
Currently Ingest inputs all content to a local EFS storage that is shared with all ingest servers.  After this content is built, Ingest sends a Storage Manifest.txt to a storage service that then pulls all of this content to local disk on the storage server host.

This proposed process would include the shared EFS on all Merritt Storage servers.  The Manifest.txt would still be sent to Storage. Storage instead of doing a secondary copy from ingest would already have this content on EFS to be input as file storage instead of through one or more HTTP calls to ingest.

By eliminating this secondary copy:
- the content is written once to EFS by ingest
- no requirements are needed for providing a 1T copy for storage processing
- copy times are eliminated
- storage may still require the RLB because of the extended read to write to the cloud but should cut timing by maybe 1/3

#### Ingest
- use file URLs for the storage Manifest.txt
e.g.
file:///dpr2scratch/bid.../jid.../file.txt

- would remove the requirement for the data on ingest to be in an http accessible file

#### Storage
- identify content as local file and use instead of temp space
- eliminate deletion of file content after has been processed - all deletion would remain on Ingest
- possible later reduction of temp space on storage

One question would be whether the EFS content has the same read stability as normal disk storage. If similar to NFS then some added testing on read might be required.

Might be useful to make this change as part of the current Merritt Storage upgrade.

## Follow On Tasks
- The Apache LB for storage will not be immediately obsolete based on this effort
- Can storage confirmation to ingest be made async?

**Comment by mreyescdl** [comment]
Recently Storage has gone to a i3 architecture which is high performance storage.  This has an attached 1TB disk (not EBS.)

Does this affect this effort?

**Comment by mreyescdl** [comment]
A little background on how Ingest uses scratch space.  
Only the "queue" directory is used for scratch.  The queue is where submissions are uploaded and processed.

```$ ls -dl /dpr2/ingest_home/queue
lrwxrwxrwx 1 dpr2 dpr2 41 Jan 10  2020 /dpr2/ingest_home/queue -> /apps/ingest-prd-shared/ingest_home/queue```

Each submission has a batch and job ID.  In the case of synchronous submissions (job only) the batch ID is `JOB_ONLY`

batch and job ID are created as directories within the queue area. 
Within the job directory processing is done in `producer` and `system` directories
