### ISSUE TITLE
[Investigation] Audit and Replic services move to i3 hosts (high performance storage)

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#424]
Now that Storage is on i3 architecture, should we follow this lead with other services that have large scratch volumes?

Replic and Audit both have 1TB /dpr2scratch volumes to process large data sets.  This is implemented as a 1TB mounted EBS volume, which is costly.
Would it be cheaper and more efficient to move to i3?

https://aws.amazon.com/ec2/instance-types/i3/

**Comment by mreyescdl** [comment]
Here is the activity involved with moving Storage to i3

https://github.com/CDLUC3/mrt-doc/issues/422

**Comment by terrywbrady** [comment]
Already done
