### ISSUE TITLE
[Ingest] Remove Apache reverse proxy for Storage retrieval 

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#425]
We will simplify the data flow for Storage retrieval from Ingest.

Now that we have remote Storage nodes, it is possible to go directly to an Ingest worker for data retrieval.
We will eliminate the Apache component for data retrieval which will save cost and be more efficient 

**was**:
```
http://merritt.cdlib.org/ingest_node_ingest01/ingestqueue/JOB_ONLY/jid-43a4eed2-9639-40b0-95f9-63791707ef7d/producer/mrt-datacite.xml
```

**will be**:
```
http://ingest01.cdlib.org:33121/ingestqueue/JOB_ONLY/jid-43a4eed2-9639-40b0-95f9-63791707ef7d/producer/mrt-datacite.xml
```

**Comment by terrywbrady** [comment]
Implemented as EFS
