### ISSUE TITLE
It appears that the # sign in filenames breaks presigned URL downloads

### ISSUE THREAD

**Issue by sfisher** [CDLUC3/mrt-doc#426]
It's kind of annoying that users put this character in filenames and maybe we shouldn't let them.

But we have a number of examples of filenames with the \# sign that make downloads fail.

MerrittError: Merritt couldn't create presigned URL for `http://merritt.cdlib.org/api/presign-file/ark%3A%2F13030%2Fm5t77r2w/2/producer%2FExperiment_KLF2_gfp_B220_DAPI_GFP_CD4_GL7_%233.tif?no_redirect=true`

`http://merritt.cdlib.org/api/presign-file/ark%3A%2F13030%2Fm5dr82dx/7/producer%2F%23README?no_redirect=true`

`http://merritt.cdlib.org/api/presign-file/ark%3A%2F13030%2Fm59d24z8/3/producer%2FPG_6_p1_f1_%232.avi?no_redirect=true`

`http://merritt.cdlib.org/api/presign-file/ark%3A%2F13030%2Fm5wb0j83/3/producer%2F%233_MEGA_Bbengalensiis_MgMg.meg?no_redirect=true`

PS.  The encoded \# sign is %23 in the urls above.

**Comment by sfisher** [comment]
At first I thought this was a problem with the http to https redirects, but maybe not.  It seems to produce the "not found" even if going directly to https, also.

```
curl -iL -u <user>:<pass> "https://merritt.cdlib.org/api/presign-file/ark%3A%2F13030%2Fm5dr82dx/7/producer%2F%23README?no_redirect=true
HTTP/1.1 404 Not Found
# ... etc ...

curl -iL -u <user>:<pass> "http://merritt.cdlib.org/api/presign-file/ark%3A%2F13030%2Fm5dr82dx/7/producer%2F%23README?no_redirect=true"
HTTP/1.1 302 Found
Location: https://merritt.cdlib.org/api/presign-file/ark:%252F13030%252Fm5dr82dx/7/producer%252F#README?no_redirect=true
# ... the redirect adds extra encoding above, but then still gets the same result below
HTTP/1.1 404 Not Found
```

Strangely enough, I can go to the Merritt U ( https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm5dr82dx ) and the download for \#README works in one place, but doesn't in another.

Under "Current Version" on the right side it works, but if I click "6 more files" and choose it from the "User Files" list then it doesn't.

These are the URLs for those:

```
# the extra encoded one below seems to work
https://merritt.cdlib.org/api/presign-file/ark%253A%252F13030%252Fm5dr82dx/8/producer%252F%2523README
# the standard encoding doesn't work 
https://merritt.cdlib.org/api/presign-file/ark%3A%2F13030%2Fm5dr82dx/8/producer%2F%23README
```
This one works.
![Screen Shot 2020-07-31 at 9 51 35 AM](https://user-images.githubusercontent.com/105433/89058342-fe268c80-d313-11ea-8791-2e0d648e7eec.png)

This one doesn't.
![Screen Shot 2020-07-31 at 9 53 00 AM](https://user-images.githubusercontent.com/105433/89058422-1f877880-d314-11ea-918e-00e27f184fb9.png)

**Comment by sfisher** [comment]
Hi @terrywbrady Can you say more about "encoding expectations on the server."

Should I be changing something to do some kind of special encoding in addition to standard URL Encoding?

This is an example that still doesn't seem to work.  https://datadryad.org/stash/dataset/doi:10.5061/dryad.f7m0cfxrq  (click the file list and click "#README" in the list.)

Thanks,

          Scott

**Comment by terrywbrady** [comment]
@sfisher , I have not changed any code in production yet.  

If you open the following page, https://merritt.cdlib.org/m/ark%3A%2F13030%2Fm5dr82dx, you will see that the URL for that file is double encoded.  

```
Merritt UI Object Page
https://merritt.cdlib.org/api/presign-file/ark%253A%252F13030%252Fm5dr82dx/8/producer%252F%2523README

Merritt UI Version Page
https://merritt.cdlib.org/api/presign-file/ark%3A%2F13030%2Fm5dr82dx/8/producer%2F%23README
```

Without the double encoding, the request fails.  I plan to modify the version page to match the object page.

Here is a commit that implements the switch.  

https://github.com/CDLUC3/mrt-dashboard/pull/74/commits/531467f63ad96d3687bf9e4f2587617d489c0c8d

I wish that I understood the origin of this double encoding.  I do not know the origin, but it seems to resolve some issues.  

Let me know if you would like to chat about this.

**Comment by sfisher** [comment]
Thanks, Terry.  I'll try things on our dev or stage.  Thanks!

**Comment by sfisher** [comment]
Thanks @terrywbrady .

I'm still seeing this problem when I test against the stage server. For example this item on our development machine (open files and click the download).  https://dryad-dev.cdlib.org/stash/dataset/doi:10.5072/FK25H7MF7Q

It returns this error.

```
Merritt couldn't create presigned URL for https://merritt-stage.cdlib.org/api/presign-file/ark%3A%2F99999%2Ffk41v6v824/1/producer%2F%231_best_fun_file.png?no_redirect=true
```

It appears to me as though everything is encoded to http standards.  (%2f is the slash and %23 is the number sign).  I'm curious what your application is actually receiving.

I'm happy to get on a call when you have time.  I suppose I could double-encode if it's really needed, but it feels like a really "dirty hack" to me to require double encoding.

**Comment by terrywbrady** [comment]
@sfisher , here is what I see in the logs.

```
Started GET "/api/presign-file/ark:%2F99999%2Ffk41v6v824/1/producer%2F" for 172.31.35.27 at 2020-08-25 14:17:31 -0700
Processing by FileController#presign as HTML
  Parameters: {"object"=>"ark:/99999/fk41v6v824", "version"=>"1", "file"=>"producer/"}
```

I think the # is being treated as a # (bookmark) rather than being part of the URL.  

The links created from the Merritt UI are working.  They are generating a link with the double encoding.

```
            <%= link_to file_basename,
              :controller       => :file,
              :action           => :presign,
              :object           => object,
              :version          => version,
              :file             => file
            %>
```

I can match the URL with the following algorithm

```
require 'cgi'
prefix='https://merritt-stage.cdlib.org/api/presign-file/'
ark='ark:/99999/fk41v6v824'
ver=1
file='producer/#1_best_fun_file.png'

# this works
"#{prefix}#{CGI.escape(ark)}/#{ver}/#{CGI.escape(CGI.escape(file))}"
# this fails
"#{prefix}#{CGI.escape(ark)}/#{ver}/#{CGI.escape(file)}"
```

If I choose a file without the # sign, then the file does not need double encoding

```
require 'cgi'
prefix='https://merritt-stage.cdlib.org/api/presign-file/'
ark='ark:/99999/fk41v6v824'
ver=1
file='producer/mrt-datacite.xml'
# this works
"#{prefix}#{CGI.escape(ark)}/#{ver}/#{CGI.escape(CGI.escape(file))}"
# this also works
"#{prefix}#{CGI.escape(ark)}/#{ver}/#{CGI.escape(file)}"
```

**Comment by terrywbrady** [comment]
For now, @sfisher will treat a # in a filename as a special case and mimic the double encoding behavior.

When we tackle https://github.com/CDLUC3/mrt-doc/issues/360, we should consider this more systematically.
