### ISSUE TITLE
Add perl URI function on EC2s

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#428]
High priority
URi::Escape is currently used by Perl functions for prod and stage Merritt Delete  and also for Replic support utilities

Add
URI functions to

- uc3-mrtstore02x2-stg

- uc3-mrtstore02x2-prd

- uc3-mrtsandbox2-stg

**Comment by ashleygould** [comment]
https://www.pivotaltracker.com/story/show/174182181

**Comment by ashleygould** [comment]
This is done
