### ISSUE TITLE
Request:  Make these collections private

### ISSUE THREAD

**Issue by sfisher** [CDLUC3/mrt-doc#429]
Can you make these collections private?

```
ucb_dash
ucd_lib_dash
uci_dash
ucla_dash
ucm_dash
ucop_dash
ucpress_dash
ucr_lib_dash
ucsb_dash
ucsc_dash
ucsf_lib_datashare
```

I thought we had done this earlier, but checked and apparently not.

**Comment by elopatin-uc3** [comment]
Confirmed "unavailable" status for these collections in EZID. Now removing "anonymous" user in LDAP.

**Comment by elopatin-uc3** [comment]
@sfisher what about UCSF Datashare?

**Comment by elopatin-uc3** [comment]
LDAP "anonymous" user read and download permissions removed from:
ucb_dash
ucd_lib_dash
uci_dash
ucla_dash
ucm_dash
ucop_dash
ucpress_dash
ucr_lib_dash
ucsb_dash
ucsc_dash
ucsf_lib_datashare

and:
ucsf_datashare
ucd_bioageng_dash

**Comment by elopatin-uc3** [comment]
Set `read_privilege`, `write_privilege`, and `download_privilege` to "restricted" for all of the above collections.

**Comment by elopatin-uc3** [comment]
Linking to #430 , as ultimately, this is the way we want to go: Migrate DASH collections into the primary Dryad collection.

This will negate the need to move these collections from having a primary node of S3, to Minio.
