### ISSUE TITLE
Assembly Bucket Retention

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#433]
Now that the Merritt Presigned Object Assembly process is established, we would like to reduce the retention S3 period for the object assembly buckets.

The retention period had previously been set to 14 or 28 days to accommodate email delivery of large objects.  The new workflow will allow a shorter retention period.  The goal of this request is to reduce costs for this transient storage.

This process operates on a special S3 bucket with a defined retention policy.

Request 1: Please confirm the retention period for the following buckets (we believe that it is 14 days or 28 days).
uc3-s3mrt1001-stg
uc3-s3mrt1001-prd
Request 2: Reduce the retention period to 3 days for the stage bucket listed above.
We will coordinate testing with Dryad after this change is applied.
Request 3: Reduce the retention period to 3 days for the production bucket listed above.
We will coordinate testing with Dryad after this change is applied.

**Comment by elopatin-uc3** [comment]
After discussion with the Dryad team, bucket retention has been reduced to 3 days.
