### ISSUE TITLE
[Audit] Increase JVM size for production Audit

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#440]
Audit 01 production needed a "hard" restart (killing process) of the Audit service on 8/21.

Librato shows a steady increase in the commit memory starting on Thurs/ 8/20 and ending upon restart.
Maximum commit memory was at 80%

This looks to be a JVM issue where the Audit processing exceeds the allotted JVM size.  
Lets increase the JVM for all production Audit servers from 2GB to 3GB.  Physical memory size for all Audit hosts is 4GB.

** Time restarts between audit workers to make sure we don't deplete burst credits. 

- [x] uc3-mrtaudit01x2-prd.cdlib.org
- [x] uc3-mrtaudit02x2-prd.cdlib.org
- [x] uc3-mrtaudit03x2-prd.cdlib.org
- [x] uc3-mrtaudit04x2-prd.cdlib.org

**Comment by elopatin-uc3** [comment]
We've decide to increased JVM memory to 3G.

**Comment by mreyescdl** [comment]
All Audit services are now using a 3GB JVM

**Comment by elopatin-uc3** [comment]
Thanks for the update @mreyescdl.
