### ISSUE TITLE
Merritt Atom Feed Changes

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#441]
see views/object/recent.atom.builder

- [x] Change file download to presigned file download
- [x] Who uses these feeds?  How are they used?
- [ ] Do we have an established way to test our RSS feeds?
- [x] Object download

Sample feed URL:
`https://merritt.cdlib.org/object/recent.atom?collection=ark:/13030/m57d2vtj&page=2`

Current link style (which can be prefaced with `merritt.cdlib.org`:
`<link href="/d/ark%253A%252F13030%252Fc8cc0zf4/3/producer%252FFILEID-1.62.43.jpg”…`

New style for use with presign file download implementation:
`<link href ="/api/presign-file/ark%253A%252F13030%252Fc8cc0zf4/3/producer%252FFILEID-1.62.43.jpg...`

@elopatin-uc3 , could we remove the object download link from the Atom feed and instead link the user to the object page in Merritt

**Comment by mreyescdl** [comment]
@terrywbrady Escholarship using the RSS feed to harvest their collection data

**Comment by elopatin-uc3** [comment]
Known users are Library IT folks at UCB. They use feeds to confirm objects and files are in Merritt, prior to deleting them manually.
