### ISSUE TITLE
Rollup totals on an ownership basis in FY reports appear to be off by a small amount

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#443]

**Comment by terrywbrady** [comment]
@elopatin-uc3 , I had not noticed this issue before.  Can you provide an example owner to investigate?

**Comment by elopatin-uc3** [comment]
@terrywbrady I've manually added entries in the Daily Average and FY End columns on the 2019 FY report and found no errors. I thought the issue was in the Daily Average column, but it seems like this was human error. I'll go ahead and close this out.
