### ISSUE TITLE
Update Merritt wiki with guidance regarding pre-sign Object API endpoint

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#454]
#### Tasks
- [ ] @elopatin-uc3 to generate diagrams based on what Terry created for our iPRES slide deck.

**Comment by terrywbrady** [comment]
@elopatin-uc3 , could you point me to the page where you would like this to be hosted?

**Comment by elopatin-uc3** [comment]
@terrywbrady yes, will do. I spent some time adding items/pages that need to be updated across the wiki in #254 and will get to this next.

**Comment by elopatin-uc3** [comment]
I think we should replace the content of the Merritt Express page with an overview of pre-sign file and object retrieval (I can help with diagram graphics):
https://github.com/CDLUC3/mrt-doc/wiki/Merritt-Express

At the same time, I'll add the task of updating the "Retrieving Objects" page to #254, which looks like it's missing a couple of images.

We have technical documentation here:
https://github.com/CDLUC3/mrt-doc/wiki/Technical-Documentation

But it feels like we should only tackle a new addition to this page when we prioritize work on the API.

**Comment by elopatin-uc3** [comment]
https://github.com/CDLUC3/mrt-doc/wiki/Retrieving-Objects#programmatic-retrieval-of-merritt-objects

**Comment by elopatin-uc3** [comment]
Moving to Done
