### ISSUE TITLE
UI Navigation/Accessiblity - Part 2

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#461]
Relates to #448 

Name | Summary | Status
 -- | -- | --
Narrow-screen global nav menu is broken– items largely pushed off the left edge of the screen. No only an accessibility issue. | Menu items should all be visible when the menu is open. | Caused by ucm_admin_ppdc in the hamburger menu
H1 not read: The page uses the Merritt logo as its h1; alt-text is present, but not read by VO with Safari. Does work with NVDA/Firefox. | VO should read "Merritt" when focus is on the H1. | In acc1
Redunant link with different link text: two links to UC3-Merrit.pdf appear in immediate succession with differing link text (the first is alt-text for a logo). | Reduce to a single link. Either remove the "Core Trust Seal" logo link (leaving the logo in place), or wrap both the logo and the "learn more..." text in a div and make that the link. | link changed.  in acc1
Downloads menu item coded as a link, but acts as a button (i.e., it opens a modal rather than a new page) | Change element from link to button. Could also be addressed with an aria-role, but native HTML is the preferred approach. | branch acc1
Three boxes uses list feature to create spacing to links after initial paragraph. | Use paragraph tag instead? | branch acc1 -- left justify
Usability note: "Home" in global nav goes to Browse Collection page while "Merritt" breadcrumb link goes to Merritt homepage and Merritt logo goes to Merritt homepage. | Change "Home" and "Change Collection" pull down labels to read "Browse Collections." Reorder so that "Browse Collections" precedes "Collection Home" in nav. Change Merritt breadcrumb to point to Browse Collections page.|The reordering makes sense.  I am not sure I agree with the label changes.  Partial implementation on branch acc1
Tab Order | Another note (which does not need to be addressed for this release): The current order in which a user's tab focus moves is from the Merritt icon, to Logged in as.., to Collection home, etc. It may be more appropriate to move from the Merritt icon, to Collection home, and continue in a left to right fashion from there.| branch acc1

**Comment by elopatin-uc3** [comment]
@terrywbrady The Data Repositories Requirements page that's linked to now from the CoreTrustSeal site makes sense to me (vs. the organization's home page). Let's stick with the requirements page.
