### ISSUE TITLE
ONEShare DataUp and DataONE Dash collections needs another copy

### ISSUE THREAD

**Issue by marisastrong** [CDLUC3/mrt-doc#467]
In reviewing collections via the mrt_admin tool, there is not a 2nd copy for the ONEShare Dataup and DataONE Dash collections.  Primary node is 4001 (Dryad S3), 1st copy is 2001 (Wasabi).  We should also copy to 9501 (SDSC).

**Comment by elopatin-uc3** [comment]
Thanks @marisastrong . @dloy is going to set up replication to Minio.

**Comment by elopatin-uc3** [comment]
Now replicated to SDSC and Wasabi.
