### ISSUE TITLE
travis-ci.org to travis-ci.com migration

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#474]
travis-ci.org will be officially closed down on December 31st, 2020. We'll need to migrate our travis-ci.org mrt builds to travis-ci.com. https://docs.travis-ci.com/user/migrate/open-source-repository-migration

Merritt builds:
- mrt-dashboard
- mrt-tind-harvester 
- mrt-ingest-ruby

**Comment by marisastrong** [comment]
https://travis-ci.org/github/CDLUC3
https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by elopatin-uc3** [comment]
Split this out to start with UI during Rails upgrade:
