### ISSUE TITLE
EZID service identifier request retry

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#475]
On the rare occasions EZID becomes unavailable, ingest should retry new identifier requests. 

### Tasks:
- [x] Determine number of retries (3?)
- [x] Implement retry and graceful failure logic

**Comment by elopatin-uc3** [comment]
https://github.com/CDLUC3/mrt-ingest/pull/10

**Comment by mreyescdl** [comment]
Implemented and tested on Ingest stage workers.  

- Requests that are serviced by EZID and returns a non successful response will not be retried.
- Requests that throw an exception (e.g. Timeout, connection error,..) will be tried a total of three times with a 5 second delay between attempts.

**Comment by mreyescdl** [comment]
Release ticket
https://www.pivotaltracker.com/story/show/174980326

**Comment by mreyescdl** [comment]
Complete
