### ISSUE TITLE
Insight into ingest processing

### ISSUE THREAD

**Issue by marisastrong** [CDLUC3/mrt-doc#476]
There was an issue with EZID and some ARKs which did not get created.  Eventually error emails were sent but it was after some time given that these objects were part of a very large submission.  

- [ ] It would be helpful to have better understanding into ingest processing esp wrt EZID.  
- [ ] better transparency into ingest and large submissions
- [ ] discuss possibilities for queuing large batches and spreading load across workers

**Comment by elopatin-uc3** [comment]
@elopatin-uc3 to reference tickets that relate to the above three tasks.

**Comment by elopatin-uc3** [comment]
I think this is covered by implementation of the callback and any future work that takes place around that, as well as any scaling work we take on for Ingest. We have some additional insight into its use of EZID as well, that was also improved upon during the coll admin work. I'm OK with closing this.
