### ISSUE TITLE
Remove duplicate entries from collection atom feeds

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#478]
#### Summary
Item entries can appear more than once in a collection atom feed – at the end of one page, and then again at the beginning of the next page. This has the side effect of making the eScholarship ETD harvest process error per an authentication routine on their side. We should ensure that items do not show up more than once in atom feeds.

 - [ ] Ensure items do not show up more than once in a collection atom feed.

**Comment by elopatin-uc3** [comment]
@terrywbrady Having kept an eye on the number of errors that have occurred with the eScholarship ETDs harvest over the past weeks, I'm starting to think this issue should be fixed sooner than later. The example that convinced me has surfaced over the past two days. UCB ingested 140 ETDs, and via spot checking objects across the submission, it looks like none of them have made it to eScholarship.

**Comment by terrywbrady** [comment]
@elopatin-uc3 , do you want to add this to the scope of the Rails 5 changes?

**Comment by elopatin-uc3** [comment]
@terrywbrady Yes, if possible, I think it would be beneficial to introduce this change as part of the upcoming Rails 5 release.

**Comment by terrywbrady** [comment]
See eschol Slack on 9/17

> it looks like sometimes the atom feed contains the same item at the end of one page and the start of another page

Note that the issue is while processing page 267 of a large feed.

Eric will send some examples of failure reports

**Comment by elopatin-uc3** [comment]
Link to an example, duplicate entry:
https://merritt.cdlib.org/object/recent.atom?collection=ark:/13030/m5pv6m0x&page=340
https://merritt.cdlib.org/object/recent.atom?collection=ark:/13030/m5pv6m0x&page=341

**Comment by terrywbrady** [comment]
@elopatin-uc3 , the following seems to fix the issue.

https://github.com/CDLUC3/mrt-dashboard/commit/2a730702f697d777239a6c23b5becdb85d4c60b1

I will let you know when this is out on stage.

**Comment by elopatin-uc3** [comment]
Thanks @terrywbrady , that's good to hear. I'm not sure if eScholarship has a test harvesting mechanism targeted at our stage, but I can find out.

**Comment by terrywbrady** [comment]
@elopatin-uc3 , this one may be easier to verify once it is in prod.
