### ISSUE TITLE
Containerize LDAP service

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#485]
Set up OpenDJ 4.5 to run in a Docker container.

**Comment by elopatin-uc3** [comment]
PR: https://github.com/CDLUC3/merritt-docker/pull/8

**Comment by mreyescdl** [comment]
PR for UI to LDAP encrypted traffic.
This involved creating a self signed cert for LDAP and adding it to the UI's CA certificate list
https://github.com/CDLUC3/merritt-docker/pull/9

**Comment by mreyescdl** [comment]
Completed and now part of the Merritt Docker stack
https://github.com/CDLUC3/merritt-docker
