### ISSUE TITLE
Collection creation: Form Section 3, Generate LDAP entries

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#489]
This issue is part of a series which describes the functionality of one or more Lambda functions and an associated web UI for generating new Merritt collections. For reference see #328 and this [document](https://github.com/CDLUC3/mrt-doc/blob/master/reports/2020-10-06_collection_creation.md).

In specific, this ticket outlines required tasks to generate entries in LDAP for the collection.

#### Form Section 3
This form section should present a series of text entry fields that enable a user to input key LDAP entries.
- Collection ARK, which maps to `arkId`
- Collection description text, which maps to `description`
- A submission profile name, which maps to the `submissionProfile` entry

Triggering the form section with a button click (button label:"Generate LDAP Entries") would trigger writing a series of entries to the LDAP service, including those for:
- The `ou`, `merrittClass`, `organizationalUnit`, and `top` entries.  
- Four permissions group names, each of which generate a `groupOfUniqueNames` entry that are named as follows: `read`, `write`, `download` and `admin`.

##### Happy path:
- "You have successfully generated entries for this collection in LDAP."
##### Sad path:
- An error message appears: "An error occurred while attempting to generate entries in LDAP for this collection."

**Comment by terrywbrady** [comment]
@elopatin-uc3 , closing
