### ISSUE TITLE
Collection creation: Form Section 5, Update Inventory collection records

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#490]
This issue is part of a series which describes the functionality of one or more Lambda functions and an associated web UI for generating new Merritt collections. For reference see #328 and this [document](https://github.com/CDLUC3/mrt-doc/blob/master/reports/2020-10-06_collection_creation.md).

In specific, this ticket outlines required tasks to update collection-specific records in the Inventory database.

#### Form Section 5
A series of fields should be presented to enter the following information in the `inv_collections` table
- `name`
- `mnemonic`
- `read_privilege = restricted`
- `write_privilege = restricted`
- `download_privilege = restricted`
- `storage_tier = standard`

Along with two additional drop-down menus to specify secondary storage nodes in `inv_collections_inv_nodes` with choices for:
- Wasabi
- S3
- SDSC
- Glacier

Submission of this form via a button (button label: "Submit") should most likely execute POST requests to new, corresponding API endpoints that will update the Inventory database.

##### Happy path:
- "Your changes to the Inventory database for this collection were successful" 
##### Sad path:
- An error message: "An error occurred when attempting to submit changes to the Inventory database."

**Comment by terrywbrady** [comment]
@elopatin-uc3 , closing
