### ISSUE TITLE
Store2 Production Deploy

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#496]
## Deploy
Deploy Store2 war on all production storage servers 10/11.

The attempt of this process will be no down time for either Dryad or Storage UI. Also, attempt this update with Ingest not being frozen.

The general schedule for this process will be
- set up file, SSM, tomcat changes on 10/12
- Begin store deploy handling starting at 2:00 p.m.

### Involved servers
- uc3-mrtstore01x2-prd.cdlib.org
- uc3-mrtstore02x2-prd.cdlib.org
- uc3-mrtstore03x2-prd.cdlib.org
- uc3-mrtstore04x2-prd.cdlib.org

#### core2
https://github.com/CDLUC3/mrt-core2/commit/857cbae169f9da645a077ca46ae11d9ddc049236

#### mrt-cloud
https://github.com/CDLUC3/mrt-cloud/pull/10

#### mrt-store
- https://github.com/CDLUC3/mrt-store/commit/c0467af7b027cbb60738797a4a3e5ae1f493c00f
- https://github.com/CDLUC3/mrt-store/commit/3a0b8279f4ba60ef76af14f056b9578b2bee6148
- https://github.com/CDLUC3/mrt-store/commit/3fb02efc02a009586cbf799bb4b71f907a095046

### Builds
http://builds.cdlib.org/job/git-core2/18/
http://builds.cdlib.org/job/mrt-s3-pub/108/console
http://builds.cdlib.org/job/mrt-store-pub/136/console

### 10/12
- For all servers confirm that all required SSM variables are properly set for /prd handling
- For each server make sure setup of  logging file: /apps/dpr2store/mrtHomes/store2/logs

### log directory - Add /apps/dpr2store/mrtHomes/store2/logs
- [x] (dloy) Add uc3-mrtstore01x2-prd
- [x] (dloy) Add uc3-mrtstore02x2-prd
- [x] (dloy) Add uc3-mrtstore03x2-prd
- [x] (dloy) Add uc3-mrtstore04x2-prd

### tomcat8_catalina_base changes
- [x] (dloy) Modify branch uc3-mrtstore01x2-prd  bin/setenv.sh to include environment variables
- [x] (dloy) Modify branch uc3-mrtstore02x2-prd  bin/setenv.sh to include environment variables
- [x] (dloy) Modify branch uc3-mrtstore03x2-prd  bin/setenv.sh to include environment variables
- [x] (dloy) Modify branch uc3-mrtstore04x2-prd  bin/setenv.sh to include environment variables

_Environment Variables_
SSM_ROOT_PATH=/uc3/mrt/prd
MERRITT_STORE_INFO=store-info
NODE_TABLE=nodes-prod

### Production storage SSM 
- [ ] (dloy) set SSM values on ops box

_SSM Variables:_
~~~
        {
            "Name": "/uc3/mrt/prd/cloud/nodes/sdsc-accessKey",
            "Value": "###",
	}
        {
            "Name": "/uc3/mrt/prd/cloud/nodes/sdsc-secretKey",
            "Value": "###",
        },
        {
            "Name": "/uc3/mrt/prd/cloud/nodes/wasabi-accessKey",
            "Value": "###",
        },
        {
            "Name": "/uc3/mrt/prd/cloud/nodes/wasabi-secretKey",
            "Value": "###",
        },

        {
            "Name": "/uc3/mrt/prd/store/config/baseURI",
            "Value": "http://store-stage.cdlib.org:35121",
        },
        {
            "Name": "/uc3/mrt/prd/store/config/log/messageMaximumError",
            "Value": "15",
        },
        {
            "Name": "/uc3/mrt/prd/store/config/log/path",
            "Value": "/apps/dpr2store/mrtHomes/store2/",
        },
        {
            "Name": "/uc3/mrt/prd/store/config/nodePath",
            "Value": "yaml:",
        },
        {
            "Name": "/uc3/mrt/prd/store/config/verifyOnRead",
            "Value": "true",
        },
        {
            "Name": "/uc3/mrt/prd/store/config/verifyOnWrite",
            "Value": "true",
        },
        {
            "Name": "/uc3/mrt/prd/store/config/log/messageMaximumLevel",
            "Value": "10",
        },

~~~

## Deploy 10/13
Deploy will be made for all production storage server store01-store02

### 1:00 
- [ ] (Mark) shutdown monitors prod storage

#### Remove store01 and store03 from load balancers
- [x] (dloy) remove  uc3-mrtstore01-prd from RLB
- [x] (Mark) remove uc3-mrtstore03-prd from ALB

#### Processing on store01 and/or store03 completes
- [x] (dloy) redeploy uc3-mrtstore01-prd
- [x] (dloy) redeploy uc3-mrtstore03-prd

- [x] (dloy) regressions uc3-mrtstore01-prd
- [x] (dloy) regressions uc3-mrtstore03-prd

#### reset load balancers to deployed storage and remove undeployed balancers
- [x] (dloy) restore uc3-mrtstore01-prd  - remove  uc3-mrtstore02-prd from RLB
- [x] (Mark) restore uc3-mrtstore03-prd  - remove  uc3-mrtstore04-prd from ALB

#### Processing on store02 and/or store04 completes
- [x] (dloy) redeploy uc3-mrtstore02-prd
- [x] (dloy) redeploy uc3-mrtstore04-prd

- [ ] (dloy) regressions uc3-mrtstore02-prd
- [x] (dloy) regressions uc3-mrtstore04-prd

#### Completion of deploys

- [x] (dloy) restore uc3-mrtstore02-prd  to RLB
- [x] (Mark) restore uc3-mrtstore04-prd to ALB

- [x] (Mark) restart prod storage monitors

**Comment by dloy** [comment]
Note cloud configuration fix was required for this install:

Jenkins:
http://builds.cdlib.org/job/mrt-s3-pub/109/console
http://builds.cdlib.org/job/mrt-store-pub/137/console

GitHub:
https://github.com/CDLUC3/mrt-cloud/blob/master/cloud-conf/src/main/resources/yaml/cloudConfig.yml

Will look into better way to detect S3 configure issues for prod.

**Comment by elopatin-uc3** [comment]
@dloy I filed #499 regarding your last comment about S3 config.
