### ISSUE TITLE
RDS Burst Credits exhausted during Audit server patching/restarting

### ISSUE THREAD

**Issue by marisastrong** [CDLUC3/mrt-doc#497]
During the 9/3 and 10/6 patching cycles and restarting of the Audit servers, the RDS INV db exhausted the 3000 burst credits allocated.  This in turn caused issues with downstream services trying to access the inv database.  

One proposed approach is before the next patching cycle, the RDS INV db will have the EBS volume re-provisioned from 200 GiB to  600 GiB at an increased cost of $96.  Team will determine if this solves the issue.

Another approach is to assess the audit code to determine if we can address issue programmatically.

## General purpose I/O

I/O subject to burst credits based on database size.  Once increased, you cannot decrease without re-provisioning a database.  Uses IOPS to migrate.

| Size (GB) | Base IOPS | Burst duration (min) | Refill (min) | Cost per mo | Note |
| -- | -- | -- | -- | -- | -- |
|100 | 300 | 33 | 300 | $23 |
|200 | 600 | 38 | 150 | $46 | current usage
|300 | 900 | 43 | 100 | $69 |
|400 | 1200 | 50 | 75 | $92 |
|500 | 1500 | 60 | 60 | $115 |
|600 | 1800 | 75 | 50 | $138 | Martin's recommendation
|700 | 2100 | 100 | 43 | $161 |
|800 | 2400 | 150 | 38 | $184 |
|900 | 2700 | 300 | 33 | $207 |
|999.99999 | 2999.99997 | 2999999985 | 30 | $230 |

## Provisioned I/O

Fixed cost, change-able.  We experience poor performance during a downgrade from provisioned to non provisioned in a test database.

| IOPS  | Cost per mo |
| -- | -- |
| 1000  | $250 |
| 1500  | $350 |
| 2000  | $450 |
| 2500  | $550 |
| 3000  | $650 |

## CPU Burst Credits

Martin will provide us with a recommended instance type for the Audit servers to use in place of this instance type.

Inst type | vCPUs | Mem (GB) | EC2 Cost/hr | EC2 Cost/mo | Scratch cost/mo | Total/mo (1 server) | Total/mo (4 servers) |  
-- | -- | -- | -- | -- | -- | -- | -- | --
t3.medium | 2 | 4 | $0.0416 | $30 | $100 | $130 | $520 | <--- current
c5.large | 2 | 4 | $0.0850 | $61 | $100 | $161 | $645 |  
m5.large | 2 | 8 | $0.0960 | $69 | $100 | $169 | $676 |  
i3en.large | 2 | 16 | $0.2260 | $163 | $0 | $163 | $651 |  

## Cost Offset

We will need to offset compute costs from another part of the system.  Martin recommends that we consider more storage-optimized instance types like the ones we used for store03/04 vs scratch volumes.

**Comment by terrywbrady** [comment]
Issue has been resolved with Audit2
