### ISSUE TITLE
Cascading Audit Errors -- CPU Credits

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#498]
- On 10/6 around 18:00, Audit04 ran out of CPU Credits.  The service has not recovered.
- On 10/12 around 00:00, Audit03 ran out of CPU Credits.  The service has not recovered.
- Audit02 is fine
- Audit01 bottomed out on 10/13 around 05:30

Can we trace an object as the source of the problem in Audit04/03?  Is it the same object?

Would RAM help?

These service will probably need to be restarted (carefully).  

Relates to #497

**Comment by terrywbrady** [comment]
## 10/14: David, Mark, Eric, Terry met
- [ ] Terry and David will review oldest unaudited file calculation
- [ ] David will restart Audit04
  - A drive is full, David will clean this up
  - Thread count will change from 5 to 3 to avoid collisions of large objects
  - Terry will watch RDS credits during restart - will the lower thread count reduce the impact?
- [ ] Once the RDS status is validated, we will do the same with 03
- [ ] Determine a plan for 01/02 - change the thread count during the next patching cycle?
- [ ] David will prioritize code changes and will meet with Terry
  - Perform size based checks
  - Consider a queue or alternate table for items in process

**Comment by elopatin-uc3** [comment]
Moving this to the project board, to In Progress.

**Comment by elopatin-uc3** [comment]
Thread count for Audit has been lowered to 3 (from 5). The plan for now is to monitor in case anything like this occurs again. However we will check in with IAS about profile of the EC2 instance for Audit when we refactor for SSM.
