### ISSUE TITLE
Disable sending stats to the CDL Dashboard

### ISSUE THREAD

**Issue by marisastrong** [CDLUC3/mrt-doc#500]
There is a CDL Dashboard which displays stats for CDL services.  Merritt is one of those services sending stats to the Dashboard.  CDL no longer needs to support the Dashboad so we can discontinue sending of the stats.  No timeline has been determined for taking down the Dashboard, but we should remove things on the Merritt end.

- [x] determine where stats are being collected and copied to intracdl server (cronjob?)
- [x] disable/remove this functionality
- [x] tarball `/bin/KPI` files, and ingest into the "CDL UC3 Rhodecode repositories" collection 
- [ ] inform Craig Thompson of the UX team so they can remove functionality on their end.

**Comment by elopatin-uc3** [comment]
Ticket 500! Thanks for filing this. The KPI script that generates monthly data for the dashboard is on `uc3-mrtinv01x2-prd.cdlib.org` here: `/dpr2/bin/KPI/KPI.pl`. It is also responsible for emailing the result to uc3@ucop.edu. The resulting .csv must be manually uploaded to the dashboard, so after we disable and archive the script, there should be nothing else to do.

**Comment by marisastrong** [comment]
Pivotal Ticker here: https://www.pivotaltracker.com/story/show/175310097

**Comment by elopatin-uc3** [comment]
The cron that runs the KPI script is on `dpr2` crontab. It is controlled by Puppet:
~~~
# Puppet Name: KPI
0 1 1 * * /dpr2/bin/KPI/KPI.pl

**Comment by ashleygould** [comment]
I only found one host in puppet with this cronjob defined - uc3-mrtinv01x2-prd.  the cronjob has been removed.

**Comment by elopatin-uc3** [comment]
Great, thanks @ashleygould.

**Comment by elopatin-uc3** [comment]
I've created a tarball of KPI directory for submission to Merritt: `kpi-scripts-2020-10-21.tar`

**Comment by elopatin-uc3** [comment]
Tarball submitted to Merritt a while back:
https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm5km4rpf

Pivotal ticket notes script removed from `uc3-mrtinv01x2-prd`. The `/bin/KPI` dir is still there with additional versions of the script and old .csv files. However this totals a little over 900k, and I don't see any harm in leaving it there in case, for whatever reason, we need to check out the stats more readily.

Closing.
