### ISSUE TITLE
In the Merritt UI, convert UTC time to PT when hovering over a date/time.

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#501]
Even better if there is a way to use a user's locale in the conversion.

**Comment by terrywbrady** [comment]
@elopatin-uc3 , did we already solve this earlier this month?

**Comment by elopatin-uc3** [comment]
You made a change that now shows PT in the UI, but were going to save a more involved change to support display in UTC until later. I can't recall exactly what that was going to be though. 

I'm inclined to leave the current PT display as is and will close this.
