### ISSUE TITLE
Migrate MySQL from 5.7 to 8.x (IAS Goal: 4Q22)

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#503]
## Action items
- [x] Upgrade docker mysql image to 8.0
- [x] Run end to end tests against 8.0 docker image
  - [x] Also test Sword/OAI manually
- [x] Big Question: are new gems/jars required for upgrade?
  - Hopefully, gem/jar upgrade can occur at a separate time 
- [x] Create a "DEV" database by exporting prod or stage and upgrading it. We could use the existing DEV database as well.
  - David has a test database available
  - [x] David will test java services
  - [x] Terry will DEV admintool
  - [x] Terry will test UI with docker stack 
- [x] Upgrade stage database
  - [x] Run end to end tests test suite against stage
  - [x] Run the admin tool automated test suite (only available for Stage)
  - [x] User test Admin Tool
  - [x] User test Merritt UI
  - [x] Pay attention to the full text index values created by triggers
  - [x] Java Service Tests (David to Specify)
    - [x] Inventory
    - [x] Audit
    - [x] Replic
    - [x] OAI
    - [x] Sword
  - [x] Leave in place for a few days
  - [x] Other special tests to run?
- [x] Upgrade production database
  - [x] Run end to end tests
- [x] Create a series of tickets to upgrade gems and jars: see #1071

## Vars to update to the dev database
```
  host: "{!SSM: inv/db-host}"
  database: "{!SSM: inv/db-name}"
  username: "{!SSM: inv/readwrite/db-user}"
  password: "{!SSM: inv/readwrite/db-password}"

    host: "{!SSM: billing/db-host}"
    database: "{!SSM: billing/db-name}"
    username: "{!SSM: billing/readonly/db-user}"
    password: "{!SSM: billing/readonly/db-password}"
```

## Finding values

```
aws ssm get-parameters-by-path --path .../inv/ --recursive
aws ssm get-parameters-by-path --path .../billing/ --recursive
```

**Comment by terrywbrady** [comment]
Marisa found this link.  Some useful stuff in here: https://severalnines.com/blog/moving-mysql-57-mysql-80-what-you-should-know/

**Comment by marisastrong** [comment]
The IAS deadline is to be in line with the exercise of reserving RDS instances which occurs at the end of the year.

**Comment by marisastrong** [comment]
More information on this here:  https://confluence.ucop.edu/display/CUG/RDS+User+Guide#RDSUserGuide-MySQL5.7to8.0Upgrade

**Comment by marisastrong** [comment]
@dloy requested from IAS a snapshot of the production database in a MySQL 8.0 instance

- A full test 8.0 MySQL RDS with an upload of our current 5.7 inv database – hopefully from a snapshot in the last 2 weeks
- If my existing dev RDS can be run as 8.0, this can be reused: rds-uc3-mrt-inv-dev-20211012-dloy.cmcguhglinoa.us-west-2.rds.amazonaws.com

**Comment by terrywbrady** [comment]
https://github.com/CDLUC3/merritt-docker/pull/37/files

**Comment by marisastrong** [comment]
Oct 24 - Merritt will request MySQL 8.0 update to stage databases for testing

**Comment by terrywbrady** [comment]
Merritt Team will reach out to IAS the week of 10/24 to start the process on stage.

MySql8 features: https://severalnines.com/blog/moving-mysql-57-mysql-80-what-you-should-know/

IAS RDS Guide: https://confluence.ucop.edu/display/CUG/RDS+User+Guide

**Comment by ashleygould** [comment]
re-image rds-uc3-mrt-inv-dev from rds-uc3-mrt-inv-prd.
drop dave loy's prd copy db
upgrade dev dp
  - capture timing and logs

**Comment by elopatin-uc3** [comment]
Timing for service pauses:
- Pause ingest, large Access and Dryad at 1pm

**Comment by ashleygould** [comment]
Prod upgrade completed Nov 16
