### ISSUE TITLE
UI Exception in guest_login 

### ISSUE THREAD

**Issue by marisastrong** [CDLUC3/mrt-doc#506]
Merritt UI throws this error occasionally

```
A NoMethodError occurred in user_sessions#guest_login:

  undefined method `to_model' for true:TrueClass
Did you mean?  to_yaml
  app/controllers/application_controller.rb:256:in `redirect_back_or_default'
```

**Comment by marisastrong** [comment]
the comment I made about an issue of when logged in as a guest user, then logging out and logging in as Marisa Strong, then logging back in and having "Logged in as Guest" displays is no longer an issue (i.e. I cannot recreate).

**Comment by terrywbrady** [comment]
I have not figured out how to force the error to repeat, but the following fix is an attempt to prevent the error:

https://github.com/CDLUC3/mrt-dashboard/commit/8962e0aecd4b4c2102293ecaebdb74877dbd5eb1
