### ISSUE TITLE
Admin tool report for general projection of annual space used

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#507]
It would be helpful to report on a rough estimate of total, potential spaced used by a collection by projecting this amount based on the rate at which new content is being added (during a given fiscal year). Such a value was provided by legacy billing scripts. Though that implementation was not very accurate, it was still beneficial to be able to pass along these estimates to campuses.

**Comment by elopatin-uc3** [comment]
https://github.com/CDLUC3/mrt-admin-lambda/pull/9

**Comment by terrywbrady** [comment]
@elopatin-uc3 , can this be closed or is more work needed?

**Comment by elopatin-uc3** [comment]
I think it can be closed @terrywbrady
