### ISSUE TITLE
Evaluate LDAP prefilter return status

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#508]
I think I found it in a prefilter in the object controller.
Please check that the user has LDAP write permissions for the profile.
@terrywbrady we may want to change the 404 to a 401 in the following for the object controller, if I'm reading the logic correctly
```
  before_filter(only: %i[ingest mint update]) do
    if current_user
      render(status: 404, text: '') unless current_user.groups('write').any? { |g| g.submission_profile == params[:profile] }
    else
      render(status: 401, text: '')
    end
  end
```

**Comment by terrywbrady** [comment]
@elopatin-uc3 , what is this?  Can we close this?

**Comment by elopatin-uc3** [comment]
I don't recognize it either; closing.
