### ISSUE TITLE
Investigate minimizing backups of application-specific disks

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#510]
Investigate minimizing backups of application-specific disks for audit, replic, ingest, and possibly inventory, in order to save money on AWS charges. (enabled in part by migration to use of SSM)

**Comment by mreyescdl** [comment]
I forgot that we seem to have already addressed this issue.  Audit/Storage/Replic all use a scratch disk that I will confirm are not backed up.  Inventory does not use a large disk and Ingest shares an EFS across all three workers.  I'll also confirm that the EFS is not backed up


```
Store 01/02
        - 50 GB application disk (backed up)
        - 1 TB scratch disk (NOT backed up)

Audit 01/02/03/04
        - 50 GB application disk (backed up)
        - 1 TB scratch disk (confirm it is NOT backed up)

Replic 01/02
        - 50 GB application disk (backed up)
        - 1 TB scratch disk (confirm it is NOT backed up)

Ingest 01/02/03
        - 50 GB application disk (backed up)
        - EFS disk (confirm it is NOT backed up)

Inventory 01/02
        - 50 GB application disk (backed up)
```

**Comment by elopatin-uc3** [comment]
Discussed in team meeting and considered done. Closing
