### ISSUE TITLE
Future Docker Configuration Changes

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#512]
Dev Server Setup 
- [x] Create script to pull from private docker config and insert values (with hostname) into the no-track directory
  - [x] ~Consider using a docker build variable to properly embed the hostname/hostname resolution into the image files~
- [x] ~Verify github credential access from role account, document procedures~

VS Code Setup 
- [x] Document host machine needs and variables
- [x] Test interactive ruby deubugging of a container

Audit/Replic
- [x] Configure a secondary minio bucket for replication testing
- [x] Configure collection replication
- [x] Add audit and replication to the stack
  - do this when SSM is added to audit and replic
- [x] Create docker compose file to include audit and replic as optional services
- [x] Create docker compose files to enable debugging of audit and replic

Create secondary profile for Merritt Docker that utilized "Dev" AWS resources
- [x] Configure DEV database into the configuration
  - [ ] ~Is an LDAP clone of prod content needed to support this?~
  - [x] Create refined collection profiles linked to DEV database resources
  - [ ] Create collection/node profiles linked to DEV resources
- [ ] Configure nodes for AWS, Wasabi, SDSC DEV buckets
- [ ] Configure lifecycle for resources in these buckets

Publish Images
- [ ] Eliminate dependencies on CDL maven repo
- [ ] Publish Merritt images to docker hub

**Comment by terrywbrady** [comment]
Ruby debugging
- https://github.com/CDLUC3/merritt-docker/commit/e053ca2ed3abf15fd40a25b127bf0195a2b4595f
- https://github.com/CDLUC3/mrt-dashboard/commit/7488769ce4540eee3aa3b173214aa3ce545903c6

**Comment by terrywbrady** [comment]
Renamed title to focus on remaining work - dev bucket configuration

**Comment by terrywbrady** [comment]
@elopatin-uc3 , I am closing this for now.  If we want to create SDSC or Wasabi DEV buckets, we should create a new ticket.

**Comment by elopatin-uc3** [comment]
Thanks @terrywbrady, that sounds good.
