### ISSUE TITLE
[Ingest] SSM - consolidation of all config files

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#514]
Remove the various properties files loaded on JVM startup.  These property control Ingest Home as well as logging

Remove three configs housed in Ingest Home and not in source control

All key value pairs are now defined in a single YAML file and resolved as an SSM parameter, an ENV variable or in the YAML file itself

**Comment by mreyescdl** [comment]
https://github.com/CDLUC3/mrt-ingest/pull/11

**Comment by mreyescdl** [comment]
Ingest stage workers (01/02) running SSM code

**Comment by mreyescdl** [comment]
@terrywbrady Can you check this Docker change?
https://github.com/CDLUC3/merritt-docker/pull/16

**Comment by mreyescdl** [comment]
SSM keys are populated for production
Jenkins production artifact is built to support SSM
Tomcat branches are committed to support SSM - https://github.com/CDLUC3/tomcat8_catalina_base

Prepared for 1/19 deployment to production

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl!

**Comment by mreyescdl** [comment]
Production Ingest now running SSM code
