### ISSUE TITLE
Revisions to Audit and Replic EC2 instance types.

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#515]
Audit: Two workers currently; four available. 
- Decommission two that are not running? 
- This is dependent on length of time for overall audit cycle (keeping this under 90 days) and costs associated with Inventory IOPS credits.

Replic: Four workers
Replics were converted to C5-Xlarge for recent project. Migrations and replication to Wasabi are done. No immediate migrations planned. Should we go back to a smaller instance type?

**Comment by terrywbrady** [comment]
Already handled during Audit2 work.  Number of replic servers was reduced.
