### ISSUE TITLE
Embed master.key during Rails5 capistrano deployment

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#518]
The SSM key has been added for all of our environments.  Docker does not use this (it generates a key during build).

Here is Brian's code with one exception.  Our SSM Key is `ui/master.key`
```
namespace :deploy do
  before :compile_assets, :env_setup
​
  desc 'Setup ENV Variables'
  task :env_setup do
    on roles(:app), wait: 1 do
      ssm = Uc3Ssm::ConfigResolver.new
      master_key = ssm.parameter_for_key('ui/master_key')
      # TODO: Switch this to ENV['RAILS_MASTER_KEY']
      f = File.open("#{release_path}/config/credentials/#{fetch(:rails_env)}.key", 'w')
      f.puts master_key
      f.close
    end
  end
```

Brian provided an alternative suggestion as well: 

> depending on how your docker/capistrano works, you could also ... as an alternative use the aws cli commands to fetch the SSM value and pipe it to a file

**Comment by mreyescdl** [comment]
Used shell commands to add SSM key.  Had little luck using "uc3-ssm" Gem
SSM key is echoed in the capistrano log file.  Hopefully this is not an issue.  Log file is not in source repo.
