### ISSUE TITLE
Delete a series of UCB objects that were accidentally submitted to the wrong collection. 

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#522]
#### Summary
David Triebwasser at Berkeley informed us that they accidentally submitted 7113 objects to the wrong collection. These were submitted in three batches (two batches each of 20 objects, and the remaining 7073 in another). 

The objects were submitted to the UC Berkeley Library ETDs collection (ucb_lib_etd) – but should have been submitted to the UCB Japanese American News collection.

A compressed .csv of the ARKs that need to be deleted is attached: JAN_ARKs_1.zip

https://confluence.ucop.edu/display/UC3/Merritt+Delete

**Comment by elopatin-uc3** [comment]
[JAN_ARKs_1.zip](https://github.com/CDLUC3/mrt-doc/files/5520885/JAN_ARKs_1.zip)

**Comment by elopatin-uc3** [comment]
Noting delete list file names:
ucb20201112-01.txt - ucb20201112-14.txt

**Comment by dloy** [comment]
Delete complete - required change on x2 service name for replic

**Comment by terrywbrady** [comment]
@elopatin-uc3 - close?

**Comment by elopatin-uc3** [comment]
Closing
