### ISSUE TITLE
Merritt UI Rails 5 Production Release -- 2/9 at 5pm

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#531]
## Proposed Time
- Tue Feb 9 at 5pm
- **This change will require a small downtime -- not high availability**

## Purpose

Rails 5 release for the Merritt UI
- includes ruby update
- includes shift to systemd and puppet deployment

## Details
- #83 
- #460
- #506 
- #537 
- #527 
- #478 
- #479  
- #97 

## Servers

The following servers will be removed from the Apache LB and provide only zookeepr
- uc3-mrtui01x2-prd.cdlib.org
- uc3-mrtui02x2-prd.cdlib.org

The following servers will run Rails 5 and will be configured in the Apache LB
- uc3-mrtui03x2-prd.cdlib.org
- uc3-mrtui04x2-prd.cdlib.org
- uc3-mrtui05x2-prd.cdlib.org (not yet available)

## Deploy Process:
- Monday: Terry will tag and re-deploy v1.0.5
- 4:45 Pre-release
  - uc3-maint alert 
  - Scott will pause Dryad Ingest 
  - Mark will pause Merritt Ingest
- 5:00 Ashley will update Apache LB to point to 03/04
  - Ashley will move crons from ui01 to ui03
  - Terry will run system tests (no ingest)
  - Mark and Scott will release ingests
  - Terry will re-run unit test with ingest
  - Mark will verify a Nuxeo job
  - Terry will merge Rails5 branch 

Post-release
- IAS will complete creation of ui05
- Ashley will add ui05 as a preview server
- Terry will test against ui05
- ui05 will be added to the Apache LB
- new boxes will be requested and configured for zookeeper.
- ui01/ui02 will be deprecated after the zookeeper service has been migrated
- Terry and Mark will re-factor the Nuxeo code

## Source changes

- https://github.com/CDLUC3/mrt-dashboard/pull/84

## Jenkins Builds
- N/A

**Comment by terrywbrady** [comment]
In the 12/21 Developer Coffee, @marisastrong and @ashleygould advised that this release should move to a different day of the week rather than bumping the server patching schedule.  @sfisher indicated that a different day of the week should be OK as long as the Dryad team is warned in advance.

@elopatin-uc3 , we should re-visit this on 1/5 and determine which day to release.

**Comment by elopatin-uc3** [comment]
@terrywbrady I've added a note the Ops board to discuss this at our team meeting on the 5th.

**Comment by elopatin-uc3** [comment]
Dryad has been notified of intended 9/2 release date, along with the need for a submissions pause.
