### ISSUE TITLE
LDAP Container Mods

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#534]
The following changes would help me out if they were added to the LDAP container

- Guest login should have download privileges for collections which it can access
- Guest login should have read access to the open context collection
- merritt-test should have read access to the open context collection
- Guest login should have read access to the escholarship collection
- merritt-test should have read access to the escholarship collection

**Comment by mreyescdl** [comment]
I've updated the barebones.ldif file to support the two new collections and download privs. for Guest.
Please test.

**Comment by terrywbrady** [comment]
Thanks @mreyescdl !  This is working exactly as I had hoped.  

@elopatin-uc3 , let me know if you would like to experiment with navigating one of the large collections to determine if the pagination performance is acceptable with with Rails 5 (atom feed) changes.

**Comment by elopatin-uc3** [comment]
@terrywbrady that sounds good. Perhaps we can do this during our Tuesday 1:1?

**Comment by elopatin-uc3** [comment]
All tasks for this ticket are done; closing.
