### ISSUE TITLE
Check caching logic for object, version, file, size counts on collection pages.

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#537]
This ticket relates to #478. The introduction of a secondary ordering to object lists may have thrown off existing caching logic.

Ordering change for reference:
https://github.com/CDLUC3/mrt-dashboard/commit/2a730702f697d777239a6c23b5becdb85d4c60b1

Observations on http://uc3-mrtdocker02x2-dev.cdlib.org:
-  Moving from the collection homepage (of the Open Context or eSchol collections) to page 2, takes less time than moving from page 2 to page 3 of the collection.
- After multiple moves from page-to-page, returning to the overall collection list (choose_collection) takes a much longer time than expected.
- Each collection page view results in object/version/file/size counts to be calculated. In production, either these are being calculated much faster and simply appear more quickly. Or, they've been cached somehow. Either way, it still looks like new requests are being made.
- If no new page requests are made to the docker instance for about 10 minutes, going back and triggering a new request results in better performance.

**Comment by terrywbrady** [comment]
@elopatin-uc3 , interestingly the code is attempting to cache for 10 min.  I need to figure out if that is working or not.

Also, the file size calculations are disproportionally slower than the file count calculation.

**Comment by elopatin-uc3** [comment]
Testing collection page views on dev 01 and 02:

Caching has helped a lot, on both dev instances. There appears to be a tiny bit more lag with the secondary sort on 01, but it’s negligible. e.g. 4.10 seconds vs. 3.94 seconds. I can see the “cached” status appear in the network tab in Firefox for each metrics call starting with page 2 (the collection home page shows three out of the five calls cached, and subsequent pages show all five cached).
