### ISSUE TITLE
Create Nagios style alert if any audit errors are detected in the database

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#539]
Audit error numbers - could we have diagnosed the Minio error sooner based on audit reporting?

To create a new ticket for a mechanism to alert us of Audit errors (as old report was removed when addressing db credits).

**Comment by elopatin-uc3** [comment]
Think about items we might want to be alerted to on a daily basis: 
- Oldest unaudited object and timing surrounding this, e.g. when this is more than n months
- Audit error/associated object

**Comment by terrywbrady** [comment]
Consistency reports
