### ISSUE TITLE
Storage Production Release: Address multi-part download issue in Minio

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#540]
Release changes for #538 to production.

This will be a high availability release. There should be no impact to Dryad submissions.
Changes will need to be deployed to Storage and Storage Access servers, including the new, additional hosts recently set up by @ashleygould.
 
### Fix
For Minio only content all downloads in the mrt-cloud code will be handled as stream. For AWS and Wasabi multipart will continue to be used - they works properly.

### Code change
https://github.com/CDLUC3/mrt-cloud/commit/ff84ad8aa6b5e1a65050c51f4795e0946f8f5618

### Jenkins
Cloud
http://builds.cdlib.org/job/mrt-s3-pub/110/

#### Store stage
http://builds.cdlib.org/job/mrt-store-pub/138/console

#### Storage prod
http://builds.cdlib.org/job/mrt-store-pub/139/console

**Comment by terrywbrady** [comment]
@elopatin-uc3 , should this have been closed after it was tagged?

**Comment by elopatin-uc3** [comment]
Yes, thanks @terrywbrady , closing.
