### ISSUE TITLE
Create "Service Alert" (Notification) Process to run daily... post alerts via admin tool

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#542]
Enable the ability to capture and consolidate application-specific alerts (that differ from health checks)

- ingest
  - report ingest fails 
  - report ingests in queue for more than X hours
- audit
  - report any unsuccessful audits in last X days (use admin tool reports)
  - report if oldest unaudited item exceeds X days
- replic
  - report unsuccessful replic?
  - count any replic waiting more than X days

**Comment by elopatin-uc3** [comment]
See also #539

**Comment by elopatin-uc3** [comment]
Closing per system consistency reports efforts.
