### ISSUE TITLE
Filenames with 4-byte Unicode characters

### ISSUE THREAD

**Issue by ryscher** [CDLUC3/mrt-doc#552]
**Describe the bug**
Filenames with 4-byte Unicode characters are not supported by the Merritt web UI nor by presigned URLs. This includes emoji characters and some Chinese/Japanese characters.

**To Reproduce**
1. Go to https://dryad-stg.cdlib.org/stash/dataset/doi:10.7959/dryad.7wm37pvnc
2. Click on 'Download dataset' -- The dataset that is downloaded will correctly include a file with an emoji in the filename.
3. Back on the web page, click on the date underneath 'Download dataset' -- See that the file is represented with the emoji in Dryad, but clicking on the file results in an error when generating the presigned URL.
4. View the dataset in the Merritt UI, https://merritt-stage.cdlib.org/m/ark%253A%252F99999%252Ffk4g74t31k -- the filename does not display correctly here, and cannot be downloaded from the list of files (though 'Download object' does work correctly)

**Comment by terrywbrady** [comment]
I am curious to know how these characters differ from the test suite I was using.

https://github.com/CDLUC3/mrt-integ-tests/blob/master/spec/test/demo_spec.rb#L27-L41

**Comment by elopatin-uc3** [comment]
@terrywbrady - Daniella followed up with Ryan for input on the priority of this ticket. @ryscher my understanding is that after reviewing the list of characters we're providing support for, emojis are the outliers and that their handling may be thrown off by double encoding. If this is the case, then it seems like this ticket should be relatively low priority per the infrequency of these characters in keys. Please let me know if you're thinking along the same lines. Thanks!
