### ISSUE TITLE
Manage UI deployment via Puppet and git tags

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#554]
This is necessary for the release #531.

@ashleygould will provision a new prod UI server to facilitate testing of these changes.

- carefully modify RLB settings to ensure that ui03 is out of the merritt web load balancer until this release is complete
- implement on ui04
- re-implement stage
- deploy rails5 to ui03 and ui04 - verify in load balancer
- migrate process to ui01 and ui02

**Comment by elopatin-uc3** [comment]
Just adding a note about next week's patching (and Ansible), to make sure ui03 isn't accidentally put back into rotation.
