### ISSUE TITLE
TEST: 8K file Dryad submission that blocked processing on ingest 03

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#567]
Create in Stage and check the updating settings with a mocked object with 41K files.

**Comment by terrywbrady** [comment]
Consider the following solution...

https://github.com/Georgetown-University-Libraries/File-Analyzer/blob/master/core/src/main/gov/nara/nwts/ftapp/filetest/DefaultFileTest.java#L155-L161

**Comment by mreyescdl** [comment]
Submitted a large zip container, mimicking a Dryad submission with 50k components of 4K size.
This did not trigger any issues with Merritt Stage.

Looking more closely at the Dryad submission.  It has 8K files with half having 5-6MB size. 
Will mock this dataset up and submit to Stage.

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl for looking into the dataset's characteristics and assembling a test object to try this out on stage.

**Comment by mreyescdl** [comment]
Next test is a 10K component container (tar file) each component at 5MB
This test exceeds the Dryad submission, but was still successful in Stage.

I suggest that we resubmit Dryad submission to ingest03 production after the build migration is completed.
Ingest03 is still out of rotation so will not see any public traffic/load.

**Comment by elopatin-uc3** [comment]
Resubmitting to ingest03 post build migration sounds good to me.

**Comment by mreyescdl** [comment]
Setting the JVM minimum Heap size to 512M (from 4GB) seems to fix the problem.  
Analysis shows that the open files were due to stream sockets left opened.  The JVM resizing triggered the Garbage Collector to increase frequency, which reclaimed the sockets.

I create a branch in the core library in case we want to explicitly close the streams.  This may be needed if we switch Garbage Collectors in the future.

https://github.com/CDLUC3/mrt-core2/tree/open-files

For now, we'll adjust the JVM parameters on all production Ingest servers.

**Comment by mreyescdl** [comment]
Talking with David, the stream is closed from within the stream2File method.  Variable inputStream in passed as an argument and closed within the method.

This branch is no longer needed.
However, as Terry mentions it does take a while for these open files to be reclaimed by the JVM.  Maybe look into an alternate Garbage Collector.  Currently, we use G1GC

https://www.oracle.com/technical-resources/articles/java/g1gc.html


Calling sequence for inputStream issue
Ingest:         FileUtil.url2File(null, URL, File, 2);
Core2:              url2File(LoggerInf, URL, File, int)
Core2:                  url2File(LoggerInf, URL, File);
Core2:                      HttpGet.getFile(URL, File, int, LoggerInf);
HttpGet:                        getHttpGet(URL, File, -1, timeout, logger);
                                    return new HttpGet(contentURL, outFile, testSize, timeout, logger);
                                get.build();
                                    buildNoContentLength(entity)  or  buildContentLength(entity);
                                          stream2File CLOSES STREAM
