### ISSUE TITLE
UI: SSM_ROOT_PATH improperly set in config/initializers/config.rb

### ISSUE THREAD

**Issue by ashleygould** [CDLUC3/mrt-doc#576]
this is some really ugly code in config/initializers/config.rb.  it relies on the hostname to obtain the SSM_ROOT_PATH.

```
  def load_uc3_config(name:, return_key: nil)
    myenv = Socket.gethostname.match?(/uc3-.*-/) ? Socket.gethostname.gsub(/uc3-.*-/, '') : 'stg'
    resolver = Uc3Ssm::ConfigResolver.new(
      def_value: 'NOT_APPLICABLE',
      region: ENV.key?('AWS_REGION') ? ENV['AWS_REGION'] : 'us-west-2',
      ssm_root_path: ENV.key?('SSM_ROOT_PATH') ? ENV['SSM_ROOT_PATH'] : "/uc3/mrt/#{myenv}/"

```

needs a cleaner way to handle situations when SSM_ROOT_PATH is not present in ENV.  Ether raise and exception or define a set of default values in a `:ssm_defaults` hash.

**Comment by terrywbrady** [comment]
@ashleygould , I think the prior was a work around for a time in which Cap was not receiving the ENV variables.  I am hard coding to DEV.  A re-deploy will test this. https://github.com/CDLUC3/mrt-dashboard/commit/9bd7aca9e13eb8b2ffab2191905f0d181093aeef
