### ISSUE TITLE
UI: Handling of `port` var in Capistrano - looks like a typo in config/puma.rb

### ISSUE THREAD

**Issue by ashleygould** [CDLUC3/mrt-doc#577]
This is clearly wrong, but does not seem to cause any issues. 
```
  uc3adm@uc3-uc3ops01x2-dev:~/tools/deploy/mrt-dashboard/config$ grep port puma.rb
  # Specifies the `port` that Puma will listen on to receive requests; default is 3000.
  port        ENV.fetch('PORT', 26_181)
```

I think we should review how we are configuring `port` var.  Perhaps it should be set as ENV with default as are other config options in `config/deploy.rb`

**Comment by terrywbrady** [comment]
I do not understand what change is being requested.

**Comment by terrywbrady** [comment]
@ashleygould , can I close this issue?
