### ISSUE TITLE
UI: rails using different assets compressor in stage vs. production

### ISSUE THREAD

**Issue by ashleygould** [CDLUC3/mrt-doc#578]
```
dpr2@uc3-mrtui02x2-stg:~/tools/deploy/mrt-dashboard/config$ grep -r compressor *
environments/stage.rb:  config.assets.js_compressor = :uglifier
environments/stage.rb:  config.assets.css_compressor = :yui
environments/production.rb:  config.assets.js_compressor = :uglifier
environments/production.rb:  # config.assets.css_compressor = :sass
```

I hd trouble getting gem `yui` to compile in rails_env stage, so I ended up commenting out `config.assets.css_compressor` in `environments/stage.rb`.  This is probably not OK. 

Why is this commented out in production?

**Comment by terrywbrady** [comment]
https://github.com/CDLUC3/mrt-dashboard/commit/ed0631881a7f6e12089cd45412868b38a255eb64

**Comment by terrywbrady** [comment]
this should have been closed previously
