### ISSUE TITLE
Investigate feasibility of delivering MARC records to Alma Community Zone

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#587]
In two recent ETDs-specific meetings, one with a SILS team and another with UCD, the notion of sending MARC records for ETDs to the ExLibris Alma Community Zone surfaced. This may become a preferred method of record delivery when the new SILS comes online. We should investigate the feasibility of doing so. e.g. review Alma API and other documentation.

References:
- https://knowledge.exlibrisgroup.com/Alma/Product_Documentation/010Alma_Online_Help_(English)/Electronic_Resource_Management/030_Working_with_Local_Electronic_Resources/070Contributing_to_the_Community_Zone_%E2%80%93_Bibliographic_Records
- https://docs.google.com/document/d/1xxRG53FexWHYeXrAoK9foJWdzf_brLvB55fFWIJ4tcw/edit?usp=sharing

**Comment by terrywbrady** [comment]
@elopatin-uc3 , 

Fyi, I have some sample code for calling the Alma API.  This sample code reads the API.  It does not publish to the API.

Search for "API_REDIRECT".
- https://github.com/Georgetown-University-Libraries/AlmaInventory/blob/master/webapp/barcode.js

This code calls a PHP, Node, OR JSP app that embeds the Alma API key on to the request.
- https://github.com/Georgetown-University-Libraries/AlmaInventory/blob/master/jetty/redirect.jsp

**Comment by elopatin-uc3** [comment]
Thanks for the heads-up @terrywbrady . It's good to hear you have worked with the Alma API. At some point in the future (when depends on the SILS group, but probably a few months from now) I suspect that a request will be made to determine use cases and look into how we could write records to the Community Zone. There's also been talk of consulting with campuses regarding a standard ETDs marc record format. As I hear more, I'll post notes to this ticket.

**Comment by terrywbrady** [comment]
N/A - this is a detail for the new ETD service which will need to consider the SILS component
