### ISSUE TITLE
MRT-CORE2 support for Formatter of Java Maps

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#588]
Trouble in having the Core2 Formatter class support the following Data type

private SortedMap<Integer,HandlerState> queueHandlers = null;

I believe there are two issue.
   1) Detecting that this is a Map data type
   2) Supporting an Integer key type (assumes that key is a string)
   
   Issue 1 can be addressed by altering match string in the following "isMap()" method in FormatterAbs.java
   ```return c.getName().endsWith(".Map");```
   
   A sorted map has a name of:  java.util.SortedMap

**Comment by terrywbrady** [comment]
@mreyescdl , could the test you propose above be implemented with an `instanceof` call?

**Comment by mreyescdl** [comment]
Hi @dloy and @terrywbrady 
Can you have a look at the following pull request?

https://github.com/CDLUC3/mrt-core2/pull/9

I changed the search string for "Map" a bit to work with a TreeMap.
Also, I do like Terry mentions and check the Instance type of a Map key before use.  It works for Strings and Integers now.

**Comment by terrywbrady** [comment]
@elopatin-uc3 , closing.  pr is merged
