### ISSUE TITLE
Audit -- the oldest unprocessed item should be between 60 - 90 days old

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#591]
### Terry
Currently, we are at approx 150 days old.  https://merritt-admintool.cdlib.org/index.html?path=audit_oldest

We agreed to explore this after the Audit SSM refactor.

I have captured some brainstorming ideas here: https://confluence.ucop.edu/display/~tbrady/Audit+Brainstorming

### Goal
Shorten the fixity cycle for all of our content to 60-90 days, hopefully without requiring additional resources and preventing depletion of our database burst credits.

The primary reason for shortening this process is to address data problems much more quickly. 

The original intent of audit (doing data fixity) was to identify content corruption as a result of storage device problems (e.g. bit rot). Instead the audit service has been the primary tool for identifying systematic problems for both our cloud providers and for our own micro-services (store, inventory, and replication)

### Approaches for optimization
Several possibilities are being considered:
- Identify and use mechanisms for performing content fixity on S3 data. This becomes critical for very large data that can be in the 1T range. 
- Optimize db updates to reduce burst credit load
- Use of docker for dynamically maximizing throughput - possibly on single servers
- . . .

### Umbrella for existing Issues
This specific issue serves as an umbrella for other secondary issues:
- utf8mb4 in audit,replic,inventory yaml #600
- Proposed audit tables and server changes #597

#### Note
The install of the audit yaml version will occur before any implementation of this issue:
See Audit yaml/ssm - initial deploy prod #606

**Comment by elopatin-uc3** [comment]
Moving this onto the board, but it will be saved for a future sprint.
