### ISSUE TITLE
Develop and integrate ingest endpoints with the collection admin tool

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#592]
Endpoints are described here:

- https://github.com/CDLUC3/mrt-admin-lambda/tree/main/src-colladmin

Relates to #488

**Comment by terrywbrady** [comment]
@mreyescdl , for the purposes of the collection admin display, it would be good to have an additional endpoint that returns a full json representation of every profile.  

The new endpoint could be a parameter passed to /admin/profiles or it could be a new endpoint /admin/all-profiles.  Whichever you choose, please update the README that defines the endpoints.

Ideally, it would be good to have it return the template profile as well.  I will plan to repurpose the UI that pulled profiles from S3 to work off of this new return object.

**Comment by terrywbrady** [comment]
@elopatin-uc3 , I think we can move this off the board

**Comment by elopatin-uc3** [comment]
@terrywbrady I will move it to Deployed/Done. #488 talks about actual form fields, but we need a more specific ticket for Mark's work on returning new profile content. I will reference the [README](https://github.com/CDLUC3/mrt-admin-lambda/tree/main/src-colladmin); specifically the Generate Profile and Owner Object sections.
