### ISSUE TITLE
Annotate provenance notes without forcing the construction of a new object.

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#596]
Feb 2021: David expressed a wish for a place to record this type of information.

Question: should we create an interim confluence page for this until we can make this a system function.

**Comment by elopatin-uc3** [comment]
@terrywbrady the related ticket you were looking for may have been this one: #480

**Comment by elopatin-uc3** [comment]
Merritt provenance file type created.
