### ISSUE TITLE
Proposed audit tables and server changes

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#597]
### Problem
The current size of inv_audits is 121,668,096 files.

The current _inv_audits_ table serves two separate functions:
- status of a specific object file being tested
- queuing status for the specific file

The _inv_audits.status_ column reflects values for both content validation and for processing. 

Several table operations are made:
- select block of potential entries for file fixity testing
- update an entry from the selected block modifying _status_

On completion of fixity test:
- modify _status_ and _verified_
- modify all file fixity content columns if status of entry changes

The update for this process includes the entire entry with changes to the associated indexes for _verified_ and _status_. This update can potentially be for an entry > 255 bytes.

Because each entry must be updated, large amounts of content are changed in the db with each entry update including indexes. If the number of audits is high - burst credits for the database can be severely impacted.

### Proposal
Separate the audit fixity content from the audit process/queuing content.

Separating the two operations in the db, provides several features:
- fixity content only needs to be updated when the content fixity changes. For 99.9999999% times this is not necessary. Without fixity status changes,  the indexes on this content do not change.
- audit queue (_inv_audit_queue_) entries will continue to be changed as testing proceeds. These entries are considerably smaller than the corresponding _inv_audits_ entries (20 bytes?)
- _inv_auditqueue.status_ reflects queuing status and not content status
- _inv_auditqueue.processed_ is DATE of fixity test much smaller than the DATETIME for_inv_audits.verified_
- _inv_audit_ entries will be selected at time of fixity as a new secondary select
- _inv_audit_ entries will only be changed if the status of the content changes
- _inv_audit_ table remains the same

### Tables
~~~
CREATE TABLE `inv_audits` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`inv_node_id` SMALLINT(5) UNSIGNED NOT NULL,
	`inv_object_id` INT(10) UNSIGNED NOT NULL,
	`inv_version_id` INT(10) UNSIGNED NOT NULL,
	`inv_file_id` INT(10) UNSIGNED NOT NULL,
	`url` VARCHAR(16383) NULL COLLATE 'utf8_general_ci',
	`status` ENUM('verified','unverified','size-mismatch','digest-mismatch','system-unavailable','processing','unknown') NOT NULL DEFAULT unknown COLLATE 'utf8_general_ci',
	`created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`verified` TIMESTAMP NULL,
	`modified` TIMESTAMP NULL,
	`failed_size` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
	`failed_digest_value` VARCHAR(255) NULL COLLATE 'utf8_general_ci',
	`note` TEXT NULL COLLATE 'utf8_general_ci',
	PRIMARY KEY (`id`) USING BTREE,
	UNIQUE INDEX `inv_node_id` (`inv_node_id`, `inv_file_id`) USING BTREE,
	INDEX `id_idx` (`inv_node_id`) USING BTREE,
	INDEX `id_idx1` (`inv_object_id`) USING BTREE,
	INDEX `id_idx2` (`inv_version_id`) USING BTREE,
	INDEX `id_idx3` (`inv_file_id`) USING BTREE,
	INDEX `status` (`status`) USING BTREE,
	INDEX `verified` (`verified`) USING BTREE,
	CONSTRAINT `inv_audits_ibfk_1` FOREIGN KEY (`inv_node_id`) REFERENCES `inv`.`inv_nodes` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `inv_audits_ibfk_2` FOREIGN KEY (`inv_object_id`) REFERENCES `inv`.`inv_objects` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `inv_audits_ibfk_3` FOREIGN KEY (`inv_version_id`) REFERENCES `inv`.`inv_versions` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `inv_audits_ibfk_4` FOREIGN KEY (`inv_file_id`) REFERENCES `inv`.`inv_files` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DYNAMIC
;

CREATE TABLE `inv_auditqueue` (
	`inv_audit_id` INT(11) NOT NULL,
	`procstatus` ENUM('pool' ,'queued', 'processing','unknown') NOT NULL DEFAULT unknown COLLATE 'utf8_general_ci',
	`processed` DATE NULL
	PRIMARY KEY (``inv_audit_id`) USING BTREE,
	INDEX `procstatus` (`status`) USING BTREE,
	INDEX `processed` (`processed`) USING BTREE,
	CONSTRAINT `inv_audits_ibfk_1` FOREIGN KEY (`inv_audit_id`) REFERENCES `inv`.`inv_audits` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DYNAMIC
;
~~~

**Comment by elopatin-uc3** [comment]
Thank for the detailed write-up @dloy .

**Comment by terrywbrady** [comment]
Terry and David chatted about this.

As the audit server gets busy, we see an interesting symptom with showprocesslist:

```
-bash-4.2$ uc3-mysql.sh inv readwrite -- -e "show processlist;" | grep -v Sleep
Id	User	Host	db	Command	Time	State	Info
331180	...	inv	Query	0	updating	update inv_audits set status='processing' where id=195701816 and not status='processing'and ((verifi
331197	...	inv	Query	1	updating	update inv_audits set status='processing' where id=195701826 and not status='processing'and ((verifi
331207	...	inv	Query	37	updating	update inv_audits set status='processing' where id=195701814 and not status='processing'and ((verifi
331431	...	inv	Query	0	starting	show processlist
```

- One small change to explore: try dropping and re-adding the 'status' index to inv_audits.  In the DEV database, Terry saw improved performance after making this change.  We should pause audit while trying this.
- Consider adding a 'processing' column to inv_audits.  Rather than setting an interim status of 'processing' to a record, set this field instead (boolean or tinyint to represent an audit thread).  When an audit is completed, clear this field.

**Comment by dloy** [comment]
## Successful optimizations
The biggest problem with audit has been the exhaustion of IO burst credits for the inv RDS. Using a replicated db from production and with suggestions from Terry found a solution to this problem that can work up to 120,000 entries a minute without collision on at least 4 servers.

### Changes
The intent with these tests was to minimize the inv db tables architecture without exhausting burst credits.

- Use a single owner select for identifying multiple (opt 250) entries that this audit will work on.
The owner process only changes the date on the inv_audits table entry. The status value is NOT changed.

This process uses a select...for update to grab multiple entries followed by an update made on all of the selected entries - identified by ids.

Since the select only returns the id as part of the select, the processing time is very low.

This fix is managed by using:
~~~
            String sql = "select id "
                    + "from " + FixNames.AUDIT_TABLE + " "
                    + "where ((verified is NULL) OR (not DATE(verified)=DATE(NOW())))"
                    + " " + auditQualify + " "
                    + "order by verified "
                    + "limit " + capacity + " "
                    + "for update "
                    + ";";
~~~
followed by
~~~
String sqlUpdate = "update inv_audits "
            + "set verified='" + verifiedDB + "' "
            + "where id in (" + concatid + "); ";
~~~
- Since the update has modified date and eliminated collisions. No additional updates are required on an inv_audit entry unless the audit validation changes - happens rarely. Most audits are successfully verified.

### Testing
Testing has been done using audit code that is modified to not use content for validation but a working architecture. As the tests were run in Docker the CDS RDS Metrics are watched to determine if I/O burst credits are exceeded.

The tests allowed the select queue size and the sleeps between queue selection. Tests confirmed an optimal queue size close to 250 entries.  Once all redundant update calls to inv_audits were eliminated the sleep time between replenishing the queue could be reduced to zero.

Once the Tests were successful I ran tests with parallel docker audits. This confirmed the lack of collisions on locking and that max throughput is ~120000 items a minute. I have increased the single server parallel dockers to 4 which had approximately the same through put on a single server with 2 dockers.

Attached are timing tests.
[test-time.txt](https://github.com/CDLUC3/mrt-doc/files/6223481/test-time.txt)

**Comment by terrywbrady** [comment]
This is very encouraging to hear.  Following up on our team meeting conversation, I see a risk in using the verified column as a lock.

I recommend one of the following:
- continue to set status to 'processing' to explicitly lock a record
- or add an additional column to the table that notes that a record is locked -- the lock could be a boolean or it could contain the name of the audit instance that has locked a record
