### ISSUE TITLE
utf8mb4 in audit,replic,inventory yaml

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#600]
My solution for the 4 byte characters might necessitate changes to other yaml files.
- https://github.com/CDLUC3/mrt-dashboard/pull/91/files

We might need to add this to the docker section of the following files
- https://github.com/CDLUC3/mrt-inventory/blob/master/inv-conf/src/main/yaml/inventoryConfig.yml
- https://github.com/CDLUC3/mrt-audit/blob/master/audit-conf/src/main/yaml/auditConfig.yml
- https://github.com/CDLUC3/mrt-replic/blob/master/replication-conf/src/main/yaml/replicConfig.yml

**Comment by terrywbrady** [comment]
@elopatin-uc3 , I think this can be closed

**Comment by elopatin-uc3** [comment]
Yes, let's go ahead and close this.
