### ISSUE TITLE
Improve integration test / instructions for production patching

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#602]
During the Mar 2021 patching cycle, the ingest tests were failing during the prod checkout

Goal: fix this before the April patching cycle

- [x] Update README to remind the user about the impact of the ingest queue
- [ ] Vary timeframes based on environment.  Increase the ingest delay time for prod OR make that a command line option

**Comment by elopatin-uc3** [comment]
Hi @terrywbrady can this be moved to Deployed/Done?

**Comment by terrywbrady** [comment]
@elopatin-uc3 , it can.
