### ISSUE TITLE
Investigate use of ISO-8859-1 character set for unpacking UCSC zip submission

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#614]
#### Summary
Sue Perry at UCSC Library recently submitted an AIP in the form of an 84GB zip file via manifest. Merritt ingest fails on uncompressing this zip with the following error:

```
info] HandlerDisaggregate: creating zip entry: /dpr2/ingest_home/queue/bid-e4ddfaf0-3efa-4625-947d-ca81f8315026/jid-26c9a920-64ff-4de8-a4a6-2554f6a1b2b0/producer/UA041_AIP/data/objects/ua0041_med_0066/data/SSCSMs 2013/SHREW/Costumes/Shrew Costume Images/B20-1292798.jpg
java.lang.IllegalArgumentException: MALFORMED
        at java.util.zip.ZipCoder.toString(ZipCoder.java:58)
```

The zip can be manually uncompressed using standard linux tooling. However handling within a java process differs. 

UCSC file, uncompressed:
/dpr2/ingest_home/queue/bid-e4ddfaf0-3efa-4625-947d-ca81f8315026/jid-26c9a920-64ff-4de8-a4a6-2554f6a1b2b0/OUT

#### Tasks
- [ ] Investigate use of the ISO-8859-1 character set for uncompressing archives.
- [ ] Determine if it's possible to scan an archive beforehand to find filenames that may require this character set.

**Comment by elopatin-uc3** [comment]
I've suggested uncompressing/recompressing by command line to UCSC. Waiting to hear back.

**Comment by elopatin-uc3** [comment]
Still waiting to hear back from SDSC.

**Comment by terrywbrady** [comment]
@elopatin-uc3 , if we have a possible solution to try, shouldn't we try it rather than continuing to wait?

**Comment by elopatin-uc3** [comment]
@terrywbrady as it's been about two weeks, I've pinged Sue Perry to see what happened in the meeting she had planned with the archivists working on this deposit. I agree we should try to move forward, but want to make sure they're comfortable with the solution we've proposed (seems like they probably would be).

**Comment by elopatin-uc3** [comment]
Sue replied and mentioned that one of the archivists has been away; hence the reason for the delay. She expects to follow up soon.

**Comment by mreyescdl** [comment]
Copied original submission to the following directory to preserve in case we need to resubmit:

/dpr2/ingest_home/queue/ucsc_ticket614_bid-e4ddfaf0-3efa-4625-947d-ca81f8315026_save

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl !

**Comment by terrywbrady** [comment]
Assigning just to @elopatin-uc3

**Comment by elopatin-uc3** [comment]
@mreyescdl while helping UCSC with a different submission, they let me know that this one (UA041, a.k.a. MS041) was eventually submitted successfully:
https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm59m02r2

Could you remove the contents of the following directory on the EFS? It looks like it's 271GB:
```
queue/ucsc_ticket614_bid-e4ddfaf0-3efa-4625-947d-ca81f8315026_save
```

**Comment by elopatin-uc3** [comment]
I deleted the above "save" directory. Moving to Done.
