### ISSUE TITLE
Investigate Alma API for the purpose of retrieving updated ETDs records

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#615]
#### Summary
SILS team is devising a workflow for ETDs marc record handling. There is the notion of having Alma being the central solution for campuses to update embargo dates for ETDs. If this part of the workflow is approved, Merritt will need to regularly monitor ETD records in Alma for updates, which can then be written back to the Proquest metadata in associated Merritt ETD objects. 

Alma API to be used:
https://developers.exlibrisgroup.com/alma/apis/bibs/

The above workflow is referenced in an email from Xiaoli L. on 2/19/21.

**Comment by terrywbrady** [comment]
Part of the new ETD system
