### ISSUE TITLE
Jenkins / Capistrano should allow Stage services to be build from a set of repo tags or branches

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#620]
Some of the concepts from Ashley's deploy process for Rails should be worked into our Java builds.

When deploying a candidate release to stage, it should be possible to assemble the build using named branches and tags from various components.

Does it make sense to say we only merge into the main branch after a successful deploy?

It would be good to design the solution for this issue with Ashley.

**Comment by elopatin-uc3** [comment]
Perhaps consider release candidate branches as part of the solution? This might be too much overhead, but thought to mention it.

**Comment by terrywbrady** [comment]
build refactor
