### ISSUE TITLE
Collection Admin Review Notes

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#628]
Profile summary
- [x] Add notifications to table
- [x] Pull database summary info (object counts) into the table
  - [x] Look for collection by ark
  - [x] Also add this (and more detail) to the profile detail page 
  - [ ] Match on ark instead of mnemonic (dep on endpoint change)
- [x] Remove object type from table

Collection Profile Table
- [x] Coll Ark - comes from EZID
- [x] Owner Ark - Drop down
- [x] Admin notify - in SSM

Queue List
- [x] Batch id and Submitter has a header Creation Date
- [x] Job - link to manifest first, then to metadata
- [x] Check the title column

Batch Summary List
- [x] Is submitter and/or collection available?  Add if so
- [x] Mark will send the full set of statuses that might appear

Job Link
- [x] byte format number

Dryad list
- [x] Bubble up local id from erc_metadata (update page after load)
  - [x] Create new endpoint to read erc_metadata for a batch and return doi and ark in simple structure 
- [x] Date sort (in progress - Mark)
- [x] Compute summary status (defer until after initial release)
- [x] Trace for database entry (job and batch)
- [x] Break summary note into sep columns

Batch folder list last 7 days 
- [x] /admin/bids/<age in days>
- [x] Trace for database entry (job and batch)
- [x] Break summary note into sep columns

Job File List (Mark)
- [x] list, date and time info
- [x] For dryad, can help detect if stuff is still in progress

Pause/Unpause
- [x] Call new endpoints

Other ideas
- [ ] Modify the notification handler to save error messages to an accessible store 
  - Keystore: ZK, S3, Other?  Keep for 7 - 14 days

**Comment by terrywbrady** [comment]
@elopatin-uc3 , I recommend that we close this.  The ZK error handler should become a separate ticket

**Comment by elopatin-uc3** [comment]
Closing. New ticket filed: https://github.com/CDLUC3/mrt-doc/issues/653
