### ISSUE TITLE
Merritt specification links in the wiki return 401 Unauthorized

### ISSUE THREAD

**Issue by dmolesUC** [CDLUC3/mrt-doc#633]
**Describe the bug**

Following the PDF links on the [Technical Documentation](https://github.com/CDLUC3/mrt-doc/wiki/Technical-Documentation) wiki page returns 401 Unauthorized.

**To Reproduce**

1. In an incognito window, or when logged into Merritt as "Guest" (or as "UCB Read-Only User"), navigate to the [Technical Documentation](https://github.com/CDLUC3/mrt-doc/wiki/Technical-Documentation) page.
2. Click on any of the PDF links under "Object Model" or "Core microservices".

**Expected behavior**

Specification PDF is downloaded.

**Actual behavior**

"Unauthorized" page appears.

**Desktop (please complete the following information):**

 - OS: macOS Catalina (10.15.7)
 - Browser: Chrome
 - Version: 89.0.4389.90

**Additional context**

I thought it might be that the `/d/<url-escaped-ARK>/<version>/<path>` URLs weren't good any more (what with all the presigned Amazon link progress recently), but the ARKs don't work either (e.g. [`https://n2t.net/ark:/13030/m55t8dtz`](https://n2t.net/ark:/13030/m55t8dtz) redirects to `http://merritt.cdlib.org/m/ark%3A%2F13030%2Fm55t8dtz`, which redirects to its HTTPS equivalent, which then returns `401 Unauthorized`).

**Comment by elopatin-uc3** [comment]
Thanks for catching this @dmolesUC. Our CoreTrustSeal certification renewal process will start relatively soon, and we'll definitely want to address this issue. It most likely has to do with our update to Rails 5.

**Comment by elopatin-uc3** [comment]
Ah, never mind; much simpler. There was an inadvertent change to LDAP permissions. Fixed.

**Comment by dmolesUC** [comment]
Thanks!

**Comment by dmolesUC** [comment]
I still can't see it as a logged-in user, only as Guest, but IIRC that might be a long-standing problem with public collections?

**Comment by elopatin-uc3** [comment]
Yes, this is a limitation of the LDAP approach taken in Merritt. I've added read and download permissions to the associated collection for the UCB Read-Only User, in case that's helpful.
