### ISSUE TITLE
Some items require double encoding to create presigned URLs

### ISSUE THREAD

**Issue by sfisher** [CDLUC3/mrt-doc#636]
**Describe the bug**
In some cases, if the filename contains a percent symbol (`%`) we seem to need to double-encode the filename, but not in other cases.

**To Reproduce**

From a bash shell, set up so you can easily test in curl:
```
# SETUP for url encoding from the shell
# see https://unix.stackexchange.com/questions/159253/decoding-url-encoding-percent-encoding
# and may be different for python2 vs 3, python 2 shown here
alias urlencode='python -c "import sys, urllib as ul; \
     print ul.quote_plus(sys.argv[1])"'

# set up your credentials for testing with curl
MRTUSER="<fill-merritt-user-here>"
MRTPWD="<fill-merritt-pwd-here>"
```

Now test presigned url creation with one that works even though it contains a percent sign.
```
# resource_id: 37183, ark:/13030/m53c15rd, filename ZnNiO_5%_400C-bet.xlsx, version is 2
ARK=`urlencode "ark:/13030/m53c15rd"`
FN=`urlencode "ZnNiO_5%_400C-bet.xlsx"`
VN="2"

curl -L -u "$MRTUSER:$MRTPWD" "https://merritt.cdlib.org/api/presign-file/$ARK/$VN/producer%2F$FN?no_redirect=true"
```

Now test presigned url creation with one that *doesn't* work even though it seems the same and contains a percent sign.
```
# resource_id: 37337, ark:/13030/m5770mw2, filename: MrBayes50%majrule_all.nex.con.tre , version is 1
ARK=`urlencode "ark:/13030/m5770mw2"`
FN=`urlencode "MrBayes50%majrule_all.nex.con.tre"`
VN="1"

curl -L -u "$MRTUSER:$MRTPWD" "https://merritt.cdlib.org/api/presign-file/$ARK/$VN/producer%2F$FN?no_redirect=true"

# this returns a 404 status code with some HTML output

# now encode the filename again so it is now double-encoded and try the request again
FN=`urlencode "${FN}"`

curl -L -u "$MRTUSER:$MRTPWD" "https://merritt.cdlib.org/api/presign-file/$ARK/$VN/producer%2F$FN?no_redirect=true"

# and it returns a 200 status
```

**Expected behavior**
A filename encoded with w3c standard encoding would work.  Also strange that it seems to be inconsistent across different files or datasets.  Both work in the Merritt UI, I believe.  What is your special magic secret sauce?

I believe I have a fairly complete list of datasets that encounter this problem.  See https://docs.google.com/spreadsheets/d/1i4hYFjLNQ78io04tc-1wOAy95hVRHlT4SXo-E46urPU/edit?usp=sharing .  See the ones that have a *note* of "Percent in filename"  (the other things in there are likely other issues for us to look at).

**Comment by terrywbrady** [comment]
Apache seems to be the culprit here.

## Double Encoded Logs
```
Started GET "/api/presign-file/ark%3A%2F99999%2Ffk41346229/1/producer%2FTest50%25majrule.txt" for 10.10.2.10 at 2021-05-07 12:21:26 -0700
Processing by FileController#presign as TEXT
  Parameters: {"object"=>"ark:/99999/fk41346229", "version"=>"1", "file"=>"producer/Test50%majrule.txt"}
```

## Single Encoded - Routed through Apache (note the `\u0000`)
```
Started GET "/api/presign-file/ark:%2F99999%2Ffk41405267/1/producer%2FTest50%majrule.txt" for 10.10.2.10 at 2021-05-07 12:22:19 -0700
Processing by FileController#presign as TEXT
  Parameters: {"object"=>"ark:/99999/fk41405267", "version"=>"1", "file"=>"producer/Test50\u0000jrule.txt"}
```

## Single Encoded - Directly to Rails
```
Started GET "/api/presign-file/ark%3A%2F99999%2Ffk41405267/1/producer%2FTest50%25majrule.txt" for 172.31.48.23 at 2021-05-07 12:26:34 -0700
Processing by FileController#presign as TEXT
  Parameters: {"object"=>"ark:/99999/fk41405267", "version"=>"1", "file"=>"producer/Test50%majrule.txt"}
```

**Comment by mreyescdl** [comment]
Running Encoding tests through ALB vs Apache Stage shows that the ALB is much better at retaining the proper encoding.
This is shown below.

Next step is to apply Terry's UI update to stage and rerun the test.

ALB stage
      Test file link from version page: File%00x.md (FAILED - 1)
      Test file link single-encoding from version page: File%00x.md (FAILED - 2)
      Test file link from version page: File%11x.md (FAILED - 3)
      Test file link single-encoding from version page: File%11x.md (FAILED - 4)

Apache stage
      Test file link single-encoding from version page: README %AF.md (FAILED - 1)
      Test file link single-encoding from version page: Test50%majrule.txt (FAILED - 2)
      Test file link from version page: File%00x.md (FAILED - 3)
      Test file link single-encoding from version page: File%00x.md (FAILED - 4)
      Test file link from version page: File%11x.md (FAILED - 5)
      Test file link single-encoding from version page: File%11x.md (FAILED - 6)
      Test file link single-encoding from version page: File%aax.md (FAILED - 7)
      Test file link single-encoding from version page: File%AAx.md (FAILED - 8)
      Test file link single-encoding from version page: File%hhx.md (FAILED - 9)
      Test file link single-encoding from version page: File%HHx.md (FAILED - 10)
      Test file link single-encoding from version page: File%??x.md (FAILED - 11)
