### ISSUE TITLE
Investigate private collection home link redirect to an external site.

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#641]
#### Summary
In the near future we will be manually submitting each of the 19 objects in the Holl and Zahawi public-facing collection to Dryad to create new datasets (only the latest version of each object is needed). The collection will then be stripped of its "anonymous" user in LDAP that provides guest access. 

Once the collection is made private, the owner would like the collection home link https://merritt.cdlib.org/m/ucsc_lib_hollzahawi to point to http://www.holl-lab.com/islas-project.html

(old url: http://www.holl-lab.com/tropical-forests.html)

This use case, where a private collection's home page redirects to an external site, will likely occur again as we migrate contents of some of the remaining few public collections to Dryad.

#### Tasks
- [x] Investigate if it is type of redirect is best accommodated by the UI, or, if it would also be something that would be addressable via an AWS load balancer (given our desire to move away from Apache).
- [ ] Todo: add integration test case for redirects

**Comment by elopatin-uc3** [comment]
Also relates to #550

**Comment by terrywbrady** [comment]
@elopatin-uc3 ,

Will content still exist in the collection?  If so, the collection page would still be needed to access collection content.

It sounds like the request is to perform this redirect only when a user is not already authenticated.

How many of these do you anticipate?  Does this need to be a configurable system feature or should we just code a few exception cases?

Does this feature need to be available before you migrate?

**Comment by elopatin-uc3** [comment]
@terrywbrady, thanks for these questions. I hadn't spotted them earlier.
> Will content still exist in the collection?
Yes, we will be keeping the collection content, but removing the anonymous user in LDAP (removing public access). That said, there is no expectation that any user (aside from UC3 team members) would be able to view content.

> It sounds like the request is to perform this redirect only when a user is not already authenticated.
Yes

> How many of these do you anticipate? 
We have ten more collections to "move" (make private) so I anticipate more of these requests to surface. 
What do you think would be involved with a configurable feature?

> No, it does not need to be available pre-migration.

**Comment by elopatin-uc3** [comment]
Dataset and collection owner Karen Holl requests that we wait until May 11 to deploy redirect changes.

**Comment by elopatin-uc3** [comment]
Noting PR: https://github.com/CDLUC3/mrt-dashboard/pull/93
