### ISSUE TITLE
consolidated logging

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#65]
Goal would be to make it easier to track down the cause of an ingest error w/o having to hunt through three log files on three servers. Can we log everything to a single place? Can we use some log-harvesting service? What are our options here?
 - [ ]

**Comment by elopatin-uc3** [comment]
It would be really helpful if these stories had a bit of information in them.  Ie. What services they affect, what changes are being made, any configuration that needs to be done to support the logging, which environments it affect, and how to test and verify that the task is complete. (Marisa Strong - Jul 18, 2016)

**Comment by terrywbrady** [comment]
Charlie on the D&D team is using Fluentd.

**Comment by terrywbrady** [comment]
@elopatin-uc3 , closing.  We have plans to implement Ashley's new logging infrastructure
