### ISSUE TITLE
[Inventory] Recent production Inventory failures

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#650]
4 Objects failed

3 objects are member of 2 collections
           ONEShare DataUp collection
           DataONE Dash
Related ticket: https://github.com/CDLUC3/mrt-doc/issues/649

1 object has encoding issue in metadata:
           what:   Kurzgeschichten unserer Zeit / [fum\ur den Schulgebrauch zusammengestellt von Wilhelm Helmich und Paul Nentwig]. 67350632D-B3632752.pdf

**Comment by mreyescdl** [comment]
Full analysis of 4 objects

mrtQ-000001165844: [failed: Tue Apr 20 09:16:06 PDT 2021] {manifestURL=http://storage.cdlib.org:35121/manifest/9501/ark%3A%2F13030%2Fm5r269bc}
        EXception:SaveObject: Exception for entry id=ark:/13030/m5r269bc -
        GENERAL_EXCEPTION[Unexpected Programmic exception] java.lang.IllegalArgumentException: Malformed \uxxxx encoding.

        ERC Data
           who:    (:unas)
           what:   Kurzgeschichten unserer Zeit / [fum\ur den Schulgebrauch zusammengestellt von Wilhelm Helmich und Paul Nentwig]. 67350632D-B3632752.pdf
           when:   (:unas)
           where:  ark:/13030/m5r269bc
           where:  b138009235

mrtQ-000001527571: [failed: Tue Apr 20 09:15:49 PDT 2021] {manifestURL=http://storage.cdlib.org:35121/manifest/3041/ark%3A%2F90135%2Fq1dv1gt9}
        Member of two collections (oid: 108926)
           ONEShare DataUp collection
           DataONE Dash

mrtQ-000001527580: [failed: Tue Apr 20 09:15:49 PDT 2021] {manifestURL=http://storage.cdlib.org:35121/manifest/3041/ark%3A%2F90135%2Fq1gh9fw0}
        Member of two collections (oid: 636875)
           ONEShare DataUp collection
           DataONE Dash

mrtQ-000001527622: [failed: Tue Apr 20 09:15:49 PDT 2021] {manifestURL=http://storage.cdlib.org:35121/manifest/3041/ark%3A%2F90135%2Fq1fb50w2}
        Member of two collections (oid: 643774)
           ONEShare DataUp collection
           DataONE Dash

**Comment by elopatin-uc3** [comment]
There was one more that was in the report this morning:
mrtQ-000001527812: [failed: Tue Apr 20 09:49:43 PDT 2021] {manifestURL=http://storage.cdlib.org:35121/manifest/3041/ark%3A%2F13030%2Fm5vn0427}

This one is part of the Dryad production collection:
https://merritt.cdlib.org/m/ark%3A%2F13030%2Fm5vn0427
