### ISSUE TITLE
Modify the notification handler to save error messages to an accessible store

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#653]
Modify the notification handler to save error messages to an accessible store
Keystore: ZK, S3, Other? Keep for 7 - 14 days

Originally in #628

**Comment by terrywbrady** [comment]
@elopatin-uc3 is this still open or did the notification improvements handle this?

**Comment by elopatin-uc3** [comment]
@terrywbrady Notification improvements (error report attachment) have this covered; closing
