### ISSUE TITLE
Investigate - use of stored Dryad bucket content for access by storage service

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#655]
See if Dryad content saved to bucket can be input directly by both Ingest and Storage - avoiding a double download of content

**Comment by elopatin-uc3** [comment]
Related to shared EFS between Storage and Ingest:

**Comment by dloy** [comment]
This process creates a new Storage manifest.xml corresponding to Dryad - apply a localized removal of a file on specific versions,

Once a "correct" Merritt version exists then the Merritt system would need to be adjusted to allow the changes to be reflected in the inv db, all Merritt replications.

Working on this approach has shown that several  new Dryad objects cannot have earlier versions adjusted using this approach because certain files were added to Dryad much later than they were added to Merritt. Examples include a file included in version 1 of Merritt and showing up in version 5 of Dryad. Adjusting manifest.xml is doable - manifest.xml now exist reflecting the needed 
changes.

The most difficult problem in addition to changing the manifest.xml is how to apply these fixes to  get Merritt to correctly look like Dryad (for current only).

This fix requires:
- replace the manifest.xml for all primary objects - this includes
    - add manifest.xml as manifest-original.xml
    - delete manifest.xml
    - add updated manifest.xml
- delete secondary content
- delete inv db
- add to inventory. This will:
    - kick in automatic replacement of secondary content with automatic update of audit
 
Discussions with Scott about his original Plan C - add a corrective ingest version  to fix these problems on Merritt would be a substantial fix on Dryad. Should not be done. So proceeding with this task as originally planned.
