### ISSUE TITLE
Replace audit stop with audit pause in shutdown scripts

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#658]
The new audit "pause" is a graceful shutdown command that should replace "stop":
curl -X POST 'http://localhost:37001/mrtaudit/service/stop?t=xml'
with
curl -X POST 'http://localhost:37001/mrtaudit/service/pause?t=xml'

Under some cases stop will drop updates in progress

**Comment by elopatin-uc3** [comment]
@dloy Would you like to bring this into the current sprint? (figure yes; will catch up via slack)

**Comment by terrywbrady** [comment]
Adding to ops board to discuss any DevOps dependencies for this task.

**Comment by terrywbrady** [comment]
https://www.pivotaltracker.com/story/show/178915295
