### ISSUE TITLE
Continue Audit Instance Type Evaluation

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#663]
Now that the Audit service has been designed to avoid RDS credit issues, we need to ensure that the assigned instance type is correct.

On 4/24, while running on T3 instances, the Audit service was able to process 5M files.  Then CPU credits drained.

On 4/27, David, Martin, Ashley and Terry met to assign new instance types to these servers.  Instance types were chosen with consistent CPU capacity.   audit01 and 02 are now c5.large; audit03 and 04 are m5.large

On 4/28, David resized the tomcat memory allocation to take better advantage of the resources on audit03 and audit04.

Performance has been steady and reliable, but the number of files per day seems close to 1M files.  We gave this a bit of time in case the performance was dependent on the files being processed.  Terry added some new reports to look at files and bytes processed during a window of time.

More analysis is needed
- [ ] Question: why did we not see a dramatic increase in performance?  What the the T3's have that the new instances do not have?
- [ ] Is the C5n type worth considering?  It offers a faster network.
- [ ] David could make the buffer size (currently 32MB) larger now that the machines processing content have more memory?
- [ ] Are there other application dials to modify such as the number of threads running per instance?
- [ ] Is something capping network throughput to these boxes?
- [ ] If we pause once server, do the others seem to make up the difference?
- [ ] What log processing could we create to calculate files and bytes processed for each instance?  This would be really useful if we try other instance types.

**Comment by elopatin-uc3** [comment]
Observations from Ashley and Mark:

- Currently 80% CPU idle on hosts
- Tomcat memory change didn't take immediate effect, but over the weekend this memory is now being utilized. 
- IAS has removed the old scratch space.
- 4GB looks like it is not enough; only a little bit of swap happening
- Setting min and max memory the same at first
- But now we set the min to 512MB and set the maximum very high so the app can grow into the available memory

audit04 settings currently:
-Xmx6114m -Xms3072m

**Comment by terrywbrady** [comment]
```
Daily audit stats
4/28 1M files
4/29 1M files
4/30 6M files (processing appeared to ramp up around 1pm)
5/1 12M files
5/2 4.8M files
5/3 7.6 M files
5/4 (so far) 1.9M files
```

**Comment by terrywbrady** [comment]
I did a super crude analysis of audit logs.  I am simply counting batches (of 248 files) processed per day in the month of May.

(Remember that audit03 and audit04 were down for 2 days after patching.
```
ssh (server) grep -c verified ".../tomcat/logs/audit2105*.log" | cut -d ':' -f 2
```
Curiously, this numbers would imply that Audit01 and Audit02 are processing more than Audit03 and Audit04.

```
	Audit01	Audit02	Audit03	Audit04
5/01	12304	13022	11871	11503
5/02	4672	5732	4788	4513
5/03	6681	8849	7555	7584
5/04	3618	4290	2027	2588
5/05	4126	4581		
5/06	7549	7827		
5/07	5485	4487	2734	2955
5/08	4456	4079	3991	4659
5/09	4907	6226	3398	5980
5/10	3283	2689	2704	3221
5/11	1841	1127	1716	1942
5/12	1430	1484	1432	1299
5/13	1196	1046	1478	1095
5/14	1477	1342	2298	2035
5/15	1744	2376	1657	1616
5/16	857 	1430	1177	870
5/17	625 	1348	1343	766
Total	66251	71935	50169	52626
```

I really wish we could explain the extraordinary performance that we saw on 05/01.

**Comment by elopatin-uc3** [comment]
@terrywbrady It seems like we may be able to close this ticket. Let me know if you like to leave it open for continued evaluation. Thanks

**Comment by terrywbrady** [comment]
@elopatin-uc3 , closing makes sense.  Thanks
