### ISSUE TITLE
Create UC Berkeley Library Kransky Collection

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#677]
Collection Repo: UC Berkeley Library Kransky Collection
user: ucblap, davidtriebwasser
permissions: r/w/download

#### Tasks: Production
- [x] Create collection intake form
- [x] Mint collection ARK
- [x] Create collection profiles
- [x] Submit collection admin object
- [x] Create associated entries in LDAP
- [x] Add collection to inventory database (introduced via admin object submission after collection profile is live)
- [x] Update collection record with name, mnemonic, privs
- [x] Set primary storage node (introduced via admin object submission after collection profile is live)
- [x] Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- [x] In EZID, set collection Status (to unavailable) and Harvesting option (to No)

**Comment by elopatin-uc3** [comment]
Collection intake form created:
https://docs.google.com/document/d/1EV3bD8T_i4xUBKXb3PtWJWca8jsueVx5fWTmMMx9AE8/edit?usp=sharing

**Comment by elopatin-uc3** [comment]
ARK minted: https://ezid.cdlib.org/id/ark:/13030/m51s2gx8

**Comment by mreyescdl** [comment]
Collection object created with ID: ark:/13030/m51s2gx8
