### ISSUE TITLE
UI Release: 2021-06-3: Improve % Encoding in preparation for migration to ALB

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#680]
## Proposed Time
- 6/3 at 5pm
- This will be a standard deploy with minimal disruption

## Purpose

- Handle percent encoding
- Add ALB rotation to puppet deployment scripts

## Details
- https://github.com/CDLUC3/mrt-doc/issues/636

## Servers

- uc3-mrtui03x2-prd.cdlib.org
- uc3-mrtui04x2-prd.cdlib.org

## Deploy Process:
- Tag and deploy using Puppet deploy process for the UI

## Source changes

- https://github.com/CDLUC3/mrt-dashboard/pull/95

## Jenkins Builds
- N/A

## Post release tasks - improve deploy process
- https://www.pivotaltracker.com/n/projects/2157590/stories/178272648

**Comment by mreyescdl** [comment]
UI source is tagged for ALB cutover - v1.0.16-dev4 

This tag references branch "prodALB" which will use a new Ingest Load Balancer endpoint (ingest.cdlib.org)

**Comment by mreyescdl** [comment]
Complete.

Of note, ran into an issue when running Puppet Agent:
https://github.com/CDLUC3/mrt-doc/issues/693

**Comment by mreyescdl** [comment]
Post process task.

Pull request:
    https://github.com/CDLUC3/mrt-dashboard/pull/97
