### ISSUE TITLE
Investigate cloud store locking of manifest.xml to prevent overlapping errors

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#684]
Concurrent ingest runs on the same object can cause eventual fixity errors. The concurrent storage updates grab the same version of the manifest.xml and create a new different version. The last storage update completing, overlays the version created by the other run.

If the single manifest.xml can be locked - this error may be eliminated. 

Research is definitely required

**Comment by elopatin-uc3** [comment]
Relates to #683

**Comment by elopatin-uc3** [comment]
David researched; not currently feasible
