### ISSUE TITLE
Storage microservice optimize/research changes

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#686]
### Description
This issue is an umbrella project for a number of earlier issues.

The purpose of the overall project is to apply a number of changes to improve overall storage performance. Currently these changes include:
1. share EFS storage with Ingest to reduce content replication: Research: Shared EFS ingest storage with Merritt Storage #421
1. use ENV variable to identify log location. Currently this is handled as an SSM variable that does not easily fit with generalized server docker applications for microservices. Change store, replic, inventory configurations for log from SSM to ENV #679
1. Optimize the confirmation reread of content for fixity to use the optimized cloud audit mechanism. This will eliminate the full download of the file.
1. research whether a different approach can be used for the generation of container files for customers. Several approaches have been proposed. Possibly Investigate - if container file downloads by Dryad users can be handled by javascript #656 or possibility of stream generation in cloud.
1. Changes indicated by admin consistency reports

**Comment by terrywbrady** [comment]
Also consider: research if it is possible to stream content into a zip while writing to S3.

**Comment by elopatin-uc3** [comment]
Related to #421

**Comment by dloy** [comment]
### stage deploy
Items:
- share EFS storage with Ingest to reduce content replication: Research: Shared EFS ingest storage with Merritt Storage #421
- use ENV variable to identify log location. Currently this is handled as an SSM variable that does not easily fit with generalized server docker applications for microservices. Change store, replic, inventory configurations for log from SSM to ENV #679
- Optimize the confirmation reread of content for fixity to use the optimized cloud audit mechanism. This will eliminate the full download of the file.

#### Servers:
uc3-mrtstore01x2-stg.cdlib.org
uc3-mrtstore02x2-stg.cdlib.org

#### Code
https://github.com/CDLUC3/mrt-store/commit/7b37db8fdab5420a8e9a32098e0c6507d21e63a8
https://github.com/CDLUC3/mrt-store/commit/37efc2a1e9e47c37078e289d1a547ee993ebc1c4
https://github.com/CDLUC3/tomcat8_catalina_base/tree/mrt-store01x2-stg
https://github.com/CDLUC3/tomcat8_catalina_base/tree/mrt-store02x2-stg

#### Jenkins
http://builds.cdlib.org/job/mrt-store-pub/141/console

#### Install
- [ ] store01
- [ ] store02

**Comment by terrywbrady** [comment]
I made a docker-compose change to support this in our docker stack: https://github.com/CDLUC3/merritt-docker/commit/5120c86378e326cbd2d324971b80c0ccb56c440a

**Comment by mreyescdl** [comment]
Changes to Ingest in place on branch "eft-storage"

Docker environment test okay.

Stage environment fails due to permission issue with Storage.  
Our umask in Ingest for user "dpr2" is correct, but Tomcat must overrule this.

I'll ask IAS to explicitly set the UMASK in the Systemctl file to 002

**Comment by mreyescdl** [comment]
Added umask to Tomcat startup

export UMASK=0022

Deployed to Ingest stage workers 1/2
