### ISSUE TITLE
New Frontera Production collection

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#695]
#### Summary
Create a collection for new Frontera submissions. This collection will eventually supersede the existing "UCLA Library: Strachwitz Frontera Collection of Sound Recordings" from which all content will eventually be deleted.

#### Tasks: Production
- [x] Create collection intake form
- [x] Mint collection ARK
- [x] Create collection profiles
- [x] Submit collection admin object
- [x] Create associated entries in LDAP
- [x] Add collection to inventory database (introduced via admin object submission after collection profile is live)
- [x] Update collection record with name, mnemonic, privs
- [x] Set primary storage node (introduced via admin object submission after collection profile is live)
- [x] Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- [x] In EZID, set collection Status (to unavailable) and Harvesting option (to No)

**Comment by elopatin-uc3** [comment]
New collection showing in UI: https://merritt.cdlib.org/m/ucla_lib_str_frontera

**Comment by mreyescdl** [comment]
Collection admin object submitted.

@elopatin-uc3 Please let me know if there is anything outstanding for me to do on this ticket.

**Comment by elopatin-uc3** [comment]
@mreyescdl thanks for submitting the admin object. I should be set from here on out.

**Comment by elopatin-uc3** [comment]
All setup tasks complete. Moving to Done.
