### ISSUE TITLE
Cleanup for inv db issues from System Admin Tool

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#696]
## Purpose of this Issue
This is an ongoing Issue used to document actions taken to cleanup problems detected by System Admin tool for the production inv database.

## link example:
https://merritt-admintool.cdlib.org/index.html?path=report&report=consistency-reports/2021-06-03

**Comment by dloy** [comment]
## Correction for problem of inv_files that have not corresponding inv_audits
### Problem list:
See attached
[file-no-audit.txt](https://github.com/CDLUC3/mrt-doc/files/6610720/file-no-audit.txt)

### Cause
Termination of inventory process before audit entries were completely written.

### Solution
Delete and re-add two problem object:
ark:/28722/k2tm72j0x
ark:/13030/m5qp1dtw

Will have the effect:
- correct file audit map
-  that creation dates will be current
- non storage replication (detects content already exists) but will use corrected audits from inv

### Action
- [ ] use inv object delete on both objects
- [ ] use inv add on both objects

**Comment by dloy** [comment]
## Processing indicates items older than 1 day still in inv_audits.status="processing"

### Problem list
https://merritt-admintool.cdlib.org/index.html?path=audit_size

### Determine items
~~~
SELECT COUNT(*)
FROM inv_audits
WHERE STATUS='processing'
AND verified < '2021-06-07 00:00:00'
~~~

After determining the time of the problem from the above SELECT did manual review of uc3-mrtauditnnx2-prd logs and determined:
~~~
Fri Jun 04 13:11:23 PDT 2021 ** (02) [audit] FixityUtil: org.cdlib.mrt.s3.tools.CloudChecksum-add:286 GENERAL_EXCEPTION[Unexpected Programmic exception] org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 16000000; received: 10061438
Fri Jun 04 13:11:23 PDT 2021 ** (02) [audit] FixityValidation: Exception for entry id=200618508 - entry:[ source="web"  itemkey="200618508"  url="http://storage.cdlib.org:35121/content/2001/ark%3A%2F13030%2Fm5qk0mwv/1/producer%2Fwayback.curator.index.tar.gz?fixity=no"  created="2015-12-10 14:28:12"  status="processing"  type="SHA-256"  value="9261aa3a7338a1f948bd7883486a638cdfcf0e34c7c97d48bcd1d12d817ccaf6"  modified="2015-12-10 14:28:20"  size="85852715464" ]
Fri Jun 04 23:14:09 PDT 2021    (01) [audit] RunFixity:  - capacity=248 - sleepTime=0 - verified=248 - non-verified=0 - processMs=53802660 - runVerifiedMs=72 - bytes=2788651833834
~~~


### Manual fix
~~~
UPDATE inv_audits
SET STATUS='unknown'
WHERE STATUS='processing'
AND verified < '2021-06-07 00:00:00'
~~~

**Comment by terrywbrady** [comment]
@dloy , would it also make sense to run the following:

```
UPDATE inv_audits
SET STATUS='unknown'
WHERE STATUS='processing'
AND verified is null
AND created < '2021-05-01'
```

**Comment by elopatin-uc3** [comment]
@terrywbrady @dloy Should this ticket be closed? Or would you like to leave it open in order to document further ideas? Thanks

**Comment by terrywbrady** [comment]
@elopatin-uc3 , this can be closed
