### ISSUE TITLE
[UI] Update gem mrt-ingest-ruby 

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#697]
Updated our Merritt Ingest Gem to address GitHub dependabot issue as well as Travis Rubocop ones.
We are now at version 0.0.6, but the UI is fixed at 0.0.4

https://rubygems.org/gems/mrt-ingest

This gem is used as part of the Nuxeo harvesting.

**Comment by terrywbrady** [comment]
@elopatin-uc3 , I think this can be closed

**Comment by elopatin-uc3** [comment]
@terrywbrady let me check in with Mark on this one.
