### ISSUE TITLE
Reset sql connection in audit when processing a large batch

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#698]
Copied from a conversation with @dloy  on Slack:

>  for extremely long runs, the old mysql connection is not tested to be valid. Have a fix that if time is > 1 hour than test if valid and reset if not

Note that this should prevent the "null batch" issue that has been appearing in the "audit size of queue" report.

https://merritt-admintool.cdlib.org/index.html?path=audit_size

**Comment by elopatin-uc3** [comment]
Closing as duplicate of #699
