### ISSUE TITLE
DOI report warning for doi:10.5061/dryad.vx0k6djps

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#701]
Recent local ID collision that needs to be addressed:
https://merritt-admintool.cdlib.org/index.html?path=report&report=consistency-reports%2F2021-06-14%2Fdoi.FAIL

DOI | Num Arks | Min Ark | First Update | Max Ark | Last Update | Status
-- | -- | -- | -- | -- | -- | --
doi:10.5061/dryad.vx0k6djps | 2 | ark:/13030/m50g8xqt | 2020-09-04 09:15:22 | ark:/13030/m59d2z6b | 2021-06-07 12:08:54 | FAIL

**Comment by mreyescdl** [comment]
Updated object "ark:/13030/m59d2z6b" 
Deleted object "ark:/13030/m50g8xqt"

Scott altered Dryad database to remap versions.

Issue is resolved

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl
