### ISSUE TITLE
Admin tool report: scan localid table for the presence of active arks

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#710]

**Comment by elopatin-uc3** [comment]
@terrywbrady what is an "active ark" in this case?

**Comment by terrywbrady** [comment]
@dloy used this term.  I think this is meant to detect any localid entries that reference an ark that has been deleted.

**Comment by terrywbrady** [comment]
@elopatin-uc3 , I am not sure I understand this issue anymore.

**Comment by elopatin-uc3** [comment]
Checking in with David.

**Comment by elopatin-uc3** [comment]
Closing; no further reference
