### ISSUE TITLE
Establish Nuxeo feed harvest for UCI Norbert Tsi photographs collection

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#711]
#### Summary
Establish new feed harvest for the following UCI collection in Nuxeo:
https://registry.cdlib.org/27794/norbert-tsi-photographs-of-activism-in-southern-ca/
/asset-library/UCI/SCA_SpecialCollections/MS-R204

This harvest should deposit content into the "UC Irvine SCA Special Collections" collection in Merritt.
As this collection is currently empty, it's probably safe to start in Production, vs. establishing a new collection on Stage and harvesting into that.

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27794.atom
Per Gabriela Montoya, this feed should be available as of 6/23. Feed URL format is:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_[Collection Registry ID].atom

Associated FreshDesk ticket:
https://help.oac.cdlib.org/a/tickets/90333

**Comment by mreyescdl** [comment]
Hi @elopatin-uc3 
I'm getting a Forbidden response when trying to access the Feed (see below)
Can you double-check that the URL is correct?  Thanks

$ curl -I https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27794.atom
     HTTP/1.1 403 Forbidden

**Comment by elopatin-uc3** [comment]
@mreyescdl Sorry about that. I have a note out to Gabriela and Adrian to determine what the correct URL is.

**Comment by elopatin-uc3** [comment]
@mreyescdl this is indeed the correct URL:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27794.atom 

However it will not be available until next Tuesday morning.

**Comment by mreyescdl** [comment]
Feed is now set up on UI03.  It will run at 8:00 AM Thursday
Ran manually to test
