### ISSUE TITLE
Bad object: ark:/13030/m54f7j9d

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#717]
### Info
~~~
mnemonic                 ark	                  created
ucb_lib_examiner	ark:/13030/m54f7j9d	2021-05-20 16:20:47
~~~
This object showed up as a problem when it could not be replicated. It is no longer possible to download the manifest.xml through the storage service.  This is required by both storage and replication for object handling.

Because so many of the services directly pull content off the cloud storage (here minio). Audit successfully verified the content and presigned url's work for many of these files.

This object was one of several that were impacted by problems at Berkeley with the use of pipe characters in content supplied in the manifest.txt.

Because some of the content is not available, I recommend that the localid for this content:
~~~
id	inv_object_ark       inv_owner_ark               local_id                                             created
1960419	ark:/13030/m54f7j9d	ark:/13030/j2x634h1	BANC PIC 2006.029--NEG box 630, sleeve 093277_03	2021-05-20 19:05:49
~~~
be removed and the content be re-ingested. Removing the localids entry allows a new ark to be created by ingest.

The remaining storage content should eventually be removed but without the manifest.xml - this is difficult.

**Comment by elopatin-uc3** [comment]
Test manifest with the three images from this object failed to ingest into the demo collection:
```
Status message: [error]: HandlerDisaggregate: [error] HandlerDisaggregate: Could not retrieve url: https://preservationassets.lib.berkeley.edu/examiner2/bsimages/Box630/cubanc_e002916/cubanc_e002916_02.tif
```

**Comment by elopatin-uc3** [comment]
All three images can be downloaded from the existing object, but oddly, cubanc_e002916_01.tif only downloads as a file (vs. being part of object version 1).

**Comment by elopatin-uc3** [comment]
These are the local IDs that will be used, per the original manifest:
```
BANC PIC 2006.029--NEG box 630, sleeve 093277_03_examiner-093277_03_cubanc_e002916_01.tif
BANC PIC 2006.029--NEG box 630, sleeve 093277_03_examiner-093277_03_cubanc_e002916_02.tif
BANC PIC 2006.029--NEG box 630, sleeve 093277_03_examiner-093277_03_cubanc_e002916_03.tif
```

**Comment by elopatin-uc3** [comment]
All three images have been resubmitted, along with DC metadata:
```
cubanc_e002916_01.tif |  | 
BANC PIC 2006.029--NEG box 630, sleeve 093277_03_examiner-093277_03_cubanc_e002916_01.tif | Fay, Murry N. | Mike Fisher, round the world trip.  cubanc_e002916_01.tif | 1936-01-17T00:00:00
bid-4b006651-328a-4004-b333-caafe58dc164
```
```
cubanc_e002916_02.tif |  | 
BANC PIC 2006.029--NEG box 630, sleeve 093277_03_examiner-093277_03_cubanc_e002916_02.tif | Fay, Murry N. | Mike Fisher, round the world trip.  cubanc_e002916_02.tif | 1936-01-17T00:00:00
bid-f540e1bb-5450-4192-a8f8-90b2bbfb91ef
```
```
cubanc_e002916_03.tif |  | 
BANC PIC 2006.029--NEG box 630, sleeve 093277_03_examiner-093277_03_cubanc_e002916_03.tif | Fay, Murry N. | Mike Fisher, round the world trip.  cubanc_e002916_03.tif | 1936-01-17T00:00:00
bid-cf8fd427-78f0-4832-a0e6-e3c49c8d89f4
```

**Comment by elopatin-uc3** [comment]
Original problematic object deleted:
```
perl ./call/.../report-ucb_m54f7j9d-20210707-1444.txt
ark:/13030/m54f7j9d REPLIC=NONE STORE=OK INV=OK LOCAL=OK
```
