### ISSUE TITLE
Create graceful batch handling when audit PAUSE is sent during patching

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#718]
## Prevent the Audit service from indefinitely holding on to batches in queue when a shutdown occurs (ie sever patching)

Terry and David discussed this.

- [x] Document the process to send the PAUSE to all audit servers at the start of patching
  - Check with Ashley to see if she could run this before starting the patching process
  - We could also incorporate this into the storage admin tool or the system inventory 
  - https://www.pivotaltracker.com/story/show/178915295
- [ ] In the storage admin tool OR in the cron server code, add a script to release audit batches that are more than 24 or 48 hours old.

## Original ticket description
When a PAUSE is sent to the audit service, immediately stop processing and update the know status of any objects within a batch that have been processed by audit. 

For objects that have not yet been processed in the batch, release them so that they can be acquired again after the service is restarted.

```
I ran the consistency reports.  It looks like the patching resulted in dropped audit branches.  I do not think the graceful shutdown is yet in place.  @Ashley Gould and @dloy, did you happen to chat about this last week?


dloy  10:31 AM
@terrywbrady The prod catelina still uses stop. There may not be  a good way to consistently fix the audit issue  - pause only works if enough time is allowed from issuing the command to the time tomcat shuts down, allowing the pause to complete which could be hours - did not discuss with Ashley whether command was in

10:31
I'll reset the audits

terrywbrady  10:37 AM
Thanks @dloy.  What would you propose as a reasonable wait time?  I'll create a ticket to also propose implement a partial batch update during a graceful shutdown.
New

dloy  10:39 AM
I suspect 15 minutes would handle over 90%
```

**Comment by terrywbrady** [comment]
Terry and David discussed this.

- [ ] Document the process to send the PAUSE to all audit servers at the start of patching
  - Check with Ashley to see if she could run this before starting the patching process
  - We could also incorporate this into the storage admin tool or the system inventory 
- [ ] In the storage admin tool OR in the cron server code, add a script to release audit batchess that are more than 24 or 48 hours old.

**Comment by elopatin-uc3** [comment]
See also #658

**Comment by terrywbrady** [comment]
Changed owner from @dloy  to @terrywbrady .  The remaining task will be implemented in the storage admin (or a cron job)

**Comment by elopatin-uc3** [comment]
Puppet will send commands to pause during patching. Window of time (~15min) should be sufficient to enable Audit to process all lingering jobs. Will review during planning for Storage admin

**Comment by terrywbrady** [comment]
@elopatin-uc3 , this can be closed.  I do not think the timing is quite right yet, but we have an easy way to resolve these.

**Comment by elopatin-uc3** [comment]
Removed from Merritt project board.
