### ISSUE TITLE
Nuxeo direct deposit: UC Irvine SCA University Archives

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#731]
#### Summary
Establish new feed harvest for the following UCI collection in Nuxeo:
https://registry.cdlib.org/27565/latino-business-student-association-records-test-c/

This harvest should deposit content into the "UC Irvine SCA University Archives" collection in Merritt.
As this collection is currently empty, it's safe to start in Production, vs. establishing a new collection on Stage and harvesting into that.

Merritt collection: https://merritt.cdlib.org/m/uci_lib_sca_ua
ATOM feed: https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27565.atom

Associated Freshdesk ticket:
https://help.oac.cdlib.org/a/tickets/92165

**Comment by mreyescdl** [comment]
@elopatin-uc3 
ark:/13030/m5bk6qsm is associated with https://merritt.cdlib.org/m/uci_lib_sca_ua (collection set up for this feed)

However, the feed itself references ark:/13030/m5v71sk2 which is associated with the UCI Nuxeo collection https://merritt.cdlib.org/m/uci_lib_nuxeo

If we want to submit to the former collection, we'll need to update the feed which has:
     _<merritt_collection_id>ark:/13030/m5v71sk2</merritt_collection_id>_

Can you advise on which collection to submit to?  Thanks!

**Comment by elopatin-uc3** [comment]
@mreyescdl thanks for pointing this out! I have pinged Gabriela to ask her to update the registry entry with ark:/13030/m5bk6qsm for the UC Irvine SCA University Archives collection. Once I hear back I'll follow up here.

**Comment by elopatin-uc3** [comment]
Gabriela has confirmed that the ATOM feed for this is ready:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27565.atom

**Comment by mreyescdl** [comment]
Created Nuxeo script and ran manually which populated collection with 2 objects
    https://merritt.cdlib.org/m/uci_lib_sca_ua

Scheduled weekly cron, which will run at 0600 on Thursday 

Ticket completed

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl !
