### ISSUE TITLE
Replication - Scan delete

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#747]
### Task
Some content stored on an S3 bucket is not referenced by the inv database tables.

This content is being charged but is not usable.

The intent of this process is the removal of all non-accessed content from a bucket with review.

### Steps
Three steps are required for removal of files from bucket:
- Scan bucket and match on inv database
- Currational review of items to be deleted
- Removal of items from bucket

### Scan process
This process contains two basic steps:
- extract lists of all keys on a bucket
- determine whether the key is referenced from the inv DB

#### Extract list of all keys on a bucket
In java, this process is performed using list functions with an "after" mechanism for restarting extractions.:
- get last extracted key
- start key extraction with a maximum # of keys returned
- save last extracted key

#### determine whether the key is referenced from the inv DB
- if key does not begin with ark add to maints table
- extract all keys returned for an object - requires combination of inv_versions and inv_files table based on node
- if no entries returned for ark - add to maints table
- with returned keys from db match all keys for specific ark - if do not match add to maints

### Review
A variety of MySQL tools can be used. This will probably be facilitated by Storage Admin. The review process can include notes about a specific entry.

The result of the review process is a list of maints entries with either a 'delete' or 'hold' status.

### Removal of Items
The replication server will remove all entries with a 'delete' status

### Possible additional use of inv_maints
- Another proposed feature for this table is to maintain a place holder for general object deletion. In this case,  the maint_status will report objremoved and the key value is the ark only.
- The table is a place holder for content deletion on system

#### Rows
id - sequential identifier for inv_maints
inv_node_id - external reference to inv_nodes id
keymd5 - md5 generated from s3key and used as part of unique identifier
size - size of bucket object
create - creation date for bucket file
logged - date inv_maints row is created
removed - date bucket file is removed

maint_status - status for processing object in bucket
- review - entry for delete needs to be reviewed
- hold - reviewed item is on hold for deletion
- delete - delete this file
- removed - file is removed from bucket
- objremoved - object is removed
- error - error occurred when attempting a removal - note should contain details
- unknown - initial program status

maint_type - characteristic of file for removal
- non-ark - key does not begin with ark ("ark:")
- missing-ark - entry begins with ark but ark not matched in db
- missing-file - entry begins with existing ark in db but the file is not matched

s3key - for scan, this is the full key as it exists on the S3 system. for object delete this is the ark
note - manual or automatic note for this content

Note:
UNIQUE INDEX `keymd5_idx` (`inv_node_id`,`keymd5`) USING BTREE,
a unique key of node+key md5

**Comment by terrywbrady** [comment]
@dloy, this table looks really nice.  I have a couple comments/recommendations.

- What is our longest key in use currently?  
- Ideally, I would like to see s3key declared after inv_node_id and for that value to be part of the index.  
- How long is longtext? What is the longest text column that can be indexed by mysql?

One very unlikely use case that we could encounter: a key could be removed from the database and then re-added later.  We could run into an issue when re-processing if it ever ends up in this table again.

We often use "created" to indicated the date that a row in a table was created.  Consider the following name changes:

- created --> file_created (or key_created)
- logged --> created
- removed --> file_removed (or key_removed)

It could also be useful to have 'note' as a maint status.  I am thinking that we could choose to add a note to the file containing the \u that cannot be replicated to wasabi.

**Comment by dloy** [comment]
Unfortunately the problem is that we are running version 4 of MySQL (as far as I can tell) which has a VARCHAR limit of 255. It isn't clear whether this is characters or bytes. Regardless our maximum length pathname is 462 bytes.

I agree that using the key directly is cleaner. With expected  sizes of this table, I doubt the LONGTEXT declaration for s3key will be an issue for "LIKE" operations.

I like the changes you suggest and will get those in.

Thanks so much for looking at this.

**Comment by dloy** [comment]
Current inv_storage_maints definition:
~~~
CREATE TABLE `inv_storage_maints` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`inv_node_id` SMALLINT(5) UNSIGNED NOT NULL,
	`keymd5` CHAR(32) NOT NULL COLLATE 'utf8_general_ci',
	`size` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
	`file_created` TIMESTAMP NULL DEFAULT NULL,
	`created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`file_removed` TIMESTAMP NULL DEFAULT NULL,
	`maint_status` ENUM('review','hold','delete','removed','objremoved','admin','note','error','unknown') NOT NULL DEFAULT 'unknown' COLLATE 'utf8_general_ci',
	`maint_type` ENUM('non-ark','missing-ark','missing-file','admin','unknown') NOT NULL DEFAULT 'unknown' COLLATE 'utf8_general_ci',
	`maint_admin` ENUM('none','run','stop','eof') NOT NULL DEFAULT 'none' COLLATE 'utf8_general_ci',
	`s3key` TEXT(65535) NOT NULL COLLATE 'utf8mb4_unicode_ci',
	`note` MEDIUMTEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	PRIMARY KEY (`id`) USING BTREE,
	UNIQUE INDEX `keymd5_idx` (`inv_node_id`, `keymd5`) USING BTREE,
	INDEX `type_idx` (`maint_type`) USING BTREE,
	INDEX `status_idx` (`maint_status`) USING BTREE,
	CONSTRAINT `inv_scans_ibfk_1` FOREIGN KEY (`inv_node_id`) REFERENCES `inv`.`inv_nodes` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DYNAMIC
;
~~~

**Comment by dloy** [comment]
### Minio Issue
Currently we use the Minio S3 interface that sits on top of the Qumulo file system at SDSC.

Minio map keys into a file system. All operations are based on the underlying file architecture.

S3 provides a get next key option. An example AWS request (SDSC) looks like:
~~~
aws s3api list-objects-v2 --bucket <sdsc bucket> \
        --cli-read-timeout 0 \
        --max-items 20 \
        --start-after 'ark:/13030/c800002d' \
        --endpoint-url <sdsc endpoint>   \
        --profile minio
~~~

This command requests the next 20 keys following the key  'ark:/13030/c800002d'. The number of file nodes following 'ark:/13030/ is close to 5M. It appears the Minio logic attempts to grab all of the 5M to determine what is next.

The aws command above completed in 4 hours without returning any content.  A similar command sent to a true S3 system, Wasabi, returned in 3 seconds.

This Minio problem makes a continuous set of requests for "next" impossible. 


### Solution
An alternative proposed by Terry and SDSC provides a line delimited file containing all keys (aka. file paths) on the production SDSC Qumulo system for the bucket file node.  This file would be provided through Minio as a cloud entry.

I (David) will need to discuss with SDSC what Gavin could provide. Ideally the file paths could be converted to our current key architecture but the conversion on our side would fairly trivial.  

#### Ideal:
- upper level file entries would be restricted to a level that only contains the key information:
~~~
minio/data/.minio.sys/buckets/cdl.sdsc.prod/
~~~
- the single file containing a line delimited list of file path/keys would be available to us on bucket cdl.sdsc.dev with key 'bucketkeys|<sdsc bucket>|<yyyymmdd'
