### ISSUE TITLE
Scripts to find and fix group, write permissions for ETDs deployments

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#762]
#### Summary
In the past, the ownership and group permissions for git-managed files (in apps/uc3-etds) on each host have had non-role account permissions applied to them accidentally. This will prevent the 'etds' role account from being able to pull code changes and write to the local .git directory.

#### Tasks
- [ ] Create script to find/fix files without _group_ etds
- [ ] Create script to find/fix files without group write permission

**Comment by terrywbrady** [comment]
```
# find files without group etds
find -not -group etds
# find who owns them
find -not -group etds -exec ls -lag '{}' +
# for the files you own, change the group
find -not -group etds -exec chgrp etds '{}' +

# find files without group write permission
find -type f \! -perm /g+w
# find who owns them
find -type f \! -perm /g+w -exec ls -la '{}' +
# for the files you own, add group write
find -type f \! -perm /g+w -exec chmod g+w '{}' +
```

**Comment by terrywbrady** [comment]
Again closing with the hope of the new ETD service
