### ISSUE TITLE
Dryad reports errors during downloads of tabular data

### ISSUE THREAD

**Issue by marisastrong** [CDLUC3/mrt-doc#768]
**Describe the bug**
Dryad recently released the Frictionless functionality which performs validation of tabular data (.csv, .xls, etc)  Files are downloaded to the Dryad servers to perform validation.  These downloads do not utilize the pre-signed URL functionality.  There have been reports in the Dryad logs of error with downloads.  There have not been any reports from users that there is an issue.

	A Stash::Download::MerrittException occurred in background at 2021-08-20 20:02:12 UTC :
	
	 Timeout in downloads_controller#download_resource for 16116 for IP 207.181.221.48

**To Reproduce**
1. Upload a csv file to Dryad on the upload files page.  Frictionless validation will occur on the files.  

**Expected behavior**
1. File is displayed depicting noting any issues of incorrect data validation.

**Screenshots**
None

**Desktop (please complete the following information):**
N/A

**Additional context**

**Comment by terrywbrady** [comment]
@marisastrong , I have ticket #769 to capture the issue related to the `README_for_MeisnerLongtermCageData.txt` file.  I am removing that from this issue.

**Comment by terrywbrady** [comment]
Ryan shared the following ark with me as an example of the download error: `ark:/13030/m5zs7xhj`.

Note that the Merritt system intends to deprecate direct file downloads and version downloads in favor of the presigned object retrievals.   This is to ensure consistent response times regardless of the size of the file being request (or version assembly being requested).

If I investigate the requests for this ark, I see the following requests:
```
I, [2021-08-20T14:06:11.048437 #17669]  INFO -- : [20a62aa1-dbfd-47e8-af8c-348ceddda16d] Started GET "/d/ark%3A%2F13030%2Fm5zs7xhj" for 44.192.120.0 at 2021-08-20 14:06:11 -0700
I, [2021-08-20T14:06:11.049052 #17669]  INFO -- : [20a62aa1-dbfd-47e8-af8c-348ceddda16d]   Parameters: {"object"=>"ark:/13030/m5zs7xhj"}

I, [2021-08-20T14:06:11.753670 #17936]  INFO -- : [3aacc04d-9552-401f-81c9-5f1c0d79f805] Started GET "/d/ark%3A%2F13030%2Fm5zs7xhj" for 23.20.236.175 at 2021-08-20 14:06:11 -0700
I, [2021-08-20T14:06:11.754280 #17936]  INFO -- : [3aacc04d-9552-401f-81c9-5f1c0d79f805]   Parameters: {"object"=>"ark:/13030/m5zs7xhj"}
```

If I am reading the logs correctly, it appears that these requests had no credentials and were redirected to the guest login.

```
I, [2021-08-20T14:06:11.048437 #17669]  INFO -- : [20a62aa1-dbfd-47e8-af8c-348ceddda16d] Started GET "/d/ark%3A%2F13030%2Fm5zs7xhj" for 44.192.120.0 at 2021-08-20 14:06:11 -0700
I, [2021-08-20T14:06:11.049007 #17669]  INFO -- : [20a62aa1-dbfd-47e8-af8c-348ceddda16d] Processing by ObjectController#download as */*
I, [2021-08-20T14:06:11.049052 #17669]  INFO -- : [20a62aa1-dbfd-47e8-af8c-348ceddda16d]   Parameters: {"object"=>"ark:/13030/m5zs7xhj"}
I, [2021-08-20T14:06:11.049505 #17669]  INFO -- : [20a62aa1-dbfd-47e8-af8c-348ceddda16d] Redirected to https://merritt.cdlib.org/guest_login
I, [2021-08-20T14:06:11.049553 #17669]  INFO -- : [20a62aa1-dbfd-47e8-af8c-348ceddda16d] Filter chain halted as :require_user rendered or redirected
I, [2021-08-20T14:06:11.049629 #17669]  INFO -- : [20a62aa1-dbfd-47e8-af8c-348ceddda16d] Completed 302 Found in 1ms (ActiveRecord: 0.0ms)

I, [2021-08-20T14:06:11.753670 #17936]  INFO -- : [3aacc04d-9552-401f-81c9-5f1c0d79f805] Started GET "/d/ark%3A%2F13030%2Fm5zs7xhj" for 23.20.236.175 at 2021-08-20 14:06:11 -0700
I, [2021-08-20T14:06:11.754234 #17936]  INFO -- : [3aacc04d-9552-401f-81c9-5f1c0d79f805] Processing by ObjectController#download as */*
I, [2021-08-20T14:06:11.754280 #17936]  INFO -- : [3aacc04d-9552-401f-81c9-5f1c0d79f805]   Parameters: {"object"=>"ark:/13030/m5zs7xhj"}
I, [2021-08-20T14:06:11.754745 #17936]  INFO -- : [3aacc04d-9552-401f-81c9-5f1c0d79f805] Redirected to https://merritt.cdlib.org/guest_login
I, [2021-08-20T14:06:11.754795 #17936]  INFO -- : [3aacc04d-9552-401f-81c9-5f1c0d79f805] Filter chain halted as :require_user rendered or redirected
I, [2021-08-20T14:06:11.754870 #17936]  INFO -- : [3aacc04d-9552-401f-81c9-5f1c0d79f805] Completed 302 Found in 1ms (ActiveRecord: 0.0ms)
```

**Comment by elopatin-uc3** [comment]
It would be good to have the actual client request in hand to help investigate. There's also the question of whether the load balancer is playing into this because one of the two Dryad hosts has not been updated for 47 days, whereas the other has.

Eric to ping Ryan on whether he's still looking into this and re: priority.

Also discussed timing for deprecation of old download endpoint – it will make more sense to deprecate when transitioning to API.

**Comment by terrywbrady** [comment]
This related to the UI stability issues resolved after siege testing
