### ISSUE TITLE
Create new UCSF Archives Books and Printed Materials Collection

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#772]
Requested by Charlie Macquarie

#### Tasks: Production
- [x] Create collection intake form
- [x] Mint collection ARK
- [x] Create collection profiles
- [x] Submit collection admin object
- [x] Create associated entries in LDAP
- [x] Add collection to inventory database (introduced via admin object submission after collection profile is live)
- [x] Update collection record with name, mnemonic, privs
- [x] Set primary storage node (introduced via admin object submission after collection profile is live)
- [x] Add secondary storage nodes to inv_collections_inv_nodes table (Glacier and Wasabi)
- [x] In EZID, set collection Status (to unavailable) and Harvesting option (to No)

**Comment by elopatin-uc3** [comment]
@mreyescdl Could you submit the admin object for this new collection? thanks!

**Comment by mreyescdl** [comment]
Hi @elopatin-uc3 ,
Can you provide a link to the intake form?  Thanks

**Comment by elopatin-uc3** [comment]
Hi @mreyescdl, yes, sorry about that! 
https://docs.google.com/document/d/1yivha_8c0md9J4u_Q_iIY0L8fHX7fSQ63_mau1c74Ik/edit?usp=sharing

**Comment by mreyescdl** [comment]
Hi Eric,

Collection admin object has been submitted.

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl !
