### ISSUE TITLE
UCI Nuxeo feed: Beginnings of Activism for the Department of Asian American Studies

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#775]
Source ticket: https://help.oac.cdlib.org/a/tickets/93803

Collection Registry entry created: 27795

ATOM feed: https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27795.atom

Root folder in Nuxeo:
https://nuxeo.cdlib.org/nuxeo/nxpath/default/asset-library/UCI/SCA_UniversityArchives/AS-198/For%20Merritt@view_documents?tabIds=%3A&conversationId=0NXMAIN109

Merritt collection:
UC Irvine SCA University Archives
ark:/13030/m5bk6qsm

**Comment by mreyescdl** [comment]
- Created Nuxeo script
- Ran script manually
- Created Nuxeo entry to run at 0610 on Thursdays
