### ISSUE TITLE
UCI Nuxeo feed: Blackburn documentary: "The 2%: Navigating UCI as a Black Student"

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#776]
Source ticket: https://help.oac.cdlib.org/a/tickets/93808

Collection Registry entry created: 27755

ATOM feed: https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27755.atom

Root folder in Nuxeo:
https://nuxeo.cdlib.org/nuxeo/nxpath/default/asset-library/UCI/SCA_UniversityArchives/AS-221/DO%20NOT%20PUBLISH@view_documents?tabIds=%3A&conversationId=0NXMAIN109

Merritt collection:
UC Irvine SCA University Archives
ark:/13030/m5bk6qsm

**Comment by mreyescdl** [comment]
Created Nuxeo script
Ran script manually
Created Nuxeo entry to run at 0620 on Thursdays
