### ISSUE TITLE
Create Code Branches to build java jars and war files without the 3rd party section of the cdl maven repo

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#778]
## Aug 27 - Terry, David, Mark, and Marisa met

- The CDL maven repo was introduced to created a filtered view of dependent jar files
- A handful of jars were loaded to the 3rd party section
- As a first step, we will attempt to build without these dependencies

## Potential Benefits
- Simplify jar update process in response to dependabot alerts
- Ability to build public docker images for all Merritt microservices
- Ability to build merritt-docker in GitHub CodeSpaces
- Work with Ashley to introduce a tag-based deployment process for microservice war files
- Tidy/cleanup obsolete workflows on the build system
- Evaluate alternative build strategies (such as GitHub Actions) instead of Jenkins
- Trigger rebuild of all microservices when a library is updated

## Pull Requests

- https://github.com/CDLUC3/merritt-docker/pull/23
- https://github.com/CDLUC3/mrt-core2/pull/10
- https://github.com/CDLUC3/mrt-cloud/pull/17
- https://github.com/CDLUC3/cdl-zk-queue/pull/2
- https://github.com/CDLUC3/mrt-ingest/pull/28
- https://github.com/CDLUC3/mrt-inventory/pull/4
- https://github.com/CDLUC3/mrt-store/pull/18

**Comment by terrywbrady** [comment]
https://confluence.ucop.edu/display/~tbrady/Java+Build+Ideas

**Comment by terrywbrady** [comment]
## Notes from 8/30 dev meeting
- https://semver.org/
- [ ] Deprecate jargs
- [ ] If well automated, can every build generate a tag

**Comment by terrywbrady** [comment]
@elopatin-uc3 , this could be closed since the build refactor work is in progress

**Comment by elopatin-uc3** [comment]
Agreed; closing
