### ISSUE TITLE
Consider tracking request response times in puma and evaluating performance

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#780]
Evaluate the following

- https://www.justinweiss.com/articles/how-to-debug-ruby-performance-problems-in-production/

Consider automating on ui05?

**Comment by terrywbrady** [comment]
@elopatin-uc3 , this should be implemented with the logging work.  I recommend closing

**Comment by elopatin-uc3** [comment]
Agreed; closing.
