### ISSUE TITLE
UCI Nuxeo feed: School of Social Ecology Pandemic Histories Archive 

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#796]
Source ticket: https://help.oac.cdlib.org/support/tickets/94771

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/27808

ATOM feed: https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27808.atom

Root folder in Nuxeo:
https://nuxeo.cdlib.org/nuxeo/nxpath/default/asset-library/UCI/SCA_UniversityArchives/AS-222/For%20Merritt

Merritt collection:
UC Irvine SCA University Archives
ark:/13030/m5bk6qsm

**Comment by elopatin-uc3** [comment]
@mreyescdl The ATOM feed for this request should be available by 9/28

**Comment by elopatin-uc3** [comment]
This feed is now available: 
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27808.atom

**Comment by mreyescdl** [comment]
Hi @elopatin-uc3 Do we need a worksheet for this collection?
I'm not sure I need one, but will need a couple pieces of info to make sure I'm creating the admin object correctly.

**profile ID
ark ID**

Thanks

**Comment by elopatin-uc3** [comment]
Hi @mreyescdl this is a case where they are adding the contents of multiple Nuxeo root folder to an existing collection in Merritt. So nothing new to set up. The collection ark is ark:/13030/m5bk6qsm (https://merritt.cdlib.org/m/uci_lib_sca_ua)

**Comment by mreyescdl** [comment]
Complete

- Created Nuxeo script for weekly processing
- Manually run to test
- Added to Puppet

Will run weekly Thursday at 05:30

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl, I will notify the requestor.
