### ISSUE TITLE
UCI Nuxeo feed: Lao Stories: Laotian American Oral History Project

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#804]
Source ticket: https://help.oac.cdlib.org/support/tickets/95477

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/27810

ATOM feed: 
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27810.atom

Root folder in Nuxeo:
https://nuxeo.cdlib.org/nuxeo/nxpath/default/asset-library/UCI/SCA_SoutheastAsianArchives/MS-SEA070/FOR%20MERRITT

Merritt collection:
UC Irvine SCA Southeast Asian Archives collection
ark:/13030/m5m95n2q

**Comment by elopatin-uc3** [comment]
Note from Gabriela – This feed was not generated as expected on 9/28. We'll either need to ask for it to be manually generated, or wait until 10/5.

**Comment by elopatin-uc3** [comment]
Actually, scratch my above comment @mreyescdl . Gabriela found that the feed just took longer than expected to become available. It is here: https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27810.atom

**Comment by mreyescdl** [comment]
Complete

- Created weekly script and ran manually
- Scheduled for Thursdays at 04:45
