### ISSUE TITLE
Coll Admin – batchFolders report intermittently fails 

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#805]
The Batch Folders, last 7 days (https://merritt-colladmin.cdlib.org/web/collIndex.html?path=batchFolders&days=7) report has been failing intermittently. Error observed in the browser on failure:
`{"error":"execution expired for admin/bids/7"}`

**Comment by mreyescdl** [comment]
There are over 23K batches on the production EFS disk and Ingest may be taking too long to produce the report.
The old batch directories go back to May.  I'll prune the disk and hopefully it will fix the issue.
