### ISSUE TITLE
UI: Permissions to public collections

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#82]
We use LDAP to define which collections are public by assigning the user "anonymous" to a collection's read and download groups. However, if someone is logged into their own account, they don't have access to these collections unless their account is explicitly included in the read/download groups also. This has caused some confusion. I realize that this has the potential to create some very complicated logic, but is there a way to check if an object is part of a public collection and then display it no matter what account the user is logged into? Will this cause other problems? 
 - [ ]

**Comment by elopatin-uc3** [comment]
Figure out most robust way to do this—i.e., don't just hack something in in five different controller methods, centralize the access logic (David Moles - Jun 15, 2018)

**Comment by elopatin-uc3** [comment]
Done on [public-permissions](https://github.com/CDLUC3/mrt-dashboard/tree/public-permissions) branch, not deployed anywhere (David Moles - Sep 10, 2018)

**Comment by elopatin-uc3** [comment]
Taking my name off this pro tem till it gets prioritized. (David Moles - Sep 24, 2018)

**Comment by elopatin-uc3** [comment]
@elopatin-uc3 note to self.

**Comment by terrywbrady** [comment]
@elopatin-uc3 , is this still applicable?

**Comment by elopatin-uc3** [comment]
@terrywbrady yes, this is still applicable. But it's not a use case that I'm concerned with. Closing
