### ISSUE TITLE
Replication Enhancement Ideas

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#820]
The replication service uses inv_nodes_inv_objects.replicated to trigger replication.

When a primary node (inv_nodes_inv_objects.role = 'primary') has a null replicated column, an object is queued for replication.

Once the replication has started, the replicated column is set to '1970-01-01'. 

If a replication fails or a server is restarted, the replicated column remains '1970-01-01'.  This makes it difficult to distinguish an active replication from a failed/abandoned replication.  Also, this could help us to detect network performance issues that are causing replications to take longer to process than expected.

Consider the following enhancements to this table
- Create a new column to record the date/time that replication processing began -- we can use a date search to identify abandoned entries
- Record some details about the size of a replication (if available) -- this could help us predict how long a replication might take to complete
- Record a note field to identify the small number of items that cannot be replicated.  This would prevent a user from accidentally attempting to re-queue an item that will not succeed.

**Comment by dloy** [comment]
Fix required to remove 404 (missing content) secondary call to storage service.

This fix treats the 404 as any other exception. This appropriately sets the fail note in inv_nodes_inv_objects with the 404 problem.
