### ISSUE TITLE
UCI Nuxeo feed: Newport Beach Public Library Foundation Stories from the Sea Project Oral History collection

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#832]
Source ticket: https://help.oac.cdlib.org/a/tickets/96752

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/27820/

ATOM feed: 
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27820.atom

Root folder in Nuxeo:
https://nuxeo.cdlib.org/nuxeo/nxpath/default/asset-library/UCI/SCA_SpecialCollections/MS-R205/FOR MERRITT

Merritt collection:
UC Irvine SCA Special Collections
ark:/13030/m5gb7gff

**Comment by elopatin-uc3** [comment]
Feed available: https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27820.atom

**Comment by mreyescdl** [comment]
Created Nuxeo script and scheduled to run on Thursdays at 04:40

@elopatin-uc3 Is it okay to run this manually for testing?

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl. Yes, please go ahead and run it manually.

**Comment by mreyescdl** [comment]
Nuxeo feed tested:
   https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm5kd8vqk

Thanks Eric.

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl, looks good.
