### ISSUE TITLE
[RELEASE] Replic update in prod to support scan and on-need replication

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#842]
# Update Time
Scheduled: 11/9/2021 - 1PM

# Service(s)
Changes to replic service on prod to 
* support scan
* Optimize version handling in replic
* Bypass current content

# Github Issue Link(s)
scan - https://github.com/CDLUC3/mrt-doc/issues/827
minimize version updates - https://github.com/CDLUC3/mrt-doc/issues/825

# Servers affected
uc3-mrtreplic01x2-prd
uc3-mrtreplic02x2-prd

# Source Code:
Link(s) to tagged release(s)

### mrt_cloud
https://github.com/CDLUC3/mrt-cloud/commit/1e52fa246f548bdb84a06a729472960c4b7c3a85#diff-2b2f08b30584fc3fdc4548fe84f460d7bc522aa289b9e560bdc2db3decca27c8

https://github.com/CDLUC3/mrt-cloud/commit/a11ee2d0dd732def61c5174d7a98d990f81a9494#diff-2b2f08b30584fc3fdc4548fe84f460d7bc522aa289b9e560bdc2db3decca27c8

### mrt_inventory
https://github.com/CDLUC3/mrt-inventory/commit/ecf923ace0642764de297c9ff58524906d5af42e#diff-1b4892e6d76e0e338dc25b8dc5b094bc4a47fca1f4e4a3bdd2f9be0b19738e57

https://github.com/CDLUC3/mrt-inventory/commit/16029bbf873283dccb58605532fb1fe953f5554d#diff-1b4892e6d76e0e338dc25b8dc5b094bc4a47fca1f4e4a3bdd2f9be0b19738e57

### mrt_replic
https://github.com/CDLUC3/mrt-replic/commit/defcd18d5580488bec00e19b0b314259317c8567#diff-cd9aa8c253b1a4c9a66929f51a8830cf68c2451ed540066d0b76e57182cf772d

https://github.com/CDLUC3/mrt-replic/commit/8efb456ecf7fedf42d14d65eb0a890b06a3fc338#diff-cd9aa8c253b1a4c9a66929f51a8830cf68c2451ed540066d0b76e57182cf772d

https://github.com/CDLUC3/mrt-replic/commit/fc0916023511b53bbb0971610bbca08369266d5c

https://github.com/CDLUC3/mrt-replic/commit/c6c4d844696eec65ef7241f9ee6a00fe2e6f25a4

### mrt_cloud
https://github.com/CDLUC3/mrt-cloud/commit/9ff729def80022491d95e0047227768f6ab8276a#diff-2b2f08b30584fc3fdc4548fe84f460d7bc522aa289b9e560bdc2db3decca27c8
https://github.com/CDLUC3/mrt-cloud/commit/0ac8054d899d6e5b7ebb3d46964d406421a1af12#diff-2b2f08b30584fc3fdc4548fe84f460d7bc522aa289b9e560bdc2db3decca27c8

### mrt_replic
https://github.com/CDLUC3/mrt-replic/commit/b280b58123da65ef9afbdf7c500ff883c806d0eb#diff-cd9aa8c253b1a4c9a66929f51a8830cf68c2451ed540066d0b76e57182cf772d

# Jenkins/Build Info: (if applicable)
## s3
http://builds.cdlib.org/job/mrt-s3-pub/116/console
http://builds.cdlib.org/job/mrt-s3-pub/117/console

## inventory
http://builds.cdlib.org/job/mrt-build-inv/56/

## replic
http://builds.cdlib.org/job/mrt-build-replic/73/console

# ssm
aws ssm put-parameter  --type String --overwrite --region us-west-2 --name /uc3/mrt/prd/replic/scan/maxkeys  --value "500"

aws ssm put-parameter  --type String --overwrite --region us-west-2 --name /uc3/mrt/prd/replic/scan/threadSleep  --value "500"

# inv db
* Add inv_storage_maints - contains individual key with key information for orphaned content
* Add inv_storage_scans - contains runtime information on replic scans

# Deployment Steps (if applicable)
## ssm
- [x] set prod ssm values
- [x] add inv_storage_maints table to prod inv
- [x] add inv_storage_scans table to prod inv
- [ ] shutdown uc3-mrtreplic01x2-prd
- [ ] shutdown uc3-mrtreplic02x2-prd
- [ ] deploy uc3-mrtreplic01x2-prd
- [ ] deploy uc3-mrtreplic02x2-prd

**Comment by dloy** [comment]
## Release of scan batch delete
Prior to this release only individual scanned entries could be deleted. This release provides a batch process for deleting multiple entries using a single call. 

Currently installed on stage.

### Date
12/1/2021 - 1:00pm

### Source:
https://github.com/CDLUC3/mrt-replic/commit/58bf569cc3fa6d18a5127ac73fa818a5d959d789

### Builds:
http://builds.cdlib.org/job/mrt-build-replic/78/console

### Deploy:
uc3-mrtreplic01x2-prd
uc3-mrtreplic02x2-prd

### Manual steps
- [ ] - Drop and reinstall of scan tables
- [ ] - deploy on each prod server

**Comment by elopatin-uc3** [comment]
@dloy I opened a separate ticket for this latest release:
https://github.com/CDLUC3/mrt-doc/issues/871
