### ISSUE TITLE
[INVENTORY] Worker uc3-mrtinv02x2-prd went unresponsive

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#853]
At 12:05 on 11/12 Inventory worker uc3-mrtinv02x2-prd went offline.

Prior to going unresponsive, logs show that the worker lost connection to ZK nodes
```org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss```

Next, when trying to reconnect to ZK nodes a host name resolution error occurred
```ZooManager:  Exception:java.net.UnknownHostException: uc3-mrtzk01x2-prd.cdlib.org: Name or service not known```

Martin tried to stop the instance, which took longer than usual.
Upon restarting the instance the service still showed name resolution errors.  
After restarting the service, the worker looked and acted as expected.

No action needed at this time, but this ticket documents the unusual behavior

**Comment by terrywbrady** [comment]
@mreyescdl , closing.  We can still search for this one if it happens again.
