### ISSUE TITLE
[Access]  Failed object assemblies

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#855]
**Failed assembly**

_/accessLarge.1 | e1cb9a13-3b31-4b62-a4a7-ee67add6f643 | 20,104,881,522 | 7001 | 201 | 2021-11-12 02:09:53 | Failed | mrtQ-000000003009_

**Cause**

_***Cloudhost Exception: org.cdlib.mrt.s3.aws.AWSS3Cloud-awsGet:734 GENERAL_EXCEPTION[Unexpected Programmic exception] com.amazonaws.SdkClientException: Unable to store object contents to disk: Connection reset
(1):org.cdlib.mrt.s3.aws.AWSS3Cloud.awsGet(AWSS3Cloud.java:734)
(2):org.cdlib.mrt.s3.aws.AWSS3Cloud.getObject(AWSS3Cloud.java:1129)
(3):org.cdlib.mrt.store.action.CloudArchive.addFile(CloudArchive.java:430)
(4):org.cdlib.mrt.store.action.CloudArchive.addListProducer(CloudArchive.java:397)
(5):org.cdlib.mrt.store.action.CloudArchive.buildProducer(CloudArchive.java:208)
(6):org.cdlib.mrt.store.action.AsyncCloudArchive.run(AsyncCloudArchive.java:281)
(7):org.cdlib.mrt.store.action.TokenRun.buildTokenSynch(TokenRun.java:305)
(8):org.cdlib.mrt.store.action.TokenRun.buildTokenContainer(TokenRun.java:279)
(9):org.cdlib.mrt.store.action.TokenRun.run(TokenRun.java:214)
(10):org.cdlib.mrt.store.consumer.ConsumeData.run(Consumer.java:584)_

**Comment by terrywbrady** [comment]
@dloy and @mreyescdl , closing for now.  We can reopen if this repeats
