### ISSUE TITLE
UI: Figure out what browser/OS combinations we actually get

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#86]
We don't currently run Google Analytics on Merritt, but we could. Or we could probably figure out how to get the information out of Apache logs if we worked at it.
 - [ ]

**Comment by elopatin-uc3** [comment]
Are there any philosophical  reasons for not having GA on the Merritt frontend? Do we have a consolidated account for viewing analytics? 

Adding GA tracking should be straightforward. We should consider doing this.
@elopatin-uc3

**Comment by terrywbrady** [comment]
@elopatin-uc3 , still applicable?  We can probably get a lot from the puma logs.

**Comment by elopatin-uc3** [comment]
Given the limited number of user accounts and what I would expect to be highly routine usage patterns and (perhaps) browsers in use, I don't consider this to be a priority. Closing
