### ISSUE TITLE
Investigate Scan handling of mrt-delete.txt files

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#860]
443,914 of the 573,973 items flagged for review in inv_storage_maints relate to the mrt-delete.txt file.

- Determine if this indicates a inv service problem
- Otherwise determine if this indicates a scan logic issue
- Or, determine if these require individual investigation

Update scan logic accordingly and re-classify these items.

```
MySQL [inv]> select count(*) from inv_storage_maints where maint_status='review' and s3key like '%system/mrt-delete.txt';
+----------+
| count(*) |
+----------+
|   443914 |
+----------+
1 row in set (0.96 sec)

MySQL [inv]> select count(*) from inv_storage_maints where maint_status='review';
+----------+
| count(*) |
+----------+
|   573973 |
+----------+

```

**Comment by dloy** [comment]
This problem is a bug in the scan processing.  It fails to include zero length files for proper testing, so they are considered orphaned.

One line fix. 

Suggest deleting the maint and scan tables entries and rerunning with the fixed code.
