### ISSUE TITLE
Consider new replic endpoint for bulk delete

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#861]
```
curl -X DELETE "http://localhost:38001/mrtreplic/scandelete-list/NODENUM"
```
This indicates that replication should perform a delete on all items marked for delete for node NODENUM.

**Comment by terrywbrady** [comment]
@dloy , let me know if you would like to discuss the details of this.

**Comment by terrywbrady** [comment]
@dloy  and @elopatin-uc3 , I updated this based on our discussion today.  David, let me know if you prefer a different endpoint path.

**Comment by dloy** [comment]
## scandelete-list
This new scan function, for each inv_storage_maints entries matching maint_status='delete' and node:
* delete s3 content based on inv_storage_maints entries marked 
* reset the maint_status='removed' and add file_removed date
### format
~~~
curl -X DELETE 'http://localhost:38001/mrtreplic/scandelete-list/5001?t=xml'
~~~
Example:
* localhost:38001/mrtreplic/ - service prefix
* scandelete-list - replic method
* 5001 - node to be used for delete
