### ISSUE TITLE
Billing script - occasional deadlock error

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#868]
Need to figure out which one of the queries is triggering this issue.  Add debug information into the script to determine which step has an error.

> ERROR 1213 (40001) at line 7: Deadlock found when trying to get lock; try restarting transaction

**Comment by terrywbrady** [comment]
Added debug and determined that the error came from the creation of the node_counts table.  I replaced the table with a view.

- https://github.com/CDLUC3/mrt-admin-lambda/commit/a8ef896c4cb1e226797b8939444ea5ca49b0801f#diff-11d285e344f8012cf52422e3c876bc8326f4dc31281caa4bf146dceb2463f4ee
- https://github.com/CDLUC3/mrt-cron/commit/4eb7f719113c208f84c4c305cbf3866a4e1ba434
-

**Comment by terrywbrady** [comment]
@elopatin-uc3 , this can be closed

**Comment by elopatin-uc3** [comment]
Closing
