### ISSUE TITLE
Refactor/simplify admin tools with bootstap tables

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#872]
The bootstrap table filters and displays that Ashley added to the system inventory could provide a significant simplification of the admin tool logic for presenting tables.  These tools should also provide a more feature rich interface (such as filtering).

**Comment by terrywbrady** [comment]
https://github.com/CDLUC3/mrt-admin-lambda/pull/43

**Comment by terrywbrady** [comment]
@elopatin-uc3 , moved to the icebox.  We might need to be selective about when to use the bootstrap tables.  They are likely to break some of the javascript html insertion that the admin tools currently perform.

**Comment by terrywbrady** [comment]
@elopatin-uc3 , I recommend closing since we are engaged with the UX team

**Comment by elopatin-uc3** [comment]
Thanks @terrywbrady, yes, agreed. Closing
