### ISSUE TITLE
Prevent concurrent update for an object via a locking mechanism

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#875]
See #874 , #873 

Consider mysql, dynamo db or zookeeper to implement ark level object locking

**Comment by mreyescdl** [comment]
Initial design thoughts:

- Create a shared Zookeeper lock area within our existing ZK nodes
- Add Ingest functionality to create a lock using an Objects *primary* identifier
- Prior to submitting to the Storage micro service, Ingest will check for an existing lock and create one if none exist
- Upon completion of Storage call, Ingest will release the lock
- If a lock does exist for an object, Ingest will suspend processing and go into a polling loop - exiting only when lock is cleared.

Tools would exist in Admin UI to examine locks and create/clear manually. 

More info on Zookeeper locks: https://www.linkedin.com/pulse/how-implement-zookeeper-locking-mechanism-minal-bagade

**Comment by elopatin-uc3** [comment]
https://github.com/CDLUC3/cdl-zk-queue/pull/5

**Comment by mreyescdl** [comment]
Deployed to stage.  
Ran 10 concurrent submissions to same object and the Storage lock worked - Storage manifest is correct.
However, Inventory had trouble processing the concurrent requests.  
See object: https://merritt-stage.cdlib.org/m/ark%253A%252F99999%252Ffk4wd5bw90

We can discuss how Inventory and Local ID service are not protected with this method.  However, the most important service (Storage) is protected and this should be pushed out to prod. 
Will create release ticket.
