### ISSUE TITLE
[RELEASE] Ingest - Support Ingest requeue of FAILED submissions

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#886]
# Overview
Ingest failures are not bubbling up to the ZK Ingest queue, so we can not requeue them.  They show up as "COMPLETED"
This change will flag failures and allow for reprocessing within the Admin UI

# Service(s)
Ingest

# Github Issue Link(s)
https://github.com/CDLUC3/mrt-doc/issues/854

# Servers affected
uc3-ingest01x2-prd.cdlib.org
uc3-ingest02x2-prd.cdlib.org
uc3-ingest03x2-prd.cdlib.org

# Source Code:
Link(s) to tagged release(s)
https://github.com/CDLUC3/mrt-ingest/pull/37

# Jenkins/Build Info: (if applicable)
http://builds.cdlib.org/job/mrt-ingest-stage/203/

# Deployment Steps (if applicable)
- [x] Remove worker from Apache LB
- [x] Redeploy worker
- [x] Repeat on all hosts

# Infrastructure Changes to support deployment (ALB, EFS, etc)
N/A

# Schedule
I would suggest that this work piggybacks off of the Ingest restart needed by the Inventory ALB consistency work
I believe this is scheduled for Tuesday at 4PM, but can not find the ticket. 
@ashleygould can you paste that ticket here??

# Note
Will need to change SSM variable to support new endpoint 
**/uc3/mrt/prd/ingest/config/localID      http://inventory.cdlib.org:36221/mrtinv**

**Comment by mreyescdl** [comment]
**Update**:  Will wait on updating SSM parameters for Inventory ALB until Ashley is available

**Comment by mreyescdl** [comment]
Deployment complete for all 3 ingest workers.

Also, now using port 36121 for local ID endpoint

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl !
