### ISSUE TITLE
[Maven Repository] Support SSL

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#889]
Enable SSL communication for our Maven repo.  
Future versions of Maven (3.8) will not support non-SSL communication with third-party repos.

This was seen while testing with a docker image using Maven 3.8

**Comment by mreyescdl** [comment]
Request for certificate has been made to IAS

**Comment by elopatin-uc3** [comment]
Will create a separate ticket for similar work for Jenkins
