### ISSUE TITLE
Update Replication spec link to point to permanent home in Merritt

### ISSUE THREAD

**Issue by dmolesUC** [CDLUC3/mrt-doc#9]
The Replication spec link on the Technical Documentation page is currently pointing to Google Drive; once the PDF's been deposited into Merritt, we should link to the Merritt copy as with the other specs.

**Comment by cpwillett** [comment]
Updated to:
https://github.com/CDLUC3/mrt-doc/blob/master/doc/Merritt-replication-service-latest.pdf

**Comment by dmolesUC3** [comment]
@cpwillett The other spec links on that page all go to files in Merritt—shouldn’t we be consistent?

**Comment by terrywbrady** [comment]
@elopatin-uc3 , I recommend closing
