### ISSUE TITLE
UCI Nuxeo feed: University of California, Irvine, School of Biological Sciences photographs

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#904]
Source ticket: https://help.oac.cdlib.org/a/tickets/98416

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/27834/

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27834.atom

Root folder in Nuxeo:
https://nuxeo.cdlib.org/nuxeo/nxpath/default/asset-library/UCI/SCA_UniversityArchives/AS-225/For%20Merritt

Merritt collection:
UC Irvine SCA University Archives
ark:/13030/m5bk6qsm

**Comment by mreyescdl** [comment]
Nuxeo script created and checked into mot-dashboard-config private repo
Scheduled with Puppet for 04:30 on Thursdays, but not yet enabled.

To do:

- [ ]  Run manually, once feed is ready
- [ ]  Enable weekly scheduling

**Comment by mreyescdl** [comment]
Feed available.

- Submitted manually to Merritt (https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm56n04pd)
- Enabled weekly processing
