### ISSUE TITLE
UCI Nuxeo feed: Edward O. Thorp papers

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#905]
Source ticket: https://help.oac.cdlib.org/a/tickets/98358

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/27833/

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27833.atom

Root folder in Nuxeo:
https://nuxeo.cdlib.org/nuxeo/nxpath/default/asset-library/UCI/SCA_SpecialCollections/MS-F047/For%20Merritt

Merritt collection:
UC Irvine SCA Special Collections
ark:/13030/m5gb7gff

**Comment by mreyescdl** [comment]
Nuxeo script created and checked into mot-dashboard-config private repo
Scheduled with Puppet for 04:35 on Thursdays, but not yet enabled.

To do: 
- [ ] Run manually, once feed is ready
- [ ] Enable weekly scheduling

**Comment by elopatin-uc3** [comment]
Thanks for the updates on both Nuxeo tickets @mreyescdl. Figured you saw it, but just in case, Barbara mentioned in the merritt-nuxeo channel that she had to make a correction in the registry for this ticket's feed.

**Comment by mreyescdl** [comment]
Feed available 

- Submitted manually to Merritt 
   https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm53v6f2g
   https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm5qk4f4f
- Enabled weekly processing
