### ISSUE TITLE
[Inventory] Concurrency lock needed

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#907]
While testing Ingest to Storage concurrency lock  ticket: https://github.com/CDLUC3/mrt-doc/issues/875 , Inventory showed it also needs a lock.

Processing 10 concurrent object updates Inventory has a problem with the inv_versions table update.
Here is a sample problem object:
     https://merritt-stage.cdlib.org/m/ark%253A%252F99999%252Ffk4wd5bw90

There are 14 versions of this object in the Storage manifest, yet the inv_versions table has 42 entries...

    `select count(*) from inv_versions where ark='ark:/99999/fk4wd5bw90';
           42 `

**Comment by elopatin-uc3** [comment]
Noting PR: https://github.com/CDLUC3/mrt-inventory/pull/9

**Comment by mreyescdl** [comment]
Deployed to Stage for testing

Submitted 10 concurrent updates to the same object at 10 second interval and saw an error in Storage despite the lock.
Must confirm that either:

- Storage lock is working correctly
- Write to Storage is completely synchronous (no async validation)

```
***Cloudhost Exception: org.cdlib.mrt.utility.FileUtil-stream2File:171 GENERAL_EXCEPTION[Unexpected Programmic exception] FileUtil: Name:clouttemp1779785449905380944.txt - Exception:com.amazonaws.SdkClientException: Unable to verify integrity of data download.  Client calculated content hash didn't match hash calculated by Amazon S3.  The data may be corrupt.
(1):org.cdlib.mrt.utility.FileUtil.stream2File(FileUtil.java:171)
(2):org.cdlib.mrt.s3.aws.AWSS3Cloud.awsGet(AWSS3Cloud.java:708)
(3):org.cdlib.mrt.s3.aws.AWSS3Cloud.getObject(AWSS3Cloud.java:1087)
(4):org.cdlib.mrt.s3.aws.AWSS3Cloud.getManifest(AWSS3Cloud.java:1331)
(5):org.cdlib.mrt.s3.aws.AWSS3Cloud.getManifest(AWSS3Cloud.java:1305)
(6):org.cdlib.mrt.cloud.action.CloudActionAbs.getVersionMap(CloudActionAbs.java:128)
(7):org.cdlib.mrt.cloud.action.StateObject.<init>(StateObject.java:80)
(8):org.cdlib.mrt.cloud.action.StateObject.getStateObject(StateObject.java:69)
(9):org.cdlib.mrt.store.cloud.CANCloudService.getObjectState(CANCloudService.java:307)
(10):org.cdlib.mrt.store.can.CANCloud.getObjectState(CANCloud.java:383)
(11):org.cdlib.mrt.store.storage.StorageService.getObjectState(StorageService.java:278)
(12):org.cdlib.mrt.store.app.jersey.JerseyBase.getCloudManifestStream(JerseyBase.java:2292)
(13):org.cdlib.mrt.store.app.jersey.store.JerseyStorage.getCloudManifest(JerseyStorage.java:894)
```

**Comment by mreyescdl** [comment]
Running into some issues with Threading on Stage.

I believe the processing of the manifest is being done Asynchronously and thus bypassing locks.
That or there are multiple entry points that need to be locked.
Will do more testing with Stage, but no production deployment for Inventory until testing complete.

**Comment by dloy** [comment]
One update we should consider with the concurrency locking is to modify the inv_versions table to include a UNIQUE index to prevent multiple version entries for number  and inv_object_id:
UNIQUE INDEX `inv_version_id` (`number`, `inv_object_id`) USING BTREE

This change will fail adding a new version if concurrent updates are attempted.
