### ISSUE TITLE
[Ingest] Admin API for Zookeeper locks

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#908]
We need visibility into Zookeeper locks.  
For all lock nodes we need the ability to view and delete lock entries.

For lock node "/mrt.lock", viewing will show:  ARK and Job ID

**Comment by mreyescdl** [comment]
Lock API now exists on Stage

To show locks nodes (only one for now)
    ``` curl http://merritt-aws-stg.cdlib.org:33121/ingest/admin/locks?t=xml```

To show lock entries for a node 
    ```curl http://merritt-aws-stg.cdlib.org:33121/ingest/admin/lock/mrt.lock?t=xml```

**Comment by elopatin-uc3** [comment]
Thanks for the update @mreyescdl!
