### ISSUE TITLE
[Ingest] Local ID lock 

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#909]
During Storage concurrency test we found that the Local ID registration can raise an exception.
Overlapping registration of Local ID for the same object causes the exception.

Creating a lock prior to registration is the simple solution, but unfortunately at the time of calling we are not yet guaranteed to have a unique primary ID (ark) to use as a lock ID.
Consider using a combination of "Owner and Local ID" as a new lock ID.

**Comment by elopatin-uc3** [comment]
Related to the following tickets:
#873, #875, #907, #908

**Comment by elopatin-uc3** [comment]
Closing as duplicate of #2029
