### ISSUE TITLE
UCI Nuxeo feed: Critical Theory Institute records

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#917]
Source ticket: https://help.oac.cdlib.org/a/tickets/100445

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/5318/

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_5318.atom

Root folder in Nuxeo:
https://nuxeo.cdlib.org/nuxeo/nxpath/default/asset-library/UCI/SCA_CriticalTheoryArchives/MS-C010/For%20Merritt

Merritt collection:
UCI Critical Theory Archives collection
ark:/13030/m5159rbd

**Comment by mreyescdl** [comment]
- [ ] Creat shell script and check into repo mrt-dashboard-config
- [ ] Add Puppet cron entry, but do not enable
- [ ] When ATOM feed available, run harvest manually
- [ ] Enable Cron entry

**Comment by elopatin-uc3** [comment]
@mreyescdl this feed is now available

**Comment by mreyescdl** [comment]
Thanks Eric.

- Manually ran harvest script which submitted 2 objects.
- Enabled weekly harvesting (Thursday at 04:25)
