### ISSUE TITLE
[RELEASE] Ingest - Lock APIs - 2/14/22

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#924]
# Overview
Newly created Zookeeper Locks need visibility, much as Queues have.  This deployment will allow access to Lock information that can be exposed by the Admin UI

# Service(s)
Ingest

# Github Issue Link(s)
https://github.com/CDLUC3/mrt-doc/issues/908

# Servers affected
uc3-ingest01x2-prd.cdlib.org
uc3-ingest02x2-prd.cdlib.org
uc3-ingest03x2-prd.cdlib.org

# Source Code:
https://github.com/CDLUC3/mrt-core2/pull/11
https://github.com/CDLUC3/cdl-zk-queue/pull/6
https://github.com/CDLUC3/mrt-ingest/pull/41

# Jenkins/Build Info: (if applicable)
http://builds.cdlib.org/job/cdl-zk-queue/lastBuild/
http://builds.cdlib.org/job/mrt-ingest-stage/lastBuild/

# Deployment Steps (if applicable)
- [x] Create SSM variable /uc3/mrt/prd/ingest/zoo/lockName
- [x] Deploy Ingest03
- [x] Deploy Ingest02
- [x] Deploy Ingest 01

# Infrastructure Changes to support deployment (ALB, EFS, etc)
Use Apache web server to deploy to production in H/A (uc3-mrtweb01x2-prd.cdlib.org)

# Note
This deployment will also deploy lock mechanics to prod (see ticket https://github.com/CDLUC3/mrt-doc/issues/906)

**Comment by mreyescdl** [comment]
Production deployment complete

**Comment by mreyescdl** [comment]
Note:  Terry noticed an error while querying locks.
This root cause is a Zookeeper connection loss issue within the CDL ZK lib.
I'll need to add some retry logic, like we have with the queue querying.

One more pull request and deployment is necessary.

**Comment by mreyescdl** [comment]
Fix has been deployed to stage.
Deploy to production on Monday

**Comment by mreyescdl** [comment]
Rolled back due to:
- ZK client not explicitly closing session which led to ZK exhausting connection threshold.

Fixed client code and increased ZK connection threshold from 60 to 300

**Comment by mreyescdl** [comment]
Redeployed to production and will monitor ZK connections

**Comment by elopatin-uc3** [comment]
Thanks for the updates @mreyescdl

**Comment by mreyescdl** [comment]
Found a potential issue while using the Admin tool to remove queue entries.  Monitoring ZK connections, they shot up from 8 to 23 on ZK01 after making API calls to delete ingest queue entries.
Two API calls are not closing the zookeeper object, thus leaving open sessions/connections - deleteq|requeue

This is a simple fix.  
https://github.com/CDLUC3/mrt-ingest/pull/42

**Comment by mreyescdl** [comment]
Redeployed fix in stage and prod and will continue to monitor Zookeeper connections.
