### ISSUE TITLE
[RELEASE] Inventory - Lock support - 2022-02-28

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#935]
# Overview of Release
Need to add a lock to Inventory.  Concurrent processing will result in DB mismatches

# Service(s)
Inventory

# Github Issue Link(s)
https://github.com/CDLUC3/mrt-doc/issues/907

# Servers affected
inv01-aws-prd
inv02-aws-prd

# Source Code:
Link(s) to tagged release(s)
https://github.com/CDLUC3/mrt-inventory/pull/9

# Jenkins/Build Info: (if applicable)
http://builds.cdlib.org/job/mrt-build-inv/59/

# Deployment Steps (if applicable)
- [x] Remove Inventory worker from ALB
- [x] Deploy 
- [x] Repeat for second worker

# Infrastructure Changes to support deployment (ALB, EFS, etc)
Add SSM variable **_/uc3/mrt/prd/inventory/zoo/lockName_** to define lock node

# Rollback Instructions
On host machine, as role account "dpr2"
- cd /dpr2/tools/deploy/mrt-tomcat
- cap mrt-inv01x2-prd|mrt-inv02x2-prd deploy:stop
- cap mrt-inv01x2-prd|mrt-inv02x2-prd deploy:rollback
- cap mrt-inv01x2-prd|mrt-inv02x2-prd deploy:start

**Comment by elopatin-uc3** [comment]
Thanks for the rollback instructions @mreyescdl!

**Comment by mreyescdl** [comment]
Updated SSM production variable that will allow Ingest and Inv to share lock

**Comment by mreyescdl** [comment]
Production release complete
