### ISSUE TITLE
Admin tool: DOI list query report page fails with a syntax error.

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#936]
The DOI list look-up is failing with a syntax error:
```
Uncaught SyntaxError: Unexpected token '<' (at doi.html:1385:5)
```

https://merritt-admintool.cdlib.org/web/doi.html

**Comment by terrywbrady** [comment]
@elopatin-uc3 , I think this can be closed

**Comment by elopatin-uc3** [comment]
The local ID list query page is working fine. However there's a console error that appears on the DOI list query page when attempting to parse a list of DOIs.

```
Uncaught SyntaxError: Unexpected token '<' (at doi.html:1385:5)
```
I'll modify the ticket and leave it open. Not a high priority.
