### ISSUE TITLE
Document a minimal path away from Sword/OAI that could be a transition before a new api is created

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#939]
This idea came out the the team discussion on 2/14 since it is difficult to requeue sword failures from the admin tool.

If we were to document a potential evolution path for Dryad to follow to become a normal Merritt depositor, I presume the process would look like this.
- POST a checkm submission to Merritt via the UI (rather than sword)
  - Is there a good documentation page that could be referenced for this purpose?
  - From Scott: BTW, we only send manifests through sword these days.  Some may be external urls a user adds but most are presigned URLs at Amazon S3.  When people upload to us, they upload to S3 for staging files until they're in Merritt for more luxurious storage.
- We would configure callback confirmation to alert Dryad that the submission is complete
  - Do we have a documentation page for the callback service?
  - https://confluence.ucop.edu/display/UC3/Merritt+Callback
- We would add a new endpoint in the UI to perform a localid lookup and to return submission details as json.  This would be intended to replace OAI.
  - UCB might like this as well
  - To help visualize what could be returned, perform a localid lookup in the UI:
  - https://merritt.cdlib.org/collection/search_results?utf8=%E2%9C%93&terms=doi%3A10.5061%2Fdryad.8sf7m0cn7&group=cdl_dryad&commit=Go

### Stage mock up
- Show object info as json: https://merritt-stage.cdlib.org/api/object_info/ark%253A%252F99999%252Ffk4qj8wb0t
- Show object info using collection mnemonic and localid:
  - https://merritt-stage.cdlib.org/api/merritt_demo/local_id_search?terms=2022_03_07_1548_combo
  - https://merritt-stage.cdlib.org/api/cdl_dryadstg/local_id_search?terms=doi%3A10.7959%2Fdryad.44j0zpc8q
  
## Thoughts about callback
- Ingest could poll the inventory queue. The callback call could be deferred until the inventory item is completed.
  
 ## Other ideas from Mark
- Another consideration is to have Dryad mint their own ARKs before sending to Merritt.  That would eliminate 

## Other discussion items
- Should non-published (or non-reviewed?) assets be deposited into Merritt?
- Could/should the published version numbers in Dryad match the Merritt version numbers?

**Comment by mreyescdl** [comment]
**Sword REST request**
     Add     POST /mrtsword/collection/cdl_dryad
     Update  PUT /mrtsword/edit/cdl_dryad/doi%3A10.5061%2Fdryad.vq83bk3vd

**Merritt UI REST request**
     Add     POST https://merritt.cdlib.org/object/ingest
     Update  POST https://merritt.cdlib.org/object/update

**Merritt UI accepted submission Form parameters**
```
      'creator' => params[:creator],
      'date' => params[:date],
      'digestType' => params[:digestType],
      'digestValue' => params[:digestValue],
      'file' => params[:file].tempfile,
      'filename' => filename,
      'localIdentifier' => params[:localIdentifier],
      'notification' => params[:notification],
      'notificationFormat' => params[:notificationFormat],
      'primaryIdentifier' => params[:primaryIdentifier],
      'profile' => params[:profile],
      'note' => params[:note],
      'responseForm' => params[:responseForm],
      'DataCite.resourceType' => params['DataCite.resourceType'],
      'DC.contributor' => params['DC.contributor'],
      'DC.coverage' => params['DC.coverage'],
      'DC.creator' => params['DC.creator'],
      'DC.date' => params['DC.date'],
      'DC.description' => params['DC.description'],
      'DC.format' => params['DC.format'],
      'DC.identifier' => params['DC.identifier'],
      'DC.language' => params['DC.language'],
      'DC.publisher' => params['DC.publisher'],
      'DC.relation' => params['DC.relation'],
      'DC.rights' => params['DC.rights'],
      'DC.source' => params['DC.source'],
      'DC.subject' => params['DC.subject'],
      'DC.title' => params['DC.title'],
      'DC.type' => params['DC.type'],
      'submitter' => (params['submitter'] || "#{current_user.login}/#{current_user.displayname}"),
      'title' => params[:title],
      'synchronousMode' => params[:synchronousMode],
      'retainTargetURL' => params[:retainTargetURL],
      'type' => params[:type]
```

**Merritt UI Authentication**
HTTP Basic Authentication

**Concerns for switch from Sword to UI**
- Dryad will need to know Merritt profile, which may not be available, but can be determined
For example, if the collection name is **cdl_dryad**, then appending **_content** will be the profile
- Dryad submits to Sword with a checkm manifest.  It is unclear to me if the the object level metadata is enclosed in a file (e.g. stash-wrapper.xml) and extracted by Sword.  However, the object level metadata can now be supplied directly in the Form submission.

**Comment by terrywbrady** [comment]
## Notes from UC3 conversation on 3/10
- From a provenance tracking perspective, the version history in Dryad and in Merritt is generally identical.  The is not a compelling desire to simplify the reduce the _number of versions_ that are created.
  - Published versions are a user-facing concept rather than a provenance concept..
- In some instances, when a digital file is rejected/replaced during the curation phase, rejected copies/versions of digital objects may not need to be preserved.  
  - This contradicts Merritt versioning practices and could be an argument to selectively push specific versions to Merritt.
  
## During the curation process, frequent changes may be made to objects
- This necessitates quick access/retrieval of objects
- The asynchronous replication of resources in Merritt could seem unnecessarily complicated during this phase of object processing.
- Fortunately, while replication can become backlogged or delayed, the replication process has not prevented subsequent updates to objects.

## Asyncronous/Syncronous Updates
- It was initially explained to me that a key need for the synchronous sword deposit was the need for an immediate return of an ark from Merritt. 
  - Based on error handling in Dryad, this may be a less immediate issue.
- Once deposit has been confirmed, Dryad relies on Merritt to provide immediate access to objects.  
- If Dryad deposits were to be processed through normal submission queues, Merritt would need to ensure that those deposits had priority processing.  It would not be acceptable for Dryad deposits to queue behind a multi-TB deposit.
- Merritt would need the ability to either launch new instances or to starve non-Dryad queues if processing were to slow down.

### Benefits of migrating to standard deposit
- Merritt could retire Sword and OAI services simplifying the architecture
  - From a timing perspective, we probably cannot prevent the need for some immediate work on these services in Spring 2022
- Queues could be managed an controlled with one mechanism
  - Dryad should not need to halt queue processing for Merritt purposes.  Merritt queues should control that.
- Queue management tools would be available through the Merritt admin tool
  - To view and requeue jobs
- Enables post-inventory callback
  - Once an item has been fully processed by ingest/inventory (verified by reading queues), the client could be notified that the item is complete
  - This could eliminate the need for OAI processing  
- High Availability Considerations 
  - Ingest requests would be sent to UI + Ingest rather than to Sword + Ingest.
  - Merritt and Dryad should design retry logic to tolerate temporary unavailability of a service (< 5sec).
  - It will continue to make sense to push for a smart deployment process that would drain ALB instances before pushign code.   

### Benefits to post-inventory validation
- The new endpoint in the Merritt UI on stage may be significantly simpler for Dryad than processing an OAI feed
  - We will want to confirm this with Scott 
- Client (Dryad) would have immediate confirmation of object availability
  - No need to poll/scrape a feed _unless_ there was a period of time where callback invocations were not processed

**Comment by elopatin-uc3** [comment]
## Key use cases to address
The following two cases can be viewed as thresholds in terms of when Dryad is perceived to be in a critical state (or not) by end users. Avoiding or mitigating the impact of these two cases, either entirely, through presentation of status information, or by providing simple troubleshooting functionality was considered key in our conversation. Mention of a 48 hour time period during which either of these cases continues to occur is also of importance. Neither should last more than two days.

- "Dryad user can't submit": Author clicks submit, but the dataset is never displayed in a Processing state. Note that optimal job priority plays into this user experience.
- "Curator tries to publish a dataset, but an error occurs": Publication by a curator is prevented.

**Comment by terrywbrady** [comment]
Notes from the Dryad Meeting in Oakland (10/22)

## Step 1: phase out OAI
- Dryad will pursue the [API endpoints](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/CDLUC3/mrt-dashboard/main/swagger.yml#/experimental) as a replacement for OAI service
- Once the Ingest callback process can confirm that inventory has completed processing, Merritt can present that as an option.  For now, replacing the OAI pull with an API pull makes sense.

## Step 2: decommission OAI service

## Step 3: refine ingest workers to ensure async processing of Dryad submissions
- Merritt Team will document the changes in API calls to facilitate starting an ingest via Merritt UI rather than via Sword. (Terry and Mark)
- Mark will explore modifying ingest workers to have a separate consumer daemon to work on only high priority submissions.  This would guarantee that threads are always available for Dryad.

## Step 4: Dryad will switch endpoint calls

## Step 5: Decommission Sword service

**Comment by terrywbrady** [comment]
If the consumer daemon solution works here, it might also be a solution for the Access Servers.  Perhaps we could restrict the number of threads that process large items.

**Comment by sfisher** [comment]
Dryad's placeholder ticket for Phasing out OAI: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2067

**Comment by sfisher** [comment]
Dryad's ticket for phasing out SWORD: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2068
