### ISSUE TITLE
[SDSC Node]  Concurrent submission failures

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#945]
During Storage lock testing we discovered that SDSC node 9502 exhibits behavior that causes sporadic failures for concurrent submissions.
These failures can be mitigated by increasing the submission interval.  Here are some statistics:

100 object submission at 15 second interval
     - 0 failures
100 object submission at 10 second interval
     - 8 failures
100 object submission at 5 second interval
     - 62 failures

The failures are shown in the Storage logs as:
```
***Existing file deleted- does not match: 
- bucket:cdl.sdsc.stage - key:ark:/99999/fk4903mg7h|1|system/mrt-ingest.txt 
- fileSha256: c9c0885390091e6749ae151345df18371049cdc11b16c47b49058e2e557cb25f 
- storeSha256: 0a745e424a92f109cc0c2a9f9d769b0ae3e9c085408877296374cedbac816bb9
```

David thinks that this is caused by SDSC's latency in replicating the content from its primary nodes to its peers.

Testing on AWS nodes does not show this behavior.

**Comment by terrywbrady** [comment]
@mreyescdl - is any more work needed on this?  If not, please close
