### ISSUE TITLE
Version/Scan Issue cleanup for Dryad objects

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#946]
#### Objects to address
- ark:/13030/m5bp553p : discuss README files w/Dryad
- ark:/13030/m5bc90d2 : discuss possible removal of ...%22canalisation in the wild%22.csv file
- ark:/13030/m5fr53p3 : discuss possible removal of dryad-general-workflow-rich-1080p.mov.tgz
- ark:/13030/m5fz2ct4 : discuss possible removal of README_for_Sample_information1.txt
- ark:/13030/m5j72k84 : Repair
- ark:/13030/m5j72nsp : Repair, Meng et al_Dataset.xlsx
- ark:/13030/m5kx0pkv : Repair? Clarkia_RNAseq.zip
- ark:/13030/m5qz7s32 : Repair? Data_File_1.xlsx

**NEW from Alias node scan**
- ark:/13030/m5j72k84: Missing version? : mrt-oaidc.xml	2019-07-23 12:23:59
- ark:/13030/m5mm36kd: Version 4 in scan, but missing from manifest (only up to version 3)
- ark:/13030/m5qg5s5c: Version 10 in scan, but missing from manifest (only up to version 9)
- ark:/13030/m5qs00fn: Version 3 mismatch between scan data and Inventory; missing some version 3 files in Inv.
- ark:/13030/m5rv5tmq: Examine content of mrt-delete.txt: mismatch between byte counts of scan vs. Inv.
- ark:/13030/m5z65rc2: Version 2 in scan results, but missing from Inv.

Review mrt-delete.txt content:
- ark:/13030/m5rv5tmq
- ark:/13030/m5tv13bj
- ark:/13030/m5wt50b3 

Area on stage to download cloud content to for review:
`/apps/dpr2/tools/node_cleanup_resubmission`

**Comment by mreyescdl** [comment]
ark:/13030/m5bc90d2 - Sent note to Scott if we should delete extra file in version 3

**Comment by elopatin-uc3** [comment]
Remaining to follow up on with Scott:
* ark:/13030/m5fr53p3 : discuss possible removal of dryad-general-workflow-rich-1080p.mov.tgz (the latest version has an mp4 format file of the same video) : **Eric**
* ark:/13030/m5j72k84 : download producer/oaidc file that is 15 bytes different than what is available in object and diff the two. Check in with Scott if it appears to be a significant difference, otherwise we can mark for delete. : **David**
* ark:/13030/m5kx0pkv : Clarkia_RNAseq.zip : Does version history in Dryad align with Merritt? We don't see the Clarkia file in Merritt : **Eric**

**Comment by elopatin-uc3** [comment]
ark:/13030/m5wt50b3 mrt-delete.txt:
Appendix_S2_Sampling_information.xlsx
Appendix_S3_12_RF_new.pdf
Appendix_S4_matrix_for_different_gene_numbers.zip
Appendix_S5_IQtree.pdf
Appendix_S6_svdquartets_tree.pdf
Appendix_S7_Astral_tree.pdf
Appendix_S8_574_IQ_SVD_astral.pdf
Appendix_S9_blength_support_qc.pdf
Appendix_S10_LTT_Oreocharis_log.pdf
Appendix_S11_CoMET_Oreocharis.pdf
Appendix_S12_Results_of_diversification_analyses_with_paleo-environmental_curves_smoothed.docx
Appendix_S13_Differences_diverisification_rate_between_HDM_and_non-HDM_with_BiSSE.pdf
Appendix_S14_the_BiSSE_model_with_different_constraints_at_the_root_state.pdf
Appendix_S15_HiSSE.xlsx
Appendix_S16_Simulations_with_SSE_models_Oreochairs.pdf
Appendix_S17_Informations_of_RASP_analyses.xlsx


m5rv5tmq-6-system-mrt-delete.txt:
List of studies_version 1.csv
SCOC database_version 1.csv

m5tv13bj-3-system-mrt-delete.txt:
size-table-2-box_plot_Extended_Fig._6a.xlsx
size-table-2-area-Extended_Fig._6b.xlsx
P._gatehousei_nexus_matrix.nex
Raw_date_of_P._gatehousei_zooid_length_and_width.xlsx

**Comment by elopatin-uc3** [comment]
See also https://github.com/CDL-Dryad/dryad-product-roadmap/issues/1748

**Comment by terrywbrady** [comment]
@mreyescdl , @dloy , @sfisher and @terrywbrady reviewed the items with a "Hold" state.  We made a couple of object updates to resolve issues.  All held files have been deleted.  A fresh scan was started on 9/19.
