### ISSUE TITLE
Replication does not complete for 2 objects, restart does not help

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#951]
```
select * from inv_nodes_inv_objects where inv_object_id in (2907068,2795499);
```

**Comment by dloy** [comment]
### ark:/13030/j2br86wx
~~~
SELECT o.id oid, o.ark,c.id cid,c.mnemonic,co.*
FROM inv_collections_inv_objects co,
inv_objects o,
inv_collections c
WHERE o.ark IN ('ark:/13030/j2br86wx')
AND co.inv_object_id=o.id
AND c.id=co.inv_collection_id

oid	ark	cid	mnemonic	id	inv_collection_id	inv_object_id
2907068	ark:/13030/j2br86wx	419	dryad_service_level_agreement	2919035	419	2907068
2907068	ark:/13030/j2br86wx	13	\N	2919036	13	2907068
2795499	ark:/13030/m5v45qp2	50	mrt_curatorial_classes	2807478	50	2795499

~~~
Note object ark:/13030/j2br86wx is in collection 419 and collection 13 which causes replication error of secondary copy = primary copy

**Comment by elopatin-uc3** [comment]
Evaluate storage node configuration for each collection for primary and secondary config.

**Comment by dloy** [comment]
## Fix 'ark:/13030/j2br86wx'
### Problem
To fix this object requires: 
- primary copy be on the production Dryad (3041)
- secondary copy be on minio (9501) 

Currently the copies:
primary - 9501 - minio
secondary - 6001 - glacier

### Steps
1. copy object from 9501 to 3041 - store copy
1. delete 6001 object - replic delete secondary node
1. do mysql update changing 9501 "primary" to "secondary"
1. force replication rerun on object

### Notes
- normally the collections-nodes entry would be modified but the current copy is correct
- the copy of merritt owners should be left alone - objects are small and glacier can never be primary
- recommendation moving forward that no object be included in 2 collections if both are replicated - only one replicating collection per object

**Comment by dloy** [comment]
## Fix 'ark:/13030/j2br86wx'
### Problem
To fix this object requires: 
- primary copy be on the production Dryad (3041)
- secondary copy be on minio (9501) 

Currently the copies:
primary - 9501 - minio
secondary - 6001 - glacier

### Steps
1. copy object from 9501 to 3041 - store copy
1. delete 6001 object - replic delete secondary node
1. do mysql update changing 9501 "primary" to "secondary"
1. force replication rerun on object

### Notes
- normally the collections-nodes entry would be modified but the current copy is correct
- the copy of merritt owners should be left alone - objects are small and glacier can never be primary
- recommendation moving forward that no object be included in 2 collections if both are replicated - only one replicating collection per object

**Comment by terrywbrady** [comment]
Could this be a simpler option?

```
MySQL [inv]> select * from inv_collections_inv_objects where inv_object_id = 2907068;
+---------+-------------------+---------------+
| id      | inv_collection_id | inv_object_id |
+---------+-------------------+---------------+
| 2919036 |                13 |       2907068 |
| 2919035 |               419 |       2907068 |
+---------+-------------------+---------------+
```

What if we just run the following

```

**Comment by dloy** [comment]
Some issues:
- ark:/13030/j2br86wx should be MRT-system not MRT-curatorial
- the backup for all MRT-system objects is glacier (6001) and wasabi (2001)
- the primary for all MRT-system object is minio (9501)
- ark:/13030/j2br86wx primary is 9501

How about removing:
~~~
id	inv_collection_id	inv_node_id	created
419                  51                 13          2016-10-14 15:35:25
~~~

**Comment by dloy** [comment]
## Action on ark:/13030/j2br86wx
### Remove collection-node
Remove the entry causing secondary-primary collision
~~~
id	inv_collection_id	inv_node_id	created
1261	419	16	2019-11-06 14:14:17
~~~
Removed from inv_collections_inv_nodes

### change MRT-curatorial to MRT-system
~~~
update inv_nodes_inv_objects
set replicated = null
where inv_nodes_inv_objects.id=10019175
and inv_nodes_inv_objects.role='primary'update inv_objects
set object_type='MRT-system'
where inv_objects.ark='ark:/13030/j2br86wx'
and inv_objects.object_type='MRT-curatorial'
AND inv_objects.id=2907068
~~~

### force new replication
update inv_nodes_inv_objects
set version_number = null
where inv_nodes_inv_objects.id IN (10019176)
and inv_nodes_inv_objects.role='secondary';

update inv_nodes_inv_objects
set replicated = null
where inv_nodes_inv_objects.id=10019175
and inv_nodes_inv_objects.role='primary';
