### ISSUE TITLE
UCI Nuxeo feed: Thomas A. Parham papers

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#953]
Source ticket: https://help.oac.cdlib.org/a/tickets/101947

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/27843

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27843.atom

Root folder in Nuxeo:
https://nuxeo.cdlib.org/nuxeo/nxpath/default/asset-library/UCI/SCA_SpecialCollections/MS-F044/For%20Merritt

Merritt collection:
UCI SCA Special Collections
ark:/13030/m5gb7gff

**Comment by elopatin-uc3** [comment]
Waiting on registry entry from Gabriela, as well as for feed to be generated.

**Comment by elopatin-uc3** [comment]
Hi @mreyescdl , this feed should now be available:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27843.atom

**Comment by mreyescdl** [comment]
Scheduled weekly at Thursday 04:15

Ticket Complete
