### ISSUE TITLE
UCI Nuxeo feed: School of Law Records

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#954]
Source ticket: https://help.oac.cdlib.org/a/tickets/101948

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/25965/

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_25965.atom

Root folder in Nuxeo:
https://nuxeo.cdlib.org/nuxeo/nxpath/default/asset-library/UCI/SCA_UniversityArchives/AS-162/For%20Merritt

Merritt collection:
UC Irvine SCA University Archives
ark:/13030/m5bk6qsm

**Comment by elopatin-uc3** [comment]
Waiting for feed to be generated.

**Comment by mreyescdl** [comment]
Create Nuxeo script: /dpr2/apps/ui/atom/bin/production-25965-UC-Irvine-UA-School-of-Law-Records-uci_lib_sca_ua.csh

Submitted manually, creating 3 objects

Checked script and creation script into mrs-dashboard-config repo

Scheduled in Puppet to run Thursday at 04:05

Ticket complete
