### ISSUE TITLE
UCI Nuxeo feed: Jaded

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#957]
Source ticket: https://help.oac.cdlib.org/a/tickets/102048

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/29/

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_29.atom

Root folder in Nuxeo:
https://nuxeo.cdlib.org/nuxeo/nxpath/default/asset-library/UCI/SCA_UniversityArchives/Publications/Jaded

Merritt collection:
UC Irvine Library SCA University Publications
ark:/13030/m5549nb2

**Comment by mreyescdl** [comment]
Created Nuxeo script production-29-UC-Irvine-Library-SCA-UPub-Jaded-uci_lib_sca_upub.csh
Ran manually and created 12 objects.

Scheduled on Thurs at 04:10
Checked all into private mrt-dashboard-config repo

Ticket complete
