### ISSUE TITLE
UCI Nuxeo feed: New University

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#958]
Source ticket: https://help.oac.cdlib.org/a/tickets/102090

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/26702/

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_26702.atom

Root folder in Nuxeo:
https://nuxeo.cdlib.org/nuxeo/nxpath/default/asset-library/UCI/SCA_UniversityArchives/Publications/New University

Merritt collection:
UC Irvine Library SCA University Publications
ark:/13030/m5549nb2

**Comment by elopatin-uc3** [comment]
@mreyescdl this feed should now be available:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_26702.atom

**Comment by mreyescdl** [comment]
Thanks @elopatin-uc3 
Can you add me to this collection in production LDAP?

Note to self:  Collection profile is `uci_lib_sca_upub_content`

**Comment by elopatin-uc3** [comment]
@mreyescdl You should have access to the collection, but let me know if you can't log in:
https://merritt.cdlib.org/m/uci_lib_sca_upub

In terms of the naming, I think the SCA University Publications collection will have multiple feeds associated with it. So naming it something linke "UC Irvine Library SCA UPub New University" would make sense.

**Comment by mreyescdl** [comment]
Looks like I still do not have read access.  Thanks for looking into this.
```
UC Irvine Library SCA University Publications | admin/write
```

**Comment by mreyescdl** [comment]
Committed Nuxeo script and creation script
     production-26702-UC-Irvine-Library-SCA-UPub-New-University-uci_lib_sca_upub.csh

Running manually.  1310 entries.
After running, need to schedule in Puppet cron

**Comment by elopatin-uc3** [comment]
Thanks Mark. That's really odd about not having read access. Just now I went ahead and removed you from each of the permissions groups for the collection in LDAP and then re-added you. Hopefully this may help; let me know.

**Comment by mreyescdl** [comment]
Perfect Eric.  I now can view the collection in the UI.  Thanks
