### ISSUE TITLE
UCI Nuxeo feed: Anthology: the University of California, Irvine yearbook

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#959]
Source ticket: https://help.oac.cdlib.org/a/tickets/102089

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/26856/

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_26856.atom

Root folder in Nuxeo:
https://nuxeo.cdlib.org/nuxeo/nxpath/default/asset-library/UCI/SCA_UniversityArchives/Publications/Yearbooks

Merritt collection:
UC Irvine Library SCA University Publications
ark:/13030/m5549nb2

**Comment by mreyescdl** [comment]
- Created Nuxeo script: production-26856-UC-Irvine-Library-SCA-UPub-Anthology-Yearbook-uci_lib_sca_upub.csh 
- Ran manually and is currently submitting 43 objects
- Checked creation script and execution script into mrt-dashboard-config repo
- Scheduled with Puppet to run on Thurs at :04:00

Ticket is complete

**Comment by elopatin-uc3** [comment]
Thanks for the update @mreyescdl . I'll notify the requestor.
