### ISSUE TITLE
UCI Nuxeo feed: Anthill, Student Newspaper

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#960]
Source ticket: https://help.oac.cdlib.org/a/tickets/102088

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/26695/

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_26695.atom

Root folder in Nuxeo:
https://nuxeo.cdlib.org/nuxeo/nxpath/default/asset-library/UCI/SCA_UniversityArchives/Publications/Anthill

Merritt collection:
UC Irvine Library SCA University Publications
ark:/13030/m5549nb2

**Comment by elopatin-uc3** [comment]
This feed will not be available until 3/22.

**Comment by mreyescdl** [comment]
Script create and manually run resulting in 43 objects
```
production-26695-UC-Irvine-Library-SCA-UPub-Anthill-Student-Newspaper-uci_lib_sca_upub.csh
```

Scheduled for Thurs at 03:55 in Puppet

Ticket complete
