### ISSUE TITLE
Manifest Validation Tool

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#965]
## Tool

https://cdluc3.github.io/mrt-doc/manifest/index.html

### Headers
- [x] Column order is fixed based on profile
- [x] If fields header is present, check that it matches the expected order
- [x] checkm declaration - optional, warn if not as expected
- [x] prefixes - optional, warn if not as expected

### Fields
- [x] Only url is required

### CSV Conversion
- [x] Reorder to match expectation

### Report
- [x] Document the number of objects to be created

### Additional Java Testing
- [x] Test for character encoding failures
- [x] Test for url format failures
- [x] Understand ISO date formats: `2017-08-25T13:28:14-08:00`.  Users have probably never used these features.
- [x] Test extra lines
  - [x] before entries
  - [x] between entries
  - [x] before eof
  - [x] after eof
- [x] Windows style newlines? 

### Mark will validate ingest checks
- [x] filename is not required (assumed from url)
- [x] url is required (note not required by checkm parser)
- [x] for the container filename checks, is it sufficient to test the filename only

## See Also

#420

**Comment by mreyescdl** [comment]
@terrywbrady 
Here are the results of the 4 tests we discussed a bit ago.  Please let me know if you have questions.

```
1) Newline after ending stanza

   Result:      Error - Consume Daemon - job message: [error]: HandlerRetrieve: Manifest: IOError in hasMoreElements:org.cdlib.mrt.core.ManifestRowCheckmAbs-handleEOF:158 INVALID_DATA_FORMAT[Generic data being processed is invalidly formatted] ManifestRowCheckmAbs: EOF without #%EOF terminator header - prevLine=

2) No URL in URL field

   Result:      Error - Retrieving remote data: https://raw.githubusercontent.com/CDLUC3/mrt-doc/main/sampleFiles/4blocks.jpg ---- 4blocks.jpg
        java.lang.NullPointerException
                at org.cdlib.mrt.ingest.handlers.RetrieveData.call(HandlerRetrieve.java:443)
                at org.cdlib.mrt.ingest.handlers.RetrieveData.call(HandlerRetrieve.java:421)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)

3) No filename, but do have filename part in URL

   Result:      Good - Defaults to filename part in URL

4) Non container for container manifest in either URL or filename

   Result:      Good - Non container filename is still unpacked
