### ISSUE TITLE
Prevent ingest queue starvation by unusually large deposits 

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#970]
Issue #939 describes a goal to process Dryad submissions with normal ingest queue processing (vs Sword).  Overall, this will provide many benefits.  

Before implementing this change, we will need to ensure that Dryad submissions are processed in a predictable timeframe.

## Possible Solutions
- [ ] Create dedicated ingest (and store?) service queue and server instances for Dryad
  - relatively simple to implement, may not be cost-efficient
- [ ] Channel exceptionally large ingest payloads to a dedicated "larger deposit" instance/thread as we have done for object assembly requests
  - Break ingest processing into 2 steps: (1)manifest interpretation (2)payload processing.  Manifest interpretation would calculate overall payload size.  Use head requests and manifest fields to calculate payload size.
  - Throttle exceptionally large item processing in order to preserve processing time for typically sized objects.
  - Auto-scale to meet demand for unusually large objects.

**Comment by elopatin-uc3** [comment]
Noting related tickets: #972, #973

**Comment by terrywbrady** [comment]
Closing... captured in the queue design ticket
