### ISSUE TITLE
Cross microservice logging

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#971]
# Logging Design Doc

https://github.com/CDLUC3/mrt-doc/blob/main/design/logging-2023/README.md

## Discussion Questions
- [x] Deploy log4j2.xml in WAR or via filesystem?
  - Application artifact or Devops artifact?
  - Think of how it will be included in ECS - use environment variables
- [x] Can a generic logstash/filebeat solution be deployed?
- [ ] Should we try to harmonize data fields across Rails, Tomcat Access and Custom logging?
- [x] Could we start building out a solution for stage?
- [ ] Should Java microservices repeat request parameters in logs?
- [ ] What tickets/requirements docs would be helpful to have for each microservice?  

---

## Why logging
I'm putting out this issue to begin some discussion for normalizing specific system logs shared between multiple microservices. 

I see an important role for this log to provide consistent information across all microservices for item behavior and service behavior.

One suggestion during Ashley's discussion of logging was to have two logs:
- The current logs
- a collected structured log

Another feature of these logs is the ability to provide customized tagging (or controlled vocabulary)

I see two major reasons for logging:
- get detail of process handling within a microservice for purposes of understand specific behavior - e.g. debugging
- get a higher level (service) view on the success or failure of an item being processed across all microservices 

#### features
- specific to a single microservice
- ease of visually interpreting
- minimal or unstructured content
- ease of access
- simplified manual methods for extracting information
- need for multiple level for creation: debug, medium, high, etc.

#### functions
- debugging individual microservice or process
- quickly manually identify when/where things go wrong

#### features
- multiple sources of log information
- automated mechanism for interpreting (Solaris?)
- highly structured content
- standardized approaches across multiple systems
- mechanized approaches for extracting specific information
- may only require one or few levels of log generation
- possible controlled  vocabulary

#### function
- completion status or error for item traversing system (e.g. object completion in ingest, store, inv, replic)
- item impacts on system - process times for item
- be able to provide a sequence of status for each item traversing system
- provide microservice log information on state change - init, 

## Moving forward (just some thoughts!)
 - maintain original logging
 - define content tags for service level logging - having consistent json tags across microservices
 - implementing service level logs in individual microservices
 - generalized handling of collected service logs
 - searching a collected service log
 
### service log tags - format json
- format: json
- one entry per processed item per microservice

#### item tags - item processing
- datetime
- level ("item", microservice")
- microservice ("storage", "inv", "replic", "ingest", "ingest_batch", "audit", "ui")
- machine (e.g. uc3-mrtinv02x2-prd)
- processid - local identifier for microservice
    - audit - audit id or url or key
    - inv - ark
    - replic - ark
    - storage - ark
    - ingest - ark or higher level batch information or both
 - node - storage node if applicable
 - process_time - milliseconds
 - process_size  - bytes
 - status - ok, error, unknown
 - exception - with or without stacktrace

#### microservice specific tags
- datetime
- level ("item", microservice")
- microservice ("storage", "inv", "replic", "ingest", "audit","ui")
- machine (e.g. uc3-mrtinv02x2-prd)
- state ("start", "stop", "build"," fail")
- note

## Note
Again, all speculative(!) to get some feedback

**Comment by terrywbrady** [comment]
At the generic service level, in addition to hostname (machine) and FQSN (microservice), it would be interesting to capture the following:

- deprecated (boolean) - a mechanism to identify the use of any deprecated functioality in the 
- semantic version number
- thread id
- internal request id (if available)
- duration
- status-code for the request (where applicable)

## Key attributes by service
_This describes an information object to be populated and submitted with each json log entry.  The object should be as fully populated as possible.  This would likely appear as a "custom" entry in the log json._

- UI
  - all requests
    - user 
  - collection-level requests
    - collection_ark
    - collection_mnemonic (also called group)
    - search term
  - object/version/file level 
    - ark
    - version
    - path
    - nodenum
    - assembly-token
- Ingest
  - job/batch processing
    - batchid
    - jobid
    - collection-profile
    - user
    - manifest-item-url
  - object/file processing
    - ark
    - localid
    - filename  
- Storage
  - node
  - ark
  - version
  - file
- Inventory
  - queue-id
  - ark
  - version
  - file
  - localid
- Replication
  - node id
  - ark
  - ver (where applicable)
  - file (where applicable)  
- Audit
  - batch (date used to batch updates)
  - node id
  - ark
  - version
  - file
- Access
  - file requests
    - node
    - ark
    - version
    - file
  - assembly requests
    - token
    - queue id
    - ark
    - version (where applicable) 
- Admin Tool
  - User
  - Request
  - Parameters
  - where applicable (collection admin)
    - node
    - ark
    - version
    - file  

## Key events to log
- UI
  - Every request/api call is a key event
- Store
  - Every request/api call is a key event
  - Every file not saved is a key event 
  - Every file saved is a key event (debug mode)
  - Every checksum not verified is a key event 
  - Every checksum verified is a key event (debug mode)
- Ingest
  - Every request/api call is a key event
  - Every queue task handled is a key event
  - Every manifest line item processed is a key event
- Inventory
  - Every request/api call is a key event (local id service)  
  - Every queue task handled is a key event
- Access    
  - Every request/api call is a key event
  - Every queue task handled is a key event
- Audit
  - Every file not verified is a key event
  - Every file verified is a key event (debug mode)
  - Every batch (inv_audits table) initiated is a key event 
  - Every batch (inv_audits table) updated is a key event 
- Replication
  - Every request/api call is a key event (admin tool calls directly)
  - Every object replicated is a key event 
  - Every file not saved is a key event 
  - Every file saved is a key event (debug mode)
  - Every checksum not verified is a key event 
  - Every checksum verified is a key event (debug mode)
- Admin Tool
  - Every request/api call is a key event (admin tool calls directly)

**Comment by terrywbrady** [comment]
Useful display fields for docker stack

<img width="1699" alt="image" src="https://github.com/CDLUC3/mrt-doc/assets/1111057/f83c9d1f-0389-4ca2-894d-cf6f3b5f8b2f">
