### ISSUE TITLE
Migrate Ingest from Apache Load Balancer to ALB

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#977]
- [x] Mark - review logs to find any evidence of a long-running ingest
  - We believe that all depositors have migrated to manifest based ingests
- [x] Eric - If any depositors are still uploading large payloads directly, Eric will have a conversation to encourage migrating from that practice
- [x] Terry - add an upload size cap in the UI (if needed)
- [x] Create new ALB for ingest
- [x] Migrate clients of the Apache ALB or create some sort of alias
- [x] Eliminate Apache  

Related to #976

**Comment by mreyescdl** [comment]
New ALB has been created for testing in Stage:

From Ashley:
     alb for uc3-mrt-ingest-stg is ready.  DNS alias are
              ingest-stg.cdlib.org
              uc3-mrt-ingest-stg.cdlib.org
These are only accessible from within cdl network.


Here are the clients that need a change in Domain Name and pathname (No rewrite ability with ALB)

UI
--
Was - (config/app_config.yml)
     mint_service:         "http://merritt-aws-stg.cdlib.org:33121/ingest/request-identifier"
     ingest_service:       "http://merritt-aws-stg.cdlib.org:33121/poster/submit/"
     ingest_service_update: "http://merritt-aws-stg.cdlib.org:33121/poster/update/"
Now
     mint_service:         "http://ingest-stg.cdlib.org:33121/request-identifier"
     ingest_service:       "http://ingest-stg.cdlib.org:33121/poster/submit/"
     ingest_service_update: "http://merritt-aws-stg.cdlib.org:33121/poster/update/"

Sword
-------
Was - (/dpr2/mrtHomes/sword/sword-info.txt)
     submit:         http://merritt-stg.cdlib.org:33121/ingest/submit-object
     update:         http://merritt-stg.cdlib.org:33121/ingest/update-object
Now
     submit:         http://ingest-stg.cdlib.org:33121/submit-object
     update:         http://ingest-stg.cdlib.org:33121/update-object

Admin Interface
----------------
Changes 
      - All requests to Ingest must change domain name to merritt-stg.cdlib.org
      - All pathnames that start with pathname "/ingest" must remove this text

Ingest
------
Changes
     - Investigate Storage manifest URL sent to Storage.  Is this using "http" protocol or "file"  
        If http: then we must remove the "/ingest" part of pathname

**Comment by mreyescdl** [comment]
Ingest Client will need to modify code.  We give Storage an http URL for the manifest...

```
http://merritt-stg.cdlib.org:33121/ingest/ingestqueue/bid-13737054-ef7d-4154-8bba-fb90cb0cc4b9/jid-80913788-6d0e-4cbf-93ba-f273c091ae1a/system/mrt-dc.xml
```

Lets make this a "file:" protocol URL since the disk is shared.  Check with @dloy if this will work for Storage

**Comment by mreyescdl** [comment]
Sword reconfigured to use ALB on Stage.  No problems encountered

**Comment by mreyescdl** [comment]
Pull request for UI change in stage
https://github.com/CDLUC3/mrt-dashboard/pull/130

**Comment by mreyescdl** [comment]
UI deployment in stage completed and tested - tag 1.1.14-dev1

**Comment by mreyescdl** [comment]
@ashleygould 
Testing with Stage Ingest ALB complete.

Please request a production ALB with much the same configuration.  Changes will include:

Name: uc3-mrt-ingest-prd-alb
Target hosts: uc3-ingest01x2-prd, uc3-ingest02x2-prd, uc3-ingest03x2-prd
Port for listening and target: 33121 (no change from stage)
New DNS entry:  ingest-prd.cdlib.org (existing entry ingest.cdlib.org will be changed after dev work is complete. NO change now)

**Comment by mreyescdl** [comment]
Production

Two clients will need to change their Ingest endpoint

UI
Was - (config/app_config.yml)
  mint_service:         "http://ingest.cdlib.org:33121/ingest/request-identifier"
  ingest_service:       "http://ingest.cdlib.org:33121/poster/submit/"
  ingest_service_update: "http://ingest.cdlib.org:33121/poster/update/"
Now
mint_service: "http://ingest-prd.cdlib.org:33121/request-identifier"
ingest_service: "http://ingest-prd.cdlib.org:33121/poster/submit/"
ingest_service_update: "http://ingest-prd.cdlib.org:33121/poster/update/"

Sword
Was - (/dpr2/mrtHomes/sword/sword-info.txt)
submit:    ingestUrlAdd=http://ingest.cdlib.org:33121/ingest/submit-object
update:   ingestUrlUpdate=http://ingest.cdlib.org:33121/ingest/update-object
Now
submit: ingestUrlAdd=http://ingest-prd.cdlib.org:33121/submit-object
update: ingestUrlUpdate=http://ingest-prd.cdlib.org:33121/update-object

Admin Interface

Changes
- All requests to Ingest must change domain name to ingest-prd.cdlib.org
- After ingest.cdlib.org DNS change, clients can also use this domain name
- All pathnames that start with pathname "/ingest" must remove this text

**Comment by mreyescdl** [comment]
Now using Ingest ALB in stage.  
Shutting down Apache Ingest LB in Stage

**Comment by mreyescdl** [comment]
Pull request for production UI
https://github.com/CDLUC3/mrt-dashboard/pull/131

**Comment by mreyescdl** [comment]
SSM variables changed for Sword client

```
/uc3/mrt/prd/sword/config/ingestUrlAdd  http://ingest-prd.cdlib.org:33121/submit-object
/uc3/mrt/prd/sword/config/ingestUrlUpdate       http://ingest-prd.cdlib.org:33121/update-object
```

**Comment by mreyescdl** [comment]
- Removed Nagios check for Apache web stage
- Shutdown Apache web Apache
- Will decomission EC2 uc3-mrtweb01x2-stg after grace period

**Comment by mreyescdl** [comment]
ingest.cdlib.org decommission request made
uc3-mrtweb01x2-stg decommission made

**Comment by mreyescdl** [comment]
uc3-mrtweb01x2-prd decommission in process

**Comment by mreyescdl** [comment]
uc3-mrtweb01x2-prd decommissioned
