### ISSUE TITLE
[Administrative] Provide documentation for Audit/Fixity error reports

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#99]
The error reports that arise when there are errors detected in Audit need documentation.  Also triage information of how to perform cleanup and other reponses to these errors should be documented.

https://confluence.ucop.edu/display/UC3/Merritt+Administration
 - [ ] Add documentation in Merritt Administration page.
 - [ ] Discuss possible  updates to the reports to help them be more meaningful

**Comment by elopatin-uc3** [comment]
https://drive.google.com/open?id=1WlQ3Db4AcfagPTrtpEVMAN-G7oS56I2UV3pfcJj-GTw (Marisa Strong - Jan 28, 2019)

**Comment by terrywbrady** [comment]
@elopatin-uc3 have the admin tools already covered this?

**Comment by elopatin-uc3** [comment]
Yes; closing
