### ISSUE TITLE
Replic - processing of large content

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#990]
## Problem
The number of Merritt objects added having total size > 100G has been increasing.

Replicating this content has become more difficult because the total system resources used in the replication server increases dramatically and fails primarily because of local timeouts on threads unable to retry. This is especially bad on wasabi which has a higher 500 status rate than other services we currently are using.

Currently an S3 saved object cannot be greater than 5G. If a file to be uploaded > 5G, then the content must be uploaded as multiple chunks. These chunks are then identified by a final manifest describing the order and key of the chunks represented on download as a single file. To upload a file > 5G can be handled as a set of sequentially uploaded chunks or it can be concurrently uploaded by serveral threads with each thread uploading a single chunk. Each thread in an upload process must be able to make connections to the S3 server and must have enough local resources on the uploading server to prevent from timing out.

Factors impacting uploads are total threads, ability of upload server to provide a connection to that thread, and restart capability of a thread to issue retries for connection.

The java SDK may attempt to do concurrent update of a file using 8M chunks with 10 threads.  For 100G files this results in a large number of possible failed connections to the target server. For AWS this works well - for wasabi this can be a problem. Wasabi failures occur because the service fails to provide an upload connection even after 3 retries. 

### S3 cloud changes
Testing of retry logic in the AWS Java SDK indicated that internal retries attempted are much lower than specified in withMaxErrorRetry. Internal count for retries appears to be 3.  Using withRetryPolicy logic allows much higher values and better approaches for performing retries.  Changing the retry logic to use FullJitterBackoffStrategy should be explored with 30 attempts to confirm the elimination of final retry failures.

Also, wasabi upload chunk handling should be modified to no longer be concurrent but sequential to avoid the possible 10 concurrent upload threads.

### Replic changes
If the S3 handling above does not eliminate the replication errors, then a single dedicated service should be reserved.

This server should:
- process only Merritt objects with updates over a specific size (e.g. 100G)
- should have limited thread handling for uploading multiple files at once (e.g. 2)
- should continue to use the s3 cloud changes above

**Comment by dloy** [comment]
### allow previously added content to be ignored
Using the largest object (to date) - ark:/13030/m5q029nw - identified a restart issue that prevented restarts on first versions from optimizing throughput from previous failed attempts. 

One fix allows the copy process to skip adding files that were previously added to S3 if an glacier style fixity check works:
- an S3 file exists for key
- file has an s3 sha256 for file that matches the input entry digest
- file length matches

This test was blocked if a new object was being added to secondary storage.

### retry on failed multipart upload
The S3 java sdk allows large upload content to be added as multiple threads each copying some part of the file to S3.

The problem with this process is that if the target S3 service has connection issues then any thread may timeout attempting to get a connection. Wasabi has a "busy" state where any connection can be difficult.

The fix for this problem is a local code retry. The imbedded retry logic in the java sdk for s3 is very difficult to measure - still looking for a technique to trap the condition.

### expand java sdk retry using scatter exponential retries
This approach looks good on paper but still not clear if this fix is actually working. Without a clean measure for retries - difficult to evaluate. May also require pushing logic out to local code.

**Comment by terrywbrady** [comment]
4/5 - Meeting with IAS
- David will document questions about S3 api and send it to IAS
  - Although the problem is mostly occurring with Wasabi, the S3 java api is used with AWS, SDSC and Wasabi 
- IAS will escalate with AWS to get answers about the api
- The group is skeptical that additional compute resources would ease this issue since it seems to be due to a failure with a cloud provider
