### ISSUE TITLE
Plan how to address dependabot alerts after initial build refactor

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#994]
I took a look at our dependabot alerts across the java services.
We should have a dedicated meeting to talk about how/when to tackle the ones that do not get covered in the first phase of our build refactor.
- ~~mrt-zoo: we have not put this on the project list~~
- log4j 1.x has been EOL since 2015; affects ingest, inventory, store, audit, oai, sword, mrt-zoo
- Tika
- Xerces
- A few others localized to a single repo

**Comment by elopatin-uc3** [comment]
update: David has taken on mrt-zoo as part of his current work on migrating Inventory

**Comment by elopatin-uc3** [comment]
Closing. This is superseded by: https://github.com/CDLUC3/mrt-doc-private/issues/10
