### ISSUE TITLE
[Zookeeper | Ingest] Ability to move Ingest queue entries to new worker

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#997]
Investigate if it is possible to move Ingest queue entries to new worker.
Needed in case a priority job is "stuck" behind a large submission.  Our Load Balancer is a simple round robin and this scenario is possible.

When investigating, look closely at the Batch statistic logic.  I imagine batch size of one would be doable, but larger batches may need care.

**Comment by terrywbrady** [comment]
4/5/22 - Merritt and IAS meeting: IAS advised that we strongly consider how to move queue items between instances.  As we migrate to containers/auto-scaling, we are likely to want to move queue tasks.
